### ISSUE TITLE
Job names are not fully displayed in pipeline page

### ISSUE THREAD

**Issue by taisukeh** [screwdriver-cd/screwdriver#1002]
**What happened**:

![image](https://user-images.githubusercontent.com/282077/38590671-ae06ae12-3d6d-11e8-9aa9-76699b843237.png)

**What you expected to happen**:

![image](https://user-images.githubusercontent.com/282077/38590747-1c5a9216-3d6e-11e8-8831-5372143d005e.png)

I expect the job names to be displayed up to about 16 characters

**Comment by catto** [comment]
Fixed by screwdriver-cd/ui#309.
@taisukeh Thank you for the report!
