### ISSUE TITLE
Request: Code coverage and Test result

### ISSUE THREAD

**Issue by cynthiax** [screwdriver-cd/screwdriver#1007]
**What feature**:
Right now Screwdriver is not showing Code coverage nor Test result for each build. As a person who cares about code quality and hoping to see each commit would increase the code coverage or at least have it stay the same, I would want a easy way to view it inside Screwdriver. Similarly for test result, I would like to know if all test passed, if not, which one failed at a easy glance in Screwdriver.

**Detail**:
There are different service different developer could use, like coverall mentioned in https://github.com/screwdriver-cd/screwdriver/issues/500, [codecov](https://codecov.io/) and [sonar](https://www.sonarqube.org/). Screwdriver should provide (default)plugin for using these services.

- [x] Spike on how to integrate different code analysis service in Screwdriver 
        Criteria: costs, ease of setup

**Comment by tkyi** [comment]
There's a related issue open already: https://github.com/screwdriver-cd/screwdriver/issues/674

**Comment by minz1027** [comment]
## Updates 04/30
After talking with the team, we have decided to go with SonarQube as default code coverage plugin. 

### Proposed implementation:
Flow: 
- Build has a teardown step `push-code-coverage` 
- Inside the step
   - build will call screwdriver API and use build `jwt` to trade for a sonar user token
   - push to sonar host with the user token
Notes: the user token will only be authorized to push its own project. Every pipeline maps to a project in sonar, and every single PR has its own project.

First pass
To do:
- [ ] sonar pipeline with customized config
- [ ] code-coverage-base and code-coverage-sonar
- [ ] `push-code-coverage` bookend

**Comment by tkyi** [comment]
This feature is working in production:
<img width="1440" alt="screen shot 2018-05-15 at 11 29 50 am" src="https://user-images.githubusercontent.com/3230529/40078501-9aab183a-5839-11e8-9df3-ddafd103873a.png">
Clicking on the link takes you to the SonarQube project page:
<img width="1440" alt="screen shot 2018-05-15 at 11 30 14 am" src="https://user-images.githubusercontent.com/3230529/40078515-a9af35f0-5839-11e8-88f6-2ccb2ddddf30.png">
Documentation can be found: https://docs.screwdriver.cd/user-guide/configuration/coverage

**Comment by marian-r** [comment]
@tkyi I am excited to try this out, but the link to the documentation shows 404. I also tried the link in the menu (which is different) https://docs.screwdriver.cd/user-guide/configuration/code-coverage and that also shows 404. Has the documentation been updated?

**Comment by minz1027** [comment]
@marian-r It's updated here: https://docs.screwdriver.cd/user-guide/configuration/code-coverage
:)

**Comment by tkyi** [comment]
@marian-r Sorry I accidentally deleted the documentation when trying to fix something else. It should be back!
