### ISSUE TITLE
Pipeline name does not reflect change in repository name

### ISSUE THREAD

**Issue by Filbird** [screwdriver-cd/screwdriver#1011]
**What happened**:
Unsure if this is intentional, but when changing the name of the underlying [repository](https://github.com/Filbird/changed-name-of-repo) I am unable to change the name of the [pipeline](https://cd.screwdriver.cd/pipelines/513) to reflect the new name.

Attempting to update the checkout URL also produces this response:
![screen shot 2018-04-13 at 10 47 28 am](https://user-images.githubusercontent.com/11892496/38761001-5197f26c-3f34-11e8-9559-0739d3598dd0.png)

**What you expected to happen**:
I expected the pipeline name to reflect the change in the repository name.

**How to reproduce it**:
Create a pipeline and change the name of the repository in the SCM.

**Comment by minz1027** [comment]
we can fix it by calling https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L653 during pipeline.sync() then pipeline names will be auto updated

**Comment by tkyi** [comment]
This issue is fixed now. The pipeline name will now be updated in our database when the repository name changes. The user will need to click the Sync button to see the changes reflected in the UI right away.
