### ISSUE TITLE
[docs] describe expected results for `meta get` of missing key

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#1016]
**What happened**:
`meta get does.not.exist` returned `null`, expected an empty string. The docs for meta doesn't describe this case.

**What you expected to happen**:
Should perhaps `meta get does.not.exist` return an empty string instead? This might be safer in case the user wants to set a value to `null` for some reason. Regardless, docs should describe behavior of this case (as well as other corner cases and failure modes).

**How to reproduce it**:

**Comment by tkyi** [comment]
The last line in the metadata docs actually mention that `meta get` will return `null` in some cases (https://docs.screwdriver.cd/user-guide/metadata). Not sure what the documentation should look like to make that more clear.

**Comment by drewfish** [comment]
I think something about an unset value returning "null". The current version says something about "the triggering job", not sure what that means.
