### ISSUE TITLE
Logs take forever to load on the Screwdriver UI

### ISSUE THREAD

**Issue by fg123** [screwdriver-cd/screwdriver#1024]
As of right now, the logs API only allows up to 1000 lines of log to be loaded each call, which means the UI loads the logs progressively 1000 lines at a time. 

Sounds like a good plan in theory but when I'm looking at a failed build with many thousand lines of logs, I don't want to have to wait minutes to get to the end of the log just to see the exception that caused the build to fail. 

I propose the UI / API to either have an option to instantly view the entire log (and not separate them into pages / limited lines per call), or to only load the last n (maybe a customizable amount) lines with an option to view the entire log (like in Screwdriver v3).

@ScottyFillups

**Comment by catto** [comment]
I found a bug that the latest api and log-service combination cannot handle old logs that have 100+ lines.
https://cd.screwdriver.cd/pipelines/1/builds/44579
Is this a breaking change?

**Comment by jithin1987** [comment]
This should be fixed.
