### ISSUE TITLE
JWT is hardcoded to expire in 2 hours

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#1030]
**What happened**:
JWT is hardcoded to expire in 2 hours.

**What you expected to happen**:
This value should be configurable based on the build timeout. It does not make sense that JWT expires before the build timeout value. For example, cluster admin set build timeout to 10 hours, but the JWT can only be valid in 2 hours.

**Comment by jithin1987** [comment]
Not JWT expiration is aligned with build timeout.
