### ISSUE TITLE
[UI] Request: SECRET_VALUE should be able to check on UI

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1033]
**What happened**:
We cannot check an input `SECRET_VALUE` on UI currently. This should cause input or copy and paste mistakes.

**What you expected to happen**:
To check `SECRET_VALUE`,  the form of UI should be like this image:
![](http://uxmovement.com/wp-content/uploads/2015/08/eye-icon-toggle.png)

Cite: http://uxmovement.com/forms/why-the-confirm-password-field-must-die/

**Comment by d2lam** [comment]
That would be nice!

**Comment by tk3fftk** [comment]
We just started implementation of this issue.
I'd like to talk about the specification. I think there are three parts:
1. Add eye-icon to new secret input to show creating secret value
2. Add eye-icon to existing secret input to show current secret value
3. Add eye-icon to existing secret input to show new secret value

I think 1. is must be implemented and  3. is also needed.

According to docs, original value is never delivered to the UI. Should we implement 2.?
> https://docs.screwdriver.cd/user-guide/configuration/secrets
> A secret’s original value is never delivered to the UI,

**Comment by catto** [comment]
@tk3fftk How about splitting them to two parts, 1+3 and 2?
We can immediately implement the former ones to let users check if their typed or pasted secrets are correct, as first pass.
And after that, we consider whether showing user's password is desirable or not with the result of the first pass, then implement it as second pass.

**Comment by jithin1987** [comment]
> Do we need part 2? If we don't, this issue should be closed.
No, closing this.
