### ISSUE TITLE
SD_BUILD_ID is global for the cluster

### ISSUE THREAD

**Issue by anilkumarmyla** [screwdriver-cd/screwdriver#1037]
Currently SD_BUILD_ID is global for the screwdriver cluster, are there any plans of having a build number that is local to the pipeline, which increments only for builds in that specific pipeline?

**Comment by tkyi** [comment]
Just to be clear, is the only reason you want this feature so you can do package versioning? Or is there another reason?

**Comment by anilkumarmyla** [comment]
> Just to be clear, is the only reason you want this feature so you can do package versioning? Or is there another reason?

Mostly yes, i don't see any other reason

**Comment by tkyi** [comment]
What about using the git tag for versioning? That's what we use for our UI.

We have a script that gets the latest git tag and sets the `VERSION` env var: https://github.com/screwdriver-cd/toolbox/blob/master/git-latest.sh
Then we use it in our `screwdriver.yaml` like this: https://github.com/screwdriver-cd/ui/blob/master/screwdriver.yaml#L46-L48

**Comment by anilkumarmyla** [comment]
Makes sense to use git tags. Closing
