### ISSUE TITLE
Update github module to @octokit/rest

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#1042]
**What happened:**
`github` is deprecated, we should switch to the new version of `octokit/rest`.

**Expectation:**
This should be an item during HIP sprint. 
We need to figure out what the changes during the past major versions bump are. This will be a major change for https://github.com/screwdriver-cd/scm-github

**Comment by tkyi** [comment]
This work has been completed. Screwdriver API has the scm-github changes starting from v0.5.409.
