### ISSUE TITLE
Increase number of lines stored per step log

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1043]
## Context

Screwdriver stores only a 100 lines per step log file, resulting in large number of S3 log files generated for a single `step`. For steps which generates large number of files this results in huge load times when viewing logs as described in this issue https://github.com/screwdriver-cd/screwdriver/issues/1024

## Objective

1.Reduce number of log files generated by a single step.

## References 
1. Issue describing large load times https://github.com/screwdriver-cd/screwdriver/issues/1024
1. PR reverting original fix of fetching more step logs https://github.com/screwdriver-cd/ui/pull/286
1. API enforced number of lines per log file https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/builds/steps/logs.js#L7

**Comment by minz1027** [comment]
With this 1000 lines per file change, the loading speed for logs improves a lot:
Before:
<img width="1384" alt="screen shot 2018-06-22 at 10 15 06 am" src="https://user-images.githubusercontent.com/20427140/41789820-74a699fe-7605-11e8-9b07-7b91b593ff86.png">

After:
<img width="1381" alt="screen shot 2018-06-22 at 10 14 17 am" src="https://user-images.githubusercontent.com/20427140/41789804-68f13a38-7605-11e8-9b01-8f481ac10a7f.png">
