### ISSUE TITLE
Support exclusions in Source Paths

### ISSUE THREAD

**Issue by chilicheech** [screwdriver-cd/screwdriver#1044]
**What happened**:
Source Paths allows you to specify what paths to monitor to trigger the pipeline.

**What you expected to happen**:
It would be awesome for Source Paths to also allow you to exclude paths. For instance, all files in a directory except one: `["docker/*", "!docker/Dockerfile"]`

**How to reproduce it**:
https://docs.screwdriver.cd/user-guide/configuration/sourcePaths

Cheers,

**Comment by jithine** [comment]
There is a limitation with current implementation. Negation works only if there is an existing parent path in `sourcePaths` it cannot be used for blanket path exclusions. Eg: ["!do-not-build-on-changes-here/"]

**Comment by jithine** [comment]
re-opening to support blanket exclusions
