### ISSUE TITLE
cut/paste of step not alligned

### ISSUE THREAD

**Issue by lgfausak** [screwdriver-cd/screwdriver#1049]
**What happened**:
When I cut and paste the step output the pasted format is staggererd.

**What you expected to happen**:
 it would be nice if the cut/paste looked like what was on the screen, or the cut and paste simply omitted the timestamp.

**How to reproduce it**:
run anything that has more then a single line output in the step.  Then try to cut and paste that output to a text window (maybe vi).

![screen shot 2018-05-07 at 10 14 16 am](https://user-images.githubusercontent.com/2189483/39719711-a5498640-51ff-11e8-9e8f-05427982643f.png)

here is the pasted output:

00:11:02
 $  psql -Upostgres reboot -c 'select stack_id, node_id, nodetype_id, service_tag, pwr2262_ts from server where reboot_signature=1 ORDER BY pwr2262_ts DESC limit 5'
00:11:02
        stack_id      |    node_id    | nodetype_id | service_tag |       pwr2262_ts       
00:11:02
 - -------------------+---------------+-------------+-------------+------------------------
00:11:02
   sXXXXXXXXXXXXXXngs | CXXXXXXXXXX14 | HYPERVISOR  | XXXXXXX     | 2018-05-05 04:56:40+00
00:11:02
   sXXXXXXXXXke       | CXXXXXXXXXX10 | CEPHOSD     | XXXXXXX     | 2018-04-26 18:23:52+00

See how the timestamps are on a line by themselves? This is similar to issue: https://github.com/screwdriver-cd/screwdriver/issues/1034

**Comment by jithin1987** [comment]
Fixed now.
