### ISSUE TITLE
Pipeline visualizer for events that propagate across multiple pipelines

### ISSUE THREAD

**Issue by anilkumarmyla** [screwdriver-cd/screwdriver#1056]
It would be nice to have a pipeline visualizer to track an event (a commit) that triggers multiple pipelines

**Comment by itleigns** [comment]
I saw a message that said, "You can also view this page from your pipeline. Simply right click on the trigger job in your pipeline and click on Open visualizer." But I can not find a text box to go from the pipeline page to the visualizer page that says "Open visualizer.". Is it still a work in progress?

**Comment by adong** [comment]
> I saw a message that said, "You can also view this page from your pipeline. Simply right click on the trigger job in your pipeline and click on Open visualizer." But I can not find a text box to go from the pipeline page to the visualizer page that says "Open visualizer". Is it still a work in progress?

It's not implemented, I can add it as an enhancement.
