### ISSUE TITLE
Build Periodically UX

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1058]
## Context

UI should differentiate builds started by scheduler.

## Objective

1. Events list should show an icon for periodic builds.
1. Build detail page should show an icon for periodic builds.
1. Clicking the icon (or hover) should give message to user that this build was started because of scheduler.

## References 

Original Feature https://github.com/screwdriver-cd/screwdriver/issues/688

**Comment by jithin1987** [comment]
@stolfi that flow looks good. Each schedule can be a trigger like `~pr/commit`

cc @DekusDenial

**Comment by d2lam** [comment]
I think we can just change the commit message or the cause message to something like `Automatic build: ...` 
Don't think we need an extra node for it.

**Comment by jithin1987** [comment]
Based on our discussion lets do this. For a periodic build we will change user to be called `Scheduler` and hover message will say "Started by Scheduler" instead of "Started by username"

**Comment by tkyi** [comment]
Should now show a special `User` and `causeMessage` in UI for builds started by the queue.

For example, for a build_periodic triggered event: User will show as `Screwdriver scheduler` and causeMessage (upon hovering on commit sha) will show as `Started by periodic build scheduler`:
<img width="1677" alt="Screen Shot 2019-04-17 at 4 26 52 PM" src="https://user-images.githubusercontent.com/3230529/56327160-fac2be00-612d-11e9-9a77-dea9ac27937d.png">

If a build is manually started/restarted through the UI, the `causeMessage` will also reflect that.
<img width="433" alt="Screen Shot 2019-04-17 at 4 32 07 PM" src="https://user-images.githubusercontent.com/3230529/56327253-745aac00-612e-11e9-8dd3-fbbc4d6005eb.png">

In general, users can now pass in `creator` and `causeMessage` when creating new events.
