### ISSUE TITLE
Pull requests section redesign

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1067]
## Context

We have new design for displaying Pull Requests on a pipeline page

Design mocks:
![05a_subway_selected](https://user-images.githubusercontent.com/3230529/39542590-d0ef84b2-4dfd-11e8-967b-cb2408ce6add.png)
![05b_subway_successful](https://user-images.githubusercontent.com/3230529/39542598-d48c9d94-4dfd-11e8-8033-3d26caf35aab.png)

## References

https://github.com/screwdriver-cd/screwdriver/issues/803#issuecomment-350404017

**Comment by jithin1987** [comment]
@DekusDenial can we get this grouping of jobs under Pull requests taken care of. 
This will help in couple of use-cases

1.. Adding Stop button for "Stop all PR jobs use-case" - https://github.com/screwdriver-cd/screwdriver/issues/1285#issuecomment-466269598
1. Adding Start button for "Start all PR jobs use-case" -  https://github.com/screwdriver-cd/screwdriver/issues/579

**Comment by tk3fftk** [comment]
We are also planning to draw a workflow graph under Pull requests tab like the events tab in https://github.com/screwdriver-cd/screwdriver/issues/1010#issuecomment-462615428

**Comment by jithin1987** [comment]
@tk3fftk My current thought process is this

1. Without `prChain` Pull Requests UX will be like the mocks above - flat list of jobs in PR
1. With `prChain` you can add the minigraph like how `Events` tab has.

But with both cases overall UX for the PR header stays same - Pull Request number + titile + associated meta. This way the UX will have some consistency over whether PR chain is enabled or not. 

cc @DekusDenial @chasturansky
