### ISSUE TITLE
Collections should be accessible from all pages

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1069]
**What happened**:

Collections is shown only if user is logged in and from home page.

**What you expected to happen**:

1. There should be a link in header along with Templates so that user can navigate to collections.
2. (Optional) Always present collection component in all pages which is collapsed by default.

**Comment by tkyi** [comment]
Should be resolved with latest Collections update:
<img width="1680" alt="Screen Shot 2019-10-09 at 2 31 51 PM" src="https://user-images.githubusercontent.com/3230529/66522142-96ac0180-eaa1-11e9-8d59-6cbbd690e0ce.png">
