### ISSUE TITLE
Build JWT should be generated at execution phase

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1075]
## Context

API generates build JWT token when it sends a build config to an executor. This approach works as long as there is not much delay from the time API generates the build config and the time the build is actually executed. With uses cases like `blockedBy`, `freezeWindows` there could be significant delay from the time API generates build config and when the build is actually executed. Also when used with `executor-queue`, API does not have all relevant information to generate JWT, such as time out config for the underlying executor. This warrants a need to generate JWT token when an executor actually runs the build so that it's expiry time starts from actual build execution and not count for the time it's awaiting it's execution.

## Objective

1. API generates a temporal scoped JWT when it sends a build to executor.
2. Executor exchanges the temporal JWT with actual build scoped JWT.
3. Temporal scoped JWT should not be exposed inside a build.

## References
1. API Design https://github.com/screwdriver-cd/models/pull/245#issuecomment-390619885 Thanks @sakka2

**Comment by sakka2** [comment]
@jithin1987 
> can they exchange temporal JWT for build JWT token without making network call ?

I thought it would be better not to make network call too, but Inside each executors, it is difficult to exchange JWT without calling new API.
The network should be internal and it calls only one time at the start of builds, so the network load will not be so much.

Another way I thought is that make If statement [here](https://github.com/screwdriver-cd/models/blob/master/lib/build.js#L214), before the `this[executor].start` method. Only in case the `executor-queue`, generate temporal JWT and in case the others, generate build JWT as before. This way do not need to call API in non-queue executor, but cannot avoid some case you mentioned above. And It seems making if statement may not a smart way.

Do you have any good idea?

**Comment by jithin1987** [comment]
@sakka2 API call makes sense. Let each executor except `queue` have logic to exchange temporal JWT. Thanks for nailing down the flow.

**Comment by sakka2** [comment]
@jithin1987 
I added new API and fixed executors to use it.
Could you review these changes please?
