### ISSUE TITLE
General approach to integrate with an external service

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1077]
## Context

Users who are looking to move from Jenkins to Screwdriver wants to know an approach to replace Jenkins plugins. Screwdriver recently launched SonarQube support for coverage and test results. We can use this as a model on how to integrate external systems (supported by Jenkins plugins) as micro services.

## Objective

1. Document a model for integrating micro services with SonarQube as a base example.
1. Micro service may or may not be hosted by Screwdriver.

## References
1. [Sonar Announcement](http://blog.screwdriver.cd/post/173938693832/code-coverage-in-screwdriver)
2. [Hygieia Service](https://github.com/capitalone/Hygieia)

**Comment by tkyi** [comment]
Related to https://github.com/screwdriver-cd/screwdriver/issues/735

**Comment by jithin1987** [comment]
I don't see anything special SD needs to do to handle external integration. Perhaps login aspects, but than can be considered on a case by case basis.

**Comment by jithin1987** [comment]
I don't see anything special SD needs to do to handle external integration. Perhaps login aspects, but than can be considered on a case by case basis.
