### ISSUE TITLE
Generate and Use Deploy Keys

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#1079]
Currently, most CI/CD services today will automatically add a R/O Deploy key to your repository and use those on checkout.

Screwdriver does not.  Would it be possible to support this?

--
UPDATE: https://github.com/screwdriver-cd/screwdriver/issues/1079#issuecomment-658256382

**Comment by jithin1987** [comment]
Doesn't user has to generate the Deploy key  and make it available to the CI/CD tool ?

What Screwdriver could do is - 
1. Define a secret KEY for the Deploy key. User must add this in secret for the pipeline,
2. Modify `scm-github` to use that KEY if available, and use it for ssh based checkout.

**Comment by stjohnjohnson** [comment]
Nah, if you use anything like CircleCI, Werker, Codeship, etc. it will generate and add the deploy key for you via [API](https://developer.github.com/v3/repos/keys/#add-a-new-deploy-key).

**Comment by jithin1987** [comment]
We could use this to support private repositories without having wide Oath access. Ask user to provide a Deploy Key and use that for checking out Private repository. So flow will be.

1. Use generates Deploy key at Github.
1. As part of create pipeline take this input and store the KEY in Secrets and then use this for git operations.
1. If user wants to move to a Deploy key after creating pipeline, then add the key at Pipeline -> Options
1. Modify `scm-github` to use that KEY if available, and use it for ssh based checkout.

**Comment by jithin1987** [comment]
We can automate generation part later on, but I guess for a CI/CD tool to do that, we should  be asking Oauth scope for adding keys.

**Comment by stjohnjohnson** [comment]
You could skip 1-3 and just take it as a secret.

**Comment by jithin1987** [comment]
> You could skip 1-3 and just take it as a secret. For the short-term

That's my first suggestion https://github.com/screwdriver-cd/screwdriver/issues/1079#issuecomment-393631839

**Comment by gthosaniNetskope** [comment]
@stjohnjohnson, @jithin1987 wondering if there was any ETA for this issue ?

**Comment by supra08** [comment]
Hi @jithine @tkyi ! I would like to work on this as my GSoC 2020 project. I am able to comprehend the goal from this issue as well as #1415. I would like to know if there are some more points to it that I should consider before drafting the proposal.

**Comment by jithine** [comment]
Hello @supra08 . Thank you for considering to work on this Screwdriver projects. I have created this slack channel for discussions without Screwdriver workspace https://screwdriver-cd.slack.com/archives/C010634SGTY Feel free to join so that we can discuss in more real time manner.

Couple of points I would consider for SCM project is that Screwdriver does support multiple SCM. While most of out features are geared towards github.com & GHE (Github enterprise) changes should be backward compatible and if possible should be implements in all scm's we support.

https://github.com/screwdriver-cd?q=scm-&type=&language=

**Comment by supra08** [comment]
Hi @jithine ! Can you please send me an invite link to the slack workspace. 
I'll do some homework based on the comment and report back to you on slack.

**Comment by jithine** [comment]
@supra08 Please use https://slack.screwdriver.cd/ to sign up.

**Comment by supra08** [comment]
Thanks!

**Comment by jithine** [comment]
Capturing product requirements

- [ ] When creating a pipeline, generate a deploy key.

  - [ ] SCM settings should have a config to denote if Deploy key generation is supported.

  - [ ] UI should display a checkbox where user can optionally disable generating deploy Key,  if the SCM module supports deploy key generation.
  - [ ] If SCM module doesn't support generating deploy key, then UI should not display this setting.

  - [ ] Generated deploy should be stored as a secret `SD_SCM_DEPLOY_KEY`

- [ ] If available, use the generated deploy key for cloning  SCM repo in `sd-setup-scm` bookend. 

- [ ] User should be able to update `SD_SCM_DEPLOY_KEY` from secrets tab.

  - [ ] UI should display `SD_SCM_DEPLOY_KEY` separately to denote it's significance to SCM operations.

  - [ ] UI should display age of `SD_SCM_DEPLOY_KEY` deploy key.

  - [ ] UI should enable rotating Deploy Key by admin users.
