### ISSUE TITLE
SCM Branch-specific jobs

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#1082]
## Context
The issue of #723 was closed but [SCM Branch-specific jobs workflow](https://github.com/screwdriver-cd/screwdriver/blob/master/design/workflow.md#scm-branch-specific-jobs) is not implemented yet.
The workflow will make ease to use git flow.

## Objective
Allow to specify branch to commit trigger.

## Related links
Documentation: https://github.com/screwdriver-cd/screwdriver/blob/master/design/workflow.md#scm-branch-specific-jobs
Related to: #723

**Comment by yuichi10** [comment]
I have split up the work into these tasks for now:
- [ ] get pipelines by like search of scmURI then search pipeline which have ~commit:{branch} trigger.
- [ ] fix regex TRIGGER to allow regex characters at data-schema.
- [ ] add branch to data-schema of SCHEMA_HOOK.
- [ ] use edge.src as a regex and check the trigger does match the regex or not at workflow-parser.
- [ ] if startFrom is ~commit, search jobs by trigger of ~commit and ~commit:{branch name} at models.
- [ ] udpate workflow documentation

**Comment by yuichi10** [comment]
To get pipelines which you start jobs, I will add function to scm repositories which get branches from scms api.

The flow is as below
1. get branches by the new function
2. create scmUris by using the branch list
3. search pipelines from the scmUris and you get the pipelines which is related to the repository you using
4. search these pipelines which have the trigger to start by using eventFactory.getJobsFromTrigger. 
5. Then you will get the pipelines which we have to start jobs.

**Comment by jithin1987** [comment]
@yuichi10 What's the use case for branch specific workflows ? Can't user specify branch while creating pipeline ?

**Comment by yuichi10** [comment]
I want to verify the specifications about SCM Branch-specific jobs.

Assuming the project which have two pipelines as below.
![piiax5b18eb55475038c7601b956c](https://user-images.githubusercontent.com/4645011/41087486-cd1a4228-6a77-11e8-8ca5-bbbb93b5539f.jpg)

When developer push to staging branch, the red jobs will triggered. (I think this is no problem)
![usetf5b18eb6bdf9db0c260d0a6fb](https://user-images.githubusercontent.com/4645011/41087550-f9404424-6a77-11e8-806a-0b495f8c534f.jpg)

And now when developer click start button on staging pipeline page, the red jobs will triggered now.
![yl5vh5b18eb55475038c7601b956d](https://user-images.githubusercontent.com/4645011/41087647-2a226fd6-6a78-11e8-83c2-e5feb32678eb.jpg)

I want to make sure the behavior, when developer click start button.

1. When developer click start button at staging pipeline, `~commit` and `~commit:staging` are triggered.
2. When developer click start button at staging pipeline, it does not affect other pipelines (e.g. master pipeline's job are not triggered).

What do you think the behavior is best, when developer click the start button on the pipeline page?

**Comment by yuichi10** [comment]
I want to verify the specifications about SCM Branch-specific jobs.

Assuming the project which have two pipelines as below.
![piiax5b18eb55475038c7601b956c](https://user-images.githubusercontent.com/4645011/41087486-cd1a4228-6a77-11e8-8ca5-bbbb93b5539f.jpg)

When developer push to staging branch, the red jobs will triggered. (I think this is no problem)
![usetf5b18eb6bdf9db0c260d0a6fb](https://user-images.githubusercontent.com/4645011/41087550-f9404424-6a77-11e8-806a-0b495f8c534f.jpg)

And now when developer click start button on staging pipeline page, the red jobs will triggered now.
![yl5vh5b18eb55475038c7601b956d](https://user-images.githubusercontent.com/4645011/41087647-2a226fd6-6a78-11e8-83c2-e5feb32678eb.jpg)

I want to make sure the behavior, when developer click start button.

1. When developer click start button at staging pipeline, `~commit` and `~commit:staging` are triggered.
2. When developer click start button at staging pipeline, it does not affect other pipelines (e.g. master pipeline's job are not triggered).

What do you think the behavior is best, when developer click the start button on the pipeline page?

**Comment by minz1027** [comment]
This behavior seems reasonable to me @jithin1987 ^^

**Comment by tkyi** [comment]
@yuichi10 Your proposal sounds reasonable to me.
If the developer clicks start button on the master pipeline page, it would start both `~commit` and `~commit:/^.*$/`, right?

So the rules would be: 
1. If the user makes a commit to `<branch>`, all triggers that match `~commit:<branch>` will be triggered, and `~commit` if the pipeline is configured to `<branch>`.
1. If the user clicks the Start button on a pipeline, `~commit` and all `~commit:<branch>` that match that pipeline's `<branch>` will start.

**Comment by Filbird** [comment]
It seems to be that (2) makes the most intuitive sense. From a developer's perspective, when I specify `~commit:staging` on a job, `main`, in **pipeline:master**, I expect `main` to run only when a new commit is made to the `staging` branch. 

In (1) there is also an implicit assumption that `main` should be run whenever the `staging` branch pipeline runs (even if there is no new commit). In this case remote requires seems more appropriate.
``` 
requires:[sd@stagingPipelineId:stagingJobName]
```

**Comment by jithin1987** [comment]
@yuichi10 
> I want to make sure the behavior, when developer click start button.
>
>    1. When developer click start button at staging pipeline, ~commit and ~commit:staging are triggered.
>    1. When developer click start button at staging pipeline, it does not affect other pipelines (e.g. > master pipeline's job are not triggered).

👍 Sounds good to me.
When manually clicking `Start` button in UI it should affect jobs only in the current pipeline user is interacting with.

**Comment by yuichi10** [comment]
Thank you for your comments! 

tkyi's explain is easy to understand!
> 1. If the user makes a commit to <branch>, all triggers that match ~commit:<branch> will be triggered, and ~commit if the pipeline is configured to <branch>.
> 2. If the user clicks the Start button on a pipeline, ~commit and all ~commit:<branch> that match that pipeline's <branch> will start.

I agree with Filbird's opinion. If developer want to run whenever not pipeline's <branch> job, they need to use remote requires. 

Thank you guys again!
I implement SCM Branch-specific jobs by this policy!

**Comment by minz1027** [comment]
@yuichi10 Hi Yuichi, I noticed that we're only adding the branch trigger for `~commit`, not `~pr`. That means if I have `~commit:staging` and I opened a PR against `staging` then nothing will happen right? Is it the expected behavior? Can you elaborate more on the use case for this feature? Thanks!!

**Comment by yuichi10** [comment]
@minz1027  Hi minz, thank you for your notice.
Yes now if you open PR for `staging` branch, nothing happen, even there is `~commit: staging` trigger. 
I am going to consider the use case of this feature.

**Comment by yuichi10** [comment]
@minz1027  To me, `~pr` for specific branch is also necessary.  

How about to use same way as `~commit` specific branch. 
If user want to trigger specific branch at pr, set `~pr:branchName` or `~pr:/^branch.*$/` to requests.

I think we can develop commit and pr functions separately, thus after this commit specific branch is finished, develop ~pr function.

**Comment by yuichi10** [comment]
There is a bug, to break the pipeline view when restart the specific branch job.
I try to find the reason now.

**Comment by yuichi10** [comment]
I found a bit bug.

When restart job, Screwdriver try to build in the same way as previous, and get screwdriver.yaml from the `sha`.
When you restart specific branch job, the `sha` is not belong to the pipeline branch, so if the branch have different screwdriver.yaml, the pipeline's workflow are changed.

**Comment by yuichi10** [comment]
Maybe I can fix this problem by using `configPipelineSha`.

**Comment by tkyi** [comment]
Hm so if I understand correctly, you are saying:
If you have pipeline configured to branch `master` and a job configured to branch `foo`, the issue is when you restart the `foo` branch job, it uses `foo` screwdriver.yaml file instead of `master` screwdriver.yaml?

**Comment by yuichi10** [comment]
Yes! So I think need to preserve the branch `master` sha by using `configPipelineSha`.

**Comment by jithin1987** [comment]
@catto yes, we should have the same behavior. We do get some asks about relaxing this restriction, however in my opinion it should be based on a configuration. For now, lets prevent the further job triggers.

**Comment by marian-r** [comment]
@jithin1987 @catto having it based on SD configuration would mean letting PR jobs to trigger next jobs as outlined in #1010 .

**Comment by jithin1987** [comment]
> having it based on SD configuration would mean letting PR jobs to trigger next jobs instead of preventing it...as outlined in #1010 .

yes, doing it behind SD config will solve it.

**Comment by marian-r** [comment]
@jithin1987 cool, is that feature on the horizon?
