### ISSUE TITLE
500 when Github sends a synchronize event

### ISSUE THREAD

**Issue by jer** [screwdriver-cd/screwdriver#109]
I guess that's what it sends when you force-push a branch for a PR:

Request URL: http://a4677c9873c9611e6aa7102b92f75d5c-1135862614.us-west-2.elb.amazonaws.com/v3/webhooks/github
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/ebd57e0
X-GitHub-Delivery: 51d2f800-656d-11e6-98e9-e30f7b03e6aa
X-GitHub-Event: pull_request
X-Hub-Signature: sha1=f995b5c95a9487d84a4f6725a14d5b4b363840a9

--------------------------------------------------------------------------------------

160818/175809.038, [request,webhook-github,51d2f800-656d-11e6-98e9-e30f7b03e6aa] data: Received event pull_request
160818/175809.038, [request,webhook-github,51d2f800-656d-11e6-98e9-e30f7b03e6aa] data: PR #50 synchronize for git@github.com:screwdriver-cd/launcher.git#master
160818/175809.647, [request,webhook-github,51d2f800-656d-11e6-98e9-e30f7b03e6aa,a6cb05361974ef8779c9d684619cf530d7f79fc4] data: PR-50 stopped
160818/175810.094, [request,server] data: TypeError: config.tokenGen is not a function
    at BuildModel.start (/usr/src/app/node_modules/screwdriver-models/lib/build.js:150:30)
    at getCommitSha.then.then.build (/usr/src/app/node_modules/screwdriver-models/lib/buildFactory.js:140:31)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
160818/175808.947, [response] http://0.0.0.0:8080: post /v3/webhooks/github {} 500 (1149ms)

**Comment by petey** [comment]
synchronize was never updated when we changed executor to require apiUrl and tokenGenerator function.

I still think these things should be given to the executor upon instantiation so the models do not have to even care about it.
