### ISSUE TITLE
Commands & Templates should store create time

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1090]
**What happened**:

Create time is not stored when creating templates or shared commands. Without this UI cannot display when was a template or command was last published.

**What you expected to happen**:

Create time should be stored in database when commands and templates are created. Similar to https://github.com/screwdriver-cd/data-schema/blob/master/models/pipeline.js#L37-L40

**Comment by tkyi** [comment]
For old templates and commands with no `createTime`, I'm thinking we can just leave `createTime = null` andd handle it accordingly in the UI.

## Tasks
- [] [data-schema] Update commands, templates, and tags with `createTime`
- [] [models] Update commands, templates, and tags to store `createTime` when creating

**Comment by jithin1987** [comment]
@tkyi
> For old templates and commands with no createTime, I'm thinking we can just leave createTime = null and handle it accordingly in the UI.

Can we set it to `Date.Now()` (time when we add this field) for old ones, this makes consuming the end point easier for all clients. Also if API supports sort templates by create time, then having a default value helps.

**Comment by tkyi** [comment]
We should be able to handle the case where no `createTime` exists.
Storing `createTime` for commands and templates should be done now. Using that information to sort templates and commands in the UI will occur in a separate issue.
