### ISSUE TITLE
Command usage improvement

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1095]
**What happened**:
UI only shows a command usage like `sd-cmd exec foo/bar@1.2.3`. There are not enough information if the command has some options (especially required options).

**What you expected to happen**:
Command should have a customizable usage and UI shows the usage instead of default usage or shows both usages.

**Comment by tkyi** [comment]
I think it would be good to add an optional field to commands called `arguments` where the user could add arguments to the command.

Example in sd-command.yaml:
```
namespace: foo
name: bar
arguments: -h <host> -d <domain>
```
Should display:
```
Usage: sd-cmd exec foo/bar@1.2.3 -h <host> -d <domain>
```

**Comment by stjohnjohnson** [comment]
I wouldn’t be so specific. Everything after the foo/bar@1.2.3 should be
passed directly to the underlying tool. We don’t want to have to recreate
every option parser.

**Comment by tkyi** [comment]
@stjohnjohnson I guess I was thinking more from a documentation perspective. It would just be an optional string where people can add arguments. We wouldn't handle it in any special way.
