### ISSUE TITLE
Step marked as failed even if succeeded

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1101]
**What happened**:
I started new build that has only a step runs `echo ok`.
And the build was finished with successful status. But the status of the step was failure.

**What you expected to happen**:
If the build is completed successfully, both the build and the step are marked as success.
Otherwise both the build and the step are marked as failure.

**How to reproduce it**:
I cannot reproduce this so far. I rarely see this behavior.

**Comment by jithin1987** [comment]
This should not happen, we have not seen this behavior yet. If you see this again or have an example to share please reopen this.
