### ISSUE TITLE
UI to view workspace/src

### ISSUE THREAD

**Issue by nirvanagit** [screwdriver-cd/screwdriver#1108]
**What happened**: Need ui for viewing `workspace/src` in sd v4

**Comment by petey** [comment]
Screwdriver shows all files saved in $SD_ARTIFACTS_DIR. If you are generating files you need to look at later, it's recommended that you copy them there.

**Comment by tkyi** [comment]
In SDv4 (unlike Jenkins), the workspace is destroyed after each build, so I'm also not sure what the value would be here. I think @petey 's suggestion should be a valid workaround.
