### ISSUE TITLE
Redirect to home when re-sign in, and cannot go back

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#1111]
**What happened**:
When expire the login and re-sign in, the UI go to Home page and sometime cannot go back the page I was looking at. 

**What you expected to happen**:
Able to go back the page I was looking at or ui redirect to the page I was looking at when sign in automatically.

**How to reproduce it**:
1. Login Screwdriver
2. Open several Screwdriver pages and look at build page or something at every page.
3. Sign out from Screwdriver at the one of them page.  
4. Re-sign in to the Screwdriver.

When you check all pages, some of the page cannot go back the page you were looking at.

**Comment by tkyi** [comment]
Should no longer be an issue
