### ISSUE TITLE
Create event with Metadata

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1113]
## Context

For users who programmatically invoke API to start a build there is no option to set context, which can be set in the form of [Metadata](https://docs.screwdriver.cd/user-guide/metadata). However this requires create event API to provide an option to take in data which can be used to seed `Metadata`

## Objective

1. User should be allowed to create an event with Metadata

**Comment by tkyi** [comment]
## Example
1. A [pipeline](https://cd.screwdriver.cd/pipelines/1146/events) makes a POST to create an event with metadata
```
{
    'foo': 'bar',
    'one': 1
}
```
2. A [second pipeline](https://cd.screwdriver.cd/pipelines/1131/events) is triggered to start with that metadata

You can see the example repositories in the [screwdriver-cd-test organization](https://github.com/screwdriver-cd-test/).
