### ISSUE TITLE
Support order of steps

### ISSUE THREAD

**Issue by pushkar2017** [screwdriver-cd/screwdriver#1115]
Screwdriver should allow users to denote which steps from a template they want to use, and in what order. They should be able to omit steps.

**Comment by jithin1987** [comment]
Order of steps is defined by template owner and most likely will affect the usage of template if it's altered. It's best for user to work with template owner if user believes order is not appropriate. 

If user wan't to omit a template step they can replace it. Please refer docs on how to https://docs.screwdriver.cd/user-guide/templates#using-a-template

**Comment by jithin1987** [comment]
Closing this since I believe tinkering with order of steps in a template is not something Screwdriver should support.
