### ISSUE TITLE
Template tags cannot start with a number

### ISSUE THREAD

**Issue by neeleshkorade** [screwdriver-cd/screwdriver#1116]
**What happened**:
When I tried to tag a template as `1-STABLE`, it gave me the following error-

`Error: Error tagging template. 400 (Bad Request): child "tagName" fails because ["tagName" with value "1-STABLE" fails to match the required pattern: /^[a-zA-Z][\w-]+$/]`

**What you expected to happen**:
I am basically looking to have a STABLE version for each major version of the template.
Could the regex be made more flexible?

** How to reproduce it**:
Use the `template-tag` function to tag a template version with a label that has a number in it. I used `1-STABLE` and it failed with the error given above.

**Comment by tkyi** [comment]
Numbers are allowed, the tag name just cannot start with a number. Can you use `STABLE1` or
`STABLE-1`?

**Comment by tkyi** [comment]
Closing issue since it isn't really a bug and there are many reasonable workarounds.
