### ISSUE TITLE
Introduce `Unstable` build status

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1122]
## Context/Objective

Give users an option to mark their build as unstable, rather than going for outright failure on certain step failures. Onus is own user to make sure their step passes and call API to mark build as `Unstable` on certain conditions. For example a user would want their build to complete all steps even after test failures and at same time have the build marked as `Unstable` if certain conditions are not met.

## Implementation
- [x] [data-schema] Allow `Unstable` status for build.
- [x] [screwdriver] Provide endpoint for build to mark its status as `Unstable`. (Via API Call)
- [x] [UI] Display `Unstable` builds with appropriate build status Icon.
- [x] [models] If a build's status is Unstable don't change it to `Success` at end of build.

**Comment by d2lam** [comment]
This should be done. Here is an example of a pipeline updating unstable build: https://cd.screwdriver.cd/pipelines/1092/events

**Comment by tkyi** [comment]
Related to https://github.com/screwdriver-cd/screwdriver/issues/1029

**Comment by drewfish** [comment]
Can we use markdown in the `statusMessage`?
