### ISSUE TITLE
UI label improvements

### ISSUE THREAD

**Issue by awick** [screwdriver-cd/screwdriver#1124]
Would it be possible to allow more characters for the labels?  Right now you get basically 6 characters.  For those of us who use screwdriver to run jobs manually its makes it really hard to see and have to use the mouse overs.  Honestly would love a way to turn off the bubbles or put the bubbles to the left of the labels if requires is an empty array.

![image](https://user-images.githubusercontent.com/427321/41431247-4e5d66f4-6fe0-11e8-80d3-06bcb02ab8fe.png)

If you can point me to where to look in the code maybe I can help.

**Comment by petey** [comment]
https://github.com/screwdriver-cd/ui/blob/master/app/components/workflow-graph-d3/component.js#L144

**Comment by catto** [comment]
Fixed via screwdriver-cd/ui#309
Thank you for the contribution
