### ISSUE TITLE
config-parse-error in parent pipeline deletes all children and secrets

### ISSUE THREAD

**Issue by Filbird** [screwdriver-cd/screwdriver#1130]
**What happened**:
In a parent pipeline, I unintentionally made a change to my `screwdriver.yaml` which resulted in a `config-parse-error`. This caused its child pipelines and secrets to be deleted.

![screen shot 2018-06-19 at 6 16 51 pm](https://user-images.githubusercontent.com/11892496/41632070-fdce8a04-73ec-11e8-8456-89b405ec106a.png)

When rolling back the change, the child pipelines were freshly created, losing all build history. Furthermore, the original pipeline secrets did not return.

**What you expected to happen**:
`config-parse-error` should not automatically delete child pipelines and secrets.

**How to reproduce it**:
1. Create a parent pipeline with one or more children and secrets.
2. Edit and commit the underlying `screwdriver.yaml` such that it becomes invalid.

**Comment by jithin1987** [comment]
This is fixed.
