### ISSUE TITLE
External Configuration does not make files from the Configuration repository available

### ISSUE THREAD

**Issue by renaud-yahoo** [screwdriver-cd/screwdriver#1132]
NOTE: This harks back to the Screwdriver3-era version of External Configuration.

In SD3, when using the External Configuration feature (http://blog.screwdriver.cd/post/175047701767/manage-multiple-pipelines-from-a-single-external), the whole git repository containing the yaml file was cloned into the workspace. This allowed for interesting configurations, where a given "pipeline" (job) would be able to customise the "target" source tree's workspace (altering build files as needed) by using pre-written files that were committed into the Configuration repository.

This has been lost with the current version of the External Configuration on Screwdriver4; CONFIG_DIR is set to $SOURCE_DIR, and I can't access the SD3 equivalent of CONFIG_DIR, breaking up the workspace alteration logic that I intended to share between SD3 (previous era) and SD4 (current era).

**Comment by jithin1987** [comment]
@minz1027 @Filbird Is it an easy change to have parent pipelines GIT repository available in the child pipeline under `$SD_CONFIG_DIR` ? Then steps in the child pipeline (which comes from screwdriver.yaml in parent pipeline) access the parent pipeline files under path `$SD_CONFIG_DIR`

So child pipelines  in addition to inheriting `screwdriver.yaml` from parent pipeline can also get access to any files in parent/config pipelines GIT repository under `$SD_CONFIG_DIR`

**Comment by Filbird** [comment]
I don't think it should be too difficult! At a glance I believe we can do this at the `sd-scm-setup` level.

**Comment by jithin1987** [comment]
This is available now https://docs.screwdriver.cd/user-guide/environment-variables#directories
