### ISSUE TITLE
Can't stop blocked job via UI

### ISSUE THREAD

**Issue by jaysoffian** [screwdriver-cd/screwdriver#1142]
**What happened**: 

A job had become blocked on itself. In an attempt to fix, I clicked the restart button. That just created a second job. The UI didn't allow me to stop (cancel) the redundant job.

**What you expected to happen**:

I should be able to cancel a blocked job.

**How to reproduce it**:

Get a job into blocked state. Note that the UI doesn't show the "Stop" button.

**Comment by jithin1987** [comment]
Fixed via https://github.com/screwdriver-cd/ui/pull/322
