### ISSUE TITLE
Swagger response schemas missing for auth, status, and stats

### ISSUE THREAD

**Issue by nicolaifsf** [screwdriver-cd/screwdriver#115]
response schemas for login, status, and stats are currently not defined

**Comment by Filbird** [comment]
Response schemas (for GETs) are also missing for **versions**, **contexts**, **badge**, and **artifacts**.

**Comment by Filbird** [comment]
As **badge** and **artifacts** are redirects, it may not make sense to add response schemas for theseendpoints.

The majority of non GET endpoints do not have response schemas defined. Likewise, the usefulness of adding response schemas for these endpoints is questionable in my opinion.

**Comment by Filbird** [comment]
Since we've covered the bulk of the response schemas, I'll be closing this PR.

Please feel free to reopen if you feel that more response schemas are needed.
