### ISSUE TITLE
Show error message when pod failing to pull image

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#1153]
**What happened**:

When I start job, the build did not start because the image, I try to use for build, was not exist. 
Screwdriver UI did not show any message to me, thus I had no idea why the build does not start until I research k8s pod information.

**What you expected to happen**:
Show message when failed to pull image, and delete pod.

**How to reproduce it**:
Build with non exist image.

**Comment by jithin1987** [comment]
We should be showing message in UI when build cannot start. It's handled in hyperctl image used to setup VM. Perhaps your SD cluster does not have the required changes See https://git.ouroath.com/cocktails-screwdriver/hyperctl-docker/blob/master/scripts/hyper-runner.sh#L18

cc @minz1027

**Comment by jithin1987** [comment]
`executor-k8s-vm` handles this already https://github.com/screwdriver-cd/hyperctl-image/blob/master/scripts/hyper-runner.sh#L4

Closing this in favor of https://github.com/screwdriver-cd/screwdriver/issues/1180
