### ISSUE TITLE
Feature Request: Edit collection description

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1154]
Currently, we cannot edit already created collection's descriptions. I think it is useful to be able to edit already created collection's descriptions.

**Comment by tkyi** [comment]
You can now edit collection descriptions but there's a couple things I think are still missing:
1. You can't add a description if you didn't already have one to begin with.
2. It would be nice to also be able to edit collection names at the same time.

**Comment by tkyi** [comment]
The above requests were addressed and merged into production. There's some minor CSS tweaks that could be done, but this feature is complete for now.
