### ISSUE TITLE
Reducing dependencies on Habitat

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1164]
# Context
Screwdriver.cd uses Habitat in each build environment. Habitat makes it possible for SD.cd to provide a compatible build environment across various build containers.
Now we depend on it for even git and curl command. And they have much impact to results of every build.
But sometimes depot goes down for a while and builds on SD.cd cannot get started, so we should reduce runtime dependencies on Habitat step by step.
https://status.habitat.sh/

# Objective
- [ ] Add more packages/binaries used well to launcher image
- [ ] Avoid [calling depot API during runtime](https://github.com/screwdriver-cd/sd-step/blob/master/hab/hab.go#L43-L46)
- [ ] (optional) Consider how we support commands used on macOS via jenkins-executor. [Habitat does not support macOS currently.](https://github.com/screwdriver-cd/coverage-sonar/blob/master/commands.txt#L1)

**Comment by jithin1987** [comment]
> Add more packages/binaries used well to launcher image

Some work on this was already done in this issue https://github.com/screwdriver-cd/screwdriver/issues/877

I believe the binaries are in launcher (cc @minz1027 ) but we need to mount in in the container in executors `executor-vm`, `executor-k8s-vm`, `executor-docker`

**Comment by tk3fftk** [comment]
#1163
