### ISSUE TITLE
Temporary JWT token exchange should happen in Executor

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1167]
**What happened**:
Today temporary JWT token is exchanged in `executor-base` with the assumption that build starts immediately. See https://github.com/screwdriver-cd/screwdriver/issues/1030

But that's not a realistic expectation with all executors. There might be delay when an executor receives the build configuration and when it actually runs the build. Example `executor-jenkins` which has it's own queue if build slaves are busy. This leads to JWT token expiration not matching with  actual build's duration.

**What you expected to happen**:

JWT token expiration should align with actual build duration. For this to happen temporary token exchange should not happen in `executor-*`, it should rather happen in `launcher` process which runs just before actual build execution happens.

**How to reproduce it**:

Run a build with timeout in `executor-jenkins` under load conditions that Jenkins cannot run it immediately.

**Comment by jithin1987** [comment]
cc @catto @Zhongtang

**Comment by kumada626** [comment]
We change to exchange temporary token in `launcher` process. However, `log-service` also use token which is passed by `executor-*`. Therefore, build logs cannot to be seen using `LAUNCHER 5.0.3` and `queue-worker 2.1.0`.
We'll fix this problem following.
1. Adding the flag to launcher which only fetch token in launcher process
2. To fetch build token before launcher and log-service processes start, calling launcher process with that flag before launcher and log-service processes start like following.
```
SD_TOKEN=`/opt/sd/launch --fetch-flag --api-uri {{api_uri}} --store-uri {{store_uri}} --emitter /opt/sd/emitter --build-timeout {{build_timeout}} {{build_id}}` &&
(/opt/sd/launch --api-uri {{api_uri}} --store-uri {{store_uri}} --emitter /opt/sd/emitter --build-timeout {{build_timeout}} {{build_id}} &
/opt/sd/logservice --emitter /opt/sd/emitter --api-uri {{api_uri}} --store-uri {{store_uri}} --build {{build_id}} &
wait $(jobs -p))
```
