### ISSUE TITLE
Provide an option to prevent auto running of pull request jobs

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1174]
## Context

Today any Screwdriver user can fork a SCM repository and create a PR against the SCM repository. This will run a PR build in Screwdriver pipeline for the jobs configured to run on `~pr`. For many projects this is not a desirable state for security reasons since secrets and other sensitive data might get exposed in the PR build.

## Objective

1. Provide a setting in Pipeline Options page to disable running PR's for forked repositories.
2. The setting should be `off` by default
2. If the setting is `on` then creating a pull request from a forked repository will not trigger a PR build.

**Comment by tkyi** [comment]
Related to https://github.com/screwdriver-cd/screwdriver/issues/579
Closing this issue in favor of that one since it has more information.

**Comment by d2lam** [comment]
Duplication of https://github.com/screwdriver-cd/screwdriver/issues/579
