### ISSUE TITLE
customizable slack notifications

### ISSUE THREAD

**Issue by amirmograbi** [screwdriver-cd/screwdriver#1177]
Hi Team,

We recently added slack notifications to our pipelines in ScrewDriver, its working well. However we thought that in order to get even more benefit from the feature, it would be nice if the messages were customizable, for example the following options would be beneficial:
- tagging team members that are involved in the build, eg. the person who opened the PR, the person who triggered the build etc.
- adding extra fields to the notification, for example the message in the HEAD of the PR/branch that is was built. Or the name of the branch that the PR was based on in addition to the PR number, as the PR number does not immediately give us valuable context about the build.
- different formatting, this would be helpful to distinguish between different builds and different statuses.

**Comment by jithin1987** [comment]
This is now available https://docs.screwdriver.cd/user-guide/metadata#notifications
