### ISSUE TITLE
Component job fails to publish new templates with `401 Unauthorized`

### ISSUE THREAD

**Issue by neeleshkorade** [screwdriver-cd/screwdriver#1181]
**What happened**:
Every time I try to publish a new template the first time, the PR build succeeds, then I merge the PR, but the component build fails to publish the same template with `401 Unauthorized` error. The component build succeeds when I delete the any existing/already published versions of the template.

**What you expected to happen**:
The component build should have been able to publish the template.

**How to reproduce it**:
The description above summarizes it. Try publishing a new template by raising a PR first.

**Comment by neeleshkorade** [comment]
Reported it on the internal slack channel. Also posted my analysis of the possible root cause, reproduced here.

> Looks like, the PR build of the template job is publishing the template with the same name. Given PR build SD principals have SD identity different from the component/main builds, and that for a new template, the PR builds run first before the component/main build can run, the PR build principal becomes the owner of the template. I had to delete the published template after merging the PR and rerun the component/main build to make the builds pass.

**Comment by tkyi** [comment]
We don’t allow template publishing in PRs, so I’m not sure how that would be possible (https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/templates/create.js#L63).

**Comment by neeleshkorade** [comment]
I was able to reproduce it. I deleted my existing templates to start publishing all over again. Again, the template publish and tag steps failed with `401 Unauthorized` as you can see here- https://screwdriver.ouroath.com/pipelines/1001194/builds/225063

And  the first version of template git published as well- https://screwdriver.ouroath.com/templates/namespaces/k8s/name/app-deploy

This makes me feel it was published by some other job.

**Comment by neeleshkorade** [comment]
Now if I delete the template again and run my template build/publish pipeline, it will succeed. Am going to try it now.

**Comment by neeleshkorade** [comment]
As I expected, the job succeeded this time- https://screwdriver.ouroath.com/pipelines/1001194/builds/225143
