### ISSUE TITLE
Setting up build takes a really long time

### ISSUE THREAD

**Issue by r3rastogi** [screwdriver-cd/screwdriver#1183]
**What happened**:  "Setting up build" takes many minutes with no indication of what's going on behind the scenes (see attached screenshot)

**What you expected to happen**: Build set up should be faster and/or there should be output informing the user what's happening/taking so long

**How to reproduce it**: Start a build

![image](https://user-images.githubusercontent.com/3217917/42779520-8be063fe-88f5-11e8-871f-dcb9dec8d5d1.png)

**Comment by d2lam** [comment]
Closing as we can track the issue here with more details: https://github.com/screwdriver-cd/screwdriver/issues/1198
