### ISSUE TITLE
UI - Pipeline arrows can be shortened to display more columns of jobs

### ISSUE THREAD

**Issue by anilkumarmyla** [screwdriver-cd/screwdriver#1186]
Below screenshot shows abundance of space between job names that can be trimmed so more columns of jobs can be displayed without horizontal scroll. 

Screenshot from latest version of firefox, chrome also appears the same

<img width="1141" alt="screen shot 2018-07-16 at 2 24 05 pm" src="https://user-images.githubusercontent.com/1934205/42784421-0a8620be-8904-11e8-8ac0-df68ceeae082.png">

**Comment by tkyi** [comment]
Should already be resolved by the pipeline page redesign.
