### ISSUE TITLE
Detached job duration doesn't display correctly.

### ISSUE THREAD

**Issue by elyzion** [screwdriver-cd/screwdriver#1188]
**What happened**:

The duration for detached jobs show up the same as the start time for jobs.

**What you expected to happen**:

The duration for detached jobs should show the actual detached job duration.

**How to reproduce it**:

Run a pipeline that includes detached jobs, acting union to trigger other jobs.

![detached_job_duration](https://user-images.githubusercontent.com/844567/42793222-132d0d80-89b4-11e8-833d-32cf34d45c7b.png)

**Comment by tanoda** [comment]
@elyzion 
Could you provide some sample of `builds` API result for that bad build? especially I want to check `steps` information.

**Comment by tk3fftk** [comment]
https://github.com/screwdriver-cd/screwdriver/issues/1173 may be related.

**Comment by jithin1987** [comment]
It's the same as #1173 there is no reasonable way for UI to calculate when an event is complete.
