### ISSUE TITLE
Repo+teardown isn't working as expected

### ISSUE THREAD

**Issue by renaud-yahoo** [screwdriver-cd/screwdriver#1192]
**What happened**:
In a teardown step, the SD_SOURCE_DIR environment variable is not the same as *during a build*.

**What you expected to happen**:
It should be exactly the same, as I have scripts expecting the value to be the same during and after (teardown) a build

**How to reproduce it**:
Use repo, echo SD_SOURCE_DIR in a normal step and in a teardown.

**Comment by renaud-yahoo** [comment]
Idea i've had chatting with @d2lam: implementing a `bookend-export` little tool (alias maybe?) that writes an environment variable's name and value to a file for each export that it is told to export a given variable. This way we can easily track which environment variables are the ones we want to restore, as the init bookends would be using this alias by default, and the user-defined build process could even want to give the teardown bookends some variables if it wanted to.

**Comment by d2lam** [comment]
This should be working now
@renaud-yahoo Please let us know if you have any issues.
