### ISSUE TITLE
Zip artifacts before upload

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1196]
## Context

Builds which generates large number of artifacts slows down the artifact bookend, since it uploads each file individually.

## Objective

Support a setting `SD_ZIP_ARTIFACTS` which if present ans has the value `yes` then artifact bookend should zip all files and upload a single file `SD_ARTIFACT.zip` file.

This opens up the possibility of processing the zip file outside of build execution flow. For example with AWS we can set up a Lambda which unzip artifact zip file automatically.

**Comment by drewfish** [comment]
Also maybe introduce some parallelism into the upload, so you have uploads happening at once.

**Comment by tkyi** [comment]
Need to add documentation for the new environment variable and also document that there is something like a 600MB file size limit.
