### ISSUE TITLE
teardown steps don't support wrapping

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#1217]
**What happened**:
I have a template which defines a `teardown-cleanup` step. In a job which uses that template I specify a `postteardown-cleanup` step. In my build, both as it happens and in the timestamps, I see that the `postteardown-cleanup` step runs before the `teardown-cleanup` step.

**What you expected to happen**:
I expect pre/post teardown steps to always run, and run in the expected order.

**How to reproduce it**:

**Digging around**:
In `launcher/executor/executor.go` in the "launcher" repo I see this where it's trying to figure out which steps are special teardown:

```go
isUserTeardown, _ := regexp.MatchString("^teardown-.+", cmd.Name)
```

That probably needs know about the "wrap" steps.

**Comment by jithin1987** [comment]
cc @d2lam 
I think we should support this, since a template owner can define a teardown step and users should have same flexibility as any other step.

**Comment by d2lam** [comment]
Sure I can work on this.

**Comment by d2lam** [comment]
This should be working now
