### ISSUE TITLE
run pipeline from a sub dir under a git repo

### ISSUE THREAD

**Issue by arunpnetskope** [screwdriver-cd/screwdriver#1222]
We have pipelines of different components under various  sub dir and want it to be executed/called from screwdriver.yaml at root folder from GitHub repo. How can we achieve that. 

git repo structure looks like:
screwdriver.yaml
dir1/job1/job1.yaml
dir2/job2/job2.yaml

basically we want both the jobs to be called from screwdriver.yaml 

sd-api 0.5.361
launcher 4.0.102
store 3.1.2

**Comment by jithin1987** [comment]
If you are following Monrepo structure then you can use `Source Paths` feature for this.  https://docs.screwdriver.cd/user-guide/configuration/sourcePaths

If not, ie you want `dir1` & `dir2` also to be build as part of each commit, then simply move the job config in `job1.yaml` & `job2.yaml` to `screwdriver.yaml` in Git root. Refer `Workflow` https://docs.screwdriver.cd/user-guide/configuration/workflow on how to can run these two jobs on each `commit` in addition to any job that should run during commit.

**Comment by arunpnetskope** [comment]
Thanks for the response. Basically I have a lot of components to run and I don't want to put everything in to screwdriver.yaml (in git root), is there any way I can call `job1.yaml` and `job2.yaml` from screwdriver.yaml.
