### ISSUE TITLE
Restarting build does not clear meta

### ISSUE THREAD

**Issue by wzhang111** [screwdriver-cd/screwdriver#1224]
**What happened**:

1.  Meta is reserved when restarting a build without commits in PR (possibly main pipeline too)
2. I am unable to clear meta without making some arbitrary commit

**What you expected to happen**: 

1. Meta should not be preserved when restarting builds, I would want a new version each time, things like meta version gets preserved between builds even if the build fails.
2. I should have some way of clearing meta if the build is PR

**How to reproduce it**: Open PR with a SD.yaml that get meta and sets meta, restart the job and the get meta should be the value of the meta set

**Comment by jithin1987** [comment]
This is a feature. So won't fix.
