### ISSUE TITLE
[UI] Long Detached Job names are not fully displayed in pipeline page

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1225]
**What happened**:
If detached job has long job name, its job name is not fully displayed in pipeline page.
<img width="125" alt="2018-07-27 15 12 24" src="https://user-images.githubusercontent.com/8113204/43304563-9d5a93ee-91af-11e8-913b-a889f8e94af1.png">

**What you expected to happen**:
Detached job's job names are fully displayed in pipeline page even if its job names are long.
<img width="125" alt="default" src="https://user-images.githubusercontent.com/8113204/43304799-69bc0bd4-91b0-11e8-9f50-30aef01231b0.png">

**How to reproduce it**:
Make detached job which has long job name.

**Comment by tkyi** [comment]
Should be resolved with new User Setting for Display Name Length
<img width="924" alt="Screen Shot 2022-10-12 at 4 43 14 PM" src="https://user-images.githubusercontent.com/3230529/195467613-6cd4352c-78fc-4925-aad8-1bcb69137470.png">
