### ISSUE TITLE
[UI] URL is verbose on template detail pages

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1230]
**What happened**:
URL of template detail page is `/templates/namespaces/<namespace>/names/<name>` currently.
(e.g. https://cd.screwdriver.cd/templates/namespaces/screwdriver-cd/names/semantic-release )
I think it might be verbose.

**What you expected to happen**:
I think `/templates/<namespace>/<name>` is better.

**Comment by jithin1987** [comment]
@tkyi @minz1027 @DekusDenial any thoughts on this ?

**Comment by tkyi** [comment]
I'm okay with having both urls point to the same place
I'm not sure what's the accepted/standard convention for UI URLs

**Comment by DekusDenial** [comment]
The longer URI format seems more prevalent in REST API endpoint than for UI pages.
`namespace` is the top of the hierarchy and when combined with `name` it can uniquely refer to a specific template, `/template/<namespace>/<name>` is RESTful to me

**Comment by tkyi** [comment]
@tk3fftk We reverted to the shortened url `/template/<namespace>/<name>` with UI v1.0.336. Does this resolve your issue?
