### ISSUE TITLE
[UI] Some templates cannot show tags in UI.

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1237]
**What happened**:
Some templates cannot show tags in UI.
<img width="337" alt="2018-08-06 18 24 32" src="https://user-images.githubusercontent.com/8113204/43708728-14d44c8c-99a6-11e8-9656-72382c4480c6.png">
However, other templates show their tags in UI, correctly.
<img width="318" alt="2018-08-06 18 24 46" src="https://user-images.githubusercontent.com/8113204/43708765-2af9b8da-99a6-11e8-9373-a65547b32ef9.png">
I think that this might be happen on old template which was first published before namespace was added to template.

**What you expected to happen**:
All templates show their tags.

**How to reproduce it**:
See the template detail page whose template was first published before namespace was added to template.

**Comment by tkyi** [comment]
I have DB migration details here that should fix any issues under the `Screwdriver Cluster Admins` section in the [Template Namespaces blog post](http://blog.screwdriver.cd/post/175385505042/introducing-template-namespaces). You will probably need to schedule some downtime though.

**Comment by jithin1987** [comment]
Closing this based on above comment. Please re-open if still and issue.
