### ISSUE TITLE
Security in swagger

### ISSUE THREAD

**Issue by nicolaifsf** [screwdriver-cd/screwdriver#124]
Requirements for authentication in swagger spec
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securitySchemeObject

**Comment by stjohnjohnson** [comment]
Looks like we'll need to do something similar to how glenn describes it here: https://github.com/glennjones/hapi-swagger/issues/242

**Comment by nicolaifsf** [comment]
this is addressed by PR #128
