### ISSUE TITLE
node icon doesn't get green when triggered by branch specific job

### ISSUE THREAD

**Issue by yokawara** [screwdriver-cd/screwdriver#1241]
**What happened**:
Now branch specific job trigger has implemented.
However, when I specify branch specific trigger with regex like ` ~pr:/^user-.*$/`, the triggered node icon does not turn green.
<img width="258" alt="2018-08-09 14 34 52" src="https://user-images.githubusercontent.com/18387253/43879969-75876022-9be1-11e8-8888-26a91f3cd7e3.png">

**What you expected to happen**:
A node icon which is triggered by branch specific trigger with regex also gets green.

**How to reproduce it**:
Specify some branch specific trigger with regex like `~pr:/^user-.*$/` and `~commit:/^user-.*$/`.

**relates**:
#1082

**Comment by yokawara** [comment]
It might be better that when some events matches a branch specific trigger with regex, pipeline page would create a node icon with the exact branch name not the regex and show that workflow started from it.

**Comment by jithin1987** [comment]
@catto this is fixed now. Now only https://github.com/screwdriver-cd/screwdriver/issues/1242 is pending to close out https://github.com/screwdriver-cd/screwdriver/issues/1082
