### ISSUE TITLE
Support executor-ec2

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1243]
**What happened**:

Enable users to leverage AWS to run builds natively on Amazon EC2 instances without going through Docker or Kubernetes. For running builds in scale, cluster admins need to set up Kubernetes based executor using [exectuor-k8s](https://github.com/screwdriver-cd/executor-k8s). By providing an executor ec2 user builds will run on ephemeral EC2 instances. We can extend this model to enable individual pipelines to provide their own AWS accounts where the EC2 instances will be launched.

**What you expected to happen**:

1. Screwdriver to support an executor to launch builds in EC2 instances.
1. Pipeline users should be able to provide their own AWS account where the EC2 instances for running builds are launched.
1. All existing functionalities of job configuration (build timeout / build periodically) should continue to work. Builds should be able to report back to SD on build step statuses and logs.

**Comment by djerraballi** [comment]
Not sure i fully understand this ticket. Would this ec2 executor spin a _new_ ec2 instance to run the build? Does it tear it down after completion?
Question for if it does spin a new EC2 Instance: 
 1.  What is the speed of spinning a new ec2 instance? Would that have an affect of build times? 
 2. Would we configure it with the aws credentials necessary to spin an ec2 instance? 

If i didn't misunderstand, and spinning a fresh instance and tearing it down is actually reasonable fast, I think this could be really useful and cost saving. Right now I have provisioned 2 very large nodes dedicated to running builds using k8 node selector. These nodes aren't running builds constantly so i am most likely paying a lot more to keep these containers up and running, then if I was getting the compute/ram on demand based on my screwdriver/cpu/ram annotations, and only paying for the ec2 time for the duration of the build.

**Comment by jithine** [comment]
@djerraballi that is the idea, support on-demand creation of compute resources on cloud, without worrying about provisioning a fixed compute for builds. Then users can tweak cpu/memory settings based on their actual compute needs.

**Comment by jithine** [comment]
Will address holistically with https://github.com/screwdriver-cd/screwdriver/issues/2550
