### ISSUE TITLE
Child pipelines fail to reset their parent pipeline's repository

### ISSUE THREAD

**Issue by Filbird** [screwdriver-cd/screwdriver#1244]
**What happened**:
A build triggered by a commit on a child pipeline, will fail on the `sd-setup-scm` step. This is because the SHA used that is used to reset the child's parent pipeline's repository belongs to the child.

Example:
https://cd.screwdriver.cd/pipelines/1072/builds/57647

**What you expected to happen**:
The SHA used for `git reset` should correspond to the last commit on the parent's repository and not the child's repository.

**How to reproduce it**:
(1) Create a parent and child pipeline
(2) Trigger a build on the child pipeline via a commit (not manually starting)

**Comment by jithin1987** [comment]
Should now work as expected.
