### ISSUE TITLE
PR authors should be able to restart their own PR builds

### ISSUE THREAD

**Issue by anilkumarmyla** [screwdriver-cd/screwdriver#1246]
**What happened**:
PR authors who do not have push permissions to repo cant restart PR builds

**What you expected to happen**:
PR authors should be able to restart their own PR builds

**Comment by tkyi** [comment]
Was able to rerun my PR build against Dao's repo: https://cd.screwdriver.cd/pipelines/173/builds/83878

**Comment by jithin1987** [comment]
This now works as expected.
