### ISSUE TITLE
push build logs to s3

### ISSUE THREAD

**Issue by arunpnetskope** [screwdriver-cd/screwdriver#1249]
As SD's default executor doesn't contain entire logs from UI, we have to regularly rotate/push the logs to s3 or somewhere else alternatively. Don't see detailed documented steps for logging in SD.

Ref: http://blog.screwdriver.cd/post/150999681452/logging-in-screwdriver

Do we have such documentation or any other way of achieving logging on SD !

**Comment by d2lam** [comment]
Does this help? https://docs.screwdriver.cd/cluster-management/configure-store#configuration

This example is a little outdated but maybe give you some idea (it's a kubernetes service): 
https://github.com/screwdriver-cd-test/config-examples/blob/master/services/store.yaml

**Comment by jithin1987** [comment]
Closing this based on above comment. If you are still blocked, then reach to us in our slack channel
