### ISSUE TITLE
Docker image caching

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#1258]
## Context

Builds are spending more time on Setup phase because of the time it spends on downloading Docker image if it's not cached. Screwdriver v4 cleanup script today clears out all hyperd cached images to work around hyperd not cleaning up disk space even in face of build failures. One solution is to use a per slave docker image caching approach. We should explore to see if we can provide a shared NFS backed storage for docker images.

## Objective

1. Implement caching solution of docker images.
1. Explore if we can provide a shared NFS backed storage across all V4 build slaves.
1. Solution depends on Kata Container approach, but since both approaches uses devicemapper for underlying storage we can explore a generic one. 

## References

1. Kata Spike - https://github.com/screwdriver-cd/screwdriver/issues/818
2. https://runnable.com/blog/distributing-docker-cache-across-hosts
3. https://github.com/travis-ci/travis-ci/issues/5358
4. https://www.ctl.io/developers/blog/post/more-docker-image-cache-tips/

_From @jithin1987_

**Comment by d2lam** [comment]
**Other CI/CD tools:**
- https://runnable.com/blog/distributing-docker-cache-across-hosts This approaches first do `docker save` and distribute the images using S3, then use `docker load` the images onto the machines.
- Travis: https://github.com/travis-ci/travis-ci/issues/5358
- CircleCi: 
    - https://circleci.com/docs/1.0/docker/#caching-docker-layers
    - https://circleci.com/docs/2.0/docker-layer-caching/
- Concourse: https://stackoverflow.com/questions/44475165/concourse-ci-leverage-docker-image-cache
- Codeship: https://documentation.codeship.com/pro/builds-and-configuration/caching/
- Codefresh: https://codefresh.io/docker-tutorial/hello-whale-layers-docker/
- Gitlab: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-docker-caching 

Most of other CI/CD solutions do not provide caching for images that used as build containers. The only “cache” mentioned above was for users that build docker images inside their builds. In these cases, they use `docker load` in the beginning of the build and `docker save` at the end of the build, so that the build of `Dockerfile` will be faster in the next run, since it will not need to execute every instruction, but use the cache for layers that already exist. This will speed up users build if they use the build to build their docker image. 

### Caching images used as build containers:
**Possible solutions 1:**
- `docker pull` images to the build hosts
- We can do analysis on images that are pulled most often, and the images that they were based off of. That way, we don't need to cache the entire image, only the base. This will provide the most value across all builds.
- During slave cleanup (every day), we can repull those images (in case a new version comes out and it's using `latest` tag)

**Possible solutions 2:**

- At beginning of each build, try to get from NFS for the corresponding `tar` file for that image. 
- If available, do `hyperctl load` (if use Kata, need to find a corresponding command). If not, do a normal `hyperctl pull`, and also use `hyperctl save` to produce a `tar` file and store to NFS so that next time it will be available.
- Note that for `hyperctl save`, will need to specify exact version
- This will save some time compared to `docker pull` because it will not need to make a network call to docker registry. However, it is not actually using any “cache”. 

**Possible solutions 3:**

- Mount `/var/lib/docker` of NFS to `/var/lib/docker` of slave hosts
- However, found some issue with this approach. Since `/var/lib/docker` is meant to be used by one single docker daemon. Sharing this mount can lead to data corruption and other issues (reference: https://stackoverflow.com/questions/36212928/implications-of-exposing-var-lib-docker-over-nfs-to-serve-hosts-with-limited-me)

**Possible solution 4:** 

- Implement a nginx proxy for docker registry. All docker requests would go through the proxy before going out to the actual docker registry. That nginx would then cache the images being proxied for future use.
- The initial request would go to the destination registry and their request would cause the image to get cached.  All subsequent requests for that image would then retrieve it from the cache that resides within the local network.
- This will save some time by having that image in the same subnet instead of making round trip calls to/from docker registry. However, it is slower than having the image already on the node (similar to solution 2).

**Decision: TBD**

**Speeding up Screwdriver builds that builds docker image in their steps:**
Many CI/CD solutions offer caching for the actual building of docker images. This is different from the above topic (caching for docker images that used as build containers). The general idea is, for builds that does `docker build` in their steps, they push the image at the end of build. Then before the next build, they pull the image. As a result, they can reuse cached layers between builds of the same job. 

Screwdriver can do something similar. We can simply `docker pull` the image before the next build and `docker push` at the end of the build. If we have artifact caching between events of the same job, we can store the built image as an artifact. In the next build, we can load that image and build using `cache-from` option. This will help significantly speed up Screwdriver builds that does `docker build`.

**Comment by Filbird** [comment]
## Update 9/6

We have decided to implement Solution 1. 

The cache is defined within our cleanup script and the images will get pulled following cleanup. Moving forward we can programmatically add/remove images from the cache depending on usage statistics.
