### ISSUE TITLE
builds get stuck at cloning private repo

### ISSUE THREAD

**Issue by arunpnetskope** [screwdriver-cd/screwdriver#1260]
We added private repo support to my api... but when the build starts (sd-setup-scm: at build step) it hangs out at cloning the repo.
Do we need to add the login details separately somewhere or any alternative to bypass this as cloning step is timing out.

<img width="812" alt="screen shot 2018-08-22 at 2 37 10 pm" src="https://user-images.githubusercontent.com/39948661/44472530-f819d280-a64b-11e8-92c8-443bd1768b83.png">

**Comment by d2lam** [comment]
Currently, for private repo, you would need to add secrets that include the credentials to clone the repo. From our docs here (https://docs.screwdriver.cd/cluster-management/configure-api.html#extending-the-docker-container): 
```
If users want to use private repo, they also need to set up SCM_USERNAME and SCM_ACCESS_TOKEN as secrets in their screwdriver.yaml.
```

`SCM_ACCESS_TOKEN` is the personal access token obtained from github: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

This is how to configure secrets for your pipeline: https://docs.screwdriver.cd/user-guide/configuration/secrets.html#configuring-a-job-to-expose-secrets

**Comment by jithin1987** [comment]
Closing this based on above comment.
