### ISSUE TITLE
[Bug] build didn't stop even if pushing stop button in the phase of running Setup steps

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1261]
**What happened**:
A build didn't stop even if pushing stop button in the phase of running `Setup` steps.

**What you expected to happen**:
A build stops certainly after pushing stop button.

**How to reproduce it**:
- Start a job from UI.
- Stop the job from UI in the phase of running `Setup` steps. Then Ui shows information of aborted 
- Reload build detail page.
- The job continues and run steps.

Our environment are below:
- api: v0.5.446
- ui: v1.0.324
- queue-worker: v2.1.2
- launcher: v5.0.11

This problem did not reproduce with `executor-docker` so `executor-queue` might cause this problem.

**Comment by wahapo** [comment]
I'll deal with it.

**Comment by tkyi** [comment]
Should be resolved now
