### ISSUE TITLE
Get coverage API returns 500 Internal Server Error.

### ISSUE THREAD

**Issue by taisukeh** [screwdriver-cd/screwdriver#1263]
**What happened**:

Get coverag API returns 500 Internal Server Error in build pages.

![image](https://user-images.githubusercontent.com/282077/44637052-0d935180-a9ea-11e8-9c4c-9928037460f0.png)

Response body:
```
{"statusCode":500,"error":"Internal Server Error","message":"Failed to get coverage percentage for job 61: 404 - {\"errors\":[{\"msg\":\"Component key 'job:61' not found\"}]}"}
```

**What you expected to happen**:

API should return 404.

**How to reproduce it**:

Open build result url, e.g. https://cd.screwdriver.cd/pipelines/27/builds/61257.

**Comment by tkyi** [comment]
GET coverage API should return 404 now.
