### ISSUE TITLE
Duplicate step still remain with template

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1268]
**What happened**:
Duplicate step still remain even if update api which includes https://github.com/screwdriver-cd/screwdriver/issues/1253 .
There is a template which has steps like below:
```
  steps:
    - install:    yarn install
    - pretest:    gulp some-task
    - test:       npm run acceptance-test
```
A user try to use the template with replacing template step. The user intended to replace `pretest` like below configuration.
```
    - pretest: echo pretest
```
After starting build,  `validation error` is raised.

But validator parses this case like this image.
![image](https://user-images.githubusercontent.com/3445553/44900859-b91d0880-ad40-11e8-8e20-db10cfc55d0d.png)

This may be caused by existing `pretest` step on the template and user's `pretest` step as **pre** wrapped `test` step.

**What you expected to happen**:
Steps should be replaced correctly or parser should raise an error.
```
  steps:
    - install:    yarn install
    - pretest:    echo pretest
    - test:       npm run acceptance-test
```

**How to reproduce it**:
- Create a template with `test` and `pretest` steps
- Use the template and add a replace setting
- Start a build
- Validate on UI

**Reference**
- related issue: https://github.com/screwdriver-cd/screwdriver/issues/1253
- template docs: https://docs.screwdriver.cd/user-guide/templates

**Comment by d2lam** [comment]
Hmmm I think it is a little confusing for the template to have the name `pretest` since `pre` and `post` are explicit keywords to wrap steps for templates. It can be confusing. For example, a template is like this:
```
  steps:
    - install:    yarn install
    - test:       npm run acceptance-test
    - hi:     echo hi
    - bye:  echo bye
    - pretest:    gulp some-task
```

In this case, if use has `pretest`, it is ambiguous whether the user actually wants to **wrap** the `test` step, or if he/she wants to **replace** the `pretest` step. 

In your example, can the template owner name it something else? And should we disallow this kind of naming so it's not ambiguous?

**Comment by tkyi** [comment]
I feel like we should disallow template steps to have `pre`/`post` steps. Since template owners get to dictate the order of steps, they shouldn't really need to use **wrapping**. 
We should add a caveat to our documentation as well.

**Comment by jithin1987** [comment]
I think we should prevent template owners from using `wrap` step names.

**Comment by tk3fftk** [comment]
> I think we should prevent template owners from using wrap step names.

I agree this. I think the problem is "validation is passed but build cannot be started".

**Comment by d2lam** [comment]
Sure. I agree with that. Let's make validation fail so that it is not ambiguous
