### ISSUE TITLE
Improvements for templates and commands list page

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1271]
## Context
Template list page with lots of templates are slower to load. SD Command list page also.
And it is hard for users to find template/command since search/filter feature doesn't exist if pagination is implemented.

## Objective
* Templates and Commands API should support pagination.
* UI should provide search feature for these pages.

**Comment by tkyi** [comment]
## Design Mocks
### Template landing page
![screen shot 2018-10-02 at 11 25 01 am](https://user-images.githubusercontent.com/3230529/46368801-00473380-c636-11e8-9141-c75acc1d0ae2.png)

- search will search through all fields: `namespace`, `name`, `description`
- results will return sorted by `name`
- pagination will look similar to pipeline events and search page

### Template Namespace page
![screen shot 2018-10-02 at 11 27 30 am](https://user-images.githubusercontent.com/3230529/46368890-400e1b00-c636-11e8-83c9-8f8328dc0840.png)
_Note: Not sure if we still need this or we can just reuse the landing page._

**Comment by tkyi** [comment]
## Implementation

#### Backend Tasks
- [ ] List namespaces (e.g.: `GET /templates/namespaces`)
- [ ] Multiple field search support
- [ ] Pagination support
- [ ] "Trusted" namespace support

**Comment by tkyi** [comment]
## "Trusted" feature

Some points of discussion when it comes to the "trusted" feature:
### 1. How will it be managed/maintained?
If we have a list of "trusted" elements, it will most likely be manually maintained by the Screwdriver admins.
Alternatively, we could have users "star" their favorite or trusted templates and display the "most starred" templates accordingly.

### 2. How will that "trusted" tag/flag be maintained?
Templates can only be created, not updated, so it's unclear how we would track the "trusted" flag (or even "most starred"). It doesn't make sense to have owners add the "trusted" flag themselves when creating the template and we would have to manually alter the template in the datastore if we wanted to add the "trusted" flag after creation. If we add an UPDATE endpoint for templates, the "trusted" flag would be tied to a specific template version, not the general template itself. 
We would definitely need to keep track of this "trusted" information in a separate table.

### 3. Should we have "trusted" template or namespace?
The issue with "trusted" namespaces is that namespaces are not protected in any way right now. Any user can create a template in any namespace. This will change if we work on [namespace auth](https://github.com/screwdriver-cd/screwdriver/issues/1121). With namespace auth, namespaces will be consolidated between templates and commands. We will also store the namespace <-> maintainer(s) relationship in a separate table, giving us the flexibility to set a "trusted" flag somewhere.

**Comment by jithin1987** [comment]
Closing this issue. Will track pending trusted template work in https://github.com/screwdriver-cd/screwdriver/issues/1427
