### ISSUE TITLE
screwdriver api can't running with gitlab

### ISSUE THREAD

**Issue by udomsak** [screwdriver-cd/screwdriver#1278]
**What happened**:
 Scm plugin gitlab is not supported
```
api_1    | Sun, 09 Sep 2018 05:21:40 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at ../sequelize/lib/sequelize.js:242:13
api_1    | Scm plugin gitlab is not supported
api_1    | /usr/src/app/node_modules/screwdriver-scm-router/index.js:42
api_1    |             throw new Error('No scm config passed in.');
api_1    |             ^
```

![image](https://user-images.githubusercontent.com/319024/45261352-7fc45700-b42a-11e8-913d-1c6f2d1ffd50.png)

**What you expected to happen**:
Gitlab SCM plugin must work. 

**How to reproduce it**:
1. python <(curl -L https://git.io/screwdriver-box)
2. do step pre-configure and select gitlab as scm. 
3. run docker-compose up 
4. Boom !! :)

**Comment by jithin1987** [comment]
`scm-gitlab` is not bundled by default https://www.npmjs.com/package/screwdriver-scm-gitlab

One option is to add a link to do `npm install screwdriver-scm-gitlab` in `https://github.com/screwdriver-cd/screwdriver/blob/master/Dockerfile.local` and update your local docker compose to use this locally built docker image for SD API.

**Comment by minz1027** [comment]
@udomsak Hi we have bundled the scm-gitlab with our api now. Just retag stable for the api image. Don't need to do anything extra as @jithin1987 mentioned now. Just `docker pull screwdrivercd/screwdriver:stable` and run you in-a-box again. :)
