### ISSUE TITLE
[Build cache] Implement CLI

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1282]
## Context
Screwdriver should provide a simple CLI that handles build caches instead of curl, wget or any other environment-dependent commands.

## Objective
- Implement `cache` CLI with [proposed design](https://github.com/screwdriver-cd/screwdriver/blob/master/design/build-cache.md#command)
  - [x] `get` subcommand
  - [x] `put` subcommand
  - [x] `delete` subcommand
- [x] Create a pipeline to publish/release
- [x] Include this command to `launcher` image

# References
Original issue: #1257

**Comment by pranavrc** [comment]
So the convention for the CLI that @d2lam and I came up with was this:

Number 1:

```
store cache get stuff —scope=event
store cache put stuff —scope=event
store artifacts get testresults
store artifacts put testresults
store logs get test
store logs put test
```

Number 2:

```
store get stuff —scope=event --type=cache
store get stuff —scope=build --type=artifacts
store put stuff —scope=event --type=steps
store put stuff —scope=event --type=logs
```

We'll go with number 2 for now because all the resource types (cache, artifact, step, log) have the same operations across them.

**Comment by d2lam** [comment]
Also, since in meta-cli we do `meta get` and `meta set`, should we do `store set` instead of `store put`?

**Comment by jithin1987** [comment]
I've updated requirement to support a `delete` command, since we need to give a handle to users or template owners to invalidate cache if required.

**Comment by d2lam** [comment]
@tk3fftk  no there is no difference. It should be `--`. The text editor from Mac automatically converted the `--` to one line.
