### ISSUE TITLE
[Build cache] Implement bookend

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1284]
## Context
If there are CLI and cache service, users can fetch and store their cache with the CLI. But we should provide automated way to fetch and store build cache with bookend.

## Objective
- [x] Implement new `build-cache` bookend
  - [ ] setup
    - Just executes `cache get`?
  - [ ] teardown
    - Just executes `cache put`?
- [x] Create pipeline for publishing
- [x] Configure API to run the bookend before and after each build

## References 
Original issue: #1257 
Blocked by: #1282

**Comment by d2lam** [comment]
All tasks are done for this.
