### ISSUE TITLE
Must be able to download complete console log

### ISSUE THREAD

**Issue by somsingh-oath** [screwdriver-cd/screwdriver#1289]
**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Comment by tkyi** [comment]
Do you mean step logs? We've just released that feature today: http://blog.screwdriver.cd/post/178220969807/build-step-logs-download

**Comment by somsingh-oath** [comment]
No, we need complete console log in one file

**Comment by tkyi** [comment]
Closing this issue in favor of a more detailed one (since this is a duplicate): https://github.com/screwdriver-cd/screwdriver/issues/1471
