### ISSUE TITLE
Add repo name to document title

### ISSUE THREAD

**Issue by redonkulus** [screwdriver-cd/screwdriver#1299]
Having the repo name (e.g. org/repo) in the browser title will make it easy to search for different pipelines by name, rather then trying to remember the project id's. 

We have many different repositories that we maintain and cannot remember which pipeline id maps to which repo.

**Comment by tkyi** [comment]
This issue should be resolved now.

![screen shot 2018-09-19 at 5 30 12 pm](https://user-images.githubusercontent.com/3230529/45788836-b15ece80-bc31-11e8-889c-823ada4d0924.png)
