### ISSUE TITLE
sd builds get stuck with private repo

### ISSUE THREAD

**Issue by arunpnetskope** [screwdriver-cd/screwdriver#1300]
I have created a pipeline with a private repo and screwdriver.yaml file has secrets defined for gituser and its access token (created via UI and allowinPR option by ticking checkbox, but unfortunately its not working.

alternatively, mentioned SCM_USERNAME and SCM_ACCESS_TOKEN as environment variables in shared but it still gets stuck at "sd-setup-launcher" step where it tries to clone the repo.

I already created an issue #1290 which is closed now. Could you help us resolving this one. 

<img width="1167" alt="screen shot 2018-09-18 at 2 53 09 pm" src="https://user-images.githubusercontent.com/39948661/45827898-08899f80-bd15-11e8-8024-735c685de8da.png">

api version: stable
ui version: stable 
launcher version: latest

**Comment by jithin1987** [comment]
Private repo support need to be enabled in API config

https://docs.screwdriver.cd/cluster-management/configure-api Search for `privateRepo`

We are also working on an alternate feature for supporting Private repo  https://github.com/screwdriver-cd/screwdriver/issues/1079#issuecomment-393636838

**Comment by arunpnetskope** [comment]
I have already enabled private repo in my api setup, resulting this I am able to create pipeline using private repos, is there any alternative to by pass this. FYI.. SCM_USERNAME and SCM_ACCESS_TOKEN worked with the previous stable version of api v0.5.361.

**Comment by jithin1987** [comment]
@arunpnetskope Is this happening only with private repo ? Does setting `SCM_USERNAME` work with public repo with newest API ?

**Comment by arunpnetskope** [comment]
@jithin1987 yes it does.. only with private repos. I guess we don't need these variables in public repos as it works fine without them.

**Comment by d2lam** [comment]
@arunpnetskope Did you configure them as secrets? If yes, did you list the secret keys as in your screwdriver.yaml?

**Comment by arunpnetskope** [comment]
@jithin1987 yes, I created two secrets and configured them as below -

```
shared:
    image:sdnode8
    secrets:
         - SCM_USERNAME
         - SCM_ACCESS_TOKEN

``` 

also tried by specifying SCM_USERNAME and SCM_ACCESS_TOKEN as env variables in yaml file.

**Comment by d2lam** [comment]
@arunpnetskope  are you using `https` or `ssh` for cloning? I think you need to use `https` for private repo to work.

**Comment by d2lam** [comment]
That is quite strange. We didn't modify any logic regarding the `SCM_USERNAME` and `SCM_ACCESS_TOKEN`. Please ping me directly on slack @d2lam. I can work with you to debug this in your environment.

**Comment by d2lam** [comment]
I think I figured out the issue. It looks like your `screwdriver.yaml` has a `config-parser-error`. Because of this, it doesn't read in the `secrets` correctly, which means `SCM_USERNAME` and `SCM_ACCESS_TOKEN` are not there. Therefore, it cannot do the cloning. I can reproduce the behavior with my pipeline. 

I would suggest the following:
- Fix your config error using: https://cd.screwdriver.cd/validator (Your own cluster should also have this. It's on the Top Right -> Documentation -> Validator)
- Or change your yaml to something simple like below and confirm whether it works:
```
shared:
  image: node:6
jobs:
  test:
    steps:
      - echo: echo hi
    requires:
      - ~pr
      - ~commit
    secrets:
      - SCM_USERNAME
      - SCM_ACCESS_TOKEN
```

**Comment by arunpnetskope** [comment]
@d2lam @jithin1987 thanks for helping out in this issue. Closing the issue as the pipeline works fine now.
