### ISSUE TITLE
Event list should have an icon to scroll to the graph

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1310]
## Context

Pipeline page requires users to interact with the big pipeline graph on top of the page for navigating to the build detail page. This works for the first event whose graph is loaded by default, but for pipelines with large number of events, it's not intuitive to scroll down to a desired event and then scroll back up to interact with the graph.

## Objecive

1. Each event should have a control to scroll to the graph.
1. Graph should have a control to scroll to the event
1. Explored fixed graph, so that event list scrolls and graph is always fixed.

**Comment by redonkulus** [comment]
There is also confusion that you are supposed to click the commit or event then scroll to the top. Why not just have the icons in the commit row also link off to the details page as well?

**Comment by tkyi** [comment]
We already have a fixed graph issue with design mocks (https://github.com/screwdriver-cd/screwdriver/issues/968). Is this issue a duplicate?

**Comment by jithin1987** [comment]
> We already have a fixed graph issue with design mocks (#968). Is this issue a duplicate?

I am not completely sold on that. Until we finalize an approach with Design team, lets keep this open.

**Comment by jithin1987** [comment]
> There is also confusion that you are supposed to click the commit or event then scroll to the top. Why not just have the icons in the commit row also link off to the details page as well?

@redonkulus Challenge here is some interactions like, running detached job / restarting a build can be done only from the main graph. If we attempt to do it from event graph there is not enough space to pull off all the interactions. So we force users to scroll to top. 

But bringing back click to go to details makes sense as well. ( I said `back` because we had that before and removed it when we added features like restart a build)

**Comment by redonkulus** [comment]
I think bringing back the "click to go to details" makes sense because you are already training users in the main graph to click buttons to go to detail view pages. Thats why I thought it was odd to not have it in the events. 

FWIW, clicking then scrolling up might be too jarring for users initially.

**Comment by jithin1987** [comment]
This usecase is no longer valid with new design https://github.com/screwdriver-cd/screwdriver/issues/1419
