### ISSUE TITLE
UI: can't use a subdirectory

### ISSUE THREAD

**Issue by cybik** [screwdriver-cd/screwdriver#1312]
Multiple issues here.

* /usr/share/nginx/html/index.html , presumably generated from https://github.com/cybik/ui/blob/master/app/index.html , is badly generated. It should prepend "/blah" with a period so that the paths become relative, and stubborn folks (such as yours truly) can then place screwdriver behind a reverse proxy and in a subdirectory.
* Easy way to configure rootURL please.

**Comment by jithin1987** [comment]
This is now fixed. Setting a `ROOT_URL` env variable will not make this happen. 
https://github.com/screwdriver-cd/ui/blob/master/nginx.conf#L14
Also checkout our Helm chart for simplifying all this setup https://github.com/screwdriver-cd/screwdriver-chart 

cc @minz1027
