### ISSUE TITLE
Allow Secrets key name longer than 25 characters

### ISSUE THREAD

**Issue by taisukeh** [screwdriver-cd/screwdriver#1329]
**What happened**:

I'd like to set `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`, but error has occured.
※https://github.com/fastlane/fastlane/blob/a556c8ba62f762a502b43c2d38e6a7e223425747/spaceship/README.md#transporter

![image](https://user-images.githubusercontent.com/282077/46692086-4d806200-cc41-11e8-94d5-05fad11d63db.png)

**What you expected to happen**:

Increase the limit of key name to at least 44 characters.

**How to reproduce it**:

**Comment by catto** [comment]
This should be fixed now. 
@taisukeh Thank you for your report!
