### ISSUE TITLE
Ability to trigger any job in a pipeline graph

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#1335]
**What happened**:
I want to use external trigger as detached job.

I have one pipeline which do acceptance test and the pipeline have some external trigger. The triggered pipeline do each test.

Now If I fix one of the test I cannot start job from the test's pipeline. I need to start from the acceptance test pipeline. It is unconvenient for me.

**What you expected to happen**:
When I fix one of the test, I want to start the test without running acceptance test pipeline. 
I want to use external trigger as detached job

**How to reproduce it**:
Use external trigger.

**Comment by jithin1987** [comment]
This can be generalized to start any job in the pipeline graph even if it was not run before. This is a change in UI, API has the support to run any job in the event.

**Comment by yuichi10** [comment]
That's looks good to me!
