### ISSUE TITLE
PR build detail page to provide information on newest build for the PR job.

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1338]
## Context

A user landing on the PR build detail page might not be aware of a newer build running for the PR job. This can lead to user clicking restart of a failed build without realizing that a newer build might be running or have ran.

## Objective

1. Display a message in PR build detail page if user is viewing an older build for a PR job. Eg: "A newer build for this job is available. Click Here"
1. If user tries to `Restart` a PR job's older build, then show an option to visit the newest build.

**Comment by redonkulus** [comment]
For 2. You could either make the Restart button say “Running” or if clicked just take them to the current running build.

**Comment by jithin1987** [comment]
Original issue of restart running an build with older SHA has been addressed. Now re-start always uses latest sha.
