### ISSUE TITLE
meta.json corrupted when multiple `meta set` executed in parallel

### ISSUE THREAD

**Issue by src-code** [screwdriver-cd/screwdriver#1341]
We've been finding that making multiple `meta set` calls in parallel will result in corruption of the metadata in `meta.json` due to the fact that every call results in the file being opened and read from before new data is written, but there is no file locking in place.  This file should be locked for reads and writes before filehandles are opened and metadata is read from and written to this file.

**Comment by src-code** [comment]
@d2lam and @pranavrc are familiar with this issue from offline discussions

**Comment by jithin1987** [comment]
Closing this. Meta cli writes to a file, if parallel operations with in a same step happens, it can corrupt.

**Comment by src-code** [comment]
@jithin1987 Curious, why close this if there's an acknowledged issue with how metadata is gathered and stored?

**Comment by jithin1987** [comment]
@src-code Reasoning is that we are unlikely to fix this, since having multiple parallel `meta sets` in parallel is a very remote use case. I can leave this open.

**Comment by okorz001** [comment]
Isn't this common for monorepos? Or is this only an issue if there are parallel `meta set` in the same job (not pipeline)?

**Comment by d2lam** [comment]
@okorz001  only for same build

**Comment by jithine** [comment]
meta cli now has locking based on flock https://github.com/screwdriver-cd/meta-cli/pull/33
