### ISSUE TITLE
[Feature request] Support for github badges for specific screwdriver jobs

### ISSUE THREAD

**Issue by master-nevi** [screwdriver-cd/screwdriver#1347]
**What happened**: Currently there's only a badge for the entire pipeline with sort-of-useful success rate counters.
![screen shot 2018-10-17 at 1 47 19 pm](https://user-images.githubusercontent.com/987706/47120431-83b27880-d223-11e8-834d-e7587a44e1e5.png)

**What you expected to happen**: It would be helpful to be able to see the status of individual jobs of your pipeline in order to be able to see issues at a glance rather than by success/current run count.

![screen shot 2018-10-17 at 1 10 35 pm](https://user-images.githubusercontent.com/987706/47120427-7dbc9780-d223-11e8-9a98-4a943261fc94.png)

**Comment by tkyi** [comment]
The work should be similar to https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/pipelines/badge.js

**Comment by jithin1987** [comment]
This is available now. https://docs.screwdriver.cd/user-guide/api.html#badges
