### ISSUE TITLE
Child pipeline removed unexpectedly

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1350]
**What happened**:
1. Create pipeline `A`
2. Create pipeline `B` which has `A` as a child pipeline
3. Parent pipeline is created, but `A` is not shown in UI of pipeline `B`
4. Remove the setting of `childPipelines` from parent screwdriver.yaml 

Then the child pipeline removed. The child pipeline page is `404`.

**What you expected to happen**:
Child pipeline is not removed. The pipeline works individually, and the event log also remains.

**What I investigated**:
I think that child pipelines is removed at [here](https://github.com/screwdriver-cd/models/blob/abdd53231c6c4a261ef18cf7b7ddee7dda837322/lib/pipeline.js#L513) after filtered as old scm urls. A child pipeline has `configPipelineId` to reach to the parents, so it might be a solution that using `configPipelineId` to judge whether remove or not.

**Comment by klu909** [comment]
closing this issue as it was resolved with issue 1949
