### ISSUE TITLE
[UI] Workflow graphs are arranged in random order

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1359]
**What happened**:
I made a pipeline that has some lines workflow.
And I look that pipeline in UI, the order of the workflow line is random as below.
<img width="919" alt="2018-10-22 14 55 30" src="https://user-images.githubusercontent.com/8113204/47279233-9ef9fb00-d60a-11e8-9c27-308bfca4d682.png">
<img width="916" alt="2018-10-22 14 55 46" src="https://user-images.githubusercontent.com/8113204/47279234-a0c3be80-d60a-11e8-948b-b69eb4e5ce20.png">

**What you expected to happen**:
Fix order of the workflow graphs.

**How to reproduce it**:
1. Make a pipeline that has some lines.
2. Run that pipeline several times.
3. Workflow graph order sometimes change.

**Comment by lbordowitz** [comment]
This also changes along different pull requests, making it difficult to find a consistent pattern to jobs that may have succeeded or failed. I was directed to this portion of code which controls the layout:

https://github.com/screwdriver-cd/ui/blob/master/app/components/workflow-graph-d3/component.js#L88

Maybe there's a way to sort appropriately in d3.

**Comment by catto** [comment]
I confirmed a workflow in the event view has been fixed via https://github.com/screwdriver-cd/ui/pull/399.
