### ISSUE TITLE
Want to know which repository remote triggers relate to

### ISSUE THREAD

**Issue by yokawara** [screwdriver-cd/screwdriver#1365]
**What happened**:
When I create a pipeline which has remote triggers, it is hard to know which repository the each remote trigger relates to.

**What you expected to happen**:
On pipeline page, we can easily want to know which repository remote triggers relate to.

**How to reproduce it**:

**Comment by tkyi** [comment]
@yokawara I added a link to the remote trigger pipeline from the event graph for this issue: https://github.com/screwdriver-cd/screwdriver/issues/1332
Does that solve your problem?

**Comment by yokawara** [comment]
@tkyi Yes! Thank you for implimenting the feature 🎉
