### ISSUE TITLE
There is no sonar-project.properties file in javascript example

### ISSUE THREAD

**Issue by anilkumarmyla** [screwdriver-cd/screwdriver#1369]
**What happened**:
Did not find a file `sonar-project.properties`

**What you expected to happen**:
Should find `sonar-project.properties` as mentioned in the guide

**How to reproduce it**:
Following the link from https://docs.screwdriver.cd/user-guide/configuration/code-coverage#sonarqube we're led to a repository which doesn't include sonar-project.properties in the repo

**Comment by jithin1987** [comment]
This is fixed with https://github.com/screwdriver-cd/guide/pull/264

**Comment by anilkumarmyla** [comment]
thank you!
