### ISSUE TITLE
SonarQube to have ability to fetch parent job's coverage results

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1370]
## Context

For pull requests to support SonarQube preview mode it needs to fetch results from another project to compare the diff. 

## Objective

1. Expose env variable for parent job id SD_PARENT_JOB_ID
2. Expose a shared command to easily fetch Job ID from a pipeline ID & job name
3. Grant Sonar Token read access on all projects.

**Comment by jithin1987** [comment]
cc @cybik @minz1027

**Comment by minz1027** [comment]
Sonar Token has read access on all projects already
