### ISSUE TITLE
k8s-vm executor doesn't clean up build VMs and sdlauncher directories sometimes

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1378]
**What happened**:
I ran a build with k8s-vm executor. After that, the executor should remove the build and its directories before stopping the build. Currently [preStop hook](https://github.com/screwdriver-cd/executor-k8s-vm/blob/0be448d5889d2d701123f9ab2972293024a8670f/config/pod.yaml.tim#L60-L64) handles that but sometimes it won't happen. And abandoned VMs and launcher binaries fill up our Kubernetes workers' cpu, memory and disk.

**What you expected to happen**:
executor-k8s-vm surely cleans up used VM and directories before finish.

**How to reproduce it**:
It's hard to reproduce manually but if a hyper runner container exits early, preStop hook won't run because the container is already exited.

**Comment by catto** [comment]
I think we should include cleanup instructions in cleanUp function and make it run on each signal such as TERM, KILL and QUIT instead of using `preStop` hook.
https://github.com/screwdriver-cd/hyperctl-image/blob/f44bbccb35f31b3b30469ef6f251dc74a409ff77/scripts/hyper-runner.sh#L4-L14

**Comment by tk3fftk** [comment]
This should be closable.
