### ISSUE TITLE
Cannot choose default collection

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#1383]
**What happened**:
I have some collections and the collection I often use one is not default.
I often need to change collection after access screwdriver and it is bit inconvenient

**What you expected to happen**:
Be able to choose default collection which will be displayed when access screwdriver root page.

**How to reproduce it**:
Nothing

**Comment by tkyi** [comment]
I think choosing a default or just keeping track of the last collection the user had open would be nice.

**Comment by will-lauer** [comment]
Even forcing the collections to always be returned in the same order would be an improvement. Right now, every time I load the page, the collections are in a different order so I have to search for the one I want.

**Comment by wahapo** [comment]
I think that it is necessary to be sorted at least. Currently it seems that sort processing is already implemented, so the sort request has probably been resolved.

Regarding displaying a collection other than `My Pipelines` on the default page, I propose three solutions referred to below.

1. Displays the default collection name with a pin. On the collection page, display a button that allows to switch the pin on/off. By turning it on, the position of the pin in the collection list also moves. If reload the screen, the pinned collection will be displayed first. By default, there is a pin on `My Pipelines`.
    <img width="400" src="https://user-images.githubusercontent.com/24538326/75748735-830c7a80-5d63-11ea-8c20-edd33a5f4d01.png">

2. Place the default displayed collection name at the top of the list. Other behaviors are the same as solution 1 except that there are no pins in the list.
    <img width="400" src="https://user-images.githubusercontent.com/24538326/75748707-7556f500-5d63-11ea-9ac2-4968fa857dc8.png">

3. Keep the last collection the user had open and show the same collection when user reloads the display.
    <img width="400" src="https://user-images.githubusercontent.com/24538326/75748748-8b64b580-5d63-11ea-819f-bbeb3971f49f.png">

The solution of 1 is not bad, but users will have to learn more ways to operate than they do now, increasing the unnecessary learning cost of using Screwdriver.cd. So I think the solution of 3 that do not require extra user operations are the simplest and best without sacrificing usability.

@jithine, @kumada626, and contributors. With agreement, I will start implementing it in the near future with solution of 3. I would appreciate your feedback.

**Comment by yoshwata** [comment]
@wahapo When I reload page on a collection screen, it shows a collection what I've see just before. Do you mean to access ui root like https://cd.screwdriver.cd/ rather than just page reloading?

**Comment by wahapo** [comment]
@yoshwata Well, that's right. What I expressed the reload was not accurate. What I really wanted to say was to close and reopen the browser for Screwdrivdr.cd.

**Comment by yoshwata** [comment]
@wahapo Thank you. I understand and agree to proceed with solution 3.

**Comment by jithine** [comment]
Solution 3 sounds good. 👍

**Comment by tkyi** [comment]
Solution 3 sounds good to me, too.
