### ISSUE TITLE
[docs] need more explicit definition of events ~pr and ~commit

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#1386]
This question comes up when I was discussing screwdriver-cd/guide#253 as to whether the `main` job would be triggered by a commit to a non-default branch. What exactly does the `~commit` event entail? Are there any other jobs that has special characteristics? That is, if I have a job `foo` that requires `~commit`, does it trigger on any commit to any branch, or would I need to use `~commit:/./` to make explicit that I really do want it to build for commits to any branch?

**Comment by tkyi** [comment]
I was just updating ~pr/~commit definitions, so I can easily update my PR if that helps: https://github.com/screwdriver-cd/guide/pull/252
We could add a sentence explaining that `requires: ~commit` implies `requires: ~commit:<default_branch>`. 
And yes, you would need `requires: ~commit:/./` to build for commits to any branch. We can add that to the documentation. I don't really know why someone would want to do that.

**Comment by jithin1987** [comment]
https://github.com/screwdriver-cd/guide/pull/252/files should address concerns in the issue.
