### ISSUE TITLE
Getting meta from the previous successful build of the same job

### ISSUE THREAD

**Issue by hakonhall** [screwdriver-cd/screwdriver#1389]
I have a job creating an RPM, and I would have liked to have the RPM build number increment by 1 if the build otherwise would create the same RPM artifact. I would like to:
 - Set meta on a successful build: version, build number, etc
 - When deciding the RPM artifact name, get the meta of the last successful build, increment the build number etc

**Comment by d2lam** [comment]
A few people have been asking about this. We should prioritize this issue @jithin1987

**Comment by jithin1987** [comment]
`GET /v4/jobs/{id}/lastSuccessfulMeta` has been implemented
