### ISSUE TITLE
Strange log output when pipeline is set USER_SHELL_BIN: bash

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1398]
**What happened**:
Strange step log appears like
<img width="569" alt="2018-11-29 9 44 39" src="https://user-images.githubusercontent.com/32473622/49191819-98099980-f3bb-11e8-9e86-fc4829f701d4.png">

**What you expected to happen**:
There is no output that is unrelated with executed commands on log UI.

**How to reproduce it**:
1. Set USER_SHELLBIN on pipline like
```
    environment:
      USER_SHELL_BIN: bash
```
2. Add simple `echo` step on pipeline
3. Start build, then strange output appears on echo step created at step2.

**Comment by d2lam** [comment]
We  also see some strange outputs on Alpine based images before: https://github.com/screwdriver-cd/screwdriver/issues/559

**Comment by d2lam** [comment]
This line is from here: https://github.com/screwdriver-cd/launcher/blob/6da62a4a7534ae76807db86f95f4f1c457e59db6/executor/executor.go#L109-L110
