### ISSUE TITLE
No error shown when trying to navigate to pipeline that doesn't exist 

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1400]
**What happened**:
The same issue is occurred. https://github.com/screwdriver-cd/screwdriver/issues/769

**What you expected to happen**:
I would expect a 404 Pipeline Not Found if the pipeline does not exist. It's hard to tell if the page is still loading and I should wait or if it's done from the UI.

**How to reproduce it**:
Tried navigating to https://cd.screwdriver.cd/pipelines/2. The header loaded but nothing else did.
<img width="1672" alt="2018-11-30 13 57 51" src="https://user-images.githubusercontent.com/8113204/49269373-ff047c80-f4a7-11e8-9440-26319df5d2c9.png">

**Comment by jithine** [comment]
Now it shows 404 page.
