### ISSUE TITLE
[Bug] Build pod is desired to be stopped gracefully

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#1403]
**What happened**:
When the user presses the stop button on the UI, not SIGTERM process is executed. Naturally, no log related to SIGTERM processing is output.

**What you expected to happen**:
I need to perform SIGTERM processing.
Revert `gracePeriodSeconds` to an unspecified state, when SIGTERM is issued it must be 
gracefully terminated.
https://github.com/screwdriver-cd/executor-k8s/pull/97
https://github.com/screwdriver-cd/executor-k8s-vm/pull/46

**How to reproduce it**:
- Start a job from UI.
- Stop the job from UI in progress. Then build pod on k8s is immediately deleted without any chance to output the end log.

Our environment are below:
- api: v0.5.513
- queue-worker: v2.3.1

**Research**:
Even if SIGTERM is issued when the stop button is pressed, launcher will not end. Perhaps, pressing the Stop button on the UI, kubelet issues a TERM against pod, SIGTERM is issued to process of pid1. Investigating the inside of pod, [launch_entrypoint.sh](https://github.com/screwdriver-cd/executor-k8s/blob/3b470f50760c33439a1351538a843eec8893d8d8/config/pod.yaml.tim#L22) is pid1. When SIGTERM is passed to the next launch process of the `launch_entrypoint.sh`, I think the build will end gracefully.

**References**:
- Related: https://github.com/screwdriver-cd/screwdriver/issues/1261
- https://kubernetes.io/docs/concepts/workloads/pods/pod/#force-deletion-of-pods

**Comment by wahapo** [comment]
@minz1027 As we contacted by another means, at all is due to an another location, it has already resolved.

**Comment by jithin1987** [comment]
Closing this.
