### ISSUE TITLE
Build Metrics

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1412]
## Context

A Screwdriver build generates metrics pertaining to a build time and status of it's individual steps. This information is presented in build detail page where information on total build time and how much time each individual step took is displayed in Build detail page of SD UI. Pipeline detail page of SD UI  shows information on total build time for an event by aggregating build times across all the jobs which was executed for that event. However SD lacks an aggregated build metrics view at a pipeline level. This Pipeline Metrics view should help a user to look at a pipeline and quickly get views on various build trends.

### Metrics at Pipeline scope

1. Trend of commit/pr events at pipeline scope.
    1. Time series graph where each point represents time taken for the event as a whole.
    1. Data points should show information about event and a link to the events page which loads that specific event.
1. Trend of builds at pipeline scope.
    1. Time series graph where each point represents time taken for a specific build across all events of the pipeline.
   1. Data points should show information about the build (eg: Job) and a link to the specific build. 
1. Trend of build steps at pipeline scope.
    1. Time series graph where each point represents time taken for a specific step across all the builds for the pipeline.
    1. Data points should show information about the build to which the step belongs to and a link to the specific build's step. 

### Metrics at Pipeline -> Job scope

This is the view user will see after filtering out a specific job in the pipeline

1. Trend of builds at job scope
    1. Time series graph where each point represents time taken for a specific build of the job in the pipeline.
   1. Data points should show information about the build (eg: Job, Event) and a link to the specific build. 
1. Trend of build steps at job scope.
    1. Time series graph where each point represents time taken for a step  across all the builds of the scoped job.
    1. Data points should show information about the build to which the step belongs to and a link to the specific build's step. 

### Metrics at Pipeline -> Job -> Step scope

This is the view user will see after filtering out a specific step in a job in the pipeline

1. Trend of build steps at job scope.
    1. Time series graph where each point represents time taken for a specific step of the build across the same job.
    1. Data points should show information about the build to which the step belongs to and a link to the specific build's step. 

<del>
### Metrics at Collection scope

1. View should be similar to pipeline scoped metrics.
1. View will involve events, builds and steps spread across multiple pipelines.
1. Data points should show information about Pipeline, event and build to which it belongs to.
</del>

## Objective

1. Design for a data store for storing aggregated views.
1. Store and aggregate build metric data for building Pipeline, Job and Collection scoped views.
1. UI to display the time series data about build metrics.
    1. In the time series graph each data point should be color coded which represents it's success/failure status. To make it clearer each data point can be a bar.

**Comment by d2lam** [comment]
### Updates 2/11/2019
The backend for **Metrics at Pipeline scope** is done. These are now available:
1. API endpoint returns time taken for all events belong to this pipeline within time range
2. For each event, there is an API endpoint returns time taken for all builds belong to that event
3. For each build, there is an API endpoint returns time taken for steps belong to that build

**Comment by d2lam** [comment]
### Updates 2/14/2019
Back end is done. The following endpoints are available:

1. [Pipeline's events duration](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/pipelines/README.md#get-event-metrics-for-a-single-pipeline)
2. [Event's builds duration](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/events/README.md#get-build-metrics-for-a-single-event)
3. [Build's steps duration](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/builds/README.md#get-step-metrics-for-a-single-build)
4. [Duration for all builds belong to a specific job](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/jobs/README.md#get-build-metrics-for-a-single-job) (eg. `deploy` job)
5. [Duration for a specific step](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/jobs/README.md#get-step-metrics-for-a-single-job) (eg. `sd-setup-launcher`) across all builds belong to a specific job (eg. `deploy` job)

**Comment by d2lam** [comment]
### Updates 3/14/2019
Based on the new mock designs, we are combining the pipeline metrics & event metrics into 1 API call (https://github.com/screwdriver-cd/models/pull/346) and also adding a couple other fields like `queuedTime` and `imagePullTime` (https://github.com/screwdriver-cd/models/pull/340)

We also decided to limit the time range to 6 months for now, as well as limit the number of returned data so that it doesn't crash our pods. We also decided to do aggregation at API level, since it might be too much for UI to handle.

**Comment by d2lam** [comment]
### Updates 3/27/2019
**Our mock designs:** 
![04a_Metrics-6hr-SelectBuild](https://user-images.githubusercontent.com/3401924/55102508-c5bdd100-5083-11e9-80d5-7cfd5640b2b0.png)

![05a_Metrics-Expanded-Legend](https://user-images.githubusercontent.com/3401924/55102637-17fef200-5084-11e9-9585-a27486c37ad5.png)

**API:** we mainly use 2 endpoints:
- `pipelines/id/metrics`: returns event metrics belong to this pipeline (1st graph), which also includes build metrics for the those events (2nd graph).
_TODO_: aggregation
- `jobs/id/metrics`: returns build metrics belong to this job, which also includes step metrics for those builds (3rd graph). 
Both endpoints are limited to 6 months range, and up to `1000` count without aggregation. 
We have a couple extra endpoints: `events/id/metrics` and `builds/id/metrics`. We can remove them once we decide that we don't need them. Or just leave them be. 

**UI:** we have released alpha version for the 1st and 2nd graph. Will continue working on fixing bugs & edge cases.

**Comment by d2lam** [comment]
### Update 4/10/2019

Build metrics is now live. Example: https://cd.screwdriver.cd/pipelines/1/metrics
<img width="1421" alt="Screen Shot 2019-04-10 at 3 32 15 PM" src="https://user-images.githubusercontent.com/3401924/55917875-d9018e00-5ba5-11e9-9043-1d4552149fb1.png">

_Note/TODO:_ 
- UI is currently displaying non-aggregated data, which will return 1000 records max to ensure it does not put too much load on our DB/API.
- We have `aggregate` option which will aggregate daily/weekly/monthly/yearly and return the average. It's not incorporated into UI yet. Might have an option to toggle this. 
- UI is currently displaying local time zone. We are planning to add an option to select UTC.
- Performance: to improve the performance, we are considering having materialized views. Another option is to spawn worker threads to do computation in parallel. However, we will wait for user feedback before over-engineering it.

**Comment by d2lam** [comment]
### Update 4/22/2019
I've added endpoints for doing aggregation. This will compute the average metric values (duration, imagePullTime, queuedTime, etc) during the aggregation interval. 

Example:
`$API_URL/v4/pipelines/$pipelineId/metrics?startTime=2019-01-01T00:00:00.000Z&endTime=2019-02-01T00:00:00.000Z&aggregateInterval=day`

Available `aggregateInterval` value: `[day, week, month, year]`

**Comment by DekusDenial** [comment]
@d2lam I have tried out the endpoints for `pipeline` and `job` with the new param `aggregateInterval`. But the return data for `pipeline` doesn't contain the aggregated values for `builds`, and for `job` the data doesn't contain aggregated values for `steps`. Also we need the endpoints to return how many actual raw data points are being aggregated as well so that we can plot that information onto the existing charts.

I believe these are the last required items.

**Comment by d2lam** [comment]
> But the return data for pipeline doesn't contain the aggregated values for builds

What do you mean by "doesn't contain values for builds"? The returned data from `https://api.screwdriver.cd/v4/pipelines/1/metrics?startTime=2019-01-01T00:00:00.000Z&aggregateInterval=month` is something like below. For each datapoint, `createTime` is the earliest build in that period. `duration`, `queuedTime`, and `imagePullTime` is the average of all builds during that month. 

```
[
    {
        "createTime": "2019-01-02T20:08:13.973Z",
        "duration": 1972.5,
        "queuedTime": 16.47,
        "imagePullTime": 11.31
    },
    {
        "createTime": "2019-02-01T00:18:06.756Z",
        "duration": 3455.32,
        "queuedTime": 56.75,
        "imagePullTime": 19.89
    },
    {
        "createTime": "2019-03-01T19:02:08.443Z",
        "duration": 2151.31,
        "queuedTime": 20.81,
        "imagePullTime": 18.15
    },
    {
        "createTime": "2019-04-01T18:12:13.722Z",
        "duration": 2054.24,
        "queuedTime": 24.69,
        "imagePullTime": 19.79
    },
    {
        "createTime": "2019-05-01T00:11:03.588Z",
        "duration": 1696.03,
        "queuedTime": 10.32,
        "imagePullTime": 20.37
    }
]
```

**Comment by d2lam** [comment]
>Also we need the endpoints to return how many actual raw data points are being aggregated as well so that we can plot that information onto the existing charts.

I can compute that. Do we only need the count?

**Comment by DekusDenial** [comment]
> > But the return data for pipeline doesn't contain the aggregated values for builds
> 
> What do you mean by "doesn't contain values for builds"? The returned data from `https://api.screwdriver.cd/v4/pipelines/1/metrics?startTime=2019-01-01T00:00:00.000Z&aggregateInterval=month` is something like below. For each datapoint, `createTime` is the earliest build in that period. `duration`, `queuedTime`, and `imagePullTime` is the average of all builds during that month.
> 
> ```
> [
>     {
>         "createTime": "2019-01-02T20:08:13.973Z",
>         "duration": 1972.5,
>         "queuedTime": 16.47,
>         "imagePullTime": 11.31
>     },
>     {
>         "createTime": "2019-02-01T00:18:06.756Z",
>         "duration": 3455.32,
>         "queuedTime": 56.75,
>         "imagePullTime": 19.89
>     },
>     {
>         "createTime": "2019-03-01T19:02:08.443Z",
>         "duration": 2151.31,
>         "queuedTime": 20.81,
>         "imagePullTime": 18.15
>     },
>     {
>         "createTime": "2019-04-01T18:12:13.722Z",
>         "duration": 2054.24,
>         "queuedTime": 24.69,
>         "imagePullTime": 19.79
>     },
>     {
>         "createTime": "2019-05-01T00:11:03.588Z",
>         "duration": 1696.03,
>         "queuedTime": 10.32,
>         "imagePullTime": 20.37
>     }
> ]
> ```

remember we have build breakdown per event?
For each event the api will return the build/job data like the following:

```
{
    "id": 79554,
    "createTime": "2019-05-15T17:49:02.849Z",
    "causeMessage": "Merged by minz1027",
    "sha": "30e86dd0a521262418c4abd9d33c73d4f8ba8e79",
    "duration": 1307,
    "queuedTime": 16,
    "imagePullTime": 40,
    "status": "SUCCESS",
    "builds": [
      {
        "id": 114317,
        "jobId": 21,
        "eventId": 79554,
        "createTime": "2019-05-15T17:49:04.267Z",
        "startTime": "2019-05-15T17:49:15.049Z",
        "endTime": "2019-05-15T17:59:56.264Z",
        "duration": 641,
        "status": "SUCCESS",
        "queuedTime": 3,
        "imagePullTime": 6
      },
      {
        "id": 114324,
        "jobId": 22,
        "eventId": 79554,
        "createTime": "2019-05-15T17:59:57.857Z",
        "startTime": "2019-05-15T18:00:21.263Z",
        "endTime": "2019-05-15T18:06:55.060Z",
        "duration": 393,
        "status": "SUCCESS",
        "queuedTime": 3,
        "imagePullTime": 20
      },
      {
        "id": 114330,
        "jobId": 23,
        "eventId": 79554,
        "createTime": "2019-05-15T18:06:56.669Z",
        "startTime": "2019-05-15T18:07:09.276Z",
        "endTime": "2019-05-15T18:09:59.570Z",
        "duration": 170,
        "status": "SUCCESS",
        "queuedTime": 5,
        "imagePullTime": 7
      },
      {
        "id": 114334,
        "jobId": 24,
        "eventId": 79554,
        "createTime": "2019-05-15T18:10:01.272Z",
        "startTime": "2019-05-15T18:10:13.979Z",
        "endTime": "2019-05-15T18:11:02.868Z",
        "duration": 48,
        "status": "SUCCESS",
        "queuedTime": 5,
        "imagePullTime": 7
      }
    ]
  }
```
By including the param `aggregateInterval`, we should also aggregate among the builds themselves.
FYI, the `pipeline` endpoint is used for plotting 1st and 2nd charts, and the `job` endpoint is for the 3rd chart.

**Comment by DekusDenial** [comment]
> > Also we need the endpoints to return how many actual raw data points are being aggregated as well so that we can plot that information onto the existing charts.
> 
> I can compute that. Do we only need the count?

Yes, the design seems to show only the `count` on top of each bar group in the chart.

**Comment by d2lam** [comment]
There are some complexity when comes to calculating `count`. Some builds might be missing some datapoint due to various of reasons, for example: `queuedTime` or `imagePullTime`. 

For example, during a time period, there might be a total of 25 builds. However, only 20 builds have duration, 15 builds have queuedTime, and 10 builds have imagePullTime. The average is calculated accordingly (avgDuration = totalDuration/20; avgQueuedTime = totalQueuedTime/15, etc). But what do we display the `count` as? We can simply display as `25`, but that is not super accurate. If we are ok with that, I can go ahead and return it.

**Comment by DekusDenial** [comment]
For `count` I think it should be the same as the number of total *raw* data points if the API request is non-aggregate, over the same aggregate interval (day, week, etc).

To put into actual use case, if I see `25` on top of the aggregated bar group for the first week of May, I expect to see 25 bars if I click it to reveal all the raw info in that same week.

But of coz if we think it's bit too complicated, we can discuss with design for a simpler modification.

**Comment by jithin1987** [comment]
Closing this issue, we will open a new one for aggregated view
