### ISSUE TITLE
"adaptor not found" on starting a build

### ISSUE THREAD

**Issue by arunpnetskope** [screwdriver-cd/screwdriver#1425]
Displays this error message in UI while initiating the builds sometimes after creating a pipeline, wonder what could be the reason for this !

We see "circuitBreaker timeout" when try to start the builds, are both these warnings dependent ?

**Comment by jithin1987** [comment]
@arunpnetskope What is usually means is that API was not able to use the executor to create a build. One place you could look is the logs of executor - Docker or k8s -  to see what it's complaining about
