### ISSUE TITLE
Users want to know which job is disablded and who disabled the job on pipeline page.

### ISSUE THREAD

**Issue by yokawara** [screwdriver-cd/screwdriver#1432]
## Context:
It would be nice if we could know which job is disablded and who disabled the job on pipeline page like below.

![image](https://user-images.githubusercontent.com/18387253/50748152-391d2700-127b-11e9-9f02-d28e41268602.png)

**Comment by jithin1987** [comment]
This would be super nice to have 👍 Thanks for the mock up 

cc @DekusDenial

**Comment by catto** [comment]
👍 
I think it's also good if when and why a job was disabled could be displayed. 
`why`: optional comments input by user such as "temporary freeze window" and "under accident response"

**Comment by tkyi** [comment]
@catto I totally agree with your idea.

That also sounds similar to another feature we wanted, which was optionally allowing a user to specify why they were starting an event:
https://github.com/screwdriver-cd/screwdriver/issues/671

**Comment by tkyi** [comment]
**Summary 1/18**: Almost done with UI, just need to fix some tests.
