### ISSUE TITLE
feature: affect commit status(es) via meta

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#1440]
**What you expected to happen**:
I'd be nice if there were some kind of special meta keys which when set would become "commit checks" for github commits (especially for PRs).

**Comment by drewfish** [comment]
(This is similar to #1355, but is for tweaking the commit checks (instead of posting comments).)

**Comment by jithin1987** [comment]
These status can also be actual build steps. If we provide a hook to mark the step itself as, say Unstable but continue with rest of steps, will that suffice ?

**Comment by drewfish** [comment]
That's less than idea. It's quite handy if the github PR page has a list of "checks", each of which either passes or fails.

**Comment by jithin1987** [comment]
I propose we use a syntax like this

```

meta.status.key = {
  status: success/failure,
  url: https://coveralls.io/builds/buildID || Screwdriver build LInk
  description: "",
  context: ""
}
```

Reference - https://developer.github.com/v3/repos/statuses/#create-a-status

**Comment by drewfish** [comment]
would/could the `url` parameter be autogenerated by whatever part of the SD system (or plugin) posts back to github?  or perhaps would it be easy to generate (`SD_BUILD_URL` or something like that)?
