### ISSUE TITLE
feature: lightweight job which just triggers other

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#1449]
For some of my workflows which fan-out, the job which initiates the fan does nothing (single step which just does `echo NOOP`). However I still have to wait for the job to get an executor, which is slow. The feature request is to have some special syntax for defining a job which doesn't actually need to run, but which will satisfy `requires` in other jobs.

**Comment by d2lam** [comment]
Makes sense 👍

**Comment by jithine** [comment]
Closing as duplicate of https://github.com/screwdriver-cd/screwdriver/issues/2470
