### ISSUE TITLE
Display test results in build detail page

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1452]
**What happened**:

Test results are hidden deep inside SonarQube UI.

**What you expected to happen**:

Display test results data in addition to the Coverage data from SonarQube. Ex - https://cd.screwdriver.cd/pipelines/7/builds/87852
 
Display next to coverage info the actual test results. Example `Tests 10/10`

**How to reproduce it**:

Using SonarQube for test results & coverage.

**Comment by jithin1987** [comment]
Also can we provide a meta hook for overriding this value ? ie don't look at SonarQube results if user has provided this in some `meta` value for build

**Comment by minz1027** [comment]
@jithin1987 can we display the unit tests success rate instead? sonar provides that as a metric. But if you think `fail/total` is better, we can also get that.

**Comment by jithin1987** [comment]
@minz1027 information on number of tests is a most asked metric.

**Comment by minz1027** [comment]
okay, will show `(Unit tests - (Unit test errors + Unit test failures)) / Unit tests`
