### ISSUE TITLE
Performance issue of webhook

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1468]
**What happened**:
I have a big github repository that has thousands of pull requests in it. When I open a new pull request in that repository, it takes tens of seconds to process webhook and sometimes ends with timeout by github webhook service (30s).

**What you expected to happen**:
Each webhook is processed in a few seconds.

**How to reproduce it**:
1. Create so many PRs in your repository. It doesn't matter keep them open or close
1. Open new PR or push new commit to the PR

**References**
1. https://github.com/screwdriver-cd/screwdriver/issues/1769
1. https://github.com/screwdriver-cd/screwdriver/issues/1737

**Comment by catto** [comment]
We should check if a result of listFiles API includes the desired SHA or not instead of putting 1.8sec wait so that webhook endpoint will be faster for most cases and every PR build ensures the latest changed files are reflected to github.
https://developer.github.com/v3/pulls/#list-pull-requests-files

**Comment by catto** [comment]
No.2 is being fixed via #1603

**Comment by jithin1987** [comment]
@catto one other issue I see is wrt `scm.getBranchList()` https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/webhooks/index.js#L174

We have that for branch filtering feature for identifying triggered pipelines. However we could refactor it such that it does not reach out to Git and instead query our database for triggered pipelines.

**Comment by jithin1987** [comment]
https://github.com/screwdriver-cd/screwdriver/pull/1643/files addresses my previous comment

**Comment by jithin1987** [comment]
Last work has been done at https://github.com/screwdriver-cd/screwdriver/pull/1653/files which addresses https://github.com/screwdriver-cd/screwdriver/issues/1468#issuecomment-460035553

**Comment by catto** [comment]
Reopening the issue because "3. magic wait for 1.8 secs every time" I wrote is probably fixable now. Also sometimes I see issues like screwdriver.yaml not found because of magic branch is not updated. #593
Let's replace 1.8 sec wait with polling pull_request API.
https://developer.github.com/v3/git/#checking-mergeability-of-pull-requests

**Comment by tanoda** [comment]
according to GitHub doc,
* if `mergeable` is `null`, wait a minute and retry
* if `mergeable` is `true`, we can use `merge` refs to get yaml.
* if `mergeable` is `false`, ... maybe we want to use pipeline branch to get yaml?

**Comment by jithin1987** [comment]
we were discussing the other day https://github.com/screwdriver-cd/screwdriver/issues/1769

current thought process is that we are doing too many processing during webhooks and should push heavy processing to an offline flow

**Comment by catto** [comment]
@jithin1987 Yes I read the issue #1769. However there are two problems around webhooks.
1. SD.cd has a lot of things to do during processing webhooks and the webhooks go timeout sometimes.
2. GitHub sends webhooks asynchronously. It doesn't ensure magic branch has been updated or not when SD.cd receives a webhook.

#1769 will resolves the problem 1 by responding webhook asap but problem 2 will still remain. It also makes unit tests slow since it waits 1.8sec for each test case.
In this ticket, We will focus on fixing problem 2 so that the performance and stability can be improved by trimming 1.8s wait and ensureing an existing of magic branches.
Does it make sense?

**Comment by jithin1987** [comment]
@catto agree. Let's tackle both angles.

**Comment by jithine** [comment]
Closing this one since we already have #1769 to tackle pending performance improvements for webhook API
