### ISSUE TITLE
Secret Management

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#148]
> As a user, I need to have access to my secrets, so I can publish / deploy my application

One of the big blockers with continuous delivery in the existing tools out there is the
availability of secrets to the build. Secrets are needed for publishing packages or code,
deploy to services, and remotely testing if a service is working.

The systems out there usually support secrets in one of three camps:
 - A secret can be available to all people on the shared system
 - A secret can be available just to your pipeline
 - A secret can be available just to a job in your pipeline

Screwdriver should provide a combination of options two and three. This gives developers the
ability to specify secrets that all jobs need to use, and then restrict production secrets
to just the production jobs.

Additionally, developers should be able to customize what secrets are available in a pull
request, even as fine-grained as should it be available in a forked pull-request.

Rules:
 - Saved secrets cannot be viewed by developers, only the name of them should be available
 - Secrets can only be listed, added, changed, or removed by admins of the pipeline
 - Secrets can be strings or generated SSH keys
 - Secrets should be available as environment variables

---
### Preparation
 - [x] Cucumber feature file
 - [x] Secret interface

### Implementation
 - [x] Screwdriver.yaml changes
 - [x] Launcher changes
 - [x] API changes
 - [x] Store changes

### Outcome
 - [x] Screwdriver publishing itself
 - [x] Cucumber feature passing
 - [x] Documentation
 
---
## Notes
 - _nice to have: SSH keys are available in an SSH agent, **not** as environment variables_
 - [Link to Cucumber Feature](https://github.com/screwdriver-cd/screwdriver/blob/fd7f1f02523f15b74a248166717f9bc6d401c467/features/secrets.feature)

**Comment by d2lam** [comment]
```Saved secrets cannot be viewed by developers, only the name of them should be available```

- So they can view the secret names even though they are not admins? 
- Also, they cannot see other fields like `id, pipelineId, allowInPR`?

**Comment by stjohnjohnson** [comment]
I would say that anyone who has `write` access should be able to list the secrets.  Those with `read` should get a 403.  Users with `write` or `admin` should be able to see all properties __EXCEPT__ `value`.
