### ISSUE TITLE
Collapsed jobs

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1482]
# Context
Given a pipeline of a project that users commit code frequently.
e.g. `~commit` -> `test` -> `func-test` -> `deploy`

Sometimes a span between commits would be shorter than job duration.
In this situation, there will be many events that wait for completion of previous `func-test`. 
Users have to wait for a long time to all blocked `func-test` jobs to be completed even if there is no need to run all `deploy` job.

# Objective
Support collapsed job which merges all the blocked jobs to one and runs only once on the most recent commit event.

# Proposal
https://github.com/screwdriver-cd/screwdriver/blob/master/design/workflow.md#collapse

**Comment by minz1027** [comment]
## Updates on 02/11/2019
Discussed with @jithin1987, by default we will do collapse but we will also provide an opt-out config. 
Plan to do it under annotations, e.g.`screwdriver.cd/collapsed: false`.

TO DO:
- [ ] data-schema: add `COLLAPSED` to build status
- [ ] queue-worker: collapsed all the blocked builds into the latest one and update collapsed build status to `COLLAPSED`
-[ ] ui: need to figure out a way to show collapsed events / builds

**Comment by jithin1987** [comment]
@minz1027 perhaps call the annotation `collapseJobs` so that it's more clear on intent.

**Comment by minz1027** [comment]
@jithin1987 `collapseBuilds` is probably more appropriate since we're collapsing builds for a job
