### ISSUE TITLE
[feature] Pre-populate basic meta about build

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#1483]
Provide a key in meta `build` which will have metadata about details pertaining to the build
Eg:
```
build.id => BUILD_ID
build.sha => SHA
build.jobId => JOB_ID
build.pipelineId => PIPELINE_ID
build.jobName => JOB_NAME
```

**Comment by d2lam** [comment]
This feature should be working now:
<img width="1355" alt="screen shot 2019-02-15 at 3 12 29 pm" src="https://user-images.githubusercontent.com/3401924/52889332-40fe9f80-3134-11e9-90f2-8796e3d65192.png">

**Comment by d2lam** [comment]
This feature should be done. 
Default meta is set under `meta.build`
