### ISSUE TITLE
Workflow graph should show job description

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#1493]
**What happened**: We currently have a field for `job` called `description`. Since we aren't displaying it in the UI and haven't advertised the `description` field, users are using job `name` field put descriptions as well. This can lead to very long, messy job names. Since we trim the job names in the UI, it's even harder to figure out which job users are seeing.

**What you expected to happen**: We should display the job `name` and `description` in the UI.

**How to reproduce it**: Create jobs with similar prefixes that are really long.

**Comment by yakanechi** [comment]
@tkyi 
I think this Issue can be closed? Thank you.
