### ISSUE TITLE
Artifacts including white spaces for the filename is unreachable from UI

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1495]
**What happened**:
Artifacts uploaded to the store like
```
./mirror_spec.js/Mirror repository not owned by user -- should fail (failed).png
./mirror_spec.js/Mirror repository owned by users -- should success (failed).png
./mirror_spec.js/Mirror repository that not exist -- should fail (failed).png
```
can not be viewed from UI, it returns 
```
{
statusCode: 404,
error: "Not Found",
message: "Not Found"
}
```

**What you expected to happen**:
Space including files can be viewed from UI

**How to reproduce it**:
Upload artifacts with filename includes white spaces

**info**
The uploading path is encoded to `+` at [here](https://github.com/screwdriver-cd/store-cli/blob/ea9b79c2a8fd9b3a6f3662f50674ac0a5c2090dc/store-cli.go#L93). It might have differences of interpretation between store-cli and UI.

**Comment by tk3fftk** [comment]
Which should we fix, store-cli or UI?
If we choose store-cli, we can use [`url.PathEscape`](https://golang.org/pkg/net/url/#PathEscape) instead of `url.QueryEscape `.

**Comment by tk3fftk** [comment]
This should be closable.
