### ISSUE TITLE
Make SD_ZIP_ARTIFACTS work for large content sizes

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1500]
**What happened**:

Current implementation of SD_ZIP_ARTIFACTS depends on running a AWS Lambda. But this brings in restriction on the size of data that can be unzipped, since the process is dependent on constraints like time & memory imposed by LAMBDA. 

**What you expected to happen**:

SD_ZIP_ARTIFACTS to always work. We can achieve this by leveraging on Screwdriver's internal queue and processing this on our servers instead of AWS Lambda.

**How to reproduce it**:

Use SD_ZIP_ARTIFACTS on a build with very large number of files. While uploading itself is fast, they don't appear in Artifacts section of the build.

**Comment by kkisic** [comment]
Since S3 lambda is not available in our environment, we(YJ team) would like to proceed with the change to a configuration using queue-service too.

**Comment by yuichi10** [comment]
I wrote design for this Issue.
https://github.com/screwdriver-cd/screwdriver/pull/2583

**Comment by kkisic** [comment]
### Remaining Tasks
- Fix queue-service
  - in-progress: https://github.com/screwdriver-cd/queue-service/pull/37
- Implement unzip-worker
- Fix api
- Fix artifact-bookend

**Comment by s-yoshika** [comment]
### Remaining Tasks (UPDATED 2021/12/20)
- [x] 1. Queue Service can accept `unzip` requests from API and enqueue the `unzip` job to `Resque(Redis)`
  - completed: https://github.com/screwdriver-cd/queue-service/pull/37
- [x] 2. Store can accept get/put requests for `artifacts` from `unzip-worker`
  - completed: https://github.com/screwdriver-cd/store/pull/130
- [x] 3. Unzip worker should dequeue `unzip` jobs and get the ZIP for the build from Store, unzip it and re-upload the unzipped artifacts to Store
  - completed: https://github.com/screwdriver-cd/artifacts-unzip-worker/pull/1 
- [ ] 4. API accepts `unzip` requests from `artifacts-bookend` in a build and requests for Queue Service to `unzip`.
  - in-progress:
    - https://github.com/screwdriver-cd/executor-base/pull/75
    - https://github.com/screwdriver-cd/executor-queue/pull/97
    - https://github.com/screwdriver-cd/models/pull/520
    - https://github.com/screwdriver-cd/screwdriver/pull/2616
- [ ] 5. `artifact-bookend` step should request for API to `unzip`
- [ ] 6. `unzip-worker` and `Store` can remove ZIP that has been already unzipped and no longer needed.

![image](https://user-images.githubusercontent.com/5774825/146852971-363da6fd-4dd5-4ca1-a327-a1c1f6d8064d.png)

**Comment by s-yoshika** [comment]
### Remaining Tasks (UPDATED 2022/1/13)
- [x] 1. Queue Service can accept `unzip` requests from API and enqueue the `unzip` job to `Resque(Redis)`
  - completed: https://github.com/screwdriver-cd/queue-service/pull/37
- [x] 2. Store can accept get/put requests for `artifacts` from `unzip-worker`
  - completed: https://github.com/screwdriver-cd/store/pull/130
- [x] 3. Unzip worker should dequeue `unzip` jobs and get the ZIP for the build from Store, unzip it and re-upload the unzipped artifacts to Store
  - completed: https://github.com/screwdriver-cd/artifacts-unzip-worker/pull/1 
- [x] 4. API can accept `unzip` requests from `artifacts-bookend` in a build and request for Queue Service to `unzip`.
  - in-review:
    - https://github.com/screwdriver-cd/executor-base/pull/75
    - https://github.com/screwdriver-cd/executor-queue/pull/97
    - https://github.com/screwdriver-cd/models/pull/520
    - https://github.com/screwdriver-cd/screwdriver/pull/2616
- [ ] 5. `artifact-bookend` step should request for API to `unzip`
- [x] 6. Unzip worker and Store can remove ZIP that has been already unzipped and no longer needed.

![image](https://user-images.githubusercontent.com/5774825/149294900-578dea1a-1cf8-4a67-b4f5-164063bf14a8.png)
