### ISSUE TITLE
Display artifacts in browser

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1501]
**What happened**:

Artifacts can only be downloaded one by one. This does not work for viewing test results or coverage information generated by build tools like codecov. Also this forces users to download all files one by one and 

**What you expected to happen**:

User should be able to browser generated Artifacts, and view test coverage html in browser itself.

**How to reproduce it**:

Click on any test result html generated by Screwdriver build.

**Comment by jithin1987** [comment]
We first need to preserve the content type of each file and find a way to serve the files via either under Screwdriver UI or a separate micro service.

cc @DekusDenial

**Comment by renaud-yahoo** [comment]
One thing to keep in mind: Teardown steps uploading multiple files get slowed down to a *crawl* if there is a high number of small files to archive.

A potential fix would be to allow the microservices to "present" a compressed archive.

**Comment by tk3fftk** [comment]
This issue seems to work in progress. Weren't related PRs referred?

**Comment by adong** [comment]
@tk3fftk 

Related PRs:

UI: https://github.com/screwdriver-cd/ui/pull/465
Backend: https://github.com/screwdriver-cd/screwdriver/pull/1703
Store: https://github.com/screwdriver-cd/store/pull/88
