### ISSUE TITLE
Dot is not permitted to sd-cmds

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1505]
**What happened**:
sd-cmd users could not register a command with the real command version. For example, today's [kustomize version](https://github.com/kubernetes-sigs/kustomize/releases) is 2.0.1, but it never be registered as version 2.0.1. It is because the patch version is incremented automatically. 

**What you expected to happen**:
To deal with it, my proposal is to use `tag name` as the real command version. For example, a command has `0.0.11` as the sd-command version, but it also has `tag` like `v2.0.1`.

**Infomation**:
Now dot is not permitted, so we need to do some changes.

code
https://github.com/screwdriver-cd/data-schema/blob/master/config/regex.js#L13
design doc
https://github.com/screwdriver-cd/screwdriver/blame/master/design/commands.md#L91

**Comment by jithin1987** [comment]
@yoshwata Is this issue about allowing dot in command names ? Could you provide some examples ?

**Comment by yoshwata** [comment]
@jithin1987 Yes, it is just allowing dot. I opened PR.

**Comment by yoshwata** [comment]
This issue is resolved.
