### ISSUE TITLE
`sourcePaths` does not work correctly with large number of changed files

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1510]
**What happened**:

`sourcePaths` does not work correctly if number of changed files is large (>300). 

**What you expected to happen**:

`sourcePaths` should independently of number of changed files.

**How to reproduce it**:

Create a Pull Request where number of changed files is larger than 300.

This happens because Git API call for changed files is paginated & Screwdriver is not handing pagination here.

1. https://developer.github.com/v3/pulls/#list-pull-requests-file
1. https://github.com/screwdriver-cd/scm-github/blob/c9902d966c302bb05afdadbf50b0b1385e06f5a0/index.js#L884-L916

**Comment by minz1027** [comment]
don't think it's paginated, the limit is 300
