### ISSUE TITLE
[feature] Stopping single job from big pipeline graph

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1516]
**What happened**:
Users have to get into the build detail UI to stop a single job.

**What you expected to happen**:
Users can stop a build from the tooltip.

<img width="300" alt="collage2" src="https://user-images.githubusercontent.com/193126/53382720-095cd800-392a-11e9-924e-33f44d22c9bc.png">

**Reference**:
https://github.com/screwdriver-cd/screwdriver/issues/1285#issuecomment-465928533

**Comment by tkyi** [comment]
Blog post: https://blog.screwdriver.cd/post/184069527107/meta-event-label-and-stop-a-build
