### ISSUE TITLE
[META] Need a "meta"/project for Completed Build Landing Page

### ISSUE THREAD

**Issue by renaud-vmg** [screwdriver-cd/screwdriver#1520]
More and more, users of Screwdrivers in VZMedia are requesting features that fall under a specific umbrella: "after-build data".

I would suggest a Project be created under which we can note down all issues related to a Completed Build Landing Page so that we can identify common functionality that would need to be introduced in the Engine Core and "prepare the field", so to speak.

**Comment by jithin1987** [comment]
I've created this label https://github.com/screwdriver-cd/screwdriver/labels/build%20page
feel free to tag issues with this if it's related to build page
