### ISSUE TITLE
Provide an easy way to fetch a job's ID from job name

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1522]
## Context

Need an easy way to fetch any job's ID given a pipeline ID and job Name. This will be useful when dealing with trigger jobs and using API's related to Job.

**Comment by jithin1987** [comment]
`SD_TOKEN` is not able to fetch a pipelines job data 

```
/ # curl -H "Authorization: Bearer $SD_TOKEN" https://api.screwdriver.ouroath.com/v4/pipelines/ID/jobs
{"statusCode":403,"error":"Forbidden","message":"Insufficient scope","data":{"got":["build"],"need":[{"selection":["user","pipeline"]}]}}/ #
```

**Comment by d2lam** [comment]
The endpoint is now available: `v4/pipelines/{id}/jobs?jobName={name}`
This will return an entire an array with 1 job model that matches the job name (since we utilize the same `LIST` endpoint, it's an array)
Also allowed `build` scope to make this call

**Comment by d2lam** [comment]
This is done. If want to create a shared step for your cluster, can follow this script: https://gist.github.com/d2lam/d1251e3431cd50cf7f1de9a5dea74368
