### ISSUE TITLE
[feature request] Officially Supported Template flag 

### ISSUE THREAD

**Issue by frankthrock** [screwdriver-cd/screwdriver#1529]
When searching for templates, I would like to be able to tell the level of support available for each template.  Was a given template built for use by one team for their exclusive use (private)?  Are they willing to address issues?  Is a given template supported by the platform owner? 

The fundamental question I am trying to get answered, is which of the 15 Java templates should I use?

**Comment by jithin1987** [comment]
This is in our backlog https://github.com/screwdriver-cd/screwdriver/issues/1427

UI Mocks - https://github.com/screwdriver-cd/screwdriver/issues/1271#issuecomment-426421541

**Comment by jithin1987** [comment]
This is now available
