### ISSUE TITLE
[bug] UI should not default to red icon if no builds 

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#1531]
**What happened**:
In the UI, the default icon for the side bar is red cross. 

**What you expected to happen**: 
For builds not started because of source path or restrictedPR, we should use gray color.

**How to reproduce it**: 
Run builds with sourcePath or restrictPR

**Comment by DekusDenial** [comment]
The new behavior is:
```
no build, no restrictedPR = no show
no build, yes restrictedPR = start button
```
