### ISSUE TITLE
SD_PULL_REQUEST do not work on PR filter

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1537]
**What happened**:
I cannot refer `$SD_PULL_REQUEST` on build of `~pr:<BRANCH_NAME>`.

**What you expected to happen**:
`SD_PULL_REQUEST` can be referred from `~pr:<BRANCH_NAME>` trigger.

**Comment by kumada626** [comment]
After merged https://github.com/screwdriver-cd/workflow-parser/pull/22 and https://github.com/screwdriver-cd/screwdriver/pull/1594 , builds of `~pr:<BRANCH_NAME>` behave the same as PR builds. Therefore, builds which requires builds of `~pr:<BRANCH_NAME>` are not triggered if chainPR is false.

**Comment by jithin1987** [comment]
@yoshwata @kumada626 is this fixed now ? Can you please close this if so ?

**Comment by yoshwata** [comment]
@jithin1987 Thanks, I confirmed that this problem has already fixed.
