### ISSUE TITLE
Build query result and event's builds query result are not consistent

### ISSUE THREAD

**Issue by DekusDenial** [screwdriver-cd/screwdriver#1545]
**What happened**:

For example:
`/v4/builds/46773` returns finished steps with `endTime`
`/v4/events/31993/builds`, which contains build `46773`, returns steps missing `endTime` even though those steps were finished.

This cause the UI to jump to previous assumingly finished steps with a `running` status, thus causing confusion

**What you expected to happen**:

Both build and event's builds endpoints results should be consistent regarding steps

**How to reproduce it**:

I just start a job on a pipeline over and over again and the issue will surface more than half the times.

**Comment by minz1027** [comment]
hmm i think i know why. We recently removed the query to stepFactory when listing builds to reduce queries to DB. Only `v4/id/build` will give accurate steps meta while the build is running.

So for `/v4/events/id/builds`, it will not get the full steps meta until the build finishes. When the build finished, it will fetch all the steps meta and update it in the `build.steps` field. Now both two endpoints mentioned in the ticket return the same results for steps.

Dekus do you know where do we use info from `/v4/events/id/builds` on the build page? The reload line is here: https://github.com/screwdriver-cd/ui/blob/master/app/pipeline/build/controller.js#L111

I think this is introduced a while ago when we have a `next` build link in the build banner to go to next build in the same event by this PR: https://github.com/screwdriver-cd/ui/pull/190/file. But we removed that already. If it's not used anywhere else, i think we can simply delete that line.

**Comment by jithin1987** [comment]
Is this is a case of race condition in UI ? Does UI take data from `events` end point if it comes first ?

**Comment by minz1027** [comment]
i think when it reloads `events/id/builds`, it override what `v4/id/build` has. But the build page shouldn't need to get other builds from events

**Comment by DekusDenial** [comment]
@minz1027 that seems like a regression to me. When moving from one factory to another, the relationship between data should remain otherwise this is consistency at risk.

The `/v4/events/id/builds` is from reloading model of builds under event model. Whenever a page that create an event model, which is reloadable by the implementation which predates me 🤷‍♂️ 
That line you pointed out only reload after almost everything is done in the build. But the event model already reloads before that happen because the current timer is set at 60 seconds. Any job that takes more than 60 seconds will face this issue. I believe the event model reloads because it needs to keep track of build status so that it can calculate the event status.

@jithin1987 Don't think that qualifies as a race condition, but rather a side effect of doing polling model data, which is more of a fundamental problem.

I think we should fix this inconsistency issue of data from two different endpoints that return , allegedly, identical data about build steps.

**Comment by minz1027** [comment]
Yeah it's kinda bad that `/v4/builds/id` and `/v4/events/id/builds` may return inconsistent data for steps. And we can easily add it back to make it consistent all the time. But i think we should also consider the use case for those 2 endpoints.

It makes perfect sense to reload `/v4/events/id/builds` on the event page, since we care about the builds status for events. But we don't need `steps` info there at all. If we try to make it consistent, that means for each `build`, we need to make a DB query to get `steps` for that build even though we don't need it. 

On the build page, all it shows or cares about will be available from `/v4/builds/id`. The only info it gets from `event` is also static. I see no value keep reloading `event/id/builds` on the build page.

**Comment by minz1027** [comment]
maybe we don't need to pass the all `event` model to the build page: https://github.com/screwdriver-cd/ui/blob/master/app/pipeline/build/template.hbs#L17
