### ISSUE TITLE
Distinct "cause message" for buildPeriodically events

### ISSUE THREAD

**Issue by jeffreytolar** [screwdriver-cd/screwdriver#1558]
The API for describing events (e.g., [`GET /v4/events/{id}`](https://api.screwdriver.cd/v4/documentation#!/v4/getV4EventsId)) returns a `causeMessage` field that details why the event was created.

For scheduled builds (with [buildPeriodically](https://docs.screwdriver.cd/user-guide/configuration/annotations)), this message looks something like `Started by $scm:$username`.

It would be helpful to have a message that indicates the event was created by a timer, e.g., `Started automatically by buildPeriodically "H 10,18 * * *"`.

An additional enhancement would be to allow specifying a custom `causeMessage` for manually triggered builds, e.g., `Started by $scm:$username: pick up new dependencies`. The [`POST /v4/events`](https://api.screwdriver.cd/v4/documentation#!/v4/postV4Events) API is documented to accept a `causeMessage` field, but it seems to be ignored in https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/events/create.js

**Comment by tkyi** [comment]
This issue should be resolved by https://github.com/screwdriver-cd/screwdriver/issues/1058#issuecomment-484299859
