### ISSUE TITLE
Store should stream uploads & downloads so that buffer does not eat up 2G on memory

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#1561]
Store should stream uploads & downloads so that it's not eating too much memory.

**Comment by minz1027** [comment]
### updates 03/21 ###

Currently we use `catbox` for store cache. However `catbox` just doesn't support stream data at this moment. There is an open issue for this: https://github.com/hapijs/hapi/issues/1948.

If we really want to support this, e.g. with `s3`, we may need to get rid of `catbox` and use aws node client directly.

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/requests-using-stream-objects.html

**Comment by minz1027** [comment]
and since we're using aws client in the `cache` plugin already. As first pass, we can just turn the `cache` plugin to use `s3` to upload and download.

https://github.com/screwdriver-cd/store/blob/master/plugins/caches.js

**Comment by jithin1987** [comment]
cc @chestery
