### ISSUE TITLE
Send slack notifications when a build recovers

### ISSUE THREAD

**Issue by karenrfay** [screwdriver-cd/screwdriver#1572]
**What happened**: 
An Sdv4 build failed and correctly alerted our slack channel. After it recovered, however, our slack channel wasn't alerted that it recovered.

**What you expected to happen**:
It would be nice to get a one-time slack message after a previously failing build had recovered. Note that we wouldn't want a slack message every time a build succeeded, however.

This is not a bug, but rather a feature request. Thanks!

This seems to be similar to https://github.com/screwdriver-cd/screwdriver/issues/867 though I think we'd be happy with either approach. If the other approach actually suppresses successive build failures, that might be even better to reduce the slack noise.

**Comment by jithine** [comment]
This now works as expected.
