### ISSUE TITLE
[feature] Filter empty events

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1577]
**What happened**:
When many empty events which are like `[skip ci]` or `no jobs to start` are shown in an event list, substantial events are not shown at first view.

**What you expected to happen**:
We'd like to check substantial events at first view.
One implementation plan is adding a toggle switch on a pipeline or an option page to filter empty events.

**Comment by jithin1987** [comment]
I suggest collapsing all `skip ci` events into one, so that user can see latest SCM content in a single `skip ci` one. This could be done in UI.

**Comment by esuc4se** [comment]
The following implementations are available for empty events or events that have no jobs to start.

1. Add a toggle switch to show / hide empty events or jobs to start in Options
* merit:
  * Once set, it can be left as it is
  * When hidden, the event column will be the cleanest among the improvement plans.
* Demerit:
  * Switching with toggle switch is required

2. Collapse if an empty event or a job to start continues
* merit:
  * If the job continues, it looks clean by folding.
* Demerit:
  * If the event that the build is not executed alternates with the normal build, the problem cannot be solved.

3. Reduce the information displayed in the empty event or the event of the job to be started to one or two lines.
* merit:
  * If there are multiple lines, it will be compact.
* Demerit:
  * It may not be a fundamental solution, such as when there are many skip cies.

Of these implementation plans, I think that **plan 1** can easily and serve its purpose, but what about it?

**Comment by esuc4se** [comment]
@jithine 
Would you take a look?

**Comment by jithine** [comment]
@esuc4se I agree with plan 1. we recently introduced pipeline settings. https://github.com/screwdriver-cd/screwdriver/issues/2605

We can use the same mechanism,

**Comment by esuc4se** [comment]
@jithine 
thank you for your reply.
I would like to implement option1 with these restrictions applied.
> we could still consider option 1 with a constraint that we don't hide the most recent skip ci event.

**Comment by jithine** [comment]
Hello @esuc4se, sounds good. Please go ahead.

**Comment by esuc4se** [comment]
@jithine 
I would like to hear about a toggle switch that shows / hides empty events or jobs.

I'd like to create this toggle switch in the user preference, but what about?
(Is pipeline preference better?)

**Comment by jithine** [comment]
I think Pipeline preference will be better, What do you think @adong  ?
Some of the existing user preferences, we have heard feedback that it would have been better for it to be a pipeline preference

**Comment by adong** [comment]
Yeah, I think pipeline preference is better, and we can let the users have the choice to show/hide empty events.
