### ISSUE TITLE
Store SCM as ID instead of URL

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#160]
I propose that we store an `scm_id` in addition to an `scm_url` in the `pipeline` model.  The `id` should be the unique field and `url` just be a display for the user.

We can generate `id` by a call to `scmModel.getID(url)`.  For GitHub that would be done via a call to https://developer.github.com/v3/repos/#get and https://developer.github.com/v3/repos/branches/#get-branch with a return of `123456:master`.  We know that branches are case-sensitive and repositories have a unique identifier.  Additionally, we can access the repository later (regardless of rename) via [https://api.github.com/repositories/:id](http://stackoverflow.com/questions/28778568/how-to-find-the-new-location-of-a-repository-after-a-rename/)

This stems from https://github.com/screwdriver-cd/screwdriver/issues/82

**Comment by catto** [comment]
`id` should include a unique hostname of GitHub instance if SD will support multiple SCMs like GitHub.com and GitHub Enterprise.  I think it would be better to generate `github.com:123456:master`.

**Comment by stjohnjohnson** [comment]
@catto that's a really good point. :+1:

**Comment by stjohnjohnson** [comment]
I love the move forward with this.  I was drafting up some changes to the data-schema that would include a new Repo, Commit, and User structure.  My idea for Repo structure was:

```javascript
const REPO = Joi.object().keys({
    id: Joi.string()
        .required()
        .label('Unique Identifier')
        .example('github.com:123456:master'),

    name: Joi.string()
        .required()
        .label('Display name')
        .example('screwdriver-cd/screwdriver'),

    url: Joi.string()
        .uri()
        .required()
        .label('Link to Repository')
        .example('https://github.com/screwdriver-cd/screwdriver/tree/master')
}).label('SCM Repository');
```

So this method you're writing should take a SCM_URI and output this structure that we can then store for later use.

**Comment by stjohnjohnson** [comment]
So @catto I did some minor refactoring and moved the scmRepo storage to the sync method:
 - https://github.com/screwdriver-cd/data-schema/pull/58
 - https://github.com/screwdriver-cd/models/pull/106
 - https://github.com/screwdriver-cd/screwdriver/pull/204/files

The next steps would be to:
- [ ] Switch key over to `scmRepo.id`
- [ ] Change create to lookup by `id` when checking for duplicates
- [ ] Update GitHub webhooks to use the `id` that is hopefully in the payload
- [ ] Write a migration script?  Or just nuke the DB and re-create everything.

**Comment by catto** [comment]
@stjohnjohnson Can I move the code checking duplicates to pipelineFactory? I think it is better because the factory has `scmPlugin` and `admin` needed for calling `getRepoId` 
https://github.com/screwdriver-cd/models/pull/110/files

**Comment by stjohnjohnson** [comment]
Good idea.  Do the duplicate check during `pipelineFactory.create`.
