### ISSUE TITLE
Can we add a way to sort jobs alphabetically in a pipeline 

### ISSUE THREAD

**Issue by jweingarten** [screwdriver-cd/screwdriver#1604]
In v3 I have 4 jobs named like this:

```
NativeCoreFlow-Desktop-step1-CreateAd
NativeCoreFlow-Desktop-step2-VerifyFromBrowser
NativeCoreFlow-Desktop-step3-CheckMX3
NativeCoreFlow-Desktop-step4-CheckReporting
```

In SD v4 the jobs are distributed and not in order, which makes it hard to find them. Can we add a view/option for this?

**Comment by yokawara** [comment]
It would also be nice if we could sort jobs according to order defined in screwdriver.yaml.

**Comment by vnugopal** [comment]
@jithin1987 can we prfioritize this

cc @adong

**Comment by adong** [comment]
UI PR: https://github.com/screwdriver-cd/ui/pull/533
