### ISSUE TITLE
Periodic build implementation decouple from API

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#1610]
Currently, periodic build logic is in [executor-queue](https://github.com/screwdriver-cd/executor-queue/blob/master/index.js#L269-L280), which is bundled with the API. However, if the API crashes during the same time periodic build is scheduled to run, it might not add itself to the delayed queue: https://github.com/screwdriver-cd/executor-queue/blob/master/index.js#L320, and periodic build will stop being scheduled.

We should decouple the periodic logic from the API so that API crashing will not affect it.

**Comment by pritamstyz4ever** [comment]
Currently when the node process receives a termination request it is abruptly closed and thus in-process messages are lost. The following PR's will add a graceful shutdown logic which will register tasks to clean up queue related tasks.
https://github.com/screwdriver-cd/models/pull/407
https://github.com/screwdriver-cd/executor-queue/pull/75
https://github.com/screwdriver-cd/executor-base/pull/61
https://github.com/screwdriver-cd/screwdriver/pull/1827
