### ISSUE TITLE
Remote triggers don't remember event source

### ISSUE THREAD

**Issue by hk-vmg** [screwdriver-cd/screwdriver#1635]
**What happened**:
Pipeline "A" job "a" commit "1" triggered pipeline "B" job "b" via a remote requires block (b is a functional test)
Then B@b triggered pipeline "A" job "c" (c is "promote the artifact of A@a to stable")
There was an intervening commit "2" in A.
A@c was run at commit "2" instead of commit "1"

**What you expected to happen**:
A@a->B@b->A@c should run A@a and A@c based on the same version of the source code. Ideally, B@b would also run based on the code that existed at the start of A@a, rather than allowing new commits to be included.

**How to reproduce it**:

**Comment by jithin1987** [comment]
Well this should be an optional behavior, the fact the remote trigger can operate on an older SHA for a pipeline by tracking the event path

**Comment by jithin1987** [comment]
This will be addressed with https://github.com/screwdriver-cd/screwdriver/issues/1710
