### ISSUE TITLE
[bug] PR branch filtering not working

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#1646]
**What happened**: 
PR builds are not created when you have a job `requires: [~pr:testBranch]` when open a PR on some other branch and is against `testBranch`. It will create an empty event but no builds.

checked the second PR from this pipeline: https://cd.screwdriver.cd/pipelines/1724/pulls

**What you expected to happen**: Create the build.

**How to reproduce it**: Create a pipeline on branch `A` and defined a job with PR branch filtering on branch `B`. Commit to branch `C` and open a PR against `B`.

Traced the code and figured out the problem, during event creation, we will call `p.syncPR()` to create necessary PR jobs. However, the trigger uses there is just `~pr` which will not return downstream jobs for `~pr:branch`. Since the job is not created, the build won't be able to be created.

https://github.com/screwdriver-cd/models/blob/master/lib/pipeline.js#L436

**Comment by jithin1987** [comment]
@catto could you take a look into this ?

**Comment by catto** [comment]
:ok_woman: I'll look into it

**Comment by yuichi10** [comment]
In syncPR, it does not assume branch specific PR jobs.
You can see the link below. The code only assume jobs which tigger from `~pr`
https://github.com/screwdriver-cd/models/blob/master/lib/pipeline.js#L436

**Comment by s-yoshika** [comment]
@minz1027 and @jithin1987 I opend some PRs to fix this bug. Could you review those?

**Comment by catto** [comment]
This issue has been fixed
