### ISSUE TITLE
[feature request] Giving permission to ClusterAdmin to delete any template and command

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1651]
**What happened**:
When a command's or template's permission leave from proper owner, for example the case like a user delete repository before pipeline, the user asks us to delete it. We deal it with DB operation on production environment.

**What you expected to happen**:
ClusterAdmin deletes such templates or commands with 🗑(delete) button of the detail page.
I think that is much safer.

**Comment by tkyi** [comment]
Should work with these versions:
API: v0.5.775
UI: v1.0.457

Example where scmUrl does not exist but Screwdriver admin can still remove:
<img width="419" alt="Screen Shot 2019-10-21 at 11 05 43 AM" src="https://user-images.githubusercontent.com/3230529/67230919-19628400-f3f3-11e9-8464-a896cf1dc286.png">
