### ISSUE TITLE
[doc] compatibility table about SCM modules

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1652]
**What happened**:
We have several SCM modules. But some features cannot use with some SCM modules and it's hard to know for users and developers.
For instance, Bitbucket (service) doesn't have release feature and GitLab has release feature but it's not implemented yet.

**What you expected to happen**:
We should provide compatibility table like below:

|                             | scm-github | scm-bitbucket | scm-gitlab |
|-----------------------------|------------|---------------|------------|
| release/tag trigger support |      ✅     |               |            | 
| some feature1               |     ✅       |        ✅       |            |
| some feature2               |     ✅       |          ✅     |    ✅        |

**Comment by tkyi** [comment]
Unfortunately, most of it will just be scm-github ✅✅✅, but I agree this would be good to have

Wondering if it would be good to have something similar for features that require the queue (such as freeze_windows, blocked_by, etc) too

**Comment by tkyi** [comment]
Documentation is available: https://docs.screwdriver.cd/user-guide/scm
