### ISSUE TITLE
Long job name is hard to read on build page

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1656]
**What happened**:
Sometimes my pipeline has a job with long name such as `thisJobBuildsVariousComponentsAndPublishThem` and it satisfies the restriction of job name length.
But the build page shows its job name in a header inappropriately.
![image](https://user-images.githubusercontent.com/1608595/58526809-44adc200-820b-11e9-9479-8b515e3d1740.png)

**What you expected to happen**:
Long job name is shown on each build page with wrapping.

**How to reproduce it**:
https://github.com/catto/sd-test/blob/master/screwdriver.yaml#L6

**Comment by jithine** [comment]
should be fixed with screwdriver-cd/ui#512
