### ISSUE TITLE
Bootstrap Screwdriver Tool

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#166]
This should be a tool that a user can run to bootstrap a Screwdriver setup:
- Create Secrets (JWT, Kubernetes, etc)
- Deploy API (Kubernetes or Locally)
- Deploy Store (Kubernetes or Locally)
- Deploy UI (Kubernetes or Locally)
- Create Database (IMDB or DynamoDB)

Think of it as a replacement/expansion of `dynamic-dynamodb`

Proposed repo name `bootstrap`

**Comment by FenrirUnbound** [comment]
Would this replace what issue #21 is addressing?

As an aside, I would be up for calling it `bb` - short for "big bang". Although some groups may be against such a label.

**Comment by jithin1987** [comment]
we now have helm chart to bootstrap SD in k8s https://github.com/screwdriver-cd/screwdriver-chart
