### ISSUE TITLE
sequalize sync with ALTER blocks all MySQL operations

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1664]
**What happened**:
We use MySQL as a sequelize dialect. 
`datastore-sequalize` setups with [`sync({ alter: true })`](https://github.com/screwdriver-cd/datastore-sequelize/blob/d15c8b1925c6b3284974fbcd8332e7a43285ccaf/index.js#L220) so all ALTER queries are executed in every SD API Pod setup including Pod Restart, Rolling Update for Deployment without schema change. 
Then our MySQL sometimes become disk busy and all operation are blocked by ALTER queries.

**What you expected to happen**:
`alter` parameter of sequalize sync should be optional.

**References:**
- `alter: true` option did not exist at first ( https://github.com/screwdriver-cd/datastore-sequelize/commit/4e9768e6c258ce7b0e5f839ab50b500240715f1b ) 
- [sequalize docs](http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-method-sync)
    - > Alters tables to fit models. Not recommended for production use.
- https://github.com/screwdriver-cd/screwdriver/issues/1298

**Comment by jithin1987** [comment]
https://github.com/screwdriver-cd/data-schema/pull/352
