### ISSUE TITLE
Header redesign

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#1665]
New header design:
<img width="1093" alt="Screen Shot 2019-06-03 at 3 23 39 PM" src="https://user-images.githubusercontent.com/3230529/58838502-b58e1900-8613-11e9-9111-d59acecddaa6.png">

**Comment by tk3fftk** [comment]
Looks good 👍  "Tools" and "Documentation" are separated at last.
Does the search box appear after pushing the magnifying-glass button in new design?

**Comment by tkyi** [comment]
@tk3fftk Yes, I think so.

**Comment by okuryu** [comment]
Don't you think links to Slack, blog and GitHub aren't needed? I have never clicked them on Screwdriver "UI". Just my two cents.

**Comment by adong** [comment]
@okuryu 
Lets see how things go in few days, then we can make changes as needed.
