### ISSUE TITLE
Configurable MAXATTEMPTS and RETRYDELAY on executor-k8s

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1678]
**What happened**:
[An error message](https://github.com/screwdriver-cd/executor-k8s/blob/2d52738caff561335b2aaa5c2620e4818b03c05b/index.js#L407-L409
) was not shown on UI and a build status was not changed even if users use invalid image.

This might be caused by pod's waiting reason is `PodInitializing` after [those retrying](https://github.com/screwdriver-cd/executor-k8s/blob/2d52738caff561335b2aaa5c2620e4818b03c05b/index.js#L391-L400).

**What you expected to happen**:
To prevent this problem, `MAXATTEMPTS` and `RETRYDELAY` should be configurable.

https://github.com/screwdriver-cd/executor-k8s/blob/2d52738caff561335b2aaa5c2620e4818b03c05b/index.js#L19-L20

**Comment by minz1027** [comment]
hmm, just tested in cd.screwdriver.cd, it shows the err msg properly.

https://cd.screwdriver.cd/pipelines/709/builds/129527/steps/sd-setup-init

**Comment by tk3fftk** [comment]
well, in our environment, the err msg is rarely shown.  

> This might be caused by pod's waiting reason is PodInitializing after those retrying.

We assume that a `PodInitializing` phase is longer than cd.screwdriver.cd in our environment because our launcher image size is bigger than OSS original launcher image and there is high disk I/O.

**Comment by tk3fftk** [comment]
This feature can be used in `queue-worker:v2.7.4` and `buildcluster-queue-worker:v1.3.4`.

**Comment by jithin1987** [comment]
Is this issue good to close @tk3fftk  ?
