### ISSUE TITLE
Validator does not recognize some annotations value

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1684]
**What happened**:
![image](https://user-images.githubusercontent.com/3445553/59894123-51909080-941a-11e9-8a83-2e9877629695.png)
A value of `screwdriver.cd/*` annotations is not shown in a validation result. 

**What you expected to happen**:
A value of `screwdriver.cd/*` annotations is shown in a validation result. 

**How to reproduce it**:
Input `screwdriver.yaml` to Validator with `screwdriver.cd/*` annotations.

**Comment by adong** [comment]
This issue is also being used to upgrade ember to 3.16, thanks to @wahapo
