### ISSUE TITLE
Improve skip ci events' view

### ISSUE THREAD

**Issue by yokawara** [screwdriver-cd/screwdriver#1685]
**What happened**:
`skip ci` events' view is hard to recognize on UI.

**What you expected to happen**:
This issue is a proposals for `skip ci` events' view improvement.
It would be better that `skip ci` events are easy to recognize on UI pipeline page like below:

1. Build status becomes `SKIPPED`
2. Pipeline graph shows only skipped icon

![image](https://user-images.githubusercontent.com/18387253/60004992-a0535a00-96a8-11e9-9c1d-a7a930d2e1db.png)

3. Events list item also shows skipped icon

![image](https://user-images.githubusercontent.com/18387253/60005126-ddb7e780-96a8-11e9-9fb1-6610d91eab3c.png)

**Comment by yoshwata** [comment]
Now my skip ci is like below.
![Screen Shot 2019-06-25 at 14 40 40](https://user-images.githubusercontent.com/32473622/60072229-d3085b80-9757-11e9-98b6-c3ad799e6208.jpg)
This proposal is reasonable to understand the job is skipped or not. The arrow between `~commit` and `build` seems to be noisy because that was trigger nothing.

**Comment by tk3fftk** [comment]
@jithin1987 
How is a discussion with design team going?
https://github.com/screwdriver-cd/ui/pull/464#discussion_r303698347

**Comment by jithin1987** [comment]
@tk3fftk we are getting  a new icon from design which will be similar to [fast-forward](https://fontawesome.com/v4.7.0/icon/fast-forward)

**Comment by jithin1987** [comment]
This has been addressed.

**Comment by tk3fftk** [comment]
@jithin1987 
How about an icon design? The current icon looks not good for users.

**Comment by jithin1987** [comment]
Will take this feed back to design our design team. I think we should have an uber issue for UI tweaks, and let this one stay closed.
