### ISSUE TITLE
Bitbucket SCM - API 1.0 Deprecated and Still Used

### ISSUE THREAD

**Issue by xangxiong** [screwdriver-cd/screwdriver#1689]
**What happened**:
The scm-bitbucket currently uses Bitbucket API version 1.0 to download file contents from Bitbucket.  Bitbucket now has officially retired this API and will return the response below:

{"type": "error", "error": {"message": "Resource removed", "detail": "This API is no longer supported.\n\nFor information about its removal, please refer to the deprecation notice at: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/"}}

**What you expected to happen**:
Expect the file to successfully be downloaded and not complain.

**How to reproduce it**:
Attempt to add a new Pipeline using the Bitbucket SCM.  Upon creation of the Pipeline, the Screwdriver internal will attempt to download the screwdriver.yaml file.  This will trigger an error.

**Comment by xangxiong** [comment]
Found that the version 2.0 API is:

https://api.bitbucket.org/2.0/repositories/{owner}/{repoId}/src/{branch}/{file-path}

**Comment by xangxiong** [comment]
Created PR #62 here https://github.com/screwdriver-cd/scm-bitbucket/pull/62.

**Comment by tkyi** [comment]
Thanks @xangxiong for the quick fix! 🙇‍♀

**Comment by xangxiong** [comment]
Looks like the {uuid} extracted from the repoId needs to be URL encoded otherwise the URL will fail.  I will be updating the fix and adding a new PR.

**Comment by xangxiong** [comment]
Ok, turns out it wasn't the {uuid} needing to be encoded.  The API for 2.0 changes and the body return is no longer a JSON, but rather the raw file content.

**Comment by xangxiong** [comment]
Ok, created PR https://github.com/screwdriver-cd/scm-bitbucket/pull/63 for this fix.

**Comment by xangxiong** [comment]
Thanks for the approval and merge @jithin1987 and @tkyi.
