### ISSUE TITLE
bell has been deprecated

### ISSUE THREAD

**Issue by s-yoshika** [screwdriver-cd/screwdriver#1692]
**What happened**:
Screwdriver API uses bell module for OAuth, but it has been deprecated.
https://www.npmjs.com/package/bell
> This module has moved and is now available at @hapi/bell. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

**What you expected to happen**:
`@hapi/bell` should be used instead.

**How to reproduce it**:

**Comment by tkyi** [comment]
Fixed with https://github.com/screwdriver-cd/screwdriver/pull/2195
