### ISSUE TITLE
Improve a modal for restart

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1706]
A model dialog for restart seems to be verbose and lacking of information.
We should select information to show and be simplify.

- Current:
![image](https://user-images.githubusercontent.com/3445553/62261444-459fe180-b450-11e9-84f6-92a39b4debb5.png)

- Improving prototype: 
![image](https://user-images.githubusercontent.com/3445553/62261189-6ae02000-b44f-11e9-9fb7-42ad872f3d39.png)
(a commit msg and sha are a link to scm)

We can add more informations like `parentEventId` or `meta` for https://github.com/screwdriver-cd/screwdriver/issues/1486 (I think users don't consider about `eventId` yet) and https://github.com/screwdriver-cd/screwdriver/issues/1339 .

**Comment by jithin1987** [comment]
Closing with https://github.com/screwdriver-cd/ui/pull/476
