### ISSUE TITLE
Relaxing blockedBy for same job

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1712]
**What happened**:

[Blocked by](https://docs.screwdriver.cd/user-guide/configuration/workflow#blocked-by) ensures that a job is always blocked on itself. However this is not desirable sometimes, if different builds of the job are completely independent, especially if the build is parameterized.

**What you expected to happen**:

Provide an open  to relax Blocked By of self. This can be a job level annotation. 

**How to reproduce it**:

N/A

**Comment by d2lam** [comment]
Sounds reasonable. This should not be too hard to implement. We already have `blockedBy` configurable by default cluster. Just need to allow the option to configure it by job level.

**Comment by jithine** [comment]
We should also take into account of collapsed feature.  Should introduce a delay (lets say 5 mins) such that jobs under this 5 min window will be collapsed into 1.
