### ISSUE TITLE
SCM Bitbucket - Webhook Parse Nonfunctional for Bitbucket Team

### ISSUE THREAD

**Issue by xangxiong** [screwdriver-cd/screwdriver#1713]
**What happened**:
If a Bitbucket repository is owned by a Team instead of a user, the Webhook parsed will have the Team uuid as the owner.  When the Team uuid is used in the SCM url, it prevents Screwdriver from successfully checking out the Bitbucket repository because the Screwdriver has no knowledge of the credentials for the Team.

**What you expected to happen**:
I expect the Webhook to be submitted successfully and the repository to be checkout out successfully.

**How to reproduce it**:
Commit to a repository and push to Bitbucket.  That will trigger the webhook, which will throw an error that the ACCESS TOKEN has expired, but really its because the username embedded into the repository URL is incorrect.

**Comment by xangxiong** [comment]
I do have a propose fix for this.  The Github SCM does not generate a repository URL with the username embedded into the URL, so we can go with the same route.  We can get rid of the username embedded in the Bitbucket URL as well.

Currently in _parseHook, we have:

parsed.checkoutUrl = `${link.protocol}//${encodeURIComponent(repoOwner)}`
                + `@${link.hostname}${link.pathname}.git`;

It can be updated to:

parsed.checkoutUrl = `${link.protocol}//${link.hostname}${link.pathname}.git`;

**Comment by xangxiong** [comment]
Looks like after correcting the URL, the issues is still there.  Still getting a 401.

"type":"error","error":{"message":"Access token expired. Use your refresh token to obtain a new access token."}}
    at breaker.runCommand.then (/usr/src/app/node_modules/screwdriver-scm-bitbucket/index.js:275:27)
    at &lt;anonymous&gt;
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

Will need to verify how the access token is generated and why it is expired and not re-generated.

**Comment by xangxiong** [comment]
Confirm that if the username parsed from the webhook is the same as the user that is logged into Screwdriver, the correct token would be found and use.  The webhook will be process correctly.

If the username parsed from the webhook does not exist in Screwdriver user table yet, or if it matches the scm-username, we will see the 401 refresh token error.  I'm thinking that because if the username is invalid or not found, Screwdriver defaults to the scm-username.  In our case, looks like the token for the scm-username is expired and no longer valid.

Need to find out why the token is not renew by Screwdriver.

**Comment by xangxiong** [comment]
If I login to Screwdriver with the scm-username, then the Webhook is process correctly.  My assumption is that once I login to Screwdriver using the scm-username, I have refresh the token in Screwdriver DB.

@jithin1987 , do you know if there is a way Screwdriver auto-renew the auth token for the scm-username?  Or do we have to manually login whenever the token expires?

**Comment by d2lam** [comment]
> If the username parsed from the webhook does not exist in Screwdriver user table yet, or if it matches the scm-username, we will see the 401 refresh token error. I'm thinking that because if the username is invalid or not found, Screwdriver defaults to the scm-username. In our case, looks like the token for the scm-username is expired and no longer valid.

You're correct. The user needs to login to screwdriver first in order for webhooks to work properly. 

> do you know if there is a way Screwdriver auto-renew the auth token for the scm-username? Or do we have to manually login whenever the token expires?
I vaguely remember that bitbucket token expires. We mainly use github and the token never expires. If bitbucket expires the token after certain time, then yes the user will need to login again. We don't have a mechanism to auto-renew auth token yet. Maybe you can think of some proposal?

**Comment by xangxiong** [comment]
Thanks for the feedback @d2lam.  Bitbucket token expires after every 1-2 hours.  In order to keep the token valid, we need to send a refresh api with the token and the refresh key.  But looks like Screwdriver does not store the refresh key.

According to Bitbucket OAuth API docs, https://developer.atlassian.com/cloud/bitbucket/oauth-2/, the refresh key is return from OAuth auth call.

Here are my thoughts and possible implementation.

1. Updating the Screwdriver Auth to store the refresh key with the token may involve too many changes.  It is probably the correct way to go, but may introduce unnecessary complexity.
    - Involve updating Screwdriver Auth and Token Model
    - Involve adding a new function to the SCM Base (refreshToken)
    - Involve finding a way to capture and handle all 401 errors, and then triggering the refreshToken
    - Can get complicated and touch too many different code locations.

2. Introduce into the Bitbucket SCM the ability to refresh a token. Issue a simple auth api call to Bitbucket using the current Bitbucket Client Id, SCM-Username/Password to re-generate a new access token when a 401 error is encounter for the SCM-Username.
    - Update the Bitbucket SCM, anywhere that makes an API call, if the error is 401, trigger the refresh token, and retry the API call.
    - Need to interact with the Token Factory/Model to update the token when it is re-generated.

Let me know what your thoughts are.  Should the Bitbucket SCM get access to the Token Factory/Model to be able to update an expire token?

**Comment by xangxiong** [comment]
Instead of saving the token in the Token Factory/Model, it was easier and makes more sense to have the Bitbucket SCM manage its own token for authenticating with Bitbucket on READ request.  This way we don't have to update the Token Factory.

The Bitbucket SCM will generate and cache in memory the access token using the OAuth Client ID and Secret passed into as parameters.  This access token will be use for all READ request. 

For WRITE request, it is assume that users are logged in and their access token will be use instead.  This will allow Bitbucket to correctly detect the user making the changes.  If we do need to support WRITE request, we can enable it if needed.

Created PR https://github.com/screwdriver-cd/scm-bitbucket/pull/64.  Please help review and merge if possible.
