### ISSUE TITLE
latest successful build

### ISSUE THREAD

**Issue by uevilwizard** [screwdriver-cd/screwdriver#1717]
Builds are accessible at `/pipelines/<pipeline_id>/builds/<build_id>`, but often I don't want to see a particular build number: I want to see the most recent successful build.  

Can we have a keyword like 'lastSuccessfulBuild' that could be used in place of `<build-id>` ?

**Comment by jithin1987** [comment]
This is similar to Badges API badges `/pipelines/ID/job_name/badge` so I propose we add an end point like thiss ``/pipelines/ID/job_name/latest?status=SUCCESS` which `status` an optional query parameter

**Comment by jithin1987** [comment]
we not have /jobs/:jobID/latestBuild, how ever it will be useful to have `/pipelines/ID/job_name/latestBuild?status=SUCCESS` as well else users will have to make an extra API call to translate job name to ID, or hardcode the information in their pipeline.

**Comment by adong** [comment]
How about the following urls with tags(revision)?

```
1) /pipelines/1/job/main/latest
2) /pipelines/1/job/main/latest?status=SUCCESS
3) /pipelines/1/job/main/latest?status=FAILURE
4) /pipelines/1/job/main/3?status=SUCCESS
5) /pipelines/1/job/main/4?status=FAILURE
6) /pipelines/1/job/main/-1?status=SUCCESS
```

This helps Users to explore

1) latest job named `main` from pipeline 1, which defaults to status `SUCCESS`
2) latest job named `main` from pipeline 1, which status is `SUCCESS`
3) latest job named `main` from pipeline 1, which status is `FAILURE`
4) job named `main` from pipeline 1, 3rd revision that has status `SUCCESS`
5) job named `main` from pipeline 1, 4th revision that has status `FAILURE`
6) job named `main` from pipeline 1, `second`-to-last revision that has status `SUCCESS`


I'd think 6) is going above and beyond for user experience.
