### ISSUE TITLE
Provide a way to set the URL of test and/or coverage reports

### ISSUE THREAD

**Issue by scr-oath** [screwdriver-cd/screwdriver#1718]
test and coverage summary can be set with meta variables, but the url always goes to SonarQube.  It would be useful to be able to set the url as well either absolutely, or also usefully, to a relative path to an artifact (such as an html report).

**Comment by tkyi** [comment]
Possibly related to https://docs.screwdriver.cd/user-guide/metadata#coverage-and-test-results

**Comment by scr-oath** [comment]
See #1716

**Comment by klu909** [comment]
this has been implemented, closing the issue
