### ISSUE TITLE
Can't navigate logs for build in progress because of jumps

### ISSUE THREAD

**Issue by hk-vmg** [screwdriver-cd/screwdriver#1720]
**What happened**:
When a build is in progress, especially a long-running one, it's useful to be able to find information in the logs. However, it's very difficult to scroll up in a log window because new build output causes the view to jump to the bottom.

**What you expected to happen**:
Scrolling a log window should disable refresh events for that window until the page is reloaded.

**How to reproduce it**:
Find a build in progress with lots of frequent output, go to the currently-running step, try to scroll up

**Comment by jithine** [comment]
related https://github.com/screwdriver-cd/screwdriver/issues/1287

**Comment by adong** [comment]
I just created this pipeline to help reproduce the log generation:
https://cd.screwdriver.cd/pipelines/11109/events

Its repo:
https://github.com/adong/sd-random-log-loop/tree/main

**Comment by adong** [comment]
Not sure if this still is an issue, and I think the thought process is something like this:

1) has a checkbox on the build log view to enable/disable the new behavior, so users can choose to opt-in for the "scroll up to stop"/ "scroll to bottom automatically enable loading new logs"

See screenshot: 

![image](https://user-images.githubusercontent.com/15989893/228621563-c7f56f17-b02f-4127-8500-8a5c33582658.png)

2) add a listener to detect scroll-up, and disable auto-scroll, (this does not mean we don't load the logs, just wont' auto scroll to bottom to show latest, just no jump to bottom, and users can navigate)

3) add a listener to detect scroll down (particularly scroll to bottom), and re-enable auto-scroll.

**Comment by hk-vmg** [comment]
FWIW I just re-tested. I don't see the jumping-in-logs now, but each time a new step starts it does jump to the new step.

Would it be possible to set this as a per-user preference for Screwdriver, rather than each build (or each step, or each pipeline)?
