### ISSUE TITLE
Use Node.js v12

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1722]
Screwdriver.cd is using Node.js v8. It will be EOL in 2019-12-31.   
We should use Node.js v10.

Note: Node.js v12 will be LTS since 2019-10-22 but I think it's hard to bump 2 major versions at one time.
Reference: [Releases | Node.js](https://nodejs.org/en/about/releases/)

**Comment by tk3fftk** [comment]
[Node.js 12 to LTS and Node.js 13 is here! - Node.js Foundation - Medium](https://medium.com/@nodejs/node-js-12-to-lts-and-node-js-13-is-here-e28d6a4a2bd)

**Comment by jithine** [comment]
We should go directly to node 12. Also this will be a good opportunity to upgrade our `hapi` dependencies. We are running very old versions.

**Comment by adong** [comment]
Upgrade from `node:10` to `node:12`
UI PR: https://github.com/screwdriver-cd/ui/pull/528

**Comment by jithine** [comment]
Pending ones are queue-worker, since we are working on a `queue-service` node:12 will be addressed in that project https://github.com/screwdriver-cd/screwdriver/issues/1951

**Comment by jithine** [comment]
Closing this, Rest of the libraries/services in node:8 will be updated on a case by case basis.
