### ISSUE TITLE
Enable to use HTML <a> tag on a banner

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1725]
**What happened**:
We cannot use `<a>` tag on a banner. A link on banner should be useful.

**What you expected to happen**:
We can use `<a>` tag on a banner.

**How to reproduce it**:
Create a banner with `<a>` tag or any HTML tags.

**Comment by tkyi** [comment]
This issue should be fixed with UI: v1.0.453

<img width="751" alt="Screen Shot 2019-10-16 at 4 45 08 PM" src="https://user-images.githubusercontent.com/3230529/66967063-6da4e700-f034-11e9-9ece-2a41c5d754c1.png">
