### ISSUE TITLE
Event created from POST /builds  API has missing data

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1741]
**What happened**:
Users can programmatically trigger a job's build in 2 ways

1. Use POST /events with `startFrom` set to job name
1. Use POST /builds with `jobId`

Former will create an `event` which can be rendered nicely (proper mini-graph in events list) in UI, while latter results in full graph in events list because it's missing `startFrom` in event data.

**What you expected to happen**:

Event created as part of POST /builds should have proper `startFrom` data

**How to reproduce it**:

Use POST /builds API to start a job's build.

**Comment by tk3fftk** [comment]
@jithin1987 
What are use case of the second way? 
I think users don't mind `jobId` in generic use so we should recommend the first way for users or should remove the second way's endpoint.

**Comment by jithin1987** [comment]
@tk3fftk 
I do recommend that users should not use `/builds` end point. We need to deprecate it. But we still have users having offline scripts which uses `POST /builds/` to create builds and should give them enough time to change their scripts. 

Issue this fix solves is the presentation in UI. Without having `startFrom` mini-graph in events list does not work and shows the entire large graph.

**Comment by tk3fftk** [comment]
@jithin1987 
I got it. I'll create another issue for deprecation.
