### ISSUE TITLE
If database is MySQL, trusted templates and commands cannot be used

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#1744]
**What happened**:
https://blog.screwdriver.cd/post/185850637397/trusted-templates-and-commands
It seems that `Trusted templates and commands` cannot be used when MySQL is adopted for Database. If even one template is trusted, the template page will not be displayed. The same phenomenon occurs on the command page.
<img width="500" src="https://user-images.githubusercontent.com/24538326/64757465-3a6ec400-d56d-11e9-8414-c7a73bdb86e5.png">

```
[request,server,error] data: Error: "List of templates" at position 0 fails because [child "trusted" fails because ["trusted" must be
 a boolean]], "value" at position 0 fails because ["id" is not allowed, "labels" is not allowed, "config" is not allowed, "name" is not allowed, "version" is not allowed, "description" is not allowed, "maintain
er" is not allowed, "pipelineId" is not allowed, "images" is not allowed, "createTime" is not allowed, "trusted" is not allowed]
    at postValidate (/usr/src/app/node_modules/hapi/lib/validation.js:214:30)
```

**What you expected to happen**:
We want to display the template page even if a trusted template exists.

**How to reproduce it**:
When using MySQL, it seems that an error has occurred due to the value being '0' in the following location.
https://github.com/sequelize/sequelize/blob/398ae59354973348d49d12a08bda2c07bdd7514e/lib/data-types.js#L391

**Comment by wahapo** [comment]
I will fix it.

**Comment by jithin1987** [comment]
fixed with https://github.com/screwdriver-cd/datastore-sequelize/pull/54 

@wahapo please re-open if this is till an issue
