### ISSUE TITLE
Not displayed error message when delete user default collection

### ISSUE THREAD

**Issue by sugarnaoming** [screwdriver-cd/screwdriver#1745]
**What happened**:
Not displayed error message when delete user default collection.
Users don't know why they can't delete.

**What you expected to happen**:
Display message to can't delete user default collection

**How to reproduce it**:
Deleting user default collection

**Image**
![image](https://user-images.githubusercontent.com/10112441/64847851-ed611f80-d64a-11e9-8629-00a7b16bc71c.png)

**Comment by jithin1987** [comment]
This is fixed with https://github.com/screwdriver-cd/ui/pull/477
