### ISSUE TITLE
The meta column in event table is not enough size in MySQL

### ISSUE THREAD

**Issue by s-yoshika** [screwdriver-cd/screwdriver#1763]
**What happened**:
The meta column in event table is defined as `text` type in our MySQL.
And meta of events is empty if the actual size of meta is bigger than 64KB(the size of text type in MySQL).

**What you expected to happen**:
Change the meta column as enough size like `mediumtext`.

**Comment by jithin1987** [comment]
Closing this based on https://github.com/screwdriver-cd/data-schema/pull/356
