### ISSUE TITLE
cannot fire tag trigger by creating annotated tag

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#1764]
**What happened**:
When I create annotated tag and push it, screwdriver cannot trigger the event.

**What you expected to happen**:
Able to fire tag trigger even we use annotated tag

**How to reproduce it**:
1. create annotated tag
2. push the tag

**Comment by jithin1987** [comment]
Fixed with https://github.com/screwdriver-cd/scm-github/pull/141
