### ISSUE TITLE
My Pipelines page is not user friendly for first time Screwdriver.cd users

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#1767]
**What happened**:
The first time you see the Screwdriver.cd screen, hi don't know what to do. If nothing is registered in My Pipelines, it would be more sexy to have the pipeline creation screen displayed.

**Comment by tkyi** [comment]
@Code-Beast is working on the UI portion of this that should help
https://github.com/screwdriver-cd/ui/pull/480

**Comment by jithin1987** [comment]
Latest changes are available in https://cd.screwdriver.cd/ which should address this concerns. Please re-open if that still doesn't address first time user experience for collections.
