### ISSUE TITLE
Restarted job does not always trigger subsequent jobs

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1785]
**What happened**:

If a job is restarted from an event which is result of a previous restart, then context of previous  jobs which successfully completed are not carried over.

For example consider the following scenario

```
jobs:
  A:
    requires: [~commit]
  B:
    requires: [~commit]
  C:
     requires: [A, B]
```

1. In event E1, A is successful but B fails.
2. Restart job B in event E1 to create event E2. Job B fails again in event E2.
3. Restart job B in event E2 to create event E3. Job B is successful in event E3. But job C won't run in event E3.
4. Restart Job B in E1 to create E4 where B is successful. Job C will now start running as part of event E4

**What you expected to happen**:

Context of an jobs in an event should be traceable back to original event from which Job restarts started. In the scenario described above in Step 3 job C should have started in event E3.

**How to reproduce it**:

This problem manifests when a job is being restarted across multiple events.

**Updated** to add one more scenario https://github.com/screwdriver-cd/screwdriver/issues/1785#issuecomment-589771683

**Comment by jithine** [comment]
@kumada626 while the trigger part is fixed, I am seeing a discrepancy on availability of meta, it is not properly carried over on multiple restart cases.

**Comment by jithine** [comment]
but perhaps user's can use `lastSuccessfulMeta` to work around this.

**Comment by jithine** [comment]
Re-opening this to address another situation with restarted jobs across events.

**What Happened**
Let's consider this updated scenario from original description.

1. E1 - Both Jobs A & B fails.
1. E2 - Restarted from E1 and re-run Job A. A passes.
1. E3 - Restarted from E1 and re-run of Job B. B passes
1. In E3 Job C did not run.

**What you expected to happen:**
1. E3 job C should have ran.

**How to reproduce it:**
https://cd.screwdriver.cd/pipelines/4256/events

**Comment by jithine** [comment]
Fix for this will also relate to another feature we want to drive https://github.com/screwdriver-cd/screwdriver/issues/1820

**Comment by tkyi** [comment]
### Tasks

- [ ] (data-schema) add groupEventId to events model
- [ ] (models) save groupEventId if passed into event create
- [ ] (screwdriver) pass in groupEventId for restart case
- [ ] (screwdriver) use groupEventId to determine restart logic
