### ISSUE TITLE
event view does not convey context which triggered it

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1790]
**What happened**:

There are 2 scenarios where a pipeline event does not convey context on what triggered  it.

1. External trigger. When an external pipeline triggers current pipeline `message` UI shows is the commit message corresponding to latest SHA on the current pipeline's SCM branch. To convey context it should display either commit message on the external pipelines SCM SHA or a message which conveys `Started by external pipeline X` and display user from the external pipeline who is responsible for the event trigger.

2. Pull request merge. Currently during pull request merge UI shows information about the user who merged the pull request, not the author of the Pull request itself. Showing the author information in the event will convey the actual user responsible for the event.

**What you expected to happen**:

Event in UI should show proper context on who started it and why. External trigger and Pull request merge is not conveying this information properly.
External trigger should show information from external pipeline - user and message.
Pull request should show information on pull request author. 

**How to reproduce it**:
Look at events for an external trigger and pull request merge.

**Comment by jithin1987** [comment]
Similar issue https://github.com/screwdriver-cd/screwdriver/issues/1407
