### ISSUE TITLE
Pipeline not removed from collection when removing a pipeline

### ISSUE THREAD

**Issue by klu909** [screwdriver-cd/screwdriver#1801]
**What happened**:
pipeline not removed from collections when we remove a pipeline
**What you expected to happen**:
pipeline should be removed from all associated collections when we remove a pipline
**How to reproduce it**:
1.Create a pipeline
2.Remove the pipeline we just created
3.Pipeline still persist in My Pipelines

**Comment by adong** [comment]
- there should NOT be delete options on `My pipelines`, which Collection type is `default`

**Comment by klu909** [comment]
> * there should NOT be delete options on `My pipelines`, which Collection type is `default`

Also adding a guard on api level to prevent modification on `My pipelines`
