### ISSUE TITLE
Deprecate POST /builds endpoint

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1807]
`POST /builds` endpoint was used to start a build in the initial stage of Screwdriver.cd.
But now Screwdriver.cd uses `POST /events` endpoint to start a build so `POST /builds` should be deprecated.

Related: https://github.com/screwdriver-cd/screwdriver/issues/1741#issuecomment-543835833

**Comment by tkyi** [comment]
Should be deprecated now
<img width="748" alt="Screen Shot 2021-05-25 at 11 40 37 PM" src="https://user-images.githubusercontent.com/3230529/119614011-a1202980-bdb2-11eb-9541-7690d2b38b79.png">
