### ISSUE TITLE
SQLite3 dependency error

### ISSUE THREAD

**Issue by tsasaki609** [screwdriver-cd/screwdriver#1810]
**What happened**:
I tried to start server from source, but the error occered.
https://github.com/screwdriver-cd/screwdriver#from-source
```
screwdriver/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81
        throw new Error(`Please install ${moduleName} package manually`);
        ^

Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (/***/screwdriver/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
```
It seems that should add sqlite3 dependency to package.json.

**What you expected to happen**:
The server starts without error.

**How to reproduce it**:
```
git clone git@github.com:screwdriver-cd/screwdriver.git ./
npm i
./bin/server
```

**Comment by jithine** [comment]
This should be fixed now with screwdriver-datastore-sequelize@5.8.4 or newer.

Please cleanup node_modules and if any package-lock.json file
