### ISSUE TITLE
Group events together

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1820]
**What happened**:

When you restart a job from an event, SD creates a new event using same context (git sha / metadata). But context is lost when another event a different trigger gets intertwined.

Lets say event list has following data.

`E1 -> jobs J1 & J2` now user restarted job `J1`. So event list is now this.

`E2  (parent event E1)                                                         -> job J1`
`E1   (parent event none, started from a commit trigger) -> jobs J1 & J2`

Now another commit happens which generates event E3.

`E3   (parent event none, started from a commit trigger) -> jobs J1 & J2`
`E2  (parent event E1, started from manual trigger)          -> job J1`
`E1   (parent event none, started from a commit trigger) -> jobs J1 & J2`

Now let's say user restart `J2` from event `E1` and creates `E4`, events list now looks like this.

`E4  (parent event E1, , started from manual trigger)        -> job J2`
`E3   (parent event none, started from a commit trigger) -> jobs J1 & J2`
`E2  (parent event E1, started from manual trigger)          -> job J1`
`E1   (parent event none, started from a commit trigger) -> jobs J1 & J2`

**What you expected to happen**:

UI Mock
![image (2)](https://user-images.githubusercontent.com/193126/74471347-ec7c2600-4e54-11ea-81b5-de06449b49c2.png)

Screwdriver UI should group events which started from same trigger (git commit/ external trigger). With sequence of events as described above. It will be more intuitive for user to see data like following.

`E4  (parent event E1, , started from manual trigger)        -> job J2`
`E2  (parent event E1, started from manual trigger)          -> job J1`
`E1   (parent event none, started from a commit trigger) -> jobs J1 & J2`
`E3   (parent event none, started from a commit trigger) -> jobs J1 & J2`

UI should club E4, E2 & E1 together since they can be traced back to same commit trigger.

**How to reproduce it**:

Work with pipeline where there are new Pull requests getting merged and user is. trying to restart failed jobs from older events. User will quickly get overwhelmed with scrolling through event list to trace builds back to a specific Pull Request merge.

**Comment by jithine** [comment]
Also one aspect to explore is if we can leverage API to return events data grouped by `groupEventId` so that UI don't have to reorder events.  cc @tkyi @klu909

**Comment by tkyi** [comment]
Would be nice to:
- more obviously visually tie the related events
- tally up number of events in collapsed group

Crude example:
<img width="531" alt="Screen Shot 2021-04-21 at 10 51 26 AM" src="https://user-images.githubusercontent.com/3230529/115599645-b32d1a80-a290-11eb-9f64-d96a31825d58.png">
