### ISSUE TITLE
Build Metrics - Direct link to job is broken

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1822]
**What happened**:

Load metrics for `beta` job from Screwdriver API  [pipeline](https://cd.screwdriver.cd/pipelines/1/metrics?jobId=3)
**What you expected to happen**:

It should have displayed metrics only for the `beta` job.

**How to reproduce it**:

Visit https://cd.screwdriver.cd/pipelines/1/metrics?jobId=3

**Comment by DekusDenial** [comment]
The `jobId` was not initially meant for the second chart, but the third breakdown chart only. But I can alter the logic there.
