### ISSUE TITLE
A little difference between data-schema models and migration file

### ISSUE THREAD

**Issue by sakka2** [screwdriver-cd/screwdriver#1824]
**What happened**:
I used sequelize-cli migrations to create new screwdriver database, and found some differences between data-schema models and migration files. Please see the list below.

| No. | Table | difference |
----|----|---- 
| 1. | banners | Migration file does not have INDEX `banner_is_active` |
| 2. | jobs |  Migration file does not have INDEX `jobs_pipeline_id ` |
| 3. | collections | Migration file does not have UNIQUE KEY |
| 4. | commands | Migration file does not have UNIQUE KEY |
| 5. | commandTags | Migration file does not have UNIQUE KEY |

**What you expected to happen**:
We should add these missing INDEX and UNIQUE KEY into migration files.

**How to reproduce it**:
Run sequelize-cli migrations for new screwdriver database (not existing DB). 

--
On a side note, there are 2 differences between our existing screwdriver database which is not created by migration files and new screwdriver database which is created by migration files.
Our database is MySQL, so I don't know this would happen in PostgresSQL database.

| No. | diffrence | existing database | new database (with migration) | 
----|----|----|---- 
| 1. | id column of all table | `int(10) unsigned` | `int(11)` |
| 2. | name of UNIQUE KEY |  `uniquerow` | different names for each table |

**Comment by jithine** [comment]
@parthasl could you please review this.

**Comment by parthasl** [comment]
@sakka2 

1. banners table count was less than 5; so no need for index banner_is_active and we are not using that index.
2. jobs -> jobs_pipeline_id index is available in migration file -> https://github.com/screwdriver-cd/data-schema/blob/master/migrations/20190919-initdb-jobs.js#L59
3, 4, 5 -> somehow our prod database don't have these unique keys - will raise a PR

1. id column of all table -> Postgresql doesn't have unsigned; if it unsigned it shifts value; is your current MySQL database id is close to 2,147,483,647 ?
2. uniquerow -> in PostgreSQL it's not created with uniquerow. Do you see any problem if it's created with different names for each table?

**Comment by parthasl** [comment]
3, 4, 5, -> somehow our prod database don't have these unique keys -> [PR 365](https://github.com/screwdriver-cd/data-schema/pull/365)

**Comment by jithine** [comment]
Closing this. Please re-open if there are more fixed needed.
