### ISSUE TITLE
use SCM_USERNAME & SCM_ACCESS_TOKEN globally?

### ISSUE THREAD

**Issue by aberfeldy** [screwdriver-cd/screwdriver#1829]
We want to use screwdriver with a github team having only private repos. 
It would be a hassle to define the scm user and password values in each project's secrets separately. 
Is there an easy way to share those(would be from a github bot user)?

**Comment by jithine** [comment]
Right approach here would be to generate & use per repo deploy keys. It's in backlog https://github.com/screwdriver-cd/screwdriver/issues/1079

**Comment by tkyi** [comment]
Above mentioned feature should be available under `Deploy Keys` section: https://docs.screwdriver.cd/cluster-management/configure-api#source-control-plugin
