### ISSUE TITLE
Build cache - disk storage strategy

### ISSUE THREAD

**Issue by parthasl** [screwdriver-cd/screwdriver#1830]
## Context

Provide disk storage strategy support for [build cache](https://docs.screwdriver.cd/user-guide/configuration/build-cache) in Screwdriver infrastructure. 

Screwdriver cluster admins can provision disk based storage (filers or any other technologies)  in the build cluster where builds run. Screwdriver should provide a mechanism to leverage this disk storage and provide local disk space available to each build. [Build cache](https://docs.screwdriver.cd/user-guide/configuration/build-cache) should be able to leverage this storage for all caching purposes. 

## Objective

1. Should support both build cache strategies s3 and disk.
1. SD Cluster admins should be able to specify supported strategies in their configuration.
1. If a SD cluster has multiple build clusters, then SD cluster admins an optionally configure to pick a default build cluster for a pipeline. All builds in the pipeline will be automatically send to the build cluster assigned at pipeline creation time. This should still honor job specific `buildCluster` annotation.
1. executors - [executor-k8s](https://github.com/screwdriver-cd/executor-k8s/) & [executor-k8s-vm](https://github.com/screwdriver-cd/executor-k8s-vm/) should mount the cache directory into build container during setup phase. 
1. [store-cli](https://github.com/screwdriver-cd/store-cli/) should properly move cache files to various paths in the disk cache based on cache scope.

## References
https://github.com/screwdriver-cd/screwdriver/issues/1257

**Comment by parthasl** [comment]
- [ ] api changes as part of 1. build creation, 2. pipeline creation and 3. pipeline update
- [ ] cluster-level configuration / environment variables for cache strategy
- [ ] executor-k8s & executor-k8s vm
- [ ] store cli

**Comment by tk3fftk** [comment]
How is a build scheduled to the same worker node which has a cache? 
I was just wondering.

**Comment by parthasl** [comment]
@tk3fftk Build will not be scheduled to same worker node, instead, cache will be stored in file server and will be available as part of the build.

**Comment by tk3fftk** [comment]
Thanks, I got it. This feature seems to rely on some shared storage.

**Comment by parthasl** [comment]
@tk3fftk yes that's correct
