### ISSUE TITLE
build timeout is not reliable

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1839]
**What happened**:
Build time out which is enforced via [launcher](https://github.com/screwdriver-cd/launcher/blob/master/executor/executor.go#L255) doesn't work on scenarios when build container crashes. This is because it relies on `launcher` process to be running to enforce the time out.

**What you expected to happen**:
SD API should have safeguard against launcher crashes to ensure that build always times out.

**How to reproduce it**:

1. Start a build.
2. Delete build container.
3. Build runs for ever in Screwdriver UI until user manually Stops it.

**Comment by jithine** [comment]
One option we have is to leverage redis-resque for this.

1. API get request to update build status to `RUNNING` from `launcher`.
1. API drops a message in redis queue using [enqueAt](https://github.com/screwdriver-cd/executor-queue/blob/master/index.js#L333-L334) `buildTimeout + delta`
1. Use queue processing to abort build if `launcher` has not already aborted it.

**Comment by kumada626** [comment]
I concern that builds timeout before the real build time is over timeout.
I think that `enqueueTime` is set when the build is added to executor(e.g. k8s, jenkins) from queue.
However, the build is sometimes queued in the executor and not start immediately. For example, the Jenkins itself has own job queue. In such case, the build is killed before the real build time is over timeout.

**Comment by pritamstyz4ever** [comment]
@kumada626 .Thank you for bringing this up, we have addressed this in new PR's by removing enqueue time and adding the build start time when the build status changes to RUNNING. This would be read in the worker and used for timeout considerations.
