### ISSUE TITLE
screwdriver-chart doesn't support kuberntes 1.16+

### ISSUE THREAD

**Issue by s-yoshika** [screwdriver-cd/screwdriver#1846]
**What happened**:
[screwdriver-chart](https://github.com/screwdriver-cd/screwdriver-chart) doesn't work in kubernetes 1.16+.
It contains deployments whose apiVersions are `extensions/v1beta1`, but this apiVersion for deployment are deprecated and removed in kubernetes 1.16. And the dependencies also has same problem.
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**What you expected to happen**:
Migrate to newer apiVersion.

**How to reproduce it**:
Install screwdriver-chart in kubernetes 1.16+.

**Comment by jithine** [comment]
Few related issues

https://github.com/screwdriver-cd/screwdriver/issues/1661
https://github.com/screwdriver-cd/screwdriver/issues/1597
https://github.com/screwdriver-cd/screwdriver/issues/1325
