### ISSUE TITLE
[Feature Request] Pipeline token should be able to create Secrets.

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1847]
**What happened**:
Currently, create Secrets API is only allowed for User's token.
Since secrets are bound to pipelines, it seems better to be able to create secrets for pipeline tokens as well.

**What you expected to happen**:
Allow Pipeline API Token to create Secrets.

**How to reproduce it**:
POST to `/v4/secrets` with Pipeline Token.

**Comment by jithine** [comment]
We should allow pipeline token to also support enable/disable jobs

**Comment by jithine** [comment]
Available with `screwdriver-api@0.5.840`
