### ISSUE TITLE
Restart option in pipeline view

### ISSUE THREAD

**Issue by ashwinjk** [screwdriver-cd/screwdriver#1862]
**What happened**:
When build fails and diving into `Go to build details` shows a restart option. Restarting a build helps preserve the event and meta

**What you expected to happen**:
Please help provide an option to restart from the pipeline view. Pipeline view currently only shows `Start pipeline from here` and this generates a new event and loses meta

**Comment by jithine** [comment]
@ashwinjk `Start pipeline from here` does preserve meta of the event it was restarted from. It does create a new event but it reads meta of the event from which it was restarted.  Infact 
`Restart` from a build detail page and `Start pipeline from here` use same underlying API.

**Comment by ashwinjk** [comment]
If the meta is preserved that is great, I was informed otherwise. Closing this as not an issue
