### ISSUE TITLE
Cannot specify parameters in start pipeline from here

### ISSUE THREAD

**Issue by clayreimann** [screwdriver-cd/screwdriver#1869]
**What happened**:
I have a parameterized pipeline, and I am not able to specify parameter values when I start build from here. This means (as near as I can tell) that there is no way to trigger a detached job with parameters.

**What you expected to happen**:
I would expect the start job confirmation to allow me to specify parameters for the job.

**How to reproduce it**:
Create a pipeline with parameters and a detached job. Try to trigger the detached job and provide parameters

**Comment by jithine** [comment]
make sure that you select an event after the change for parameterized builds was committed. 
if you select an older event prior to parametrized build being enabled in your `screwdriver.yaml`  UI won't allow you to enter parameters.

Also there is an existing bug which prevents parameters being not available to a detached job before atleast one job in the pipeline completes. That was fixed, but new API might not be released in all environments.

**Comment by jithine** [comment]
Please re-open if this is still an issue.
