### ISSUE TITLE
Build with parameters does not get defaults from external trigger

### ISSUE THREAD

**Issue by clayreimann** [screwdriver-cd/screwdriver#1870]
**What happened**:
I have a build that defines parameters. When my build is triggered by `~commit` I see that the parameters have the default values specified in my `screwdriver.yaml`. However when my build is triggered from an external pipeline I see no indication that the parameters are being set to their default values.

```
# sd-setup-init from ~commit triggered run
23:59:07 Build created.
00:00:00 Build parameters: {
  "tag": {
    "value": "none"
  }
}
23:59:08 Build enqueued.
23:59:16 Build scheduled on node94.kube1.corp.bf1.yahoo.com. Starting image pull.
00:00:00 Image pull completed. Build init completed.
```

```
# sd-setup-init from externally triggered run
23:51:27 Build created.
23:51:27 Build enqueued.
23:51:31 Build blocked, putting back into queue.
23:59:39 Build scheduled on node37.kube3.corp.gq1.yahoo.com. Starting image pull.
00:00:00 Image pull completed. Build init completed.
```

**What you expected to happen**:
I expect the default values for my parameters to be set in all cases.

**How to reproduce it**:
Create a build with parameters. Add a `requires: [ sd@xxx ]`. Notice that parameters are not set when run from an external trigger.

**Comment by jithine** [comment]
cc @klu909 @adong
