### ISSUE TITLE
Email notification for UNSTABLE build not supported.

### ISSUE THREAD

**Issue by aatishraj** [screwdriver-cd/screwdriver#1878]
**What happened**:
email notification setting for UNSTABLE is not supported.

**What you expected to happen**:
Expect email notification for an unstable build aswell 

**How to reproduce it**:
`email: 
      addresses: [user1@email.com, user2@email.com]
      statuses: [FAILURE, UNSTABLE]`

**Comment by jweingarten** [comment]
Fix in https://github.com/screwdriver-cd/notifications-email/pull/20

**Comment by adong** [comment]
Thank you @jweingarten !
