### ISSUE TITLE
PRs trigger main?

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#189]
I added an sd.yaml for scm-base to get a build running from an external contributor pr. After closing and reopening the PR, I watched as the PR build completed as expected. Then, much to my surprise, github reported that the build was still running. Clicking into the details again, I was surprised to see the "main" build running for the PR "caused" by some cryptic user id.

https://github.com/screwdriver-cd/scm-base/pull/5
https://cd.screwdriver.cd/builds/dd88e23cf7b306fb9a21503080649a99840d200d

**Comment by d2lam** [comment]
The message is confusing. I believe that's not a cryptic user id but a build id.

**Comment by petey** [comment]
Just to prove this isn't a fluke, the exact same thing happened with: https://github.com/screwdriver-cd/ui/pull/27
