### ISSUE TITLE
Source Directory Support for Bitbucket SCM

### ISSUE THREAD

**Issue by xangxiong** [screwdriver-cd/screwdriver#1890]
**What happened**:
The Source Directory feature seems to only support Github SCM.  It would be beneficial to also support Bitbucket as well.

**What you expected to happen**:
The Source Directory feature to work for Bitbucket.

**How to reproduce it**:
Setup Screwdriver to interface with Bitbucket SCM and try and add a new pipeline specifying the source directory is different than root.

This is more of a feature request and I'm looking for insight on what is missing in the Bitbucket SCM that will need to be implemented to support Source Directory.  Once I have a better understanding of the missing functionality, I can help develop the feature if require.

**Comment by xangxiong** [comment]
Caveats for Source Directory is listed here https://docs.screwdriver.cd/user-guide/configuration/sourceDirectory, supporting only Github.

**Comment by tkyi** [comment]
Bitbucket should support source dir feature now
