### ISSUE TITLE
[Feature Request] Update button on Secrets UI is hardly noticeable

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1892]
**What happened**:
The button on Secrets UI is too simple that users do not notice that the button
on right side of screen becomes `update`. The `VALUE` tends to be unchanged because
they do not push `update` button.

**What you expected to happen**:
This is just an idea.

- The red `delete` button is shown when nothing is filled in `VALUE` text box.
- The blue `update` button is shown something is inputted.
- The green `Add` button is shown every time.

**How to reproduce it**:
Access to secrets page and input something to `VALUE` text box.

**Comment by jithine** [comment]
cc @adong
