### ISSUE TITLE
The /artifacts link of failure build leads to step's screen 

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1903]
**What happened**:
When I click the link like `my.screwdriver.co.jp/pipelines/123/builds/12345/artifacts`, the screen shown in my browser is `my.screwdriver.co.jp/pipelines/123/builds/12345/steps/mystep`.

Then I found that it was happen failed build. This problem is not happen on success build.

**What you expected to happen**:
/artifacts link should leads to /artifacts screen on failure builds.

**How to reproduce it**:
Click the failure build's /artifacts link given your colleagues.

**Comment by jithine** [comment]
This is a UI bug cc @adong

**Comment by adong** [comment]
We have PR https://github.com/screwdriver-cd/ui/pull/517 for UI in place.
