### ISSUE TITLE
hyper-runner.sh exit with error on worker v2.8.6

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1916]
**What happened**:
On vm-build, hyper-runner.sh exit with error like below after update worker to v2.8.6
```
│ vm-launcher Unkown argument: "--job_id"
│ vm-launcher hyper-runner.sh --container <build_container>
│ vm-launcher                 --api_uri <sd_api_uri>
│ vm-launcher                 --build_id <build_id>
│ vm-launcher                 --store_uri <store_uri>
│ vm-launcher                 --ui_uri <ui_uri>
│ vm-launcher                 --id_with_prefix <build_id_with_prefix>
│ vm-launcher                 --build_token <sd_token>
│ vm-launcher                 --cpu <cpu>
│ vm-launcher                 --memory <memory>
│ vm-launcher                 --launcher_version <launcher_version_tag>
│ vm-launcher                 [--build_timeout <seconds>]
│ vm-launcher exit with non-zero code
│ vm-launcher cleanup used workspaces...
```

It seems that hyper-runner.sh do not have option `--job_id`.

**What you expected to happen**:
vm-build can be launched without errror.

**How to reproduce it**:
Update worker to v2.8.6, and start vm-build.

**Reference**
https://github.com/screwdriver-cd/executor-k8s-vm/blob/f8bd60ddc11460ce068993f4c647964bae9b3950/config/pod.yaml.tim#L46
https://github.com/screwdriver-cd/hyperctl-image/blob/90d37d3a2f808b3c55b9f2a1076af5105222f7e8/scripts/hyper-runner.sh#L75

**Comment by jithine** [comment]
Merged PR. Please check if this fixes API issues.

**Comment by yoshwata** [comment]
I confirmed the PR fixed our issues. Thank you @jithine @parthasl @SDTeam
I'll close it.
