### ISSUE TITLE
The title of the command and template detail pages is confusing

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#1920]
**What happened**:
Since the page title of the details page of the command and template is `screwdriver.cd`, it is difficult to distinguish it when using tools such as [Create Link](https://chrome.google.com/webstore/detail/create-link/gcmghdmnkfdbncmnmlkkglmnnhagajbm?hl=ja).

**What you expected to happen**:
I want to be able to identify the command or template page and its name in the page title.
e.g. `Command - <namespace>/<name>`

**How to reproduce it**:
Open any template or command detail page.
(e.g. <https://cd.screwdriver.cd/templates/screwdriver-examples/images-example>)

**Comment by kumada626** [comment]
The page title of a pipeline page likes following.
<img width="255" alt="スクリーンショット 2020-01-27 15 31 33" src="https://user-images.githubusercontent.com/8113204/73154298-47eeaa00-411a-11ea-81eb-52c58e21beb9.png">
I think it is better to show the command/pipeline name in the details page of the command and template, like the pipeline page.
