### ISSUE TITLE
External job that should have been triggered was not triggered

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#1921]
**What happened**:
The external job that should have been triggered was not triggered. This occurred only once a week ago. There is no error in our logs, and I had no clue what was happed.
<img width="1000" src="https://user-images.githubusercontent.com/24538326/72874878-60378100-3d36-11ea-8b33-bae707e4b525.png">

**What you expected to happen**:
Two external jobs in the screenshot are triggered.

**How to reproduce it**:
Sorry, unknown cause.

**Comment by jithine** [comment]
@wahapo can you check any API time out in API logs ? We are noticing increasing API response times which is causing errors like this.

**Comment by wahapo** [comment]
I put it on the team task list. Please give me time to investigate.

**Comment by yoshwata** [comment]
A cause of this issue is fails to access github's `repositories/:id` api. 

The code is here.
https://github.com/screwdriver-cd/scm-github/blob/2d977730f9695c22186c952bcf4d4e13e4603655/index.js#L166

The error is like this.
```
Getting errors with [{"scopeType":"request","route":"GET /repositories/:id","token":"abcde","params":{"id":"12345"}}]: Error: CircuitBreaker timeout
```

**Comment by yoshwata** [comment]
About `/repositories/:id` case, we observed improvement after update API. Most likely reason is node version's update(v12) or relevant oktkit's update.

**Comment by jithine** [comment]
Closing this based on previous comment, please re-open if you are still seeing an issue.
