### ISSUE TITLE
Pull request jobs are not running when using "Source Directory" feature

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1927]
**What happened**:

I have a pipeline which uses source directory https://cd.screwdriver.cd/pipelines/4013/pulls
Pull requests are not running builds despite `requires: [~pr]` in `screwdriver.yaml`

https://github.com/screwdriver-cd-test/source-dir-example/pull/1

**What you expected to happen**:
Pull requests should work.

**How to reproduce it**:

1. Create a pipeline which uses [Source Directory](https://docs.screwdriver.cd/user-guide/configuration/sourceDirectory)
1. Create a pull request against the repository.

**Comment by jithine** [comment]
So this is by design, we need to see if we can relax this constraint.

**Comment by dwmarshall** [comment]
This seems to be working at the present time.

**Comment by jithine** [comment]
It's indeed working. https://github.com/screwdriver-cd-test/source-dir-example/pull/1

Thanks for checking @dwmarshall
