### ISSUE TITLE
Usability when the logged-in SCM is different

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#1937]
**What happened**:
In Screwdriver.cd where multiple scm can be used, I started scm2 pipeline while logged in to scm1. The page displays `Pipeline has no admin` error message. Looking at this error message, I do not know that I should log in to a different SCM.
<img width="600" src="https://user-images.githubusercontent.com/24538326/73430961-99996d80-4382-11ea-85dd-5dea5ef4c9aa.png">

**What you expected to happen**:
I think that adopting `Solution-1` and `Solution-2` will increase users convenience. Solution3 does not know if it is useful unless it measures the effect and measures it, but I think it will be less effective than solution2. Because it is much easier for the user to follow the displayed errors.

`Solution-1`:  At least we need to change the error message to something like the pipeline registration page.
<img width="500" src="https://user-images.githubusercontent.com/24538326/73435310-b8503200-438b-11ea-9d9b-cf979feca099.png">

`Solution-2`:  It is easy for users to display the SCM that requires login along with the message, and then click to log in.
<img width="500" src="https://user-images.githubusercontent.com/24538326/73434075-69a19880-4389-11ea-9e09-519d28215d21.png">

`Solution-3`:  Displaying the logged-in SCM with the user name, users to always recognize the SCM.
<img width="500" src="https://user-images.githubusercontent.com/24538326/73434077-69a19880-4389-11ea-9077-5540f5637211.png">

---
I want to implement Solution1 and solution2. I'm glad if you can give me a response if you have any opinions.

**Comment by jithine** [comment]
I agree with the proposal. Let's do solution 1 & 2. With solution 2 giving us most value. 

Also we can make the link a login dialogue for `scm2`

**Comment by wahapo** [comment]
It is very useful for usability that the login dialog is displayed if necessary. However the case of displaying a login dialog may need to be carefully considered so that users who do not have an account on scm2 will not be inconvenience. If it can not be easily realized, I will fix the put of a login link, which is a mandatory condition for minimal modification.
