### ISSUE TITLE
LogService uses /sd, breaking platforms where /sd is not allowed

### ISSUE THREAD

**Issue by renaud-vmg** [screwdriver-cd/screwdriver#1938]
**What happened**:
Builds in environments that do not allow access to / (such as userspace-enabled macOS builds) cannot use recent versions of log-service (0.0.34 onwards, I believe).

**What you expected to happen**:
Behaviour of 0.0.29, where log files were properly created through the executor and funnelled back to the SD4 core engine.

**How to reproduce it**:
Use log-service 0.0.34+

**Additional comments**:
This can be considered as a major issue for infrastructures that pull in ~latest at all times and may not have ways of forcing earlier versions of certain parts of the engine

**Comment by jithine** [comment]
This is fixed with https://github.com/screwdriver-cd/log-service/releases/tag/v0.0.37

pass in flag `--build-log-folder` to customize where build logs are stored with default being `/sd`
