### ISSUE TITLE
add auto retry functionality 

### ISSUE THREAD

**Issue by jlyons18** [screwdriver-cd/screwdriver#1939]
**What happened**:

I have a service now script that runs to open and close change tickets. 

At the beginning of my job, the service now script opens a change.

I cannot automatically kick off the "cancel" job if my pipeline fails which will leave an unattended open change ticket.

**What you expected to happen**:

If my pipeline fails at any point, I need to kick off the cancel job in order to close out the change ticket it initiated. 

**How to reproduce it**:

Create a repository on Github and use it to create a pipeline in Screwdriver.cd.

This is how it should work:
Create 2 jobs. 
If job one fails, have job two start.
If job one is successful, job two does not run.

**Comment by tk3fftk** [comment]
This issue may be related to https://github.com/screwdriver-cd/screwdriver/issues/1080

**Comment by jithine** [comment]
Closing this in favor of https://github.com/screwdriver-cd/screwdriver/issues/1645
