### ISSUE TITLE
skip_ci events display

### ISSUE THREAD

**Issue by ashwinjk** [screwdriver-cd/screwdriver#1940]
**What happened**:
For pipelines that do a lot of automated skip_ci commits. It makes the UI noisy and harder to trace the last real user commit

**What you expected to happen**:
It will be great if there was UI filter / toggle / tab to separate the skip_ci commits from the real user commits

**Comment by tk3fftk** [comment]
Related https://github.com/screwdriver-cd/screwdriver/issues/1577
