### ISSUE TITLE
Cannot see the step logs in the build that has active step

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1948]
**What happened**:
In the build that has active step, I cannot see the step logs which is not active in the build.
e.g. In the FAILURE build, I cannot see the step logs which is executed before failed step.
https://cd.screwdriver.cd/pipelines/1/builds/169744/steps/install-ci

**What you expected to happen**:
I can see all step logs in all builds.

**How to reproduce it**:
1. Following job exists.
```
jobs:
  steps:
    - foo: ...
    - bar: ...
```
2. Build failed in the `bar` step.
3. Cannot see the `foo` step logs.

**Comment by jithine** [comment]
Fixed with https://github.com/screwdriver-cd/ui/pull/524
