### ISSUE TITLE
External config cleanup deleted non-child pipelines

### ISSUE THREAD

**Issue by klu909** [screwdriver-cd/screwdriver#1949]
**What happened**:
External Config can automatically create child pipelines for listed scm url's. However if there is a pipeline which exists already it won't create a pipeline. Now when this child list is changed and child url is removed, the child pipelines are deleted.

**What you expected to happen**:
External config child pipelines should affect only the child pipelines which were created as part of that specific external pipeline's setup.

**How to reproduce it**:
1.Create two pipeline A and B.
2.Add B as child pipeline in A's yaml.
3.Remove B from A's yaml.
4.Now pipeline B will be deleted even though it shouldn't

**Comment by tk3fftk** [comment]
Is https://github.com/screwdriver-cd/screwdriver/issues/1350 also resolved?

**Comment by klu909** [comment]
> Is #1350 also resolved?

yeah, this was a duplicate to 1350
