### ISSUE TITLE
[Feature Request] Set hook automatically on change repository of a pipeline

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1954]
**What happened**:

Hook on github repository is not set automatically when repository of pipeline is changed manually on Options screen. 

**What you expected to happen**:

Hook on github repository is set automatically on repository's change, like a pipeline is created.

**How to reproduce it**:

1. A pipeline is created as repository `git@aaa`
2. The pipeline's repository is changed to `git@bbb`
3. There is no hooks on repository `git@bbb`, so nothing is triggered on commit.

**Comment by wahapo** [comment]
Fixed in [API@v0.5.965](https://github.com/screwdriver-cd/screwdriver/releases/tag/v0.5.965). It's good to close.
