### ISSUE TITLE
Support AWS Build cluster

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1955]
**What happened**:

With [build cluster queue worker](https://github.com/screwdriver-cd/buildcluster-queue-worker/) Screwdriver can support multiple Build clusters where user builds can run. This involves cluster admins setting up an environment where `build cluster queue worker` can run and picks up bulds available for the cluster. We need an easy way to bring up a build cluster in AWS, where build cluster compute nodes can be scaled up on demand.

**What you expected to happen**:

1. Provide an easy way for users to register a build cluster.
1. Provide a setup script to bring up a build cluster in AWS. 

**How to reproduce it**:

N/A

**References**
1. https://github.com/screwdriver-cd/screwdriver/issues/1243
1. https://github.com/screwdriver-cd/buildcluster-queue-worker/
1. https://github.com/screwdriver-cd/screwdriver-chart

**Comment by DekusDenial** [comment]
infra and build cluster setup can be found at https://github.com/screwdriver-cd/aws-build-cluster with detailed instructions to get started

**Comment by DekusDenial** [comment]
internal mirror and forked were completed, moving to build tool image for internal usage

**Comment by jithine** [comment]
Closing this since build cluster based on AWS EKS setup can be found at https://github.com/screwdriver-cd/aws-build-cluster
