### ISSUE TITLE
Upgrade hapi.js dependencies

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1958]
**What happened**:

Screwdriver hapi.js dependencies are outdated and not supported anymore. 

**What you expected to happen**:

Use current stable versions of `hapi` dependencies. 

**How to reproduce it**:

N/A

**Comment by pritamstyz4ever** [comment]
Initial upgrade:
[data-schema](https://github.com/screwdriver-cd/data-schema):

Upgrade to @hapi/joi
Update breaking schemas:
TypeError: Joi.object(...).keys(...).requiredKeys is not a function
TypeError: Joi.reach is not a function
Error: "language" is not allowed
Error: Method no longer accepts array arguments: valid. Joi.string.valid() does not allow array 
Update structure of Joi.extend schema
https://github.com/sideway/joi/blob/v17.1.1/API.md#extendextensions
