### ISSUE TITLE
Artifact deeplink redirects to console log for failed build

### ISSUE THREAD

**Issue by anilkumarmyla** [screwdriver-cd/screwdriver#1963]
**What happened**:
When opening an artifact deeplink for a failed build, the page redirects to the build log showing why it failed

**What you expected to happen**:
Open the artifact deeplink

**Comment by adong** [comment]
Thank you for reporting, and PR opened to fix this issue.
PR: https://github.com/screwdriver-cd/ui/pull/529

**Comment by anilkumarmyla** [comment]
I believe this is fixed, anything else that needs a followup @adong ? feel free to close
