### ISSUE TITLE
Users who are not cluster admin cannot trash Template/Command even if the Template/Command ware published by them.

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1977]
**What happened**:
The Template/Command which was published by not cluster admin user cannot be trashed by them.
Only cluster admins can trash Template/Command.
Users who have authority to repository that published Template/Command should be able to trash Template/Command.

**What you expected to happen**:
Users who have authority to repository that published Template/Command can trash Template/Command.

**How to reproduce it**:
1. Users who are not cluster admin publish Template/Command.
2. They cannot trash that Template/Command.

**Comment by jithine** [comment]
Does this happen, when user deleted the pipeline which published the command/template in between ?

**Comment by kumada626** [comment]
This happens not only  when user deleted the pipeline which published the command/template, but also even if the pipeline which published the command/template exists.
