### ISSUE TITLE
[Feature Request] Pipeline description

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2007]
**What happened**:
We want to display the description on the pipeline page, just like the description of the collection.

**What you expected to happen**:
If we define the description in the screwdriver.yaml, it is displayed in its pipeline page.
<img width="710" alt="スクリーンショット_2020-03-05_9_22_26" src="https://user-images.githubusercontent.com/8113204/75935761-874fa980-5ec3-11ea-8af1-2dbac3df6594.png">

**How to reproduce it**:
N/A

**Comment by jithine** [comment]
cc @chasturansky

**Comment by yoshwata** [comment]
Let me suggest a specification. @jithine @chasturansky 
Please let me know if you have any concerns. 

# Where to set the description

## Conclusion

Set it with `screwdriver.yaml`

```yaml
annotations:
  screwdriver.cd/pipelineDescription: |
    Please check them before starting job myjob01
    1. foo
    2. bar
    3. buz
```

Then it is shown a prominent position of `/events` and `/builds` screen.

![20200828-pipeline-description-proposal](https://user-images.githubusercontent.com/32473622/91533323-a860f680-e94a-11ea-93ba-0238691b1056.jpg)

## analysis

Our user's needs is to display a note on manual operation of the pipeline in a prominent position on the pipeline page. These note is what users have to check before starting jobs and is what they could not cover with automation.For that reason, the description becomes quite long. That is not something like an introduction of single sentence.

It is important that such description is reviewed by team members before it has shown a pipeline's screen. Therefore, the description should be managed by `screwdriver.yaml`. Like this:

```yaml
annotations:
  screwdriver.cd/pipelineDescription: |
    Check then before starting job myjob01
    1. foo
    2. bar
    3. buz
```

It triggers builds by each changes of description even so the change is only for the description, but it is avertible with `skip ci` function.

On the contrary, being able to manage from the UI is not very suitable for this use case. Although you can modify it easily, it is possible that you accidentally erased it, rewritten it, or no one notices it.

# Should description be shown on collections?

I would like to discuss the question of whether to display this description on the collection screen. 

## Conclution

We don't show the description on the collection screen for now.

## analysis

The collection screen is a function to manage pipelines by grouping them into folders with names of your choice. You can also get a glimpse of relatively fresh information about execution status of pipelines from the screen. There is no room for such the cautionary notes this time, and I think it will be noise. It is sufficient that the precautions for executing jobs are displayed on the screen for executing jobs like `/events` or `/builds`.

**Comment by wahapo** [comment]
I think it's enough if you don't show it on the Collection page at first and respond to requests afterwards.

**Comment by ibu1224** [comment]
@yoshwata 
I think good specification.
Let me ask you one question.
Does the Pipeline description need a character limit?

**Comment by yoshwata** [comment]
> Does the Pipeline description need a character limit?

Yes. 4k bytes of characters is sufficient like command usage.

reference
https://github.com/screwdriver-cd/screwdriver/issues/1596

**Comment by kumada626** [comment]
An annotation field has no limit for a character limit.
https://github.com/screwdriver-cd/data-schema/blob/679ed5d26a7c16d44e69ecac149a37bde1007cb2/models/pipeline.js#L58
https://github.com/screwdriver-cd/data-schema/blob/master/config/annotations.js
So I think it is better to add a description field to pipeline model if we need a character limit to a description field.

**Comment by yoshwata** [comment]
@kumada626 Thanks, I was noticed that the annotation field does not fit to limit the length of characters. I do not think that the limit of the character length is required, so I will set no limit for the time being.

**Comment by adong** [comment]
I like the idea, and looks like this message is scoped to the `pipeline` level.

**Comment by tkyi** [comment]
I'm worried if there's no character limit, could cause issues in the UI display. But we could set a window height limit.

I like the proposed design, and the feature is a great idea. 👍

**Comment by yoshwata** [comment]
@adong @tkyi 
Thank you. We will try to implement with this proposal.
