### ISSUE TITLE
[Feature Request] Needs to fix a hundred of settings

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2013]
**What happened**:

If there are a hundred of repository which have same settings for notification on sd.yaml, the users needs to fix a hundred of notification when the destination was changed.

**What you expected to happen**:

It is just an idea. Expand `Tempalte` function for `settings` not only for `jobs`.

**How to reproduce it**:
N/A

**Comment by tkyi** [comment]
Should be able to pass settings now: https://github.com/screwdriver-cd/template-validator/blob/master/lib/helper.js#L50
