### ISSUE TITLE
 Sign in with gitlab，An error has occurred

### ISSUE THREAD

**Issue by donhui** [screwdriver-cd/screwdriver#2016]
**What happened**:
 Sign in with gitlab，An error has occurred: The redirect URI included is not valid.
screenshot as follows：
![image](https://user-images.githubusercontent.com/5702065/76226574-02fd7d80-6259-11ea-828e-f5134c45f918.png)

**What you expected to happen**:
 Sign in with gitlab success.

**How to reproduce it**:
Getting startted with  [sd-in-a-box](https://git.io/screwdriver-box)
Then use gitlab as the SCM provider.
After installation,  Sign in with gitlab.

**Comment by jithine** [comment]
Is this still happening ? What's the redirect UI setup ? Does the same redirect URI work in github ?

**Comment by donhui** [comment]
@jithine thanks for your feedback.
It's still happening. The 'Redirect URL' is http://192.168.124.4:9001/v4/auth/login , which `192.168.124.4` is my local ip. The same redirect URI works in github.

**Comment by tkyi** [comment]
@donhui it looks like it works if you put the entire thing
Can you try http://192.168.124.4:9001/v4/auth/login/gitlab:gitlab.com/web
