### ISSUE TITLE
SSH Certificate Authorities breaks Webhook

### ISSUE THREAD

**Issue by klu909** [screwdriver-cd/screwdriver#2017]
**What happened**:
When we enable SSHCA in org security it would break webhook due to signature validation errors
**What you expected to happen**:
Webhook should work correctly
**How to reproduce it**:
1. Enable SSHC in org security setting.
2. Open a PR

**Comment by tkyi** [comment]
@jithine suggested it might be good to look into switching to use the npm package's native solution for verification rather than our custom validation logic: 
https://github.com/octokit/webhooks.js/tree/master/verify
https://www.npmjs.com/package/@octokit/webhooks
