### ISSUE TITLE
child pipeline's hook is not set automatically

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2056]
**What happened**:
When creating child pipeline by using external config, webhook is not set on child pipeline's repository automatically.

**What you expected to happen**:
Webhook is set automatically when creating child pipeline.

**How to reproduce it**:
1. Create child pipeline by using external config.
2. See child pipeline's repository, there is no webhook.

**Comment by kumada626** [comment]
I create a parent pipeline like following screwdriver.yaml.
https://github.com/kumada626/parent-pipeline/blob/master/screwdriver.yaml
Then, a child pipeline is created.
https://cd.screwdriver.cd/pipelines/4646/events
However, child pipeline's repository has no webhook.
<img width="1021" alt="スクリーンショット 2020-04-07 14 59 38" src="https://user-images.githubusercontent.com/8113204/78635117-6f16e400-78e0-11ea-9346-cc4f02a23ff5.png">

**Comment by jithine** [comment]
In your case it created the child pipeline but didn't add repo, that means that it did validate permissions and all. 
Will have to check logs on why this happened.
