### ISSUE TITLE
Remove expiry of shared commands

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2058]
**What happened**:
Shared commands expire due to a side effect of using `catbox-s3` for uploading to AWS. Cluster admins must set an expiry time and users suffer if they don't have period builds.

**What you expected to happen**:
This life cycle for shared command is arbitrary and Screwdriver should not be in the business of policing how long should command owners rebuild the commands and force users to use a new version. 

**How to reproduce it**:

1. Publish a shared command. 
2. Try to use it after the command expiry time.

**Comment by jacobtolar** [comment]
Do you propose fixing this by having Screwdriver automatically set an expiry time very far into the future (pretty simple), or by reworking things to not use `catbox-s3` (which I assume is more work https://github.com/hapijs/hapi/blob/a61f7801c525fb7238adf3b074141b20c1bd0517/lib/route.js#L145 https://github.com/screwdriver-cd/store/blob/1dda93eb2ddb07499561e001079ff37b9cbeb5a8/plugins/commands.js#L23-L151 )?
