### ISSUE TITLE
SCM webhooks throws "Not found" error under certain circumstances

### ISSUE THREAD

**Issue by gganapathyvzm** [screwdriver-cd/screwdriver#2062]
**What happened**:
Clicking on SCM webhooks sync throws - "Not found" error

**What you expected to happen**:
The git repo configured for the pipeline is updated with the webhook

**How to reproduce it**:
Let's say we have a repo named - org/repo. 

- A user forks the repo to say - user/repo
- Creates a SD pipeline for the forked repo
- Completes coding and testing the pipeline, merges his/her changes to the main repo and updates the pipeline to use the original repo - org/repo

Now, the original repo - org/repo doesn't have the required webhooks. If the user navigates to the pipeline's options and tries to sync the SCM webhooks, an error - "Not found" is displayed. 

Things to consider - 
The forked repo - user/repo still exists and hasn't been delete/re-created
The main repo - org/repo wasn't deleted/re-created. 

Sync works for pipeline and pull-request options. It only fails for SCM webhooks. 

- Girish

**Comment by jithine** [comment]
I believe https://github.com/screwdriver-cd/screwdriver/issues/2074 should fix this. Please re-open if you still face this.
