### ISSUE TITLE
Branch filtering picks up tags/releases when regex is used

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2067]
**What happened**:
Using regex for branch filtering is starting pipeline jobs on tag/release creation.  

**What you expected to happen**:

When using branch filtering only commits to branches should start pipeline jobs.

**How to reproduce it**:
1. have a regex config for branch filtering `[~commit:/staging/]`. https://github.com/screwdriver-cd-test/branch-filtering-example/blob/master/screwdriver.yaml#L10
1. Create a release with staging in it https://github.com/screwdriver-cd-test/branch-filtering-example/releases 
1. https://cd.screwdriver.cd/pipelines/1838/events

**Comment by jithine** [comment]
cc @yoshwata  @s-yoshika @kumada626

**Comment by kumada626** [comment]
It looks that commit event was created by tag/release action. We will be working on fixing this issue.

**Comment by jithine** [comment]
@kumada626 @wahapo did we support regex match for tags/release ?

I tried in a test repo https://github.com/screwdriver-cd-test/tag-trigger-example/blob/master/screwdriver.yaml#L30
But it didn't trigger the regex job

**Comment by kumada626** [comment]
@jithine Currently, I didn't think there was any support for tag or release filtering.
https://github.com/screwdriver-cd/screwdriver/issues/823#issuecomment-496424248
https://docs.screwdriver.cd/user-guide/configuration/workflow
