### ISSUE TITLE
Large step logs causes browser to hang

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2068]
**What happened**:

UI is loading all the step log data in memory and looping through the data to create a blob to make it downloadable. This does not work for large step log files where there are hundred thousands of log lines.

**What you expected to happen**:

1. UI should not do any custom logic and should defer to API for log download.
1. New API to download step logs with proper caching.
1. UI should remove all custom processing for download step log.

**How to reproduce it**:
1. Create  a large step log file with about 153, 000 lines. 
1. Attempt to download the step log using Download button in log page.

**Comment by sladyn98** [comment]
@jithine I could give this a shot, any tips on how to begin

**Comment by jithine** [comment]
@sladyn98 my apologies, I didn't see your message, now it's a little late I guess 😢
