### ISSUE TITLE
Multiple builds are created for a join job

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2071]
**What happened**:

We're noticing cases where multiple builds are created for a join job. In instance we noticed there were 4 builds created for the join job, with 2 in `SUCCESS` state and 2 in `CREATED` state.

Also one of the `SUCCESS` builds was started because it was ran from a different event's join. See https://github.com/screwdriver-cd/screwdriver/issues/2070

So original state would have been 1 `SUCESS` and 3 `CREATED` builds. 

**What you expected to happen**:

Only one join build should be created for an event. 

**How to reproduce it**:

Difficult. In the event where this was observed, parent builds for the `job` in question completed about same time. 
For example the following config
```
jobs:
   parent-1:
   parent-2:
   parent-3:
   parent-4:
   join:
    requires: [parent-1, parent-2,  parent-3, parent-4]   
```
This issue can happen if builds for parent-1, parent-2,  parent-3, parent-4 completes about same time.

**Comment by jithine** [comment]
Another side effect of this issue is that the join job sometimes doesn't run because the parentBuilds info gets overwritten when multiple parent's complete at about same time.

**Comment by jithine** [comment]
Another scenario when locking is required is for `blockedBy` use case. If there are 2 jobs which blocks each other and when both builds are created almost at same time, it tends to break `blockedBy` guarantees.

**Comment by jithine** [comment]
Explore making the following action into a transaction 
1. Update event.meta
2. SELECT build id for join job name
3. CREATE/UPDATE join build

**Comment by itleigns** [comment]
This problem can still happen. Redlock prevents [triggerNextJobInSamePipeline](https://github.com/screwdriver-cd/screwdriver/blob/d8bd3979fa573ed2cebae7b99432e71b0df62a93/plugins/builds/index.js#L788) from running in parallel, but not for [build state updates](https://github.com/screwdriver-cd/screwdriver/blob/34d7a9ec545a0dc9516e3b5f6d9d18f47dc23d91/plugins/builds/update.js#L228). So this problem occurs in the following cases.
```
jobs:
   parent-1:
   parent-2:
   join:
    requires: [parent-1, parent-2]
```
- `parent-1` succeeds and the status of the build is set  SUCCESS
- `parent-2` succeeds and the status of the build is set  SUCCESS
- `parent-1` triggers `join`
- `parent-2` triggers `join`

In this case, [getParentBuildStatus](https://github.com/screwdriver-cd/screwdriver/blob/d8bd3979fa573ed2cebae7b99432e71b0df62a93/plugins/builds/index.js#L887-L892) returns `done` as `true` in both triggers, so the build is executed twice.

**Comment by jithine** [comment]
@itleigns good catch. We should add protect the status check update with locking https://github.com/screwdriver-cd/screwdriver/blob/34d7a9ec545a0dc9516e3b5f6d9d18f47dc23d91/plugins/builds/update.js#L196-L213 so that the state transition checks can catch this scenario

**Comment by itleigns** [comment]
YJs are thinking about adding a process to check that `newBuild.status` is `CREATED` [here](https://github.com/screwdriver-cd/screwdriver/blob/d8bd3979fa573ed2cebae7b99432e71b0df62a93/plugins/builds/index.js#L530).
This also solves #2612.

**Comment by itleigns** [comment]
Fixed with [this PR](https://github.com/screwdriver-cd/screwdriver/pull/2626).
