### ISSUE TITLE
Randomize build executor selection.

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2083]
**What happened**:

Screwdriver cluster has ability to support multiple build executors - k8s, k8s-vm, jenkins etc . Currently users can use annotation `screwdriver.cd/executor` to pin to a specific executor available in the build cluster,  if they don't want to use the default executor selected by the cluster admin. But there is a need to support distributing builds to multiple executors with in a build cluster instead of always picking the default one. 

**What you expected to happen**:

1. queue workers should have ability to select a build cluster based on weight assigned to an executor type. 
1. Current behavior of users having ability to select an executor should stay.
1. When picking an executor based on weight, cluster admins should be able to set 0 weight to an executor if it should not be part of this random selection. 

We have similar logic when selecting build cluster https://github.com/screwdriver-cd/models/blob/8215e04b6162ed059ba2be8c1974d0d53c14cd8e/lib/helper.js#L105-L118

**How to reproduce it**:

N/A

**Comment by tk3fftk** [comment]
I don't make sense about this feature's value 😥 What is the motivation of this feature? Or do you have any use cases or problems?

**Comment by jithine** [comment]
@tk3fftk use case is this. We are moving from hyperd to Kata as build executor VM. See https://github.com/screwdriver-cd/screwdriver/issues/818 What this means is that the builds have to use `exeucutor-k8s` instead of `executor-k8s-vm`

In a production build cluster with over hundreds of build nodes, we cannot move all the nodes to `Kata` in one shot. So we do it in a staggered manner. What that means is slowly in a production build cluster number of `Hyperd` nodes goes down and number of `Kata` nodes goes up. And a single node cannot have both `Hyperd` & `Kata`. During this process, which can span months, we want to automatically shift build traffic from `Hyperd` nodes to `Kata` nodes. This feature will enable Production Engineering teams to work at their own pace and slowly convert and shift build traffic to `Kata` over a period of time. 

And default executor remains `executor-k8s-vm` in our cluster until we have enough confidence that Kata will work with all build containers. With `weights` we can control how much builds goes to `kata` vs `hyperd`

**Comment by tk3fftk** [comment]
Thank you for your response. I see. It looks like phased releases rather than randomize.

> In a production build cluster with over hundreds of build nodes, 

by the way, it's awesome. We'd like to know the details of your environment another time 🙏
