### ISSUE TITLE
Meta or env var to indicate when build is started by scheduler

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#2084]
**What happened**: When a build is started by the scheduler (due to build periodically, freeze window, etc), the event has scheduler data set in the causeMessage and creator meta; however, there are no fields in the build itself to indicate that the build was started by a scheduler.

**What you expected to happen**: Users expect to be able to get scheduler information from the build itself without having to make another call to get event data.

**How to reproduce it**: Use the [screwdriver.cd/buildPeriodically annotation](https://docs.screwdriver.cd/user-guide/configuration/annotations) in a job and inspect the build data.

**Comment by tkyi** [comment]
Can probably pass in scheduler `meta` from the event to the build here: https://github.com/screwdriver-cd/queue-service/blob/415aa19006f30be7e69753c8736eb03bf3d9c1ea/plugins/queue/scheduler.js#L46-L54

**Comment by anilkumarmyla** [comment]
Any updates?

**Comment by anilkumarmyla** [comment]
Any traction on this ticket would be greatly appreciated

**Comment by anilkumarmyla** [comment]
thanks!
