### ISSUE TITLE
Build runs twice

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2086]
**What happened**:
When I commit to the pipeline branch, GitHub throws the webhook push event twice, resulting in the build running twice.
It only happens on GitHub Enterprise and it doesn't seem to happen on github.com.

The following `1st webhook` and `2nd webhook` were posted at the same time.
`1st webhook`:
```
Request URL: https://(snip)/v4/webhooks
Request method: POST
X-GitHub-Event: push

{
  "ref": "refs/heads/master",
  "before": "dcf15(snip)",
  "after": "ccf8a(snip)",
  "compare": "https://(snip)/wahapo/test/compare/dcf15...ccf8a",
  "head_commit": {
    "distinct": true,
    "url": "https://(snip)/wahapo/test/commit/ccf8a(snip)",
```

`2nd webhook`:
```
Request URL: https://(snip)/v4/webhooks
Request method: POST
X-GitHub-Event: push

{
  "ref": "refs/heads/master",
  "before": "ccf8a(snip)",
  "after": "ccf8a(snip)",
  "compare": "https://(snip)/wahapo/test/compare/ccf8a...ccf8a",
  "head_commit": {
    "distinct": false,
    "url": "https://(snip)/wahapo/test/commit/ccf8a(snip)",
```

**What you expected to happen**:
I want to skip the build of `2nd webhook`.

**How to reproduce it**:
- It can be reproduced by creating a pipeline like [this](https://cd.screwdriver.cd/pipelines/4763) in Screwdriver.cd linked with GitHub Enterprise.
- Probably caused by updating GitHub Enterprise from 2.19.9 to 2.19.13. Details are currently under investigation.
https://enterprise.github.com/releases/2.19.13/notes
https://enterprise.github.com/releases/2.19.12/notes
https://enterprise.github.com/releases/2.19.11/notes
https://enterprise.github.com/releases/2.19.10/notes

**Comment by kumada626** [comment]
This was because of GitHubEnterprise bug. This issue is fixed after GitHubEnterprise version 2.20.X.
