### ISSUE TITLE
Cache cleanup is broken when disk based cache is used

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2087]
**What happened**:

Cache cleanup buttons in Pipeline settings page, does not clear the cache when using disk cache. 

**What you expected to happen**:

Cache cleanup should work no matter which cache strategy is used. 

**How to reproduce it**:

Configure Screwdriver cluster to use disk based cache.

**Comment by parthasl** [comment]
Approach:

Pipeline Options -> Clear Cache

UI -> api
   - check multi-build cluster enabled & cache strategy is disk
   - along with full build config message, add message property type 
            1. pipelines clear cache - {"resource":"caches","type":"invalidate","entity":"pipelines"} or 
            2. jobs clear cache - {"resource":"caches","type":"invalidate","entity":"jobs"})
   - push message to all queues (even if the cluster is disabled). queues will be configured as part of multi-build cluster.

consumer (queue-consumer)
   - mount /cache folder queue-consumer pod, if cache strategy is disk (cluster admins responsibility)
   - check message property type
          - if not available, regular flow (start or stop build)
          - if pipelines clear cache
                 - get pipeline id from full build config and remove the respective folder from the /cache/pipelines  path
          - if jobs clear cache
                 - get job id from full build config and remove the respective folder from the /cache/jobs  path

**Comment by jithine** [comment]
API & UI changes 

1. UI to call new clear cache API
2. Clear cache API will forward requests to store (existing flow) if cache strategy is S3.
3. Clear cache API will forward request to queue-service if cache strategy is disk.

cc @pritamstyz4ever
