### ISSUE TITLE
Pipes of same sd-commands tends to be error

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2090]
**What happened**:
When I use sd-cmd like `sd-cmd exec foo/bar | sd-cmd exec foo/bar`, an error occurs frequently, not everytime.

```
ERROR: Failed to create command file: open /opt/sd/commands/common/yq/3.3.0/yq: text file busy
```

**What you expected to happen**:
The error not happen, and pipes of same sd-cmds work.

**How to reproduce it**:
Execute command like `sd-cmd exec foo/bar | sd-cmd exec foo/bar` in a build

**Comment by tk3fftk** [comment]
I've taken a look this issue with @yoshwata .  
A pipeline of shell just pass `stdout` to piped command's `stdin`. It does not sync.
In this case, the second `sd-cmd` doesn't wait the end of the first `sd-cmd` execution.
Then the second `sd-cmd` try to initialize a binary even the first `sd-cmd` is initializing the binary.
The second `sd-cmd` will run to [this line](https://github.com/screwdriver-cd/sd-cmd/blob/5e0c65b2b7fae59eeec2c253dc3aeb68af795093/executor/executor.go#L81)(or, L71)  before streaming `stdout` from the first `sd-cmd`.

Ref: [Pipeline (Unix) - Wikipedia](https://en.wikipedia.org/wiki/Pipeline_(Unix))
