### ISSUE TITLE
QUEUED notification is sent twice

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2096]
**What happened**:
After we start to use queue-service, QUEUED notifications are sent twice per one build.
![queued_sent_twice](https://user-images.githubusercontent.com/8113204/82965593-7e263280-a003-11ea-8732-afcdbd26a729.jpg)

**What you expected to happen**:
QUEUED notification is sent only one time per one build.

**How to reproduce it**:
Using queue-service,
1. Setting `QUEUED` notifications on a build.
2. A build is queued.
3. `QUEUED` notifications are sent twice.

**Comment by jithine** [comment]
cc @pritamstyz4ever did we create an issue already ? We've seen this before.

**Comment by yoshwata** [comment]
# Cause

I analysed the cause of this issue.

![Screen Shot 2020-08-06 at 14 42 24](https://user-images.githubusercontent.com/32473622/89620585-d5316900-d8ca-11ea-8e4c-071bb6180199.jpg)

1. SDAPI accesses to queueService's [/queue/message](https://github.com/screwdriver-cd/executor-queue/blob/ccedf9e2f69317af9b5c1074bbd1c98344edde20/index.js#L155)
1. queueService [enqueues a build](https://github.com/screwdriver-cd/queue-service/blob/938d3fc5b41c675257806812cac65ecd3e1d0c36/plugins/queue/scheduler.js#L376) to Redis
1. queueService [accesses](https://github.com/screwdriver-cd/queue-service/blob/938d3fc5b41c675257806812cac65ecd3e1d0c36/plugins/queue/scheduler.js#L384) to  [SDAPI's build/{id}](https://github.com/screwdriver-cd/screwdriver/blob/5e60269e36c3bcf3da78a7935f438d922137b7b3/plugins/builds/update.js#L12) for updating build's stats([queueEnterTime](https://github.com/screwdriver-cd/queue-service/blob/938d3fc5b41c675257806812cac65ecd3e1d0c36/plugins/queue/scheduler.js#L285)).
1. queueService [gets a build queue](https://github.com/screwdriver-cd/queue-service/blob/938d3fc5b41c675257806812cac65ecd3e1d0c36/plugins/worker/lib/jobs.js#L155) while it polls Redis.
1. queueService [notifies](https://github.com/screwdriver-cd/queue-service/blob/938d3fc5b41c675257806812cac65ecd3e1d0c36/plugins/worker/lib/jobs.js#L141) k8s to [create a build pod](https://github.com/screwdriver-cd/executor-k8s/blob/04570ed121d55c6bc340436f109824892dbd573f/index.js#L492).
1. queueService [accesses](https://github.com/screwdriver-cd/executor-k8s/blob/04570ed121d55c6bc340436f109824892dbd573f/index.js#L522) to [build/{id}](https://github.com/screwdriver-cd/screwdriver/blob/5e60269e36c3bcf3da78a7935f438d922137b7b3/plugins/builds/update.js#L12) for updating build's stats([imagePullStartTime](https://github.com/screwdriver-cd/executor-k8s/blob/04570ed121d55c6bc340436f109824892dbd573f/index.js#L516)).

Twice QUEUED notifications are kicked on No.3 and No.6. QUEUED notification should be done on No.3, so No.6 is an extra thing.

# Idea to fix

To avoid the extra QUEUED notification, sending [desiredState](https://github.com/screwdriver-cd/screwdriver/blob/5e60269e36c3bcf3da78a7935f438d922137b7b3/plugins/builds/update.js#L37) on No.3 and checking it on SDAPI is effective way. If the desiredState is undefined, the notification would be skipped.

Is this plan reasonable? @jithine @pritamstyz4ever

**Comment by jithine** [comment]
@yoshwata does this ensure queue notification is sent at 3 ? Also when is desired status set to `queued` today ?

**Comment by yoshwata** [comment]
@jithine Yes, QUEUED notification is sent at 3. Today desired status is not set, in other word it is `undefined` at 3 and 6.

**Comment by pritamstyz4ever** [comment]
@yoshwata @jithine 
The slack notification message is sent by triggering of event from [here](https://github.com/screwdriver-cd/screwdriver/blob/5e60269e36c3bcf3da78a7935f438d922137b7b3/plugins/builds/update.js#L187) which is picked up by the notification subscription.
No.6 is doing a build update and that causes another trigger. The build is set to QUEUED after the first build update from queue service at No.3
@yoshwata By sending desiredStatus, do you mean sending the status as 'QUEUED' from No.3 ? and then updating [this](https://github.com/screwdriver-cd/screwdriver/blob/5e60269e36c3bcf3da78a7935f438d922137b7b3/plugins/builds/update.js#L114-L148) logic in api?

**Comment by yoshwata** [comment]
> By sending desiredStatus, do you mean sending the status as 'QUEUED' from No.3 ? and then updating this logic in api?

@pritamstyz4ever Yes, I am currently expecting to send QUEUED as desiredStatus. To do that, It is need to fix where you pointed out to prevent extra notification.

**Comment by jithine** [comment]
@kumada626 are these issues related https://github.com/screwdriver-cd/screwdriver/issues/2507 ? Both seems to contradict each other ?

**Comment by kumada626** [comment]
@jithine This issue and #2507 are not the same cause.
First, this issue was caused and QUEUED notifications were sent twice.
Then, #2507 was caused and QUEUED notification was not sent.
After that, #2510 fixed #2507 and QUEUED notifications were sent twice again.
Finally, #2512 and screwdriver-cd/queue-service#31 were fixed this issue.
Now, QUEUED notification is sent only once each build.
