### ISSUE TITLE
/v4/builds/statuses API error when using MySQL 5.7

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2100]
**What happened**:
Failed to display the [Aggregate View](https://github.com/screwdriver-cd/screwdriver/issues/1967). Because, when I called the following API, SQL error was displayed in the response.

`GET /v4/builds/statuses?jobIds=<snip>&numBuilds=5&offset=0`

`Response`:
```
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '( PARTITION BY jobId ORDER BY id DESC ) AS `rank`\n        FROM builds WHERE jobI' at line 2"
}
```

So, I investigated where the SQL failed.
Screwdriver uses [RANK()](https://github.com/screwdriver-cd/models/blob/2224538ed817a0c1695f95c03907b7af8f3ddad0/lib/rawQueries.js#L14) for [Aggregate View](https://github.com/screwdriver-cd/screwdriver/issues/1967). However, MySQL supports [Window Function Descriptions](https://dev.mysql.com/doc/refman/8.0/en/window-function-descriptions.html) from [8.0.2](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-2.html). Our(YJ) platform doesn't have MySQL8.0 yet.

**What you expected to happen**:
It is preferable that any of the following measures be taken.
- I want to display the aggregate view correctly even when using MySQL5.7.
- I want to disable the aggregate view with the feature flag.

**How to reproduce it**:
- Use MySQL5.7 for DB.
- Use [`screwdrivercd/screwdriver:v0.5.904`](https://hub.docker.com/r/screwdrivercd/screwdriver) of the docker image.
- Call API `GET /v4/builds/statuses`.

**Comment by jithine** [comment]
We might have to tweak the SQL query. We are using `RANK()` in all the SQL raw queries https://github.com/screwdriver-cd/models/blob/master/lib/rawQueries.js

 cc @tkyi @parthasl

**Comment by jithine** [comment]
2 use cases are be impacted here.

1. Aggregate view - https://github.com/screwdriver-cd/screwdriver/issues/1967
2. Restart build - https://github.com/screwdriver-cd/screwdriver/issues/1785

**Comment by parthasl** [comment]
Using FIND_IN_SET and GROUP_CONCAT should work in MySQL 5.7. Need to dump data to MySQL to test it out.
