### ISSUE TITLE
Create pipeline timed out without screwdriver.yaml

### ISSUE THREAD

**Issue by MysticDoll** [screwdriver-cd/screwdriver#2105]
**What happened**:
The request to create a pipeline for a repository without `screwdriver.yaml` timed out. But that pipeline has successfully created.

**What you expected to happen**:
If some errors occur while creating a pipeline, the request should not be timed out and the error response should be returned on that request.

**How to reproduce it**:
1. Create a repository with only a README.md
2. Create a Screwdriver pipeline for that repository

**Comment by MysticDoll** [comment]
I think braces in [this then statement](https://github.com/screwdriver-cd/screwdriver/blob/cfe68b374f1b1d287c9e5f68408ced08e0683666/plugins/pipelines/create.js#L116-L133) cause this problem. If `pipeline.sync` or `pipeline.addWebhook` fails, API cannot reply to the user because the rejected promise is not returned and it can't reach the `catch` statement.

**Comment by jithine** [comment]
@MysticDoll  Is this still an issue ?

**Comment by MysticDoll** [comment]
@jithine This resolved by screwdriver-cd/scm-github#161.
But I think it has still been the problem that it will be timed out if `pipeline.sync()` or `pipeline.addWebhook()` fails while creating a pipeline.

**Comment by jithine** [comment]
Since those are different source than the original concern, I am closing this.
