### ISSUE TITLE
Hermetic server tests

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#211]
We've been hurting for end-to-end testing. As an alternative to E2E tests, what if we proposed having hermetic functional tests? [Related blog post that I have bookmarked that shows my age 😭 ](https://testing.googleblog.com/2012/10/hermetic-servers.html)

In a nutshell, having these tests would perform functional tests for our system, which is what we care about. Instead of mocking internal modules, we would mock external systems (e.g., Github API). This would give us confidence that all of our changes work together. It would _not_ replace E2E testing, which would verify that our product works with everything else in the ecosystem.

**Comment by jithin1987** [comment]
won't fix.
