### ISSUE TITLE
Application metrics

### ISSUE THREAD

**Issue by s-yoshika** [screwdriver-cd/screwdriver#2115]
**What happened**:
Screwdriver.cd has many features and components. And new features are still being developing. It’s becoming complicated and hard to cover all features is correct after new features or components are released. We have acceptance-tests for that, but it doesn’t cover all feature tests, e.g. build timeout, periodic build and so on, these features are hard to test in our acceptance-tests. And also performance issues are hard to notice in these tests.

**What you expected to happen**:
We want to get metrics for our application to detect these problems in monitoring tools like prometheus.

**Comment by s-yoshika** [comment]
If we use prometheus, we can use [promster](https://github.com/tdeekens/promster) which supports some nodejs web framework including hapi.
It exposes nodejs runtime and http based metrics and all we have to do is just register the plugin to hapi server.
https://github.com/tdeekens/promster#-documentation
The list of metris is like following.
```
http_request_duration_seconds_bucket{le="0.05",method="get",path="/v4/pipelines/{id}/jobs",status_code="200"} 1
http_request_duration_seconds_bucket{le="0.1",method="get",path="/v4/pipelines/{id}/jobs",status_code="200"} 1
http_request_duration_seconds_bucket{le="0.3",method="get",path="/v4/pipelines/{id}/jobs",status_code="200"} 1
http_request_duration_seconds_bucket{le="0.5",method="get",path="/v4/pipelines/{id}/jobs",status_code="200"} 1
http_request_duration_seconds_bucket{le="0.8",method="get",path="/v4/pipelines/{id}/jobs",status_code="200"} 1
http_request_duration_seconds_bucket{le="1",method="get",path="/v4/pipelines/{id}/jobs",status_code="200"} 1
http_request_duration_seconds_bucket{le="1.5",method="get",path="/v4/pipelines/{id}/jobs",status_code="200"} 1
http_request_duration_seconds_bucket{le="2",method="get",path="/v4/pipelines/{id}/jobs",status_code="200"} 1
http_request_duration_seconds_bucket{le="3",method="get",path="/v4/pipelines/{id}/jobs",status_code="200"} 1
http_request_duration_seconds_bucket{le="10",method="get",path="/v4/pipelines/{id}/jobs",status_code="200"} 1
http_request_duration_seconds_bucket{le="+Inf",method="get",path="/v4/pipelines/{id}/jobs",status_code="200"} 1
http_request_duration_seconds_sum{method="get",path="/v4/pipelines/{id}/jobs",status_code="200"} 0.018253836
```
It migh be good to start with http based metrics, it represents how long duration takes and what kind of status are increasing on each paths.
And if we need to know more details in each path, we can also add SD’s own metrics with [prom-client](https://www.npmjs.com/package/prom-client) where we need.

**Comment by s-yoshika** [comment]
We can collect API metrics in https://api.screwdriver.cd/v4/metrics now.
but I found some metrics are lost.
The metrics,`sd_http_request_*`, have `status_code` label, but it seems there are no status_code about 40x and 50x but only 20x and 30x.
I think it's due to using boom because these status code are all replied with `boom.boomify`.
And i found it go well if hapi is upgrade to 19 even if it uses boom.boomify.

**Comment by DekusDenial** [comment]
@s-yoshika also, do you happen to know the configuration to enable the `sd_*` metrics data labeled with the pod's name as well as the node instance?

**Comment by jithine** [comment]
We modified our deployment to do a canary release, wight now `4.0.14` is serving 25 % production traffic. Will be using prometheus data to monitor API latency and throughput, if all goes well, we will move canary to 100% traffic

**Comment by jithine** [comment]
<img width="349" alt="Screen Shot 2020-09-30 at 9 55 27 PM" src="https://user-images.githubusercontent.com/193126/94769899-f614b880-0367-11eb-87ee-66d0321c8f49.png">

With hapi 19 40xx & 5xx status codes are now showing up.
