### ISSUE TITLE
Should not use too common env PUSHGATEWAY_URL

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2116]
**What happened**:
Screwdriver.cd uses `PUSHGATEWAY_URL` env for sending metrics.
However, env name `PUSHGATEWAY_URL` is too common, this env name sometimes used by other frameworks(e.g. spring boot properties automatically read env `PUSHGATEWAY_URL`).
So we should use more uniqueue env name(e.g. `SD_PUSHGATEWAY_URL`).

**What you expected to happen**:
Screwdriver.cd uses not too common env name.

**How to reproduce it**:
1. Cluster admin sets [ECOSYSTEM_PUSHGATEWAY_URL](https://github.com/screwdriver-cd/queue-service/blob/521b50eb7ff24bc7a979d2975cc1b91c66f9f8ef/config/custom-environment-variables.yaml#L206).
2. In all builds, env `PUSHGATEWAY_URL` is defined by default.

**Comment by jithine** [comment]
cc @parthasl @DekusDenial
