### ISSUE TITLE
Notification of deployments

### ISSUE THREAD

**Issue by jpcollins** [screwdriver-cd/screwdriver#212]
It would be great to have a hook where I can get notified in my slack channel when a deploy starts and stops.

**Comment by stjohnjohnson** [comment]
This should be possible now if you wanted to.  Add your slack token as a secret (via your pipeline page) and run a curl call against slack's API: https://api.slack.com/incoming-webhooks before/after your deployment

If you wanted something more formalized, we have three options:
 - shared step for slack notification
 - SD bot service we can offer (to shuffle data to/from slack - even respond to `/` commands)
 - direct integration into SD for slack notifications

**Comment by petey** [comment]
We will track adding Slack support in https://github.com/screwdriver-cd/screwdriver/issues/687
