### ISSUE TITLE
Pipeline list view issues

### ISSUE THREAD

**Issue by DekusDenial** [screwdriver-cd/screwdriver#2124]
**What happened**:

~1. If you click any of the sortable column headers, it seems it will query /v4/coverage/info for each job.~
~2. Clicking on the “play” button doesn’t bring up the build parameter modal if it’s enabled.~
~3. If you are on a list view, then click collection and click on another pipeline, it will land on the list view again but with jobs from the previously selected pipeline as well.~
~4. The clickable buttons should be using a different cursor when hover.~

**What you expected to happen**:

The above issues should be resolved.

**Comment by jithine** [comment]
Also adding to list. 

5. shareable link to jobs list view. Eg: `pipeline/id/jobs` 
6. Link to Job Metrics
7.. Default job list order to match with position in workflow graph.

**Comment by jithine** [comment]
https://github.com/screwdriver-cd/ui/pull/630
https://github.com/screwdriver-cd/ui/pull/629
https://github.com/screwdriver-cd/ui/pull/628

**Comment by jithine** [comment]
moved out jobs order to https://github.com/screwdriver-cd/screwdriver/issues/2365
