### ISSUE TITLE
Github releases are breaking pipelines which doesn't have a release trigger

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2128]
**What happened**:
Pipeline event calls are failing on a pipeline resulting in 404 page. There is an invalid entry in events which contains `startFrom` as `release:`. This happened when user created a Github Release with out a name while the pipeline doesn't have any release/tag triggers. 

**What you expected to happen**:

If a pipeline doesn't have any tag/release trigger, there should not be any invalid events created.

**How to reproduce it**:
1. Create a release without a name, but just tag name.
2. Pipeline event gets creates with `startFrom` as `relase:`
2. Events API starts returning 500
3. Pipeline details page becomes 404 page

**Comment by jithine** [comment]
cc @kumada626 @ibu1224 @wahapo

**Comment by ibu1224** [comment]
@jithine 
The following pipeline was unable to reproduce the problem.
https://cd.screwdriver.cd/pipelines/4471/events

However, several pipelines within YJ are experiencing similar problems.
