### ISSUE TITLE
Refactor using frameworks and modules

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#2134]
**What happened**:
Hapi will seem to be EOL in 2020 https://github.com/hapijs/hapi/issues/4111

> https://twitter.com/hapijs/status/1275887984114413569
The hapi project is reaching its conclusion. While the details are still a work-in-progress, the work as it is known today is going to end.

> https://twitter.com/hapijs/status/1276063627972194305
hapi will continue to be fully supported and maintained until the end of the year. A fully supported commercially licensed version will be available for at least 2 years after that for companies looking to continue using the framework.

**What you expected to happen**:
- now SD is using old version (16.x) of hapi.  At least we have to update it.
    - next, to consider about migration to other framework from hapi or keep using
    - related: https://github.com/screwdriver-cd/screwdriver/issues/1958
- we should have update policy to use framework like hapi, ember and other frameworks and modules.

**Comment by hueniverse** [comment]
Why?

You have been using a version that has not been maintained for about 4 years and has known security issues and bugs. The code you are using comes with dozens of deprecation warnings. Clearly quality and security were not a primary concern here before...

So what do you care about the status of hapi v19?! You are not using it. I just want to point out how absurd this is. You are fine using a version that has known problems but now that a completely different version is being potentially deprecated you decided it was time to switch?!

**Comment by tk3fftk** [comment]
thank you for your comment. you are totally right. I'll update the issue name and description. We should think more about other things.

**Comment by jithine** [comment]
@tk3fftk I'm closing this based on new updates See github.com/hapijs/hapi/issues/ 4113

We will continue with our original plan of clearing out tech debt on using an unmaintained hapi.js version https://github.com/screwdriver-cd/screwdriver/issues/1958
