### ISSUE TITLE
The template list in the create pipeline page does not show template namespace.

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2140]
**What happened**:
Currently, we can create a screwdriver.yaml when creating pipeline.
At that time, we can choose a template to automatically generate the screwdriver.yaml file.
However, a template list that we choose a template from does not show template namespace like below.
<img width="688" alt="スクリーンショット 2020-07-08 16 25 41" src="https://user-images.githubusercontent.com/8113204/86890091-c2930b00-c137-11ea-812d-8bd0160800e8.png">
`template: test` is actually `template: nodejs/test`.

**What you expected to happen**:
The template list shows template namespace.

**How to reproduce it**:
Click template dropdown list in the create pipeline page.

**Comment by jithine** [comment]
cc @adong
