### ISSUE TITLE
UI test is unstable

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2144]
**What happened**:
UI test sometimes fails for `build log` test.
We need to restart the build each time.

Below is the example of same SHA build has instability.

<img width="285" alt="Screen_Shot_2020-07-10_at_10_24_19" src="https://user-images.githubusercontent.com/32473622/87106364-4237eb80-c298-11ea-8dd2-3f1a02e85b3b.png">

failed build example:
https://cd.screwdriver.cd/pipelines/7/builds/378964/steps/test

**What you expected to happen**:
UI build become stable.

**How to reproduce it**:
N/A

**Comment by jithine** [comment]
@adong  @yoshwata did ember upgrade help ?

**Comment by yoshwata** [comment]
@jithine I tried some times with ember 3.16, and there is no failed test by this instability.
