### ISSUE TITLE
Bitbucket SCM module is not included in package.json

### ISSUE THREAD

**Issue by ysaakpr** [screwdriver-cd/screwdriver#2147]
The documentation says it supports bitbucket.
<img width="455" alt="Screenshot 2020-07-13 at 9 11 01 PM" src="https://user-images.githubusercontent.com/20730186/87324202-653ef580-c54d-11ea-96b8-1c11e6872816.png">

While running getting this error
```
{"message":"Scm plugin bitbucket is not supported","level":"warn","timestamp":"2020-07-13T15:26:06.593Z"}
```

scm package for bitbucket is not included in the default build, Any specific reason for this?
<img width="430" alt="Screenshot 2020-07-13 at 9 09 44 PM" src="https://user-images.githubusercontent.com/20730186/87324048-3032a300-c54d-11ea-98c2-7c1d5f4a0502.png">

**Comment by ysaakpr** [comment]
Any update on this?

**Comment by tkyi** [comment]
Added screwdriver-scm-bitbucket package
