### ISSUE TITLE
Why branch name need to be part of repo url in a pipeline

### ISSUE THREAD

**Issue by ysaakpr** [screwdriver-cd/screwdriver#2149]
```
Enter your repository link into the field. SSH or HTTPS link is fine, with #<YOUR_BRANCH_NAME> immediately after (ex: git@github.com:screwdriver-cd/guide.git#test). If no BRANCH_NAME is provided, it will default to the master branch. Click Use this repository to confirm and then click Create Pipeline.

```

This looks so weird to me. Why do we need to have a branch name part of the pipeline repo URL. What is the meaning of adding branch name to the repo URL? Does it mean, the pipeline only works for a commit happening on that specific branch, And if so do I have to create multiple pipelines for all the branches that i have to enable build for? Can I add a branch filter in pipeline config somewhere to filter out buildable branches ?

**Comment by jithine** [comment]
You are right. Pipeline is usually scoped to the branch against with it's created. That also means that you can have multiple pipelines for different branches. 

However providing branch is optional, if not provided, it should default to your default branch. And you can use branch filtering to if you want to manage feature branches with a single pipeline.  https://docs.screwdriver.cd/user-guide/configuration/workflow#branch-filtering
