### ISSUE TITLE
Sonarqube Pull Request flow is broken

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2152]
**What happened**:

Screwdriver creates a new Sonar Project  for each pull request. This is not ideal and does not enable a project to make use of [Pull Request Analysis](https://docs.sonarqube.org/latest/analysis/pull-request/). Uses looses out on a unified Quality Gate Status check against Pipeline branch and Pull Requests. This also prevents Screwdriver from offering [Pull Request Decorations](https://docs.sonarqube.org/latest/analysis/pr-decoration/)

**What you expected to happen**:

1. When a Pull Request Analysis runs, Screwdriver Sonar Coverage book end must make use of [Pull Request Analysis](https://docs.sonarqube.org/latest/analysis/pull-request/). 
1. Screwdriver should not create a new Sonar Project for each Pull Request. We should rather use Pull Request Analysis](https://docs.sonarqube.org/latest/analysis/pull-request/) feature and use analysis data from Pull Request to populate coverage data on UI.

**How to reproduce it**:

Create a Pull Request and observer it's Sonar Project. It's a separate one from the Sonar Project for main repository.

**References**
1. https://docs.sonarqube.org/latest/analysis/pull-request/
1. https://docs.sonarqube.org/latest/analysis/pr-decoration/
1. Implementation references
   1. https://github.com/screwdriver-cd/coverage-sonar/blob/master/commands.txt#L11
   1. https://github.com/screwdriver-cd/coverage-sonar/blob/master/index.js#L215-L226
   1. https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/coverage/token.js#L24-L28

**Comment by renaud-vmg** [comment]
Adding: we're also missing the "source off truth" project key, which is to say, the Parent Job's project key, which is likely known by the engine. We have a local workaround in that we set a certain meta value to tell Screwdriver which project to get the required key from, but it would be easier for integration to have something such as `PR_PARENT_SQ_PROJECT_ID`.

**Comment by jithine** [comment]
Tasks


1. Add SD_SONAR_ENTERPRISE=false (by default)
2. coverage-sonar command to check this variable, and if present and equals true, do the following
   1.  pass projectKey=`SD_PR_PARENT_JOB_ID` in this API call  https://github.com/screwdriver-cd/coverage-sonar/blob/master/commands.txt#L6
   1. Change project key here https://github.com/screwdriver-cd/coverage-sonar/blob/master/commands.txt#L11 to  SD_PR_PARENT_JOB_ID
3. Pass these sonar params on PR   SD_SONAR_OPTS="-Dsonar.pullrequest.key=$SD_PULL_REQUEST -Dsonar.pullrequest.branch=${PR_BRANCH_NAME#*/} -Dsonar.pullrequest.base=${PR_BASE_BRANCH_NAME#*/}"
4. Update build coverage fetch logic to fetch from PR analysis for PR jobs.

**Comment by jithine** [comment]
Pending design consideration is to determine whether we should use `pipelineID` as Sonar Project Key. Concerns are
1. Can a single pipeline contain multiple kinds of analysis, mono-repo ?
2. How can a job's coverage be fetched if `pipelineId` is project key ? 
   1. Lets say there are 3 jobs for project which runs in different containers, Today UI uses build start/end times to pickup an analysis https://github.com/screwdriver-cd/coverage-sonar/blob/2ad56393a948b66176d350a13602390f33d12f9f/index.js#L128

Downside of not associating with project key is that Sonar Enterprise will count number of lines 3 times for above scenario. 

@kumada626 thoughts ?

**Comment by renaud-vmg** [comment]
Actually I've been thinking about this myself, and in this case I have to introduce a new concept: an SQ_Truth _**map**_.

There are use-cases where multiple projects, covering single parts of a given repository, have their own jobs, both for PR and Commit events (possibly separate jobs at certain points).

* In the case of multi-event jobs (`~commit, ~pr`) it becomes relatively easy and can be considered an "automatic" process where using an sd-cmd with auto-filled values can be used, and the source of truth is thus relayed
* In the case of single-event jobs (only `~commit` or `~pr`, not both at once ), we need to be able to specify that a given job is the source of truth for a given "string", which technically we can consider to be the job name. This is essentially what has been done in some projects under my control, as we specify an "SQ_SOURCE_OF_TRUTH" target and then use an sd-cmd to get the sonarqube project ID out of it. Streamlining this into a directly-invoked command without any other arguments than the target job name would simplify things. 

The concept of "map" comes in as, essentially, the jobID would be (as an illustration) _keyed_ to the job_name (by default), and using a command with only a target job name as input would be akin to fetching a value from a map.

**Comment by jithine** [comment]
We will support both pipeline and job level granularity

**Comment by jithine** [comment]
Updated Proposal


1. Add `SD_SONAR_ENTERPRISE=false` or some config which is `false` by default to determine whether Sonar serve is enterprise or not.
1. coverage-sonar command to check this variable, and if present and equals `true` (Enterprise Sonar), do the following
   1.  pass projectKey=`SD_PIPELINE_ID` in this API call  https://github.com/screwdriver-cd/coverage-sonar/blob/master/commands.txt#L6 when generating Sonar Token
   1. Change project key here https://github.com/screwdriver-cd/coverage-sonar/blob/master/commands.txt#L11 to  `pipeline:SD_PIPELINE_ID`
   1. Update build coverage fetch logic to fetch from PR analysis for PR jobs when under Enterprise mode.
   1. Expose job level annotation `screwdriver.cd/coverageGranularity: pipeline/job` with `pipeline` as default. This controls whether project key should be job or pipeline.
1. Job level Project Key to be of format. `pipeline:ID:job:ID`
1. If Sonar is not Enterprise Edition existing logic of separate Sonar Projects for Jobs to continue
1. Pass these sonar params on PR   ```SD_SONAR_OPTS="-Dsonar.pullrequest.key=$SD_PULL_REQUEST -Dsonar.pullrequest.branch=${PR_BRANCH_NAME#*/} -Dsonar.pullrequest.base=${PR_BASE_BRANCH_NAME#*/}"```

**Comment by kumada626** [comment]
I think that the proposal of support both pipeline and job level granularity is reasonable.
However, why job level project key includes `pipeline:ID`?
I think it is enough only includes `job:ID` as current.
If job level project key changes to `pipeline:ID:job:ID`, there is no continuity with the past data event if using Sonar Community Edition?

**Comment by jithine** [comment]
@kumada626 makes sense. updated Point 3. to Keep existing behavior for Sonar Community Edition

**Comment by tkyi** [comment]
See blog post: https://blog.screwdriver.cd/post/626730108375465985/sonarqube-enterprise-edition-support
