### ISSUE TITLE
UI - Specify timezone for CREATE TIME

### ISSUE THREAD

**Issue by argowang** [screwdriver-cd/screwdriver#2160]
**What happened**:
![image](https://user-images.githubusercontent.com/12148127/88363575-5caca300-cd35-11ea-80b3-c4bd0e4635a9.png)
Currently, there is no indication of the timezone for the CREATE TIME field. It could be very confusing since the user would have no idea whether the time is in UTC, PST or something else. For example, I was debugging a system while connected to a VPN site that's not in my timezone. I am totally confused about what timezone is the timestamp in. 

**What you expected to happen**:
1. Provide the timezone. For example, instead of `2020-07-23 21:48:43`, say `2020-07-23 21:48:43 PST`
2. Provide a button to convert the timestamp to UTC.

**How to reproduce it**:

**Comment by jithine** [comment]
closing this in favor of https://github.com/screwdriver-cd/screwdriver/issues/2218
