### ISSUE TITLE
Store docker is not running

### ISSUE THREAD

**Issue by ysaakpr** [screwdriver-cd/screwdriver#2162]
Trying to run store server in k8s, and running to an error like this. And possibly this is because we are installing the npm module, which doesn't not have the bin/server in it(My guess). The error says, package.json exists, but no node_modules.
<img width="869" alt="Screenshot 2020-07-26 at 9 04 41 PM" src="https://user-images.githubusercontent.com/20730186/88483207-fc5f7080-cf83-11ea-97ee-81a3fd5b40e3.png">

**Comment by jithine** [comment]
Does logs have any data ? Likely it's not able to connect to it's storage

**Comment by ysaakpr** [comment]
I am running in a cluster where the nodes has access to s3 bucket using ec2 roles
But unfortunately, the catbox-s3 library setting some ACL permissions on the object, which is something I was not expecting. In my bucket i am blocked all public access on my bucket using acl.


Anyway, now i have dropped the usage of screwdriver, because i think its still pretty early and has got lots of issue(auth error)  error while using with bitbucket. Thinking screwdriver gonna screw me :-P... joking.

**Comment by jithine** [comment]
@ysaakpr you don't need to make S3 objects public. You can use this config https://github.com/screwdriver-cd/store/blob/master/config/custom-environment-variables.yaml#L68 to specific what should be the expected bucket policy.

Bitbucket is not the primary SCM we use, so there are gaps. Pull Requests are welcome. 
Are you using Bitbucket server ?

**Comment by jithine** [comment]
Not sure if anything more can be done, here. Closing this.
