### ISSUE TITLE
Highlight the latest commit in the Events tab

### ISSUE THREAD

**Issue by ibu1224** [screwdriver-cd/screwdriver#2168]
**What happened**:
When there are a lot of events, it's hard to know which is the recent commit.

**What you expected to happen**:
It makes it easier to see which is the latest commit.

**How to reproduce it**:
Look for the latest commit in the pipeline with many events in the pipeline.

**Comment by yoshwata** [comment]
Let me propose about how work it looks like.

<img src="https://user-images.githubusercontent.com/32473622/98073145-04944980-1eab-11eb-8805-94b0aa1766e9.jpg" width=300 />

Is it looks good? @jithine @tkyi @adong

**Comment by wahapo** [comment]
Let me suggest another idea. What do you think if we put a green box around the latest commit SHA and show the tag as last successful?

**Comment by yoshwata** [comment]
Your suggestion seems reasonable. What we want to express about sha should be decorated on sha. 

<img src="https://user-images.githubusercontent.com/32473622/98076513-bc2c5a00-1eb1-11eb-8fc4-7d540907fe24.jpg" width=300 />

- Green box means latest commit sha
- Last successful is moved from its original location and displayed in a blue box

**Comment by wahapo** [comment]
It would be better to have a couple of target SHA in the image to help us visualize the image, but I think it's good.

**Comment by ibu1224** [comment]
Basically, I agree with Proposal 2.
However, we need to think about the color of the latest commit sha.
In screwdriver.cd, green means success.
The color of `last successful` should be green.

**Comment by yoshwata** [comment]
# Proposal 2-2

@ibu1224 Thank you. The image below reflects your idea. And I think this is the best.

<img src="https://user-images.githubusercontent.com/32473622/98083082-239bd700-1ebd-11eb-9b8f-cc661abd7dac.jpg" width=300 />

**Comment by jithine** [comment]
@yoshwata couple of questions

1. will events still be sorted chronologically in the events list ?
2. last successful will have the green label
   1. Since we already have the green check mark against the successful event what more info does the label provide ?
   1. Is the idea to also leverage success states of the pipelines from https://github.com/screwdriver-cd/screwdriver/issues/2199 ?
3. latest commit will have the blue label
    1. If there are multiple events with last commit sha will all of them get the blue label ?
     1. Slightly related to https://github.com/screwdriver-cd/screwdriver/issues/1820

**Comment by yoshwata** [comment]
@jithine Thanks

> will events still be sorted chronologically in the events list ?

Yes, I'm not going to care about sorting in this issue.

> Since we already have the green check mark against the successful event what more info does the label provide ?

When a pipeline has a lot of failed or skipped build, it provides visibility for users to search latest successful build by their eyes with scrolling up or down.

> Is the idea to also leverage success states of the pipelines from #2199 ?

I've concerned but no idea, sorry.

> If there are multiple events with last commit sha will all of them get the blue label ?

Yes! In that case all of last commit sha get blue label.

> Slightly related to #1820

Thanks for linking. One event group should gets one blue label. I think it is beautiful.

**Comment by ibu1224** [comment]
@screwdriver-cd/maintainers 
It would be good to highlight the areas in the red frame in the following image.
<img width="431" alt="highlight" src="https://user-images.githubusercontent.com/17828065/107323073-017fa980-6ae9-11eb-8ee1-2780e902227a.png">
