### ISSUE TITLE
Homepage - dead link for video

### ISSUE THREAD

**Issue by Endle** [screwdriver-cd/screwdriver#2169]
**What happened**:
https://docs.screwdriver.cd/
There's a video https://s3-us-west-2.amazonaws.com/static.screwdriver.cd/videos/SD+Video+Demo.mp4

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>AC5EC2A9331EAD77</RequestId>
<HostId>
DgJNalGogVb/1mGRiH25Ka59AnG/LAOkH511MsRKm195fMAVzydKOS7yLM9LRqBmcD8judAiSCo=
</HostId>
</Error>
```

**Comment by jithine** [comment]
Dead video has been removed. We will update later with a new one.
