### ISSUE TITLE
The build may start with a different value than the specified parameters

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2175]
**What happened**:
When I change the build parameters each time and run the build in succession, the build seems to start using a different parameter than the one I specified in rare cases.

For example, I started with the parameters `wahapo`, `wahapo111` and `wahapo222`.
<img width="922" src="https://user-images.githubusercontent.com/24538326/89865200-3f5a4e80-dbe8-11ea-8378-e4f8dd4f7fa2.png">

Even though I filled `wahapo222` as a parameter, the build started using the old `wahapo111` parameters.
<img width="931" src="https://user-images.githubusercontent.com/24538326/89865206-408b7b80-dbe8-11ea-9681-d4e938b6f411.png">

**What you expected to happen**:

**How to reproduce it**:
If you change the build parameters each time and start the build in succession, it will be reproduced.

https://cd.screwdriver.cd/pipelines/5495/events

**Comment by adong** [comment]
Thanks for reporting, let me take a look.
