### ISSUE TITLE
[Feature Request] Drop-down values in parameters on job starting

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2180]
**What happened**:

There is no dropdown when `start pipeline from here`

<img src=https://user-images.githubusercontent.com/32473622/90091289-ecf06d80-dd60-11ea-81a0-db6f405bbf87.jpg width=300 />

**What you expected to happen**:

Dropdown appears like `Start` button

<img src=https://user-images.githubusercontent.com/32473622/90091400-3c369e00-dd61-11ea-857d-191a23d06db9.jpg width=300 />

**How to reproduce it**:

Define build parameters with array, then start build with `start pipeline from here`

**Comment by wahapo** [comment]
Fixed in UI@v1.0.541 with https://github.com/screwdriver-cd/ui/pull/589. It's good to close.
