### ISSUE TITLE
Feature Request: permalink in event list

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#2207]
It's very good to have a permalink in the browser's URL bar when clicking on an event, so thank you for that! However, that's not intuitive behavior. It would be better to have a little link indicator for each event such that when I click it, the URL is copied to my clipboard.

**Comment by tk3fftk** [comment]
now we have permalink for per event.
https://cd.screwdriver.cd/pipelines/1/events/654226?jobId=
