### ISSUE TITLE
PR build does not test for code that is merged target branch and pr branch.

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2209]
# What happened

Due to a recent change, PR builds that previously merged changes into a target branch are now checked out PR branch directly.

This is a big change for users. The behavior after merging is tested only after merging. User's productivity will drop if real unit test results are not known in PR builds.

<img src="https://user-images.githubusercontent.com/32473622/92444962-9571e000-f1ee-11ea-8eba-d2cb1370b702.jpg" width="300" >

Users also need to be very careful with pipeline which aren't testing when triggered by a commit, otherwise untested code will be deployed into production. Like this situation:

<img src="https://user-images.githubusercontent.com/32473622/92443691-d0731400-f1ec-11ea-9fd7-bf320143d5cd.jpg" width="300" >

# What you expected to happen

Therefore, the PR build should be done with the code which target branch and the PR branch is merged as in the previous specifications.

I understand that it was for the Sonar PR analysis. It may be solved by merging the target branch after checkout PR branch.

# Reference

https://github.com/screwdriver-cd/scm-github/pull/173
https://github.com/screwdriver-cd/scm-github/pull/175
https://github.com/screwdriver-cd/scm-github/pull/177

**Comment by jithine** [comment]
cc @tkyi
