### ISSUE TITLE
[Feature Request] UI shows parameter's description

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2210]
**What happened**:

[Parameters have a filed to fill the description](https://docs.screwdriver.cd/user-guide/configuration/parameters.html) but it is not used to show on UI.

**What you expected to happen**:

UI shows parameter's description. Below is just an idea.

<img src="https://user-images.githubusercontent.com/32473622/92683852-f88a8080-f36e-11ea-9f22-8d760ef41593.jpg" width="500">

**Comment by tkyi** [comment]
I like this idea
Should use that description data somehow in the UI, and the proposed solution looks good to me 👍
