### ISSUE TITLE
move same repository pipeline easily

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#2215]
**What happened**:
When I'm looking at the pipeline of a repository with multiple pipelines, I often want to go to the other pipelines in that repository.
But in order to get there, I have to search again to get to the pipeline, and I find that a bit of a pain.

**What you expected to happen**:
Able to move the same repository pipeline easily.

For example,
<img width="566" alt="スクリーンショット 2020-09-15 11 25 35のコピー" src="https://user-images.githubusercontent.com/4645011/93158428-0b260080-f747-11ea-9b27-437b04bf5156.png">
When you click 1, pull-down about other branches and source directory are shown. Users click the pull-down and go to the pipeline page.
Currently, when users click 1, the GitHub repository is shown. It is inconvenient cannot move Github repositories, so move the function to 2.
When users click 2, users can go to the GitHub repository.

**How to reproduce it**:
Nothing.

**Comment by tkyi** [comment]
I like this idea 👍 
Definitely makes more sense to have function 2 as you described.

One question: Would it only show branches for repositories that have Screwdriver pipelines? Or would it show all branches in Github?

**Comment by yuichi10** [comment]
I think only show branches for repositories that have Screwdriver pipelines is better. 
If there are too many branches the tooltip will become hard to see.

**Comment by tkyi** [comment]
I agree, sounds good.

**Comment by yoshwata** [comment]
I thought about a concrete display design that pipeline's screen transitions in the same repository and the development plan. YJ members ask for confirmation, and we can proceed with confidence if the VM members can also react.

## Step1: Branch

The first thing to implement is something like this:
![branch-close-1st](https://user-images.githubusercontent.com/32473622/138379338-0b23937e-b8be-42d7-9993-30da4255756b.png)

A small caret has been added next to the branch name, and clicking on this area will expand the drop-down list as shown below:
![branch-open](https://user-images.githubusercontent.com/32473622/138379392-254a5272-5747-4a3f-969f-b9f0c0a35aed.png)

What is displayed here is the branch name of the same repository registered as pipeline. Select to move to the branch's pipeline screen.

The scm text part turns into a link. If you have selected the feature1 branch as shown in the image, it will be a link to the feature1 branch of SCM.

![feature1-github](https://user-images.githubusercontent.com/32473622/138379484-fa4a8111-9170-45aa-80fa-10084f7773e6.png)

## Step2: SourceDirectory

Allows Source Directory to transition from a pipeline of the same repository.

![branch-withsource-dir](https://user-images.githubusercontent.com/32473622/138379575-813bfb94-40cb-4a38-a69f-36ebd9ea7545.png)

This mimics the search screen of the pipeline.

![pipeline-search](https://user-images.githubusercontent.com/32473622/138379661-a5700a17-df9c-416b-ac62-b8817ea2ceb7.png)

The SCM link in the pipeline where the Source Directory is set is also the link to the target directory.

![scm-link-sourcedir](https://user-images.githubusercontent.com/32473622/138379750-3deed7ba-9389-434a-b9bc-b7a292d57bfe.png)
