### ISSUE TITLE
[UI] Need user setting for pedantic time wants

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#2218]
**What happened**:

When I look at events, I see that several events happened "2 months ago." When I look at the list view, I see a timestamp such as "August 18, 2020 4:52 PM."

**What you expected to happen**:

My personal preference is to have absolute timestamps on the events sidebar. Also, "4:52 PM" is ambiguous? Is it my timezone, is it UTC? I'd rather see that as "2020-08-18 23:52 UTC."

Lots of people have different preferences, so it would be best to allow a preference for time formats.

**How to reproduce it**:

Look at any pipeline

**Comment by jithine** [comment]
Sounds like a customer for the preferences API https://github.com/screwdriver-cd/models/pull/475

**Comment by tkyi** [comment]
Looks like a reoccurring ask: 
https://github.com/screwdriver-cd/ui/pull/731#issuecomment-877393593
https://github.com/screwdriver-cd/screwdriver/issues/1581
https://github.com/screwdriver-cd/screwdriver/issues/2511
https://github.com/screwdriver-cd/screwdriver/issues/2160

**Comment by adong** [comment]
@banusha2 maybe you can take a look.

**Comment by adong** [comment]
> what should we do here use a user's local TZ or give a toggle button to convert timestamp to UTC?

I dont know what David thinks, and my take on this to have a session for `Event Timeline Format` under the `Options -> User Preference`

![image](https://user-images.githubusercontent.com/15989893/180863607-43250721-2eaa-4c57-989c-8f98c8153212.png)

I have 3 options in mind: `UTC Timestamp`, `Local Timestamp`, `Human Readable Timestamp`

![image](https://user-images.githubusercontent.com/15989893/180863936-011db929-3b7c-4969-93c2-5e9d50aecf79.png)

See reference: https://www.unixtimestamp.com/index.php.

See the below example for the explicit local timezone time, after PR https://github.com/screwdriver-cd/ui/pull/731.  

1) the list view,
![image](https://user-images.githubusercontent.com/15989893/180864410-74cd0c8c-780e-4985-9edd-224e94859aba.png)

and 2) the event view
![image](https://user-images.githubusercontent.com/15989893/180864288-873dea3f-feec-4e16-90fe-453c71240b8b.png)


Once that "User Preference" is set, should all have the same time format, with respect to the user's preferred timestamp selection.

**Comment by dwmarshall** [comment]
Some people might like "2 months ago," but I'm not one of them. I also don't care whether time is presented in my local time or UTC, but I need to know what time zone is being used. "04:27 PM" isn't very helpful. Is it 4:27 PM PDT or 11:27 PM PDT?

**Comment by jithine** [comment]
This setting should be a global one, user shouldn't have to go to each Pipeline to update preference.

**Comment by adong** [comment]
> This setting should be a global one, user shouldn't have to go to each Pipeline to update preference.

This change will increase the scope a little bit, as this section would be moved to `/user-settings` rather than pipeline -> options

cc @banusha2

**Comment by tkyi** [comment]
Looks good to me now
<img width="1231" alt="Screen Shot 2022-11-30 at 11 31 50 AM" src="https://user-images.githubusercontent.com/3230529/204891252-31e8c59f-f360-48e9-b2b2-7e0c936a045e.png">
