### ISSUE TITLE
Environment variables for image being used

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#2222]
It would be useful to have environment variables describing the image being used for a particular job, suggested names are `SD_IMAGE_NAME` and `SD_IMAGE_FULLNAME`.

### Just steps
```
jobs:
  main:
    image: screwdrivercd/noop-container
    steps: ...
```
Both `SD_IMAGE_NAME` and `SD_IMAGE_FULLNAME` would be `screwdrivercd/noop-container`.

### With descriptive image labels:
In the template:
```
images:
    stable-image: node:6
    latest-image: node:8
```

in `screwdriver.yaml`:

```
jobs:
  main:
    image: stable-image
```

`SD_IMAGE_NAME` would be `stable-image`, and `SD_IMAGE_FULLNAME` would be `node:6`.

Specific use case: I want to have a template for testing Chef cookbooks. For different images, in the steps, some small variations are needed. It would be nice to condition these variations on the image actually being used. There are workarounds, but having these environment variables would likely be useful.

**Comment by jithine** [comment]
This is actually present with name CONTAINER_IMAGE https://github.com/screwdriver-cd/executor-k8s/blob/master/config/pod.yaml.hbs#L35 need to add to doc

**Comment by jithine** [comment]
https://github.com/screwdriver-cd/guide/pull/451
