### ISSUE TITLE
UI should hide "CREATED" builds

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2227]
**What happened**:

Join feature introduced "CREATED" status builds which is a holder build for storing intermediate status of upstream builds which can trigger this job. However UI shows "CREATED" as status for such events and users are able to navigate to such builds and get confused on job's status. 

**What you expected to happen**:

UI should ignore builds with `CREATED` status.
Users should not be able to visit build detail page of job's with 'CREATED' status.

**How to reproduce it**:

1. A job which depends on multiple jobs in same pipeline
1. One of the upstream jobs fails, while rest of them passes.
1. join job has a build in `CREATED` status.

**Comment by jithine** [comment]
cc @tkyi  @adong We should either relook at having `CREATED` builds for holding join status, or have UI hide such builds.

**Comment by tkyi** [comment]
Can probably just have the UI hide these builds; don't think it matters to users if builds are created or not
