### ISSUE TITLE
Display job name length range on the pipeline option page

### ISSUE THREAD

**Issue by ibu1224** [screwdriver-cd/screwdriver#2234]
**What happened**:
The other day, DISPLAY_NAME_LENGTH added. https://github.com/screwdriver-cd/ui/pull/595
I prefer this feature.
However, users have difficulty finding a valid range.

**What you expected to happen**:
The valid range is displayed as shown in the following image.
<img width="904" alt="job-name-length" src="https://user-images.githubusercontent.com/17828065/94657875-0cf1e580-033d-11eb-80e6-8d5619abed04.png">

**How to reproduce it**:
Visit the options page in the pipeline.
Set the job name length.

**Comment by jithine** [comment]
cc @adong
