### ISSUE TITLE
Different PRs with the same SHA have 2 checks instead of one

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#224]
LOL

When opening another PR using the same SHA, the Pull Request has 2 checks (one for each unique PR)

![screen shot 2016-09-29 at 4 38 36 pm](https://cloud.githubusercontent.com/assets/721148/18975993/3b1a3a9e-8663-11e6-9df0-748f5750a6de.png)

**Comment by stjohnjohnson** [comment]
Technically this is valid.  Statuses are based on the commit, not the PR.  That's why we have:
<img width="1005" alt="screen shot 2016-09-29 at 9 51 44 pm" src="https://cloud.githubusercontent.com/assets/622065/18980998/efecd730-868e-11e6-9f2c-e981501b81da.png">

**Comment by stjohnjohnson** [comment]
I would actually vote to close this.  I would consider this expected behavior.  What do you think @FenrirUnbound ?

**Comment by FenrirUnbound** [comment]
It was just unexpected.
