### ISSUE TITLE
The build is not started in buildCluster when routing key replaced

### ISSUE THREAD

**Issue by kkokufud** [screwdriver-cd/screwdriver#2241]
**What happened**:
When we add new routing key `bbb-build` and deleted old routing key `aaa-build` with buildCluster API,  the build did not started with the following error.
```
Cluster specified in screwdriver.cd/buildCluster: aaa-build for scmContext: xxx does not exist.
```
The old routing key was remaining as annotations in `pipelines` table.
```
mysql> select annotations from pipelines where id=1111\G
*************************** 1. row ***************************
annotations: {"screwdriver.cd/buildCluster":"aaa-build"}
```
Since this build did not specify annotations, I think the routing key was assigned automatically.

**What you expected to happen**:
The build starts even if the routing key is replaced.

**How to reproduce it**:
1. Start build in buildCluster without annotations for buildCluster
1. Add  routing key and delete old routing key with buildCluster API
1. Restart build

**Comment by parthasl** [comment]
Yes, this limitation is per design as we want the cluster stickiness. For any change in routing key, need to update affected pipelines and Rabbitmq exchange configuration. 

Another option is to create a new build cluster and disable the old build cluster. In this case, it will auto-route the build to the next available active cluster. note: it will not update pipeline annotations.

**Comment by parthasl** [comment]
I will work to remove this build cluster stickiness.

**Comment by kkokufud** [comment]
I'm sorry I misunderstood. I think this issue is that cannot change the buildcluster name. 
As you said, We'll have to change the settings manually.
If it seems difficult to solve that, maybe we should close it.
