### ISSUE TITLE
Missing PR builds

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#225]
For some fun reason, my pull request doesn't exist in [the Pipeline](https://cd.screwdriver.cd/pipelines/2e0138dfa7c4ff83720dc0cd510d2252a3398fc3). 

![screen shot 2016-09-29 at 4 47 13 pm](https://cloud.githubusercontent.com/assets/721148/18976156/a0b5a46e-8664-11e6-84e3-03c37d74650c.png)

-----

The [API call](https://api.screwdriver.cd/v4/pipelines/2e0138dfa7c4ff83720dc0cd510d2252a3398fc3/jobs) confirms this:

```
$ -> curl https://api.screwdriver.cd/v4/pipelines/2e0138dfa7c4ff83720dc0cd510d2252a3398fc3/jobs
[]
```

But, the PR [definitely build exists](https://cd.screwdriver.cd/pipelines/2e0138dfa7c4ff83720dc0cd510d2252a3398fc3/build/f60569684b3118118f0c53a361c394503df2b39e)

![screen shot 2016-09-29 at 4 47 26 pm](https://cloud.githubusercontent.com/assets/721148/18976149/8e035000-8664-11e6-8c7c-aa835cb9c8e9.png)

-----

And [the API call](https://api.screwdriver.cd/v4/builds/f60569684b3118118f0c53a361c394503df2b39e) confirms that it exists

```javascript
{
  id: "f60569684b3118118f0c53a361c394503df2b39e",
  jobId: "f4a997df83ac900a5d6c98ecb09e1784d784538b",
  number: 1475192298096,
  container: "node:6",
  cause: "Started by user FenrirUnbound",
  sha: "a7378bd6bf16c3f8ae277269cf3feeb0113f717b",
  createTime: "2016-09-29T23:38:18.096Z",
  startTime: "2016-09-29T23:38:21.289Z",
  endTime: "2016-09-29T23:38:47.378Z",
  meta: { },
  steps: [
    {
      startTime: "2016-09-29T23:38:20.822456053Z",
      name: "sd-setup",
      code: 0,
      endTime: "2016-09-29T23:38:23.966406993Z"
    },
    {
      startTime: "2016-09-29T23:38:24.095650198Z",
      name: "install",
      code: 0,
      endTime: "2016-09-29T23:38:43.304733019Z"
    },
    {
      startTime: "2016-09-29T23:38:43.434064284Z",
      name: "test",
      code: 0,
      endTime: "2016-09-29T23:38:47.170913225Z"
    }
  ],
  status: "SUCCESS"
}
```

**Comment by FenrirUnbound** [comment]
The Github PR for reference is screwdriver-cd-test/functional-git#77

![screen shot 2016-09-29 at 4 56 01 pm](https://cloud.githubusercontent.com/assets/721148/18976300/aebb3abe-8665-11e6-9752-a6e68b14efc9.png)

**Comment by d2lam** [comment]
I think you deleted the pipeline, so this PR is gone now. This should be fixed by https://github.com/screwdriver-cd/datastore-dynamodb/pull/24

I closed and reopened the PR:
<img width="1064" alt="screen shot 2016-10-03 at 4 04 15 pm" src="https://cloud.githubusercontent.com/assets/3401924/19057218/19009976-8983-11e6-9161-bd45a574f486.png">

**Comment by d2lam** [comment]
https://api.screwdriver.cd/v4/pipelines/2e0138dfa7c4ff83720dc0cd510d2252a3398fc3/jobs
