### ISSUE TITLE
Autolinking in docs is not working

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#2252]
**What happened**:

I visited https://docs.screwdriver.cd/user-guide/templates

**What you expected to happen**:

I expected that line 188 of [the doc](https://github.com/screwdriver-cd/guide/blob/1b07bdde38359b6281bbc88c374ec01173f19a35/docs/user-guide/templates.md) which is

```
Example repo: https://github.com/screwdriver-cd-test/template-images-example
```

would be automatically linked in the rendered document.

Sadly, it is rendered as

```
<p>Example repo: https://github.com/screwdriver-cd-test/template-images-example</p>
```

**How to reproduce it**:

Visit https://docs.screwdriver.cd/user-guide/templates and search for `Example repo: h`

**Comment by tkyi** [comment]
Should be fixed now, thanks for filing the issue
