### ISSUE TITLE
Create default cluster not randomly selected

### ISSUE THREAD

**Issue by kkisic** [screwdriver-cd/screwdriver#2258]
**What happened**:
If we set `managedByScrewdriver` to `true`, the cluster is randomly selected cluster if the annotation is not specified.
We want to create a build cluster that can be used by anyone with annotation but will not be randomly selected if the annotation is not specified.

Specifically, we want to be able to use the following build clusters.

|id|name|scmOrganizations|isActive|managedByScrewdriver|weightage|
|-|-|-|-|-|-|
|1|ClusterA|null|true|true|100|
|2|ClusterB|null|true|true|0|

ClusterA is used as a default cluster that can be used by public users without the annotation.
ClusterB is used as a cluster that is only available to users who specified an annotation. However, we don't want to limit users who can use ClusterB by `scmOrganizations`.

Currently, the following error occurred when we try to create ClusterB.
```
$ curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json'\
       -d '{ "name": "clusterB",\
             "scmOrganizations": [],\
             "managedByScrewdriver": true,\
             "maintainer": "<maintainer address>",\
             "isActive": true,\
             "description": "some descriptsion",\
             "weightage": 0 }'\
       -H "Authorization: Bearer <Token>" "http://<ApiEndpoint>/v4/buildclusters"

> {"statusCode":400,"error":"Bad Request","message":"Invalid request payload input"}
```

**What you expected to happen**:
We would like to be able to set `weightage` to `0` and `managedByScrewdriver` to `true` when the build cluster is created.

**Comment by jithine** [comment]
cc @pritamstyz4ever

**Comment by kkisic** [comment]
I think at least the following need to be fixed.

- https://github.com/screwdriver-cd/data-schema/blob/c38a18fe69745ecec4cceccb6738fee153d558d1/models/buildCluster.js#L48
- https://github.com/screwdriver-cd/models/blob/master/lib/buildClusterFactory.js#L46-L48
