### ISSUE TITLE
Deleting a pipeline is a long-ish operation

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#227]
Our test repository with ~100 PRs took about 11 seconds to delete. When we hit this limit again, we'll investigate the length of time again.

**Comment by stjohnjohnson** [comment]
Things to investigate:
 - [ ] Does `Promise.all` run in parallel or in series?
 - [ ] Is the slowness on the fetching of models or deleting?

**Comment by d2lam** [comment]
I think this is understandable. Deleting a pipeline requires deleting all the builds, secrets, and jobs associated with it. So it has to delete all the secrets & builds belong to those 100 PRs, then when that's done, it has to delete those 100 PR jobs, then the pipeline itself. That's a lot of things to delete.

But it's good to investigate the above 2 things.

**Comment by FenrirUnbound** [comment]
Assuming all the promises are started independently, the `Promise.all` should wait for all the promises to resolve, regardless of how they're linked. `Promise.all` does not initiate the promises, so saying that it runs in parallel is a mis-characterization.

**Comment by FenrirUnbound** [comment]
The long time in deleting a pipeline may be considered understandable, but does it make sense for the end-user to experience? It is the longest running operation, and it gives this false impression of the request "hanging". 

Alternatives could be that we return to the user an `ACCEPTED` response, and work on completing the process in the back-end. 

@stjohnjohnson's investigation checklist on looking into the performance of certain operations would be a good place to start.

**Comment by d2lam** [comment]
@FenrirUnbound  I actually haven't experienced slowness in deleting pipelines. This was caused most likely because it was deleting a pipeline with LOTS of builds and other data, which is acceptable imo. Are you ok with closing this issue?

**Comment by FenrirUnbound** [comment]
I don't mind closing it. It may still be valuable to track the performance limits of the product, but that's about it.

If the leading hypothesis is that it only occurs with deleting a pipeline with a lot of builds and associated data, the bottleneck may be the AWS interactions. We may have to implement a bulk-remove in the models if that's the case.

**Comment by d2lam** [comment]
Closing this. We can reopen if we see more problems.
