### ISSUE TITLE
Job display name issues

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2273]
**What happened**:

1. Validator complains that it's not a valid job level annotation
1. PR job names are not updated

**What you expected to happen**:
1. validator should display correctly
1. User should be able to verify the feature in PR build

**How to reproduce it**:

**Comment by jithine** [comment]
@wahapo @kumada626 please review

**Comment by yoshwata** [comment]
relevant issue
https://github.com/screwdriver-cd/screwdriver/issues/2243
