### ISSUE TITLE
In MySQL, migration script (20201102) does not work

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2277]
**What happened**:
If use mysql as the DB, migration script [20201102-change_column_subscribedScmUrlsWithActions_to_pipelines.js](https://github.com/screwdriver-cd/data-schema/blob/9ebe3a42/migrations/20201102-change_column_subscribedScmUrlsWithActions_to_pipelines.js) does not work.

I got the following error.
```
ERROR: BLOB/TEXT column 'subscribedScmUrlsWithActions' used in key specification without a key length
```

**What you expected to happen**:
Please specify lenght for the index, like [20190919-initdb-builds.js](https://github.com/screwdriver-cd/data-schema/blob/9ebe3a42d3779de62e8c371ebe06cde74de883ec/migrations/20190919-initdb-builds.js#L100)

**How to reproduce it**:

**Comment by parthasl** [comment]
Thanks, @wahapo, and @kumada626 for the fix. Sorry didn't pay attention to MySQL syntax. 
Fixed by PR: https://github.com/screwdriver-cd/data-schema/pull/426
