### ISSUE TITLE
build cluster worker have no functional tests

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2281]
**What happened**:

Any change which has an error can go all the way to production cd.screwdriver.cd

**What you expected to happen**:

CD pipeline should run a functional test after beta deployment to validate that builds can run.

**How to reproduce it**:

**Comment by parthasl** [comment]
Tested Pipeline: https://cd.screwdriver.cd/pipelines/1825/events/604203
Functional test run: https://cd.screwdriver.cd/pipelines/1825/builds/671579
