### ISSUE TITLE
Create pipeline flow is not showing all templates

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2282]
**What happened**:
When searching for template during create pipeline flow, only template name is matched. UI is not searching in template namespace. Refer screenshots.

<img width="360" alt="Screen Shot 2020-11-18 at 4 11 38 PM" src="https://user-images.githubusercontent.com/193126/99603768-dccbd800-29b8-11eb-9c1e-8893dad07976.png">
<img width="345" alt="Screen Shot 2020-11-18 at 4 11 45 PM" src="https://user-images.githubusercontent.com/193126/99603771-dd646e80-29b8-11eb-94f3-96d48c3004ce.png">

**What you expected to happen**:

Searching for a template name should match both namespace & name.

**How to reproduce it**:

**Comment by tkyi** [comment]
Probably need to refer to this: https://ember-power-select.com/docs/the-search
