### ISSUE TITLE
sd-local ability to mount custom volumes

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2294]
**What happened**:
It is useful if sd-local can mount any volumes.

**What you expected to happen**:
For example, we can use ssh keys by mounting `~/.ssh/` with interactive mode. There are probably other use cases as well.

```
$ sd-local build job -i -v "~/.ssh/:/root/.ssh/"
```

Relates to:
https://github.com/screwdriver-cd/sd-local/pull/50#pullrequestreview-542069879

**How to reproduce it**:

**Comment by jithine** [comment]
usage ` sd-local build A --vol "/Users/jithine/.ssh/known_hosts:~/.ssh/known_hosts"`
