### ISSUE TITLE
When using restrictPR, "start" button should never go away

### ISSUE THREAD

**Issue by hk-vmg** [screwdriver-cd/screwdriver#2298]
**What happened**:
We triggered a PR build once manually (due to restrictPR) using the "Start" button. After the build has completed, more changes were pushed. However, the "start" button disappeared, so triggering the build required clicking through to the pull-request event, and clicking "restart" on top right.

Original "start" implementation https://github.com/screwdriver-cd/screwdriver/issues/1528 

**What you expected to happen**:
The "Start" button should continue to live forever as long as restrictPR applies

**How to reproduce it**:

**Comment by jithine** [comment]
This could be made generic such that start button should always be shown for pull requests.

**Comment by jithine** [comment]
This has been fixed in latest UI.
