### ISSUE TITLE
UI doesn't show the status message for invalid image with buildcluster-queue-worker

### ISSUE THREAD

**Issue by s-yoshika** [screwdriver-cd/screwdriver#2303]
**What happened**:
The build with invalid image is stuck in `sd-setup-init` step without error, if we enabled the buildcluster feature in our envirnoment.
before enabling the buildcluster feature, we have confirmed the error message like following in UI and the build was failed.

![image](https://user-images.githubusercontent.com/5774825/102425163-23f8c780-4050-11eb-8799-e807a2d030c4.png)

**What you expected to happen**:
The build with invalid image is failed and the message status show the error correctly even if we use buildcluster.

**How to reproduce it**:
1. Enable the buildcluster feature
2. build with invalid image

**Comment by jithine** [comment]
cc @parthasl I think what we tried was to increase the time executor-k8s waits to fetch status from k8s to that this can be detected. But it's not quite working for all cases.

**Comment by jithine** [comment]
Next things to try will be to create an offline workflow using queue service to check status of k8s pod to properly fail a build

**Comment by parthasl** [comment]
@s-yoshika is this with containerd + kata? docker? or hyper?
from open source SD cluster - https://cd.screwdriver.cd/pipelines/3484/builds/669348/steps/sd-setup-init
yes as @jithine doesn't work for all cases, where fetch status exceeds default wait time.

**Comment by s-yoshika** [comment]
We found the deadLetter settings doesn’t work for our rabbitmq and the retryCount has not been increased.
We guesses the [queueOptions](https://github.com/screwdriver-cd/buildcluster-queue-worker/blob/master/config/default.yaml#L236) aren’t passed to rabbitmq. the options are passed into channel.checkQueue.
https://github.com/screwdriver-cd/buildcluster-queue-worker/blob/master/index.js#L145
but the function seems not received the options.
http://www.squaremobius.net/amqp.node/channel_api.html#channel_checkQueue

we can confirm the error message correctly after we set both `x-deadletter-exchange` and `x-deadletter-routing-key` options in `load_definitions` for our rabbitmq directly.

**Comment by s-yoshika** [comment]
> is this with containerd + kata? docker? or hyper?

@parthasl it's executor-k8s build(not kata) but this may  be happened for any environment if rabbitmq doesn't have x-deadletter options.

**Comment by parthasl** [comment]
Ok, I thought executor-k8s error is not returning the error and was trying to understand the implementation. 

Regarding the queueOptions (https://github.com/screwdriver-cd/buildcluster-queue-worker/blob/master/index.js#L145); wanted to validate the queue settings in rabbitmq with the definition in default.yaml (or) custom-config.yaml. In this case, it should be assertQueue instead of checkQueue. But I felt it's not needed to re-validate again and changed it to checkQueue which will just validate queue name and doesn't validate queueOptions. If needed, we can change it to assetQueue instead of checkQueue. As mentioned, routing is controlled by dead letter configuration.

**Comment by s-yoshika** [comment]
Thanks, I got it. Is my understanding correct?
* we have to set deadletter settings in rabbitmq directly and `checkQueue` or `assertQueue` can't populate the settings in queueOptions into rabbitmq
* `queueOptions` was used for `assertQueue` to validate the queue settings in rabbitmq but it nolonger used

I think it's hard for new SD admins to configure rabbitmq correctly, and it's good to add the cluster guide for this.

**Comment by parthasl** [comment]
yes, you are correct. checkQueue or assertQueue is only to validate the settings. Will raise PR to change from checkQueue to assertQueue so that consumer will fail if the expected settings are not available. sorry for the confusion. will update cluster guide as well.

**Comment by s-yoshika** [comment]
I understand. Thanks for your help.

**Comment by parthasl** [comment]
Removed unused queueOptions settings. Cluster admin can configure the queue and retry mechanism based on their environment.

**Comment by jithine** [comment]
https://docs.screwdriver.cd/cluster-management/configure-buildcluster-queue-worker
