### ISSUE TITLE
failed to create command directory /opt/sd/commands

### ISSUE THREAD

**Issue by eagleshine** [screwdriver-cd/screwdriver#2304]
Hi,
I was trying to run a build locally with `sd-local` but with an error:
```
init-rpms: ERROR: Failed to create command directory: mkdir /opt/sd/commands: permission denied
```

The `init-rpms` is a step that uses an sd-cmd stored in screwdriver.

**Comment by jithine** [comment]
fix: https://github.com/screwdriver-cd/sd-local/pull/56
