### ISSUE TITLE
Buildcluster doesn't support multiple SCM contexts

### ISSUE THREAD

**Issue by MysticDoll** [screwdriver-cd/screwdriver#2307]
**What happened**:
We tried to enable multiple buildcluster for 2 SCM contexts. But we couldn't set 2 SCM contexts to `buildcluster.SCMContext` column in DB.
Therefore we couldn't build in only one SCM context by multiple buildcluster, jobs for the other SCM context have never been started.

**What you expected to happen**:
buildcluster supports multiple SCM contexts

**How to reproduce it**:
Enable buildcluster with the environment there are multiple SCM contexts

**Comment by s-yoshika** [comment]
we can't register scmContext as array but resolved this issue to register the same `buildClusterName` with for each scmContext.
```
+-----+---------------+----------------------------------------+-------------------------------------+------------------+----------+----------------------+------------------------------------+-----------+
| id  | name          | description                            | scmContext                          | scmOrganizations | isActive | managedByScrewdriver | maintainer                         | weightage |
+-----+---------------+----------------------------------------+-------------------------------------+------------------+----------+----------------------+------------------------------------+-----------+
|  96 | buildcluster  | Build cluster                          | github:myghe1.com                   | []               |        1 |                    1 | foo@example.com                    |       100 |
|  97 | buildcluster  | Build cluster                          | github:myghe2.com                   | []               |        1 |                    1 | foo@example.com                    |       100 |
+-----+---------------+----------------------------------------+-------------------------------------+------------------+----------+----------------------+------------------------------------+-----------+
```
we can't specify scmContext because it's passed by the credetntials of login user. so we had to re-login for another scm.
https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/buildClusters/create.js#L23

**Comment by jithine** [comment]
This should be fixed with the updated documentation. Please re-open if still an issue
