### ISSUE TITLE
UI lost color rendering

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#231]
See this page: https://cd.screwdriver.cd/pipelines/27cec39c9baea6cf64c684479115300d22039b2a/build/36d1e630f8769722d4684bb9e912baed9165213b

![screen shot 2016-10-03 at 9 38 59 am](https://cloud.githubusercontent.com/assets/622065/19045354/3cb12c54-894d-11e6-9a1d-40b40adcf022.png)

**Comment by petey** [comment]
Fixed by https://github.com/screwdriver-cd/ui/pull/62
