### ISSUE TITLE
Badge URL is not taking trailing slashes

### ISSUE THREAD

**Issue by shashankrnr32** [screwdriver-cd/screwdriver#2310]
**What happened**:
| Badge | URL |
| ------- | ---- |
|![Badge](https://cd.screwdriver.cd/pipelines/1/badge) |"https://cd.screwdriver.cd/pipelines/1/badge"|
|![Badge](https://cd.screwdriver.cd/pipelines/1/badge/)| "https://cd.screwdriver.cd/pipelines/1/badge/" |

**What you expected to happen**:
Trailing Slashes should be accepted for Badge URL

**How to reproduce it**:
1. Take any Pipeline Badge URL.
2. Append a Trailing Slash to it.

**Comment by jithine** [comment]
Don't use trailing slash, you can't use an invalid url and expect it work or make the software support it..
