### ISSUE TITLE
Don't show "Start pipeline from here" in pipelines where no event exists

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2314]
**What happened**:
When an event does not exist yet, click `Start pipeline from here` to start the build, the build will not start with `Loading` displayed.

**What you expected to happen**:
In this case, I don't want to show `Start pipeline from here`.
Or, if the event does not exist, don't show the graph even if turn on `Show triggers`.

**How to reproduce it**:
1. Prepare a pipeline where no events exist. (ex. <https://cd.screwdriver.cd/pipelines/6420/events>)
2. Turn on `Show triggers`, and click `Start pipeline from here` for any job. <br /><img width="800" src="https://user-images.githubusercontent.com/24538326/104534593-e93a7d00-5657-11eb-9649-fe747191aba0.png">
3. Click `Yes`. <br /><img width="200" src="https://user-images.githubusercontent.com/24538326/104534671-0a9b6900-5658-11eb-83c3-2def0e4b6c1f.png">
4. Build will not start with `Loading` displayed. <br /><img width="150" src="https://user-images.githubusercontent.com/24538326/104534751-31f23600-5658-11eb-939d-cc98febc83f6.png">

**Comment by tkyi** [comment]
Agree, shouldn't show or give options in the UI for actions if they are not permitted or possible.

**Comment by tkyi** [comment]
No longer shows workflow if no events
<img width="1709" alt="Screenshot 2024-11-12 at 6 25 38 PM" src="https://github.com/user-attachments/assets/eae6ea6d-47fe-40ff-8abd-29767c93d095">
