### ISSUE TITLE
Confused by dashboard deletion

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2315]
**What happened**:
If user accesses a dashboard created by someone else and try to delete it, nothing happens.
Users are not sure if it is the deletion of the dashboard itself or the removal from the dashboard list.

The error log is output to console.
<img width="600" src="https://user-images.githubusercontent.com/24538326/104553404-ee122780-567d-11eb-97f3-0e6103c57a1f.png">

**What you expected to happen**:
- Don't show trash icon if user doesn't have delete permission.
- Display errors correctly.
- Make it clear whether the deletion is from the list or from the dashboard itself.

**How to reproduce it**:
1. Access a dashboard created by someone else. (ex. https://cd.screwdriver.cd/dashboards/3380 (created by wahapo))
2. Click the trash icon. <br /><img width="400" src="https://user-images.githubusercontent.com/24538326/104554079-0d5d8480-567f-11eb-9776-85caa58af52f.png">
3. Click the Confirm button. <br /><img width="460" src="https://user-images.githubusercontent.com/24538326/104554128-2108eb00-567f-11eb-86ec-ddace4c1f7ba.png">

**Relates to?**:
https://github.com/screwdriver-cd/screwdriver/issues/1669

**Comment by tkyi** [comment]
I agree with everything you mentioned above. 👍 
In this case, would be better to have the confirmation modal say something like: `You're about to delete the collection "asdf". Are you sure?`


---
I want to add I think it would also be good to reevaluate how we're using the words "Remove" vs "Delete" in the UI.

1. When clicking on the red "x" in the corner of a pipeline card in a Collection, should show a notification that the pipeline has been removed from the Collection.
<img width="662" alt="Screen Shot 2021-01-19 at 1 38 13 PM" src="https://user-images.githubusercontent.com/3230529/105096430-e70f5e80-5a5b-11eb-8162-aded09eed365.png">


2. When trying to delete a pipeline on the pipeline options page, the dialogue says "Remove". Should be "Delete".
<img width="1470" alt="Screen Shot 2021-01-19 at 1 26 10 PM" src="https://user-images.githubusercontent.com/3230529/105095136-25a41980-5a5a-11eb-95f6-ae36345253f1.png">

**Comment by tkyi** [comment]
Changes should be available with UI v1.0.594
