### ISSUE TITLE
In some cases, the same job cannot be started multiple times within the same event

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2321]
**What happened**:
<img width="400" src="https://user-images.githubusercontent.com/24538326/105436449-90479600-5ca2-11eb-90d2-d5e2b0ca03bb.png">
https://cd.screwdriver.cd/pipelines/6441/events/606628

sub-{1,2,3,4} jobs create four end jobs successfully, but only one job starts. In addition, only one of the QUEUED jobs is shown in the pipeline graph.

https://cd.screwdriver.cd/pipelines/6441/builds/674134 (SUCCESS, Not visible in pipeline graph)
https://cd.screwdriver.cd/pipelines/6441/builds/674135 (QUEUED, Not visible in pipeline graph)
https://cd.screwdriver.cd/pipelines/6441/builds/674136 (QUEUED, Not visible in pipeline graph)
https://cd.screwdriver.cd/pipelines/6441/builds/674137 (QUEUED, Visible in pipeline graph)

_It isn't reproduce in the pipeline below._
<img width="500" src="https://user-images.githubusercontent.com/24538326/105436726-0d730b00-5ca3-11eb-9638-427e869ddd41.png">
https://cd.screwdriver.cd/pipelines/6442/events/606632

- https://cd.screwdriver.cd/pipelines/6442/builds/674146 (SUCCESS, Not visible in pipeline graph)
- https://cd.screwdriver.cd/pipelines/6442/builds/674148 (SUCCESS, Not visible in pipeline graph)
- https://cd.screwdriver.cd/pipelines/6442/builds/674150 (SUCCESS, Visible in pipeline graph)

**What you expected to happen**:
I want to start all the jobs that have been created.

**How to reproduce it**:
https://cd.screwdriver.cd/pipelines/6441/events/606628

**Relates to**:
https://github.com/screwdriver-cd/screwdriver/issues/2320#issuecomment-765056299
https://github.com/screwdriver-cd/screwdriver/issues/2004 (This one is similar)

**Comment by jithine** [comment]
This is same as https://github.com/screwdriver-cd/screwdriver/issues/2071 we have started working on a fix. Closing this. We can track fix in #2071
