### ISSUE TITLE
transition loop occurs in invalid pipelines/{pipelineId}/builds/{buildId} route

### ISSUE THREAD

**Issue by MysticDoll** [screwdriver-cd/screwdriver#2324]
**What happened**:
Transitions to `pipeline` and `pipeline.build.step` occur simultaneously and these transitions are repeated in `https://<screwdriver url>/pipelines/{pipelineId}/builds/{buildId}` where `buildId` is not associated with `pipelineId` and `buildId` is for failed or running build.
This problem fires over 4000 requests per 200secs and these requests is endlessly repeated until the tab is killed.

It seems to execute both of `afterModel` and `redirect` event in the page.
Then if the build was failed or running, `getActiveStep` for it returns something and cause the transition to `pipeline.build.step` for the same pair of `buildId` and `pipelineId`. Of course, these ids are not related each other and that transition is repeated.

**What you expected to happen**:
The transition to `pipeline.build.step` does not occur in that case.

**How to reproduce it**:
Access `https://<screwdriver url>/pipelines/{pipelineId}/builds/{buildId}` where buildId is not associated with pipelined and buildId is for running or failed build.

**Comment by jithine** [comment]
cc @adong @OronNadiv
