### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#233]
We temporarily removed pagination due to DynamoDB limitation [#24](https://github.com/screwdriver-cd/datastore-dynamodb/pull/24). We should think of another way to implement pagination and deal with DynamoDB.

**Comment by stjohnjohnson** [comment]
I was thinking we could use something like `?from=5bf1fd927dfb8679496a2e6cf00cbe50c1c87145&count=10`

**Comment by jithin1987** [comment]
This is not valid anymore since we don't use DynamoDB
