### ISSUE TITLE
Lock template steps

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2331]
**What happened**:

As a template owner I want to prevent users from overriding my step. This is useful to provide the bare minimum steps a user must run to use my template. Also with [Template composition](https://github.com/screwdriver-cd/screwdriver/issues/2319) involved I would like to prevent another Template from redefining a step which must run, let's say a step for doing security scanning. 

**What you expected to happen**:

1. Provide a mechanism for template owner to specify that this step should not be overridden 

eg:
```
steps:
 - run: ./run.sh
 - scan:
     command: ./scan.sh
     locked: true
```

2. User's shouldn't  be able to [override](https://docs.screwdriver.cd/user-guide/templates#replace) step `scan` in their screwdriver.yaml

**How to reproduce it**:

N/A

**Related**

There are few issues related to expanding a step's capabilities. 
1. [Continue step](https://github.com/screwdriver-cd/screwdriver/issues/1208) on failure.
2. [Retry step ](https://github.com/screwdriver-cd/screwdriver/issues/1645)on failure.

**Comment by jithine** [comment]
cc @klu909 @tkyi

**Comment by jithine** [comment]
## How `locked` step interfaces with template composition.

Locked status of a step should be preserved in template composition. 
1. If `order` is being used, a child template author must include a locked step, else it will throw an error. 
   1. It will be up to child template author to `figure` out if position of the step in the order is correct. 
1. A child template author cannot redefine a locked step. 

While this results in a child template author lose flexibility when dealing with steps of parent template, making a locked step immutable preserves the intent that this is a step which must run as it is.

**Comment by jithine** [comment]
Also one aspect to keep in mind is how to handle transition if a template owner makes a step locked which a user was overriding in the past.

**Comment by tkyi** [comment]
<img width="1370" alt="Screen Shot 2021-03-01 at 3 14 40 PM" src="https://user-images.githubusercontent.com/3230529/109571930-3c01b400-7aa1-11eb-8b56-022101e52660.png">

Working with these versions:
screwdrivercd/screwdriver - v4.1.65
screwdrivercd/ui - v1.0.602
