### ISSUE TITLE
Highlight is not showing in the events tab

### ISSUE THREAD

**Issue by ibu1224** [screwdriver-cd/screwdriver#2342]
**What happened**:
The functions added in the following PR are not shown in the current UI
https://github.com/screwdriver-cd/ui/pull/654

<img width="363" alt="screenshot" src="https://user-images.githubusercontent.com/17828065/107322259-7ce05b80-6ae7-11eb-9755-f8eeabc48a47.png">
https://cd.screwdriver.cd/pipelines/4471/events/610567

**What you expected to happen**:
The latest commit will be highlighted.

**How to reproduce it**:
Open pipeline page

**Comment by wahapo** [comment]
Relates to?: https://github.com/screwdriver-cd/ui/pull/658

**Comment by jithine** [comment]
@kumada626 @ibu1224 There seems to be a bug in API. When a PR is opened, it's returning the PR event as the `latestCommitEvent` When in event's tab, it should only consider non-PR events. 

So blue highlight is gone, moment a PR is opened.

**Comment by jithine** [comment]
@kumada626 @ibu1224 one question on implementation. If we miss a webhook, won't UI incorrectly show a `latestCommit` event

**Comment by kumada626** [comment]
That's right. In the current implementation, the API gets the latest commit sha from the latest event. If we miss a webhook and an event is not created, the API returns the latest commit which is not latest on the SCM 😢

**Comment by jithine** [comment]
Closing this, if anything is pending to implement, please re-open
