### ISSUE TITLE
Parameters at job level

### ISSUE THREAD

**Issue by shashikreddy** [screwdriver-cd/screwdriver#2346]
**What happened**: We have a pipeline that has over 100 jobs, out of those 100+ jobs only 2 jobs need [parameters](https://docs.screwdriver.cd/user-guide/configuration/parameters.html) option and those jobs are always triggered manually to run some custom scripts based on the parameters. Current parameters option seems to be set at the pipeline level and it shows the parameters for every event even though it's not used by other jobs, in our use-case showing parameters for each event will be misleading. 

**What you expected to happen**: Expect to choose parameters while starting the job and it should show those parameters in the events section only for those jobs instead of showing it for every commit.

**How to reproduce it**: It is reproducible with any pipeline with parameters.

**Comment by tkyi** [comment]
Wondering if it would be possible to set `parameters` in shared section
or if they're set in pipeline-level, would they be merged with job-level `parameters`?
