### ISSUE TITLE
Sort collection by start date

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#2349]
**What happened**:
I have a collection of pipelines, and I want them ordered by start date

**What you expected to happen**:
I expected to have a way to sort the pipelines by start date

**How to reproduce it**:
Sadly gaze on unclickable column headings.

**Comment by jithine** [comment]
@CatWithNineLives Thank you for your interest. I just assigned this to you. Please checkout out contribution guide https://docs.screwdriver.cd/about/contributing/index#general-guidelines-for-contributing Happy coding 👍

**Comment by jithine** [comment]
This has been completed. Column name is `Last Run`
