### ISSUE TITLE
Cannot filter trusted templates/commands

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2350]
**What happened**:
Toggle on trusted in the template/command list page, trusted templates/commands are not listed.

**What you expected to happen**:
All trusted templates/commands are listed on the template/command list page when toggle on trusted button.

**How to reproduce it**:
1. Toggle on trusted button in [template list page](https://cd.screwdriver.cd/templates).
2. [python/package_rpm](https://cd.screwdriver.cd/templates/python/package_rpm) template is a trusted template but it is not shown in template list.

**Comment by kumada626** [comment]
This issue may be caused by https://github.com/screwdriver-cd/screwdriver/issues/2312 .

**Comment by jithine** [comment]
We should be able to carry over trusted status to newly published templates, since we are anyways querying the previous one for version update.
Might need another DB migration file at this point.

**Comment by klu909** [comment]
You will need to fix entries in template/command table manually with query like this `UPDATE commands AS t1, commands AS t2 SET t1.trusted = true WHERE t1.namespace = t2.namespace AND t1.name = t2.name AND t2.trusted = true`

**Comment by kumada626** [comment]
This issue still occurs.
1. Mark a template trusted.
2. Update template minor or major version(not patch version).
3. The template is not shown in trusted template list.

**Comment by klu909** [comment]
This was my mistake, last fix didn't properly fix this. I am fixing template/command creation flow and you would have to manually mark these affected template/command as trusted.
