### ISSUE TITLE
completed teardown steps sometimes have  a failure code

### ISSUE THREAD

**Issue by MysticDoll** [screwdriver-cd/screwdriver#2351]
**What happened**:
Sometimes completed teardown steps look failure in UI. But logs for these steps tell it has been successfully completed.
These weird teardown steps exited status `141` (exited with SIGPIPE).

SIGPIPE can occur when launcher opens FIFO file `/sd/emitter` without reader process(log-service) of it, and then if there are no log-service, steps usually have no log but these steps have completed log.

Therefore I think maybe this problem is caused by re-executing teardown phase.

**What you expected to happen**:
Completed teardown steps have correct exit status.

**How to reproduce it**:

**Comment by jithine** [comment]
launcher build logs should say if a step is getting processed twice. Are you seeing that ?

**Comment by MysticDoll** [comment]
> launcher build logs should say if a step is getting processed twice. Are you seeing that ?

Yes. I checked logs of the build pod that this occurs, I saw logs below.

```
2021/02/15 16:07:24 Failure due to non-zero exit code: exit 141
2021/02/15 16:07:24 [DEBUG] PUT https://OUR_SDAPI_HOST/v4/builds/33670962/steps/sd-teardown-step-4
2021/02/15 16:07:24 [DEBUG] PUT https://OUR_SDAPI_HOST/v4/builds/33670962/steps/sd-teardown-step-4
2021/02/15 16:07:24 [DEBUG] PUT https://OUR_SDAPI_HOST/v4/builds/33670962/steps/sd-teardown-step-3
2021/02/15 16:07:24 [DEBUG] PUT https://OUR_SDAPI_HOST/v4/builds/33670962/steps/sd-teardown-step-3
2021/02/15 16:07:24 [DEBUG] PUT https://OUR_SDAPI_HOST/v4/builds/33670962/steps/sd-teardown-step-2
2021/02/15 16:07:24 [DEBUG] PUT https://OUR_SDAPI_HOST/v4/builds/33670962/steps/sd-teardown-step-2
2021/02/15 16:07:23 [DEBUG] PUT https://OUR_SDAPI_HOST/v4/builds/33670962/steps/sd-teardown-step-1
2021/02/15 16:07:23 [DEBUG] PUT https://OUR_SDAPI_HOST/v4/builds/33670962/steps/sd-teardown-step-1
2021/02/15 16:07:23 [DEBUG] PUT https://OUR_SDAPI_HOST/v4/builds/33670962/steps/sd-teardown-step-0
2021/02/15 16:07:23 [DEBUG] PUT https://OUR_SDAPI_HOST/v4/builds/33670962/steps/sd-teardown-step-0
2021/02/15 16:07:23 Get Workspace in /sd/workspace
2021/02/15 16:07:23 [DEBUG] GET https://OUR_SDAPI_HOST/v4/pipelines/34858
2021/02/15 16:07:23 Fetching Pipeline 34858
2021/02/15 16:07:23 [DEBUG] GET https://OUR_SDAPI_HOST/v4/jobs/305263
2021/02/15 16:07:23 Fetching Job 305263
2021/02/15 16:07:23 [DEBUG] GET https://OUR_SDAPI_HOST/v4/builds/33670962/secrets
2021/02/15 16:07:23 Fetching secrets 305263
Exit code:143 received in run.sh, waiting for 60 seconds
Terminated
2021/02/15 16:07:23 [DEBUG] GET https://OUR_SDAPI_HOST/v4/builds/33670962
2021/02/15 16:07:23 Fetching Build 33670962
2021/02/15 16:07:23 Starting teardown steps before exiting
Received terminated signal in launcher, processing signal 
```

But  logs also exist that completes those teardown steps before logs above.

```
2021/02/15 16:07:22 Completed step processing for sd-teardown-step-4
2021/02/15 16:07:20 Completed step processing for sd-teardown-step-3
2021/02/15 16:07:20 Completed step processing for sd-teardown-step-2
2021/02/15 16:07:18 Completed step processing for sd-teardown-step-1
2021/02/15 16:07:17 Completed step processing for sd-teardown-step-0
```

**Comment by s-yoshika** [comment]
This issue has been occurred in our environment after we updated the launcher [from v6.0.91 to v6.0.106](https://github.com/screwdriver-cd/launcher/compare/v6.0.91...v6.0.106)
It includes the [feat](https://github.com/screwdriver-cd/launcher/pull/369) which ensure the teardown steps are executed even when aborted, with [sighandler](https://github.com/screwdriver-cd/launcher/pull/369/files#diff-0952bc032b3245f7e7282a5d24e8a1775eb3e1f265de43bb26834860e6acc4edR720).
Can it be probable that teardown steps are re-executed  when it received SIGTERM after the build is finished succcessfully?

**Comment by s-yoshika** [comment]
And recently, https://github.com/screwdriver-cd/launcher/pull/388 seems remove that feature.
if we'll update launcher to latest, this issue will be resolved?

**Comment by jithine** [comment]
@s-yoshika could it be that sigterm happened when teardown steps were being executed ?

**Comment by itleigns** [comment]
This problem was resolved when we updated the version of launcher to the latest.

**Comment by itleigns** [comment]
In that process, we tested [this PR](https://github.com/screwdriver-cd/launcher/pull/404). However, when we abort a build, the subsequent teardown steps do not get the environment variables. We tested with [this pipeline](https://github.com/pritamstyz4ever/sd-sample-build/blob/6c6e5b9b3108052b0a1a929e57948c825b2ed336/screwdriver.yaml) as a reference but it does not work correctly.
We set `TERMINATION_GRACE_PERIOD_SECONDS` as `360` of `buildcluster-queue-worker`. 
Is there any other setting we need to do?

Related Issue : https://github.com/screwdriver-cd/screwdriver/issues/2361

**Comment by parthasl** [comment]
sleep is behaving differently, will update once I have a fix for the same.
