### ISSUE TITLE
API will not start with default.yaml

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2354]
**What happened**:
If notifications are not used, an error occurs at startup.
```
$ npm start

> screwdriver-api@4.1.0 start /Users/wahapo/screwdriver
> ./bin/server

/Users/wahapo/screwdriver/bin/server:65
    hoek.reach(config.get('notifications').options, 'throwValidationErr', { default: true })

TypeError: Cannot read property 'options' of null
    at Object.<anonymous> (/Users/wahapo/screwdriver/bin/server:65:43)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

[These lines](https://github.com/screwdriver-cd/screwdriver/blob/0c6fe84daec4fcc61e2456a1c0c1e1fbc98ba3fd/config/default.yaml#L273) are commented out, so I think the error is occurring in [this line](https://github.com/screwdriver-cd/screwdriver/blob/0c6fe84daec4fcc61e2456a1c0c1e1fbc98ba3fd/bin/server#L65).

**What you expected to happen**:
The API can be started correctly even when using [default.yaml](https://github.com/screwdriver-cd/screwdriver/blob/master/config/default.yaml).

**How to reproduce it**:
Start the API with the following settings.
```
notifications:
  # options:
  #   # Throw error when validation fails (default true); otherwise show warning
  #   throwValidationErr: true
  # # Email notification when a build finishes
  # email:
  #   host: email-host
  #   port: email-port
  #   from: email-address-to-send-from
  #   username: optional-username
  #   password: optional-password
  # # Slack notification when build finishes
  # slack:
  #   token: your-slack-bot-token
```

**Relates to**:
https://github.com/screwdriver-cd/screwdriver/pull/2340

**Comment by tkyi** [comment]
Hm I thought the default value would make sure it doesn't fail.

Does it work okay if you uncomment out those lines in the default.yaml?

**Comment by jithine** [comment]
fixed with https://github.com/screwdriver-cd/screwdriver/pull/2355
