### ISSUE TITLE
Bintray will be Sunset status

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#2366]
**What happened**:
Bintray will be Sunset status: 
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Screwdriver.cd is using Bintray for storing some binaries.
https://bintray.com/screwdrivercd/screwdrivercd

**What you expected to happen**:
Decide how to handle bintray sunset if needed.

**Comment by tk3fftk** [comment]
> **What happens after the sunset of Bintray and JCenter?**
On May 1, 2021, the sunset will impact all existing Bintray users. Bintray users will be blocked and will no longer be able to use the Bintray service. This includes existing software distribution, account administrative access, UI access, and the REST API.

We use some binaries in Bintray for building Launcher image.
https://github.com/screwdriver-cd/launcher/blob/d99488f7fe3723ffb4d29d345bf4de413b9bbbf0/Dockerfile#L71-L95
so we should switch these paths until May 1, 2021.

**Comment by jithine** [comment]
This was addressed with https://github.com/screwdriver-cd/launcher/pull/418
