### ISSUE TITLE
Multiple machines running

### ISSUE THREAD

**Issue by justinzelinsky** [screwdriver-cd/screwdriver#2373]
In the [documentation](https://docs.cypress.io/guides/guides/parallelization.html#Turning-on-parallelization) for Cypress regarding setting up parallelization, it mentions configuring your CI environment to support multiple machines.

>Refer to your CI provider’s documentation on how to set up multiple machines to run in your CI environment.

Is this possible in Screwdriver? Are we able to run Cypress in parallel instead of one test after another?

**Comment by jithine** [comment]
While Screwdriver itself doesn't do this natively, you can split your tests into mulitple jobs and run tests. Also cypress might be talking about configuring your CI job to make use on parallelization. Either ways, this is something you will have to configure at your job configuration.
