### ISSUE TITLE
Show PR Jobs behavior

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2391]
**What happened**:

I tried using the ShowPR function, but it seems that the behavior is different from the explanation displayed on the UI. The trigger is hidden but the job is not hidden. Is this the intended behavior?

explanation Show PR Jobs

<img width="360" alt="スクリーンショット 2021-03-23 16 58 01" src="https://user-images.githubusercontent.com/32473622/112112538-fe53ff00-8bf8-11eb-991c-cbe097383527.png">

Show ON

<img width="145" alt="スクリーンショット 2021-03-23 16 56 01" src="https://user-images.githubusercontent.com/32473622/112112393-d06eba80-8bf8-11eb-8e35-a75a4084c0b1.png">

Show OFF

<img width="149" alt="スクリーンショット 2021-03-23 16 56 45" src="https://user-images.githubusercontent.com/32473622/112112371-c8af1600-8bf8-11eb-9ae1-472800a5bbe7.png">

**What you expected to happen**:

UI explanation matches the behavior.

**How to reproduce it**:

1. Make pipeline
https://cd.screwdriver.cd/pipelines/6876/events/620093

2. Toggle Show PR Jobs

**Comment by tk3fftk** [comment]
related: https://github.com/screwdriver-cd/ui/pull/677

**Comment by jithine** [comment]
This was fixed with above PR
