### ISSUE TITLE
UI: Edit Collection Modal accepts empty Name and updates the UI screen though API rejects it.

### ISSUE THREAD

**Issue by kprasadpvv** [screwdriver-cd/screwdriver#2392]
**What happened**:
 - Edit Collection modal don't have validations and accepts the empty string for `Collection Name` field.
 - Saving collection modal with empty string for  `Collection Name` field close the edit model and update the UI screen with white space resulting distorted UI screen and also data integrity issue.

**What you expected to happen**:
 - Should restrict user to enter empty values.

**How to reproduce it**:

- Navigate to screwdriver UI
- Click on collections
- Edit any collection from the list of available collections (If none is available create 1 and edit it)
- In the `Edit Collection Modal` remove the name of the collection and Save it.
- Observed that in the browser console API is throwing the error but in UI the `Modal` is getting closed and UI screen is updated with the empty name.

**Screenshots**:
1) Edit modal:
<img width="1213" alt="Screenshot 2021-03-23 at 6 08 21 PM" src="https://user-images.githubusercontent.com/10308692/112147568-dff30100-8c02-11eb-90c5-fd3e81f84774.png">

2) After Updating the Edit Model:
<img width="1680" alt="Screenshot 2021-03-23 at 5 52 14 PM" src="https://user-images.githubusercontent.com/10308692/112147360-9dc9bf80-8c02-11eb-90ab-af0afb6b7bd8.png">

**Comment by kprasadpvv** [comment]
I'll work on it.

**Comment by kprasadpvv** [comment]
Fix got merged, Closing this issue

**Comment by jithine** [comment]
Thank you @kprasadpvv
