### ISSUE TITLE
UI:Available collection list is not displaying under `copy to` option in default pipeline collection dashboard

### ISSUE THREAD

**Issue by kprasadpvv** [screwdriver-cd/screwdriver#2395]
**What happened**:

- Available collection list is not displaying under `copy to` option in default pipeline collection dashboard

**What you expected to happen**:

**How to reproduce it**:

- Navigate to screwdriver UI
- Click on collections
- Ensure that we landed on default `Pipelines` collection also make sure you have more than 1  collection
- Click on `Organize` button.
- Ensure that organizing mode is enabled 
- Select any pipeline in the list and ensure that collection action buttons were displayed 
- Select `Copy To` button in the buttons available on right top corner.
- Observed that available `collection list` is not being displayed.

**ScreenShot**
<img width="1639" alt="NoCollectionListUnderCopyToOption" src="https://user-images.githubusercontent.com/10308692/112503259-c7c0e480-8db0-11eb-809b-74df88549b9e.png">

**Comment by kprasadpvv** [comment]
I will work on it.

**Comment by tkyi** [comment]
Also fixed now, thank you for your contributions! 🙇‍♀️
