### ISSUE TITLE
Selected pipeline list is not being reset after completing edit/copy to operations

### ISSUE THREAD

**Issue by kprasadpvv** [screwdriver-cd/screwdriver#2396]
**What happened**:
 - In the `Collection View` click on `Organize` and select the pipelines.
 - Selecting pipelines will show the count on the Top,
 - Remove/ Copy pipelines
 - Ensure that selected pipelines are deleted.
 - Now click on organize again
 - Observed that count from previous selection operation still displayed and `Remove`, `Copy To` buttons are also displayed though we haven't selected anything.
 
**What you expected to happen**:
- Counter should reset and respective buttons should not display without selecting any pipeline
**How to reproduce it**:
<img width="1635" alt="Screenshot 2021-03-25 at 8 53 20 PM" src="https://user-images.githubusercontent.com/10308692/112508637-c0500a00-8db5-11eb-82ee-84c725cf3ba3.png">

**Comment by kprasadpvv** [comment]
will work on it

**Comment by tkyi** [comment]
This issue is fixed now with your change. Thank you! 🎉
