### ISSUE TITLE
[External Config] Source Directory not at checkout root for child pipelines

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#2398]
**What happened**: Some groups might have separate teams managing their build pipeline using [external config](https://docs.screwdriver.cd/user-guide/configuration/externalConfig). When specifying `scmUrls` for child pipelines, you currently cannot point to [a different source directory than checkout root](https://docs.screwdriver.cd/user-guide/configuration/sourceDirectory.html) for those child pipelines.

Current syntax:
```
childPipelines:
   scmUrls:
      - git@github.com:minz1027/test.template.git
      - git@github.com:minz1027/quickstart-generic.git#main

```

**What you expected to happen**: It would be nice if child repos could keep code for multiple pipelines within the same repo. External config should be able to specify `rootDir` for child pipelines.

Perhaps we could use `:` as the separator, will need to change UI to match.

Current UI:
<img width="373" alt="Screen Shot 2021-03-26 at 9 51 42 AM" src="https://user-images.githubusercontent.com/3230529/112665982-e65ac600-8e18-11eb-95f1-70c6f035ba4b.png">

Proposed syntax where the `rootDir` is *deploy/dir*:
```
childPipelines:
   scmUrls:
      - git@github.com:minz1027/test.template.git
      - git@github.com:minz1027/quickstart-generic.git#main:deploy/dir

```

**How to reproduce it**:

**Comment by jithine** [comment]
Can you also update how source directory is displayed in pipeline detail page ?

Eg: https://cd.screwdriver.cd/pipelines/4013/events/106046

from `master#sd` => `master:sd` since `#` is associated with branch name in Git
