### ISSUE TITLE
Duplicate step error bug

### ISSUE THREAD

**Issue by itleigns** [screwdriver-cd/screwdriver#2403]
**What happened**:
Multiple steps with the same name can be in a single job. Pipelines containing this job can be executed, but they are not run properly.

**What you expected to happen**:
`config-parse-error` should occur.

**How to reproduce it**:
Use the following YAML.
```
jobs:
  test:
    requires: ~commit
    image: node10
    steps:
      - echo "Hello Screwdriver.cd"
      - step-1 : echo "E"
```
<img width="980" alt="スクリーンショット 2021-04-06 17 41 51" src="https://user-images.githubusercontent.com/22903716/113688506-5401ce80-9704-11eb-829e-8e9229644d02.png">

**Comment by kumada626** [comment]
At that case, test job only execute `echo "Hello Screwdriver.cd"` step, not execute `step-1 : echo "E"` step. This behavior is not the same with what the validator shows.
