### ISSUE TITLE
Cannot use dot in the key of environment

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2414]
**What happened**:
The yaml in the [guide](https://docs.screwdriver.cd/user-guide/configuration/environment) will show a validation error when checked by the [validator](https://cd.screwdriver.cd/validator).

<img width="1087" alt="validationerror" src="https://user-images.githubusercontent.com/24538326/114862483-8d83b980-9e29-11eb-9063-445b9175435f.png">

**What you expected to happen**:
We need to correct the description in the document.

**How to reproduce it**:

**Comment by tkyi** [comment]
Should be coming from here: https://github.com/screwdriver-cd/data-schema/blob/master/config/regex.js#L77-L80
Seems like we get these rules from here: https://pubs.opengroup.org/onlinepubs/009696899/basedefs/xbd_chap08.html#:~:text=Environment%20variable%20names%20used%20by,not%20begin%20with%20a%20digit.

We can relax the requirement if it makes sense
cc: @jithine

**Comment by wahapo** [comment]
If it is correct that dot cannot be used, then I think we can just modify the description in the [guide](https://github.com/screwdriver-cd/guide/blob/master/docs/user-guide/configuration/environment.md).

**Comment by tkyi** [comment]
Yeah I think we should just fix the guide. Doesn't look like we originally meant to support dot notation for environment names.

**Comment by tkyi** [comment]
Should be fixed here: https://docs.screwdriver.cd/user-guide/configuration/environment
