### ISSUE TITLE
UI publish job intermittent failures

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#2421]
**What happened**: 
UI `publish` job fails intermittently with this error:
```
00:01:19 $ ./node_modules/.bin/ember build --environment production
00:01:23 Building
00:01:27 WARNING: Option "nodeWorker" is deprecated since workerpool@5.0.0. Please use "workerType" instead.
00:01:27 Environment: production
00:01:27 building... 
00:05:04 Killed
```
https://cd.screwdriver.cd/pipelines/7/builds/698411/steps/build
https://cd.screwdriver.cd/pipelines/7/builds/697664/steps/build

**What you expected to happen**:
Expect UI `publish` job to be consistent.

**How to reproduce it**: Merge code to UI repo, monitor `publish` job.

**Comment by jithine** [comment]
we likely need to bump up the compute resources  for the build job.
