### ISSUE TITLE
Commits created by detached jobs are not triggering the right previous pushed commit 

### ISSUE THREAD

**Issue by martoc** [screwdriver-cd/screwdriver#2432]
**What happened**:

When a job `A` commits some code to the same repo then job `B` is triggered with the previous commit and not the new one we are using this `requires: [~commit, ~sd@1000000:A]` in job `B`

**What you expected to happen**:

it should trigger B with the new commit created by A

**How to reproduce it**:

```
  A:
    steps:
      - init: |
          date > file.txt
          git add file.txt
          git commit -m "Updating file at $(date)"
          git push origin master
B: 
  requires: [~commit, ~sd@1000000:A]
  steps:
     - build: echo $SD_BUILD_SHA
```

**Comment by tkyi** [comment]
If you want job B to be triggered with job A's commit only, you can remove the `~commit` in the requires.
You can also drop the external syntax for A if it's in the same pipeline: `~sd@ 1000000 :A` => `~A`.
The result would then look like this:
```
A:
    steps:
      - init: |
          date > file.txt
          git add file.txt
          git commit -m "Updating file at $(date)"
          git push origin master
B: 
  requires: [~A]
  steps:
     - build: echo $SD_BUILD_SHA
```
