### ISSUE TITLE
UI is not updating workflowgraph for a running pipeline

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2434]
**What happened**:

When jobs in a pipeline runs and triggers subsequent jobs, UI workflow graph doesn't update. User has to do an explicit page reload to see current status.

At the same time event status is properly computed as can be seen from screenshot. So this means UI is indeed fetching new builds, but graph is not updated.
<img width="1430" alt="Screen Shot 2021-04-28 at 1 30 07 PM" src="https://user-images.githubusercontent.com/193126/116485981-6e315700-a841-11eb-93df-ef36016cac7b.png">

**What you expected to happen**:
UI shows updated workflow graph when it fetched new data

**How to reproduce it**:

**Comment by adong** [comment]
I need to take a deep look, I still was able to reproduce it on `https://cd.screwdriver.cd/pipelines/4648/events/629655` for commit `950a1e9`. 


I was not able to see this behavior happening on commit `4a6c175`. So something happened in between. Need to double-check.
