### ISSUE TITLE
Address linter warnings

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2443]
**What happened**:

Screwdriver [eslint config](https://github.com/screwdriver-cd/eslint-config-screwdriver) is used in most of the libraries and applications under the project, however not all warnings are addressed.

eg: https://github.com/screwdriver-cd/screwdriver/blob/master/package.json#L7

**What you expected to happen**:

Address all static analysis warnings.

**How to reproduce it**:

**Comment by jithine** [comment]
https://github.com/screwdriver-cd/screwdriver/issues/2486

**Comment by jithine** [comment]
API project has 489 eslint warnings, majority of them are caused by rules

1. https://eslint.org/docs/rules/max-statements
1. https://eslint.org/docs/rules/max-lines-per-function
1. https://eslint.org/docs/rules/max-params

Warnings https://cd.screwdriver.cd/pipelines/1/builds/712791/steps/test

Bring down total warnings per project to under 1 per 100 lines.

**Comment by jithine** [comment]
@screwdriver-cd/yahoo-japan @wdstar [These eslint rules ](https://github.com/screwdriver-cd/eslint-config-screwdriver/pull/31/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R33-R35 )which we introduced in the past is not realistic. There has been no movement on addressing the strict limitations these rules imposes and we[ have over 450 warnings](https://github.com/screwdriver-cd/screwdriver/issues/2443#issuecomment-859932805) due to these 3. 

I would like to get your thoughts on relaxing or removing these rules. We should relax these to better suit our project needs.

**Comment by kumada626** [comment]
I agree with your opinion of relaxing the rules. However, I am not certain about how much to relax it.

**Comment by yuichi10** [comment]
It is ok to relax the rule, but I think it is better not to remove all.
I think we don't have to fix everything at once, but it would be nice to be able to fix the error every time you write some code, or the code around it.

How about to introduce [reviewdog ](https://github.com/reviewdog/reviewdog)?

**Comment by jithine** [comment]
PR to relax eslint rules https://github.com/screwdriver-cd/eslint-config-screwdriver/pull/50

@yuichi10 reviewdog looks interesting. We can try it on few repos and see how it works out.

**Comment by jithine** [comment]
Will track upgrading eslint version work in this issue .screwdriver.cd/
