### ISSUE TITLE
Invalid git repo name marked as valid

### ISSUE THREAD

**Issue by mchengat** [screwdriver-cd/screwdriver#2448]
"Create pipeline" page accepts invalid git repo urls.

Show validation error/ red color for invalid urls.
 
For git  urls like "https://github.com/mchengat/quickstart-nodejs in the "Create pipeline" page , green check-mark are shown which shows urls are fine. After submitting UI throws error, "Invalid request payload input"

**Comment by jithine** [comment]
https://github.com/screwdriver-cd/ui/pull/714
