### ISSUE TITLE
API is using outdated crypto module

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2452]
**What happened**:

[Token generation](https://github.com/screwdriver-cd/models/blob/master/lib/generateToken.js#L4) depends on [crypto](https://www.npmjs.com/package/crypto) library, which is deprecated. 

**What you expected to happen**:

Use node.js [built in module crypto](https://nodejs.org/api/crypto.html)

**How to reproduce it**:

**Comment by ombharatiya** [comment]
It's already using node.js built-in crypto module.
