### ISSUE TITLE
The user default collection does not need a remove button

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2458]
**What happened**:
Users will see `Collection with type "default" cannot be changed by user` when they try to remove pipelines from the user default collection. The remove button should not be needed.

**What you expected to happen**:
Don't show the remove button.

**How to reproduce it**:
1. Access [your default collection page](https://cd.screwdriver.cd/)
2. Remove pipelines from collection
    <img width="800" src="https://user-images.githubusercontent.com/24538326/119299389-c9683500-bc99-11eb-86e9-2349ea767fe6.png">
    <img width="800" src="https://user-images.githubusercontent.com/24538326/119299383-c79e7180-bc99-11eb-8f0c-7d9d40a26520.png">

**Comment by tkyi** [comment]
Should be available with `screwdrivercd/ui v1.0.637`
