### ISSUE TITLE
[Feature Request]Difficult to understand the branch of the event

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2465]
**What happened**:
When trying to start a detached job, if user accidentally select and start an event that was started from a specified branch, user will not notice the mistake.
[Branch filtering](https://docs.screwdriver.cd/user-guide/configuration/workflow#branch-filtering)
<img width=700 src="https://user-images.githubusercontent.com/24538326/119953262-c7bfa980-bfd8-11eb-93df-a31644d95944.png">

**What you expected to happen**:
I came up with an idea that it would be nice to have an indication of which branch an event refers to.
<img width=500 src="https://user-images.githubusercontent.com/24538326/119957267-e6c03a80-bfdc-11eb-94fd-de8c95e68599.png">

**How to reproduce it**:

**Comment by kumada626** [comment]
## Proposal

If the baseBranch of selected event is differ from pipeline branch, UI shows event baseBranch on event-info area like below.

<img width="1239" alt="スクリーンショット_2021-08-11_15_20_39" src="https://user-images.githubusercontent.com/8113204/128980020-e0530c39-8984-4f8c-b33a-d31f4ccd9828.png">
In this proposal, I think there is a discuss point like below.

- Should UI show branch name if event baseBranch is the same branch of the pipeline branch?

To emphasis the branch is differ from pipeline branch, UI should show the branch name only if baseBranch if differ from pipeline branch.
However, the unified view is the merit of showing branch name always.

**Comment by tkyi** [comment]
**bug**: not sure why latest events are missing `baseBranch`
<img width="1368" alt="Screen Shot 2022-10-12 at 4 14 40 PM" src="https://user-images.githubusercontent.com/3230529/195464734-7b8c0586-cd74-4de4-9546-9708597da980.png">

**idea**: would be nice if branch was accurate for Pull requests
