### ISSUE TITLE
[FEAT] Virtual Trigger Job

### ISSUE THREAD

**Issue by renaud-vmg** [screwdriver-cd/screwdriver#2470]
**Why?**

Mostly as a UX enhancement. When a job specifies a "requires" with a job name that doesn't exist, Screwdriver could _create_ a **virtual trigger** job that merely acts as a trigger event, removing the need to create a true job with container specs, a shimmed step and all the running implications of a full job.

**Details**

* Annotation-activated only for now
* Iconography: arrow job, much like the commit icon

**Comment by tkyi** [comment]
probably related? https://github.com/screwdriver-cd/screwdriver/issues/1323

**Comment by renaud-vmg** [comment]
That second one looks very similar, yes.

**Comment by kumada626** [comment]
I think #1449 is related too.

**Comment by jithine** [comment]
Closing this one as duplicate of https://github.com/screwdriver-cd/screwdriver/issues/1449
