### ISSUE TITLE
[Feature request] Link to the pipline from template/command detail page.

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2473]
**What happened**:
When I maintain a template, I always search and find the pipeline I'm publishing, but it's a hassle. It would be nice to have a hassle-free and reliable way to get to the pipeline.

**What you expected to happen**:
It would be nice if the template detail page has a link to the pipeline that is publishing the template.

**How to reproduce it**:

**Comment by tkyi** [comment]
Should be available with `screwdrivercd/ui v1.0.638`
