### ISSUE TITLE
We can not get meta-cli using go get 

### ISSUE THREAD

**Issue by itleigns** [screwdriver-cd/screwdriver#2474]
**What happened**:
The following command fails.
```
go get -d -v github.com/screwdriver-cd/meta-cli
```
**What you expected to happen**:
We can install the package using go get.

**How to reproduce it**:
Execute the following command.
```
$ export GO111MODULE=on
$ go get -d -v github.com/screwdriver-cd/meta-cli
```

**Comment by itleigns** [comment]
The reason this happens is that meta-cli has files which contains `:` in the filenames.
https://github.com/screwdriver-cd/meta-cli/tree/master/mock

**Comment by itleigns** [comment]
In addition, `:` can not be used as a pathname in Windows.

**Comment by wahapo** [comment]
FYI https://github.com/golang/go/issues/28001

**Comment by jithine** [comment]
Fixed with https://github.com/screwdriver-cd/meta-cli/pull/48

**Comment by scr-oath** [comment]
Verified fix works with your use-case

```bash
[scr@C02XD8VFJG5J]$ go get -d -v github.com/screwdriver-cd/meta-cli
go: downloading github.com/screwdriver-cd/meta-cli v0.0.48
```
