### ISSUE TITLE
Cannot start pipeline from "Start pipeline from here" button

### ISSUE THREAD

**Issue by itleigns** [screwdriver-cd/screwdriver#2489]
**What happened**:
When I clicked `Start pipeline from here` and `Yes` button, loading does not finish. If I then reload, the loading window disappears, but the build does not start. This does not happen with `Restart pipeline from here` button.

**What you expected to happen**:
I can start the build.

**How to reproduce it**:
Choose `removeTag` job and click `Start pipeline from here` and `Yes` button with the following pipeline.
https://cd.screwdriver.cd/pipelines/7289/events/635054
<img width="1439" alt="スクリーンショット 2021-06-18 17 23 04" src="https://user-images.githubusercontent.com/22903716/122530890-eeae5000-d059-11eb-8ad9-b9d004396488.png">

**Comment by yoshwata** [comment]
[memo] Error in my sandbox
<img width="739" alt="スクリーンショット 2021-06-21 13 22 14" src="https://user-images.githubusercontent.com/32473622/122706929-f22d1b80-d293-11eb-9624-f2c49024f4cd.png">

Changes that may be relevant
https://github.com/screwdriver-cd/ui/pull/716
