### ISSUE TITLE
Toggle to view different Date Time Formats on Events Details Page

### ISSUE THREAD

**Issue by ombharatiya** [screwdriver-cd/screwdriver#2511]
**What happened**:

Events Details Page shows Start Date in Exact date format in current time zone. Exact Time can be helpful for comparing the time between events but it is less readable.

**What you expected to happen**:

Date Time can be formatted into UTC or Words and shown on the Events Details page just with a toggle functionality. It will make it more user friendly and readable based on preferences.

**Comment by tkyi** [comment]
Closing as duplicate of linked issue
