### ISSUE TITLE
Start/Stop button placements in the UI

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2516]
**What happened**:

Button placements of Start/Stop for events and pull requests are confusing. Start button is always shown and it's not clear that it's applicable only for creating a new event. Stop button for a running event is shown next to start button, creating a confusion that it's applicable to entire event list. Also Start/Stop buttons are missing for Pull Requests and is shown only for chainPR use case.

**What you expected to happen**:

1. For Pull Requests Start/Stop button should be displayed next to the PR where it's applicable.
2. For events Start button for creating a new event should be displayed separately from the Stop button which is applicable for a specific event.

**How to reproduce it**:

**Comment by itleigns** [comment]
There is no Start button after creating a new pipeline now. So we can not trigger the first build from UI. Is this intended?

<img width="1440" alt="スクリーンショット 2021-08-11 18 18 03" src="https://user-images.githubusercontent.com/22903716/129003703-ebaeb58c-94d0-4550-b0ec-3b3f919ba9cc.png">

**Comment by jithine** [comment]
> Currently, there is no Start button after creating a new pipeline. So we can not trigger the first build from UI. Is this intended?
> 
> <img alt="スクリーンショット 2021-08-11 18 18 03" width="1440" src="https://user-images.githubusercontent.com/22903716/129003703-ebaeb58c-94d0-4550-b0ec-3b3f919ba9cc.png">

Not intended. @ombharatiya please fix this
