### ISSUE TITLE
Join job did not start when restarting a failed job

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2526]
**What happened**:

A build in an older event is not able to effect a join job, when conditions become favorable in newer events.

Example Pipeline https://cd.screwdriver.cd/pipelines/4256/events/642766

In above example following happens
1. `bucket_1_ui` job fails in event 1.
2. `build_test` is running in event 1.
3. User restarts `bucket_1_ui` job in event 2 and it passes. 
4. `build_test` is still running in event 1 when `bucket_1_ui` job in event 2 passes.
5. `build_test` becomes successful but join job `certify_tag` did not run.

**What you expected to happen**:

Join job `certify_tag` should have ran in event 2, when `build_test` completed in event 1. 

**How to reproduce it**:

Example Pipeline https://cd.screwdriver.cd/pipelines/4256/events/642766
Steps as per above description.

**Comment by tkyi** [comment]
Looking at the logs, it looks like `certify_tag` in event 2 gets to `getParentBuildStatus`, finds that `build_test` in event 1 is status `RUNNING` and therefore not done, and skips.

It doesn't look like we revisit the status of the parent builds that are not done yet anytime again to eventually trigger the join job. But the join job still exists and is in `CREATED` status.

My guess is some logic was changed in this refactor PR (https://github.com/screwdriver-cd/screwdriver/pull/2374) around these lines (https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/builds/index.js#L1058) that has caused this bug.

**Comment by jithine** [comment]
Seeing this in beta for https://beta.cd.screwdriver.cd/pipelines/10213/events/84316?jobId=

```{"level":"error","message":"Error in triggerNextJobInSamePipeline:join_job from pipeline:10212-internal_fork2-event:84314  content.toJSON is not a function","stack":"TypeError: content.toJSON is not a function\n    at decodeFromDialect (/usr/src/app/node_modules/screwdriver-datastore-sequelize/index.js:26:35)\n    at /usr/src/app/node_modules/screwdriver-datastore-sequelize/index.js:631:31\n    at Array.map (<anonymous>)\n    at /usr/src/app/node_modules/screwdriver-datastore-sequelize/index.js:631:22\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async getFinishedBuilds (/usr/src/app/node_modules/screwdriver-api/plugins/builds/index.js:414:20)\n    at async triggerNextJobInSamePipeline (/usr/src/app/node_modules/screwdriver-api/plugins/builds/index.js:831:46)\n    at async /usr/src/app/node_modules/screwdriver-api/plugins/builds/index.js:1056:33\n    at async handler (/usr/src/app/node_modules/screwdriver-api/plugins/builds/update.js:257:17)\n    at async exports.Manager.execute (/usr/src/app/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at async Object.internals.handler (/usr/src/app/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at async exports.execute (/usr/src/app/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at async Request._lifecycle (/usr/src/app/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at async Request._execute (/usr/src/app/node_modules/@hapi/hapi/lib/request.js:281:9)","timestamp":"2022-01-13T22:35:37.089Z"}
220113/223550.631, (1642113350443:sdapi-beta-55d7ff9564-fbvqk:18:kyapm0rm:30993) [request,webhook,28345598-74c1-11ec-9704-653ab1b9b7e4] data: Skipping since Pipeline git@github.com:screwdriver-cd/screwdriver.git#debug_restart does not exist
```
