### ISSUE TITLE
/bin/jq: Read-only file system

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2529]
**What happened**:
Our users have reported that they can no longer write to `/bin/jq`

**What you expected to happen**:
The build system does not occupy areas that users frequently use. Even if the build system puts the tool in `/bin/`, the user can overwrite it.

**How to reproduce it**:
https://cd.screwdriver.cd/pipelines/7826/builds/727866/steps/echo

**Hints**:
[The binlink command](https://docs.chef.io/habitat/habitat_cli/#hab-pkg-binlink) can receive distination path with an arg or env.

**Comment by wahapo** [comment]
This bug is fixed in [screwdrivercd/launcher:v6.0.142](https://hub.docker.com/layers/screwdrivercd/launcher/v6.0.142/images/sha256-69a0936311c37ca0577437b55266066607ad1c5e98bd9aef27b8bc1e4ce01622).
