### ISSUE TITLE
Unable to access `http://172.16.20.94:900`

### ISSUE THREAD

**Issue by cystal-dot** [screwdriver-cd/screwdriver#2536]
**What happened**:
I get a 404 error when I try to access `http://172.16.20.94:9000` for authentication, I ran docker-compose pull on terminal, why can't I access it?
**What you expected to happen**:
I thought I could access the page.
**How to reproduce it**:

**Comment by jithine** [comment]
Can you provide a bit context? Is this SD in a box setup ?
