### ISSUE TITLE
AWS Integration

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2550]
**What happened**:

Screwdriver builds are executed on a Kubernetes environment.  This works well in a hosted on-prem model, where fixed compute resources are available or if a service like [AWS EKS](https://github.com/screwdriver-cd/aws-build-cluster) is used which can scale up/down based on build load. However service like EKS has an inherent cost.

Current options for building and deploying in AWS are far from ideal. We should provide a solution where users can use native AWS build tools and solutions which allow users to run builds within their AWS account.

**What you expected to happen**:
Most of these requirements are under assumption that it's a hosted Screwdriver environment where Screwdriver application and it's users are running on separate AWS accounts. For a user who is running their own Screwdriver instance in AWS will be better off following AWS EKS based build execution, since they would need a Kubernetes environment for hosting Screwdriver application. 

1. Functionality to route new builds for user’s SD Pipelines into their AWS accounts for the users using AWS-based build executor.
1. Functionality in user AWS account to listen for builds specifically for their SD Pipelines and execute it inside the user's AWS account.
1. Screwdriver should support ingress from a user AWS account who has registered to use AWS build cluster.
1. User builds can configure their AWS account resources without having to expose any IAM credentials to Screwdriver. 
1. Minimal resource footprint for launching builds inside user AWS account.

**How to reproduce it**:

**References**

1. https://github.com/screwdriver-cd/screwdriver/issues/1955

**Comment by pritamstyz4ever** [comment]
Following are the tasks:
1. Create [screwdrivercd/aws-consumer-service](https://github.com/screwdriver-cd/screwdriver/issues/2554) (consumer lambda function)
2. Create [screwdrivercd/aws-eks-cluster ](https://github.com/screwdriver-cd/screwdriver/issues/2555) (a simplified version of [aws-build-cluster)](https://github.com/screwdriver-cd/aws-build-cluster)
3. Create [screwdrivercd/executor-serverless](https://github.com/screwdriver-cd/screwdriver/issues/2556) (aws code build executor logic to be used in lambda)
4. Create [screwdrivercd/executor-eks](https://github.com/screwdriver-cd/screwdriver/issues/2557) (aws eks executor logic to be used in lambda)
5. Create [screwdrivercd/aws-integrator](https://github.com/screwdriver-cd/screwdriver/issues/2558) (terraform scripts to onboard to sd aws integration)
6. Update [screwdrivercd/screwdriver-queue-service](https://github.com/screwdriver-cd/screwdriver/issues/2559) (add config for kafka broker connection)
7. Update [screwdrivercd/launcher](https://github.com/screwdriver-cd/screwdriver/issues/1658) (update to add NO_HAB flag and make compatible with consumer svc)
8. Create [screwdrivercd/aws-kakfa-queue ](https://github.com/screwdriver-cd/screwdriver/issues/2560)(scripts to create kafka setup in sd)
9. Update [screwdrivercd/data-schema](https://github.com/screwdriver-cd/screwdriver/issues/2561) (update schema for aws integration compatibility in screwdriver.yaml)
10. Create [screwdrivercd/aws-producer-service](https://github.com/screwdriver-cd/screwdriver/issues/2562) for push messages to queue

**Comment by pritamstyz4ever** [comment]
![AWS Build Cluster - sd-aws-integration-cb](https://user-images.githubusercontent.com/4926830/135318342-2deb82ab-4443-4eb9-94d0-ccc22d1c1578.jpeg)


![AWS Build Cluster - sd-aws-integration-eks (1)](https://user-images.githubusercontent.com/4926830/135318365-97d8785d-4828-4356-9138-f7947ee04306.jpeg)
