### ISSUE TITLE
Power button on the Create Pipeline page

### ISSUE THREAD

**Issue by itleigns** [screwdriver-cd/screwdriver#2552]
**What happened**:
I feel odd with the power button on the Create Pipeline page.
<img width="995" alt="PowerButton" src="https://user-images.githubusercontent.com/22903716/132190765-9b429048-9e0e-4435-a094-31ec75285ecf.png">

**What you expected to happen**:
We want to discuss the following.
- Why we chose this icon
- The intent of this feature

We want to manage the presence of the feature with a feature flag.
**How to reproduce it**:

**Comment by adong** [comment]
The intent of this feature was to have an onboarding guide for 1st timer users. So users can follow the instruction, step by step, to create a pipeline. I agree we can have a feature flag to turn it on or off. 


cc @jazminorozco maybe we can have a different icon, what's your thought on that?

**Comment by tkyi** [comment]
Yeah maybe a question mark or info kind of symbol?
I never noticed this before but it is strange to have.
