### ISSUE TITLE
Cannot publish templates/commands without specifying minor version

### ISSUE THREAD

**Issue by itleigns** [screwdriver-cd/screwdriver#2575]
**What happened**:
If we publish a template or command without specifying a minor version, it sometimes fail. This even happens before [this PR](https://github.com/screwdriver-cd/models/pull/513) was incorporated.
**What you expected to happen**:
They are published with the appropriate minor version.
**How to reproduce it**:
Publish the command twice with the following `sd-command.yaml`, and It will fail at the second time.
```
# Namespace for the command
namespace: itleigns
# Command name itself
name: itleigns-test
# Description of the command and what it does
description: |
   Hello World example
maintainer: itleigns@gmail.com
# Major and Minor version number (patch is automatic)
version: 0
# Format the command is in (see below for examples)
# Valid options: habitat, docker, binary
format: binary
binary:
    file: ./hello.sh
```

**Comment by jithine** [comment]
Closing this. Please re-open if issue still persists
