### ISSUE TITLE
Disabled jobs still trigger from GitHub PRs

### ISSUE THREAD

**Issue by ec-mark** [screwdriver-cd/screwdriver#2591]
**What happened**:
I have a disabled Screwdriver job that still triggers when I open a PR. The job has actually been disabled for three weeks.

**What you expected to happen**:
I expect the job to not execute until being re-enabled.

**How to reproduce it**:
Not sure... Disable a job, and see that it's still triggered through a PR.

**Comment by jithine** [comment]
Let's close this one and consolidate in #2704
