### ISSUE TITLE
Please add a stacked Screwdriver logo to the CDF landscape

### ISSUE THREAD

**Issue by MarckK** [screwdriver-cd/screwdriver#2592]
**What happened**:
We want the Screwdriver logo to look its best on the [CDF landscape](https://landscape.cd.foundation/) -- and stacked logos display best!

**What you expected to happen**:
To see a stacked Screwdriver logo -- similar to all the other CDF projects on the landscape.

**How to reproduce it**:
Check out [CDF landscape](https://landscape.cd.foundation/)

**How to fix it**:
Please add by PR an SVG of the official screwdriver logo that is stacked (with the image on top of the project name - Screwdriver) to the `hosted_logos` directory of the [CDF landscape repo](https://github.com/cdfoundation/cdf-landscape).
The current logo SVG is listed as screwdriver.svg - please use that same name to replace the logo with a new stacked one.

Thank you!

**Comment by jithine** [comment]
@MarckK I've send a PR to use vertical logo https://github.com/cdfoundation/cdf-landscape/pull/189

**Comment by jithine** [comment]
It's updated https://landscape.cd.foundation/

**Comment by MarckK** [comment]
Thank you, Jithin! Looks great on the landscape! :)
