### ISSUE TITLE
RemoteJoin does not join properly when started from an external pipeline

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2620]
**What happened**:
Currently, RemoteJoin only work properly if they come back through the external pipeline.
<img src="https://user-images.githubusercontent.com/24538326/146712037-931308a0-d22f-4ca7-b058-c658041a7918.png" width="400px" />

RemoteJoin does not work properly when it is started from an external pipeline.
<img src="https://user-images.githubusercontent.com/24538326/146712010-b3f1728b-472a-4fc8-bc25-2377906f583a.png" width="400px" />

**What you expected to happen**:
I would like RemoteJoin to work properly even when started from an external pipeline.
<img src="https://user-images.githubusercontent.com/24538326/146712044-44acccad-8df9-4776-8ad6-efb8a93c27f1.png" width="250px" />

**How to reproduce it**:
https://cd.screwdriver.cd/pipelines/8232/events/661670

**Comment by jithine** [comment]
There was a bug around remote join, which was reverted last week. Not sure if this is the same issue. cc @tkyi

**Comment by wahapo** [comment]
It appears to be a different issue. I ran it earlier and it still reproduces.
https://cd.screwdriver.cd/pipelines/8231/events/671054
