### ISSUE TITLE
[Feature Request] Get event creator information from metadata

### ISSUE THREAD

**Issue by ibu1224** [screwdriver-cd/screwdriver#2631]
**What happened**:
I want to get the event creator information from metadata.

There is no information about the event creator in metadata.
https://docs.screwdriver.cd/user-guide/metadata

The Screwdriver API can be used to get information about the event creator, but it involves communication and is inconvenient.

**What you expected to happen**:
I want to get it in metadata as follows:
```
$(meta get creator.name)
```

**How to reproduce it**:
This is a request, not a bug.

**Comment by tk3fftk** [comment]
Using some environment variable (like `SD_EVENT_CREATOR` or `SD_EVENT_USER`? ) should be alternative. 
GitHub Actions has `GITHUB_ACTOR` and CircleCI has `CIRCLE_USERNAME` representing the user name who triggered the  workflow/pipeline.

https://docs.github.com/en/actions/learn-github-actions/environment-variables
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

**Comment by tk3fftk** [comment]
meta seems to already have a lot of build related information. so adding to metadata is looks good.

**Comment by tkyi** [comment]
Works!
https://cd.screwdriver.cd/pipelines/9295/builds/788091/steps/meta

**Comment by jithine** [comment]
@ibu1224  `event.creator` in case of external trigger is not having correct information, it still has the pipeline admin's data. I think every other scenario it's working as expected.
