### ISSUE TITLE
[Feature Request] Checkout URL change history

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2634]
**What happened**:

If the options screen can display the change history of Checkout URL, it is convenient in the following points.
- It will be a way to confirm that it has been changed. Currently there is no way for users to recognize the changes.
- The user who sees the Option screen can confirm the intention of the change to the person who made the change.

**What you expected to happen**:

The UI can display the change history (change datetime and user) of the Checkout URL.

**Comment by tkyi** [comment]
Wonder if it would be good to have some audit log of all UI interactions eventually

**Comment by jithine** [comment]
I think this is a duplicate of https://github.com/screwdriver-cd/screwdriver/issues/2700
