### ISSUE TITLE
PR build workflowGraph is not reflected depending on build status.

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2660]
**What happened**:

Previously, it was fixed to display the complete workflow Graph even during PR. In other words, the display of workflowGraph is integrated at commit time and pr time. However, it seems that the workflow Graph at the time of PR does not reflect the build state like commit build.

Below is an image when the PR build is Running:

![スクリーンショット 2022-02-07 16 27 04](https://user-images.githubusercontent.com/32473622/152746746-dcd92a47-3627-4d5c-8804-d0c34b702d7d.png)

Below is an image when the PR build is Success:

![スクリーンショット 2022-02-07 16 27 46](https://user-images.githubusercontent.com/32473622/152746756-cbc4ec9a-a292-4f3e-9009-8b7d4919ca4d.png)

**What you expected to happen**:

The build status is reflected in the workflow Graph even during PR.

**How to reproduce it**:

Open PR and make PR build without chainPR.
(There was no problem building with chainPR.)

**Comment by jithine** [comment]
This is a known limitation with current implementation.
cc @adong
