### ISSUE TITLE
The parameters to be displayed in the UI are difficult to understand

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2662]
**What happened**:
In the UI of Screwdriver.cd, the parameters value and description are not fully explained.

`Templates`:
<img width="300" src="https://user-images.githubusercontent.com/24538326/152948616-98a74c4d-e79c-4071-9786-6b9f1041a20e.png">

`Validator`:
<img width="400" src="https://user-images.githubusercontent.com/24538326/152948667-0e197216-361e-4442-9960-3dbf12616420.png">

**What you expected to happen**:
It would be nice if the values and description were clearly visible.
<img width="200" src="https://user-images.githubusercontent.com/24538326/152950409-9235e12e-c428-4e7e-8cd7-a72374bb6814.png">

**How to reproduce it**:
See https://cd.screwdriver.cd/templates/screwdriver-examples/parameters-example

**Comment by tkyi** [comment]
Fixed thank you! 🙇‍♀️ 
<img width="893" alt="Screen Shot 2022-10-12 at 3 02 03 PM" src="https://user-images.githubusercontent.com/3230529/195456283-1f39e62c-665a-4d81-bb91-402058cdf1d6.png">
