### ISSUE TITLE
Update Node.js versions

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2683]
**What happened**:
Screwdriver.cd is using Node.js v12. It will be EOL in 2022-04-30.
We should use LTS Node.js versions v14 or v16.

**What you expected to happen**:
Screwdriver.cd uses Node.js versions v14 or v16.

**How to reproduce it**:

**Comment by tk3fftk** [comment]
[note] After Node.js 15, `UnhandledPromiseRejection` throws an error.
https://developer.ibm.com/blogs/nodejs-15-release-blog/
