### ISSUE TITLE
[Feature Request] sd-local for arm64 architecture(M1 Mac)

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2692]
**What happened**:
Currently, sd-local provides linux_amd64 and darwin_amd64 binaries.
However, M1 Mac uses arm64 architecture.
We should better to provide arm64 sd-local binary for M1 Mac.

**What you expected to happen**:
sd-local also provides arm64 binary.

**Comment by jithine** [comment]
we did that for meta-cli @pritamstyz4ever will take care of remaining go binaries.
