### ISSUE TITLE
Unable to login to screwdriver CI through github

### ISSUE THREAD

**Issue by odidev** [screwdriver-cd/screwdriver#2703]
I'm trying to run a screwdriver.yml file from a forked repository but while trying to log in https://cd.screwdriver.cd/login with github it gives an access denied message: `{"statusCode":403,"error":"Forbidden","message":"User github:odidev is not allowed access"}`

Could you please suggest how can I use the Screwdriver CI to run the screwdriver.yml file?

**Comment by tk3fftk** [comment]
@odidev 
https://cd.screwdriver.cd has whitelist to access as a user. You can access as a guest user through `Sign in with Guest Access` .
You can run Screwdriver.cd locally with https://github.com/screwdriver-cd/in-a-box . 

Or, please ask admins to use `cd.screwdriver.cd` in http://slack.screwdriver.cd/

**Comment by jithine** [comment]
We don't provide general build service, https://cd.screwdriver.cd/ is for running only Screwdriver related projects
