### ISSUE TITLE
[Feature Request] Use self-hosted SonarQube server

### ISSUE THREAD

**Issue by y-oksaku** [screwdriver-cd/screwdriver#2709]
**What happened**:

When users have secret source code in a private repository and the default SonarQube server is public (not support a private project), then they cannot use the SonarQube plugin in secure.
So, users would like to choose whether the SonarQube server is the cluster default or self-hosted one.

**What you expected to happen**:

Users can choose the SonarQube server based on what they can configure (ex. `screwdriver.yaml`).

**How to reproduce it**:

**Comment by y-oksaku** [comment]
# Proposal

It needs the URL and the admin token for the self-hosted SonarQube.
I think using environment variables is simple and easy for users.

## 1. Set the URL and the admin token to environment variable

(User side setting) Set the URL and the admin token for the self-hosted SonarQube API to environment variables `SD_SELF_SONAR_HOST`, `SD_SELF_SONAR_ADMIN_TOKEN`.
(`SD_SELF_SONAR_ADMIN_TOKEN` should be set by secrets)

## 2. Include the URL and the admin token in the request body

Include the URL and the admin token in the request to Screwdriver API.
Fix: [sd-teardown-screwdriver-coverage-bookend commands](https://github.com/screwdriver-cd/coverage-sonar/blob/master/commands.txt)

## 3. Use the URL and the admin token in Screwdriver API

Get the URL and the admin token from request payload. And use them for request to self-hosted SonarQube API.
Fix: [Screwdriver API](https://github.com/screwdriver-cd/screwdriver/tree/master/plugins/coverage)

**Comment by adong** [comment]
I have a thought For 4), 

I think we can add another section under **Option -> Pipeline Preference** to ask users to enable the private sonar host, and store the customized URL to allow users to fetch the coverage. _(CROS needs to be taken care of by the private Sonar Instance to allow the coverage information to be fetched)_, so instead of querying coverage info to the backend, we can send the query to the URL that customers predefined. 

![image](https://user-images.githubusercontent.com/15989893/171931916-9e9c13fd-9bdb-4909-b673-2e6de9040f24.png)

**Comment by kumada626** [comment]
I think that idea is good. However, other pipeline preference info are stored in the pipeline.settings. To get coverage info from SonarQube, sonar token is needed other than host URL. Tokens should not be put directly into the DB, so we need to think about how to store the customized SonarQube info.

**Comment by adong** [comment]
Kudos! This is a really useful feature for some team who wants to run their own SonarQube instance, and I felt we should have a documentation section added to [guide](https://github.com/screwdriver-cd/guide) on how-to use it.
