### ISSUE TITLE
Feature addition to collection dashboard to enhance usability

### ISSUE THREAD

**Issue by banusha2** [screwdriver-cd/screwdriver#2713]
**What happened**:
~Request for additional features to collection dashboard~

Users would like to 
1) add `last run` time on job from such pipeline on collection page and sort
2) be able to sort on the `build history` with number of failed events and jobs (if they have same number of failed events, then sort based on number of failed events)

**What you expected to happen**:
1) add the "Last Job Run" column with sorting in ascending or descending order.
2) add sorting feature based on number of failed builds

![image](https://user-images.githubusercontent.com/15989893/174337186-e15354cb-a61a-4746-b7e5-963dbd6db6e5.png)

**How to reproduce it**:

**Comment by itleigns** [comment]
`last run job` seems to show the time elapsed since the pipeline was created.

**Comment by itleigns** [comment]
There was a discussion among YJ members that the current UI makes it hard to understand what `Build History` button sorts by.

**Comment by banusha2** [comment]
> There was a discussion among YJ members that the current UI makes it hard to understand what `Build History` button sorts by.

'Build History' button sorts no.of failed, aborted builds in ascending or descending order.

**Comment by jithine** [comment]
I think we need to move the Status column to the left of Build history (since both are related) and move the sorting interaction to the status column.
