### ISSUE TITLE
PR build cannot be run from the UI after adding a new job with PR using the chainPR

### ISSUE THREAD

**Issue by ibu1224** [screwdriver-cd/screwdriver#2720]
**What happened**:
Using chainPR, add a new job in PR.

The build started correctly from the GitHub hook, but when I press the Start button from the UI, the API returns a 500 error and shows Validation Error.
<img width="764" alt="スクリーンショット 2022-06-17 14 50 16" src="https://user-images.githubusercontent.com/17828065/174233767-38709d8e-8350-4c8c-9d3d-0a7ce856eb9c.png">
<img width="1424" alt="スクリーンショット 2022-06-17 14 50 39" src="https://user-images.githubusercontent.com/17828065/174233791-60a1d771-73db-4a5f-bd22-284421ad5bae.png">

I don't know why, but opening/closing the PR and sending the hook again fails.

**What you expected to happen**:
PR build can be successfully run from the UI

**How to reproduce it**:
Reproducible pipeline and its PR
https://cd.screwdriver.cd/pipelines/7040/pulls
https://github.com/ibu1224/sd-sample/pull/3

**Comment by itleigns** [comment]
@sagar1312
Currently, when a new PR event is created, all jobs without `parentJobId` corresponding to other PRs become archived.

**Example**:
- Prepare a pipeline with only job `main`
- Create a pull request number 1 which adds job `main-2`
- Create a pull request number 2
- We find `PR-1:main-2` is archived

**Comment by itleigns** [comment]
[This function](https://github.com/screwdriver-cd/models/blob/72e18f52dcc23e22de4e4df3285876e91e723479/lib/pipeline.js#L1382) gets not only non pull request jobs but also pull request jobs without `parentJobId`.
