### ISSUE TITLE
SD_PARENT_BUILD_ID is not always accurate

### ISSUE THREAD

**Issue by DekusDenial** [screwdriver-cd/screwdriver#2725]
**What happened**:
The environment variable `SD_PARENT_BUILD_ID` created at the beginning of a build is sometimes missing parent build ID if the build itself has multiple joined parents

**What you expected to happen**:
`SD_PARENT_BUILD_ID` must be accurate and include all parent build IDs

**How to reproduce it**:
Not all the times, but if you have two parent builds completed closely following one another, the next build may be missing the build ID for the parent which completed last.

**Comment by jithine** [comment]
Should we fixed with the linked pR
