### ISSUE TITLE
Make it so all PRs can be started from UI, even if submitted by non writer

### ISSUE THREAD

**Issue by awick** [screwdriver-cd/screwdriver#2735]
In the opensource world it is common to get PRs from people who don't have write access and we use `screwdriver.cd/restrictPR: fork` so the pipeline doesn't run. We want a way that we can click a button after reviewing the code (to make sure they didn't mess with screwdriver.yml) so we can run the PR build which will run our test suite.

If there is another way to do this please let me know

This is maybe a simpler version of #2221

**Comment by hk-vmg** [comment]
Do you mean in the Github UI, or the Screwdriver UI? For the Github UI, is this like #2297 ?

**Comment by adong** [comment]
We have implemented and added a start button to PR jobs in the UI.
@awick can you verify if your issue is resolved?
