### ISSUE TITLE
Pull Request Sync button shows unrelated PRs

### ISSUE THREAD

**Issue by ibu1224** [screwdriver-cd/screwdriver#2740]
**What happened**:

From the pipeline options page, pressing the Pull request Sync button showed a PR to another branch in the same repository.

**What you expected to happen**:
PRs to branches not specified in base branch or branch specific should not be shown.

**How to reproduce it**:
1. create a pipeline with builds starting with ~pr, (branch is main at this time)
2. create a different branch (dummy) from the main branch and create a PR for that branch
3. click the Pull Request Sync button on the options page of the pipeline created in step 1 to show the PR workflow graph.

The following links are the reproduced repositories and pipelines.
repo: https://github.com/ibu1224/sync-pr-test
pipeline: https://cd.screwdriver.cd/pipelines/10070/pulls

**Comment by minghay** [comment]
This is still an issue
