### ISSUE TITLE
Unnecessary periodic jobs sometimes keep running

### ISSUE THREAD

**Issue by itleigns** [screwdriver-cd/screwdriver#2743]
**What happened**:
If [stopPeriodic](https://github.com/screwdriver-cd/queue-service/blob/6a1428893cecef880fcf1269ca286d73f3d8ea36/plugins/queue/scheduler.js#L89) of queue-service fails for some reason, the periodic execution of the job that becomes archived does not stop.
**What you expected to happen**:
The latest status of the job is gotten from the DB each time a periodic run is performed and the periodic job stops if the job is already archived.
**How to reproduce it**:

**Comment by jithine** [comment]
@itleigns @y-oksaku can the change be put behind a feature flag. I think more than the change itself,  it's the removal of the `periodicBuildConfigs` is affecting a logic we had to scan for missing periodic builds. 

cc @DekusDenial

**Comment by kumada626** [comment]
I think that it is reasonable to make a feature flag for the corresponding function, because it looks to have a large impact.
For my reference, is it possible to tell me what kind of logics use periodicBuildConfigs?
