### ISSUE TITLE
artifact bookend uploads sometimes fail with store-cli error

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2755]
**What happened**:

Few builds failed at `sd-teardown-screwdriver-artifact-bookend`  with the following error

```
failed to request to store: Put "https://store.screwdriver.....com/v1/builds/.../ARTIFACTS/SD_ARTIFACT.zip": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
08:33:00 2022/07/28 15:33:00 (Try 1 of 3) error received from PUT https://store.screwdriver.....com/v1/builds/../ARTIFACTS/SD_ARTIFACT.zip: Put "https://store.screwdriver.....com/v1/builds/.../ARTIFACTS/SD_ARTIFACT.zip": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
```

Retry also fails, however we notice from that Screwdriver Store API logs that the request has indeed succeeded in first attempt. 
**What you expected to happen**:

Above error should not have happened based on server logs. Client store-cli needs to handle this properly. `store-cli` has not been built in a long time, and it uses a custom retry logic instead of relying on a library like `retryablehttp`

**How to reproduce it**:

**Comment by adong** [comment]
```context deadline exceeded (Client.Timeout exceeded while awaiting headers)``` is a golang error

If someone decides to take a look: 

https://github.com/screwdriver-cd/store-cli/blob/2315bef2ea06f0f2daa383dc0d61786f1bd79a87/sdstore/sdstore.go#L37
