### ISSUE TITLE
Add Screwdriver logos to CDF logos table

### ISSUE THREAD

**Issue by MarckK** [screwdriver-cd/screwdriver#2761]
Hi,

Please add Screwdriver logos to the [CDF logos table](https://github.com/cdfoundation/artwork#cdf-logos).

Having them there helps others quickly see and use the correct logos. 

Thank you!

**Comment by tkyi** [comment]
@MarckK MarckK Created a pull request!

**Comment by jithine** [comment]
Closing this based on above PR
