### ISSUE TITLE
Collections issues

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2765]
- [x]  `Last Run Job` column's data is incorrect. Also build history seems wrong. 
- [x]  Display full name instead of truncating pipeline name
- [x]  Search results displayed when adding multiple pipelines to a collection from Collection page does not display branch and source path info. UX should be similar to search results page. 
- [x]  Support sorting on all columns 
- [x]  Clarify what does sorting on `build history` mean. Let's add a tool tip which says `sort on number of failed builds`
- [x]  Adding pipelines to a collections from different browser tabs is overwriting collection data. 
- [x]  Cannot reset pipeline's `aliasName` (Alan checked, API issue)
- [x]  Once any pipeline's aliasName is set in a collection, that collection shows pipline's aliasName for all pipeline, which isn't ideal.
- [x] handle user type long alias name for pipeline, like `this is a loonnnnng long longggggg alias name`

**Comment by banusha2** [comment]
@jithine `Cannot reset pipeline's aliasName ` is already fixed. Could you please test it again?
API fix PR: https://github.com/screwdriver-cd/data-schema/pull/501
If there is still some issue, let me know.

**Comment by tkyi** [comment]
I don't think sorting on status is working as expected
<img width="222" alt="Screen Shot 2022-11-02 at 11 50 20 AM" src="https://user-images.githubusercontent.com/3230529/199576686-09936d00-5725-4c5d-a350-828d670441dd.png">

**Comment by tkyi** [comment]
Sorting on last run looks like it's sorting by month vs year/date
<img width="143" alt="Screen Shot 2022-11-02 at 11 52 35 AM" src="https://user-images.githubusercontent.com/3230529/199577008-e0522f7d-e278-43c5-bdfa-25e7ed40fbc4.png">
