### ISSUE TITLE
[Defect] Not Able to Go to Build Details Sometimes

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#2770]
**What happened**:

A pipeline is running, and I'm watching jobs finish and trigger later jobs. When I click on the now-running job, "Go to build details" is not listed on the dropdown:

<img width="170" alt="image" src="https://user-images.githubusercontent.com/64489/190698394-a7b14ec7-e5c5-49e8-bd36-30f94743bcc1.png">

**What you expected to happen**:

I expected to see "Go to build details" on any running job

**How to reproduce it**:

Create a pipeline of serial jobs that take a while. When one finishes and a new one starts, click on the new job.

**Comment by tkyi** [comment]
I've also run into this problem and it fixes itself after refreshing, but the user shouldn't have to manually refresh as the build is progressing. Seems like the UI doesn't refresh often enough.
