### ISSUE TITLE
Unable to see display name on Build Details or Options, and unable to see "real" name on Overview 

### ISSUE THREAD

**Issue by hk-vmg** [screwdriver-cd/screwdriver#2773]
**What happened**:
I am trying to find a specific build of a specific job in a large pipeline. However, on the main Overview page I can only see `screwdriver.cd/displayName` names, and on the job-specific view I can only see "real" names, so it's not possible to easily cross-reference.

**What you expected to happen**:
All UI views should be consistent about which name is used for a job.

**How to reproduce it**:

**Comment by adong** [comment]
[screwdriver.cd/displayName](http://screwdriver.cd/displayName) is an annotation on https://docs.screwdriver.cd/user-guide/configuration/annotations to create an alias name for the job, so say, jobTest can be displayed as `job_functional_test`

I think the ask is to display the jobName's `alias` on the job list view if it exists, so maybe we can do something similar as the alias feature on this PR https://github.com/screwdriver-cd/ui/pull/815

**Comment by adong** [comment]
screwdriver.yaml 
https://github.com/adong/annotation-displayName/blob/main/screwdriver.yaml#L14-L20

[`displayName`](https://docs.screwdriver.cd/user-guide/configuration/annotations) works on workflow-graph view:
![image](https://user-images.githubusercontent.com/15989893/225718436-63093aff-e96e-4be7-a05c-a7a41e18fbb9.png)

While it does not work expectedly on the job-list view, see

![image](https://user-images.githubusercontent.com/15989893/225718405-4ab95b5d-ef28-42ac-ba4b-53741954880f.png)

Should have been:
![image](https://user-images.githubusercontent.com/15989893/225718713-677bb675-05cb-4679-be24-6ae3485b2486.png)
