### ISSUE TITLE
Invitation of thelinuxfoundation to GitHub Screwdriver org

### ISSUE THREAD

**Issue by fdegir** [screwdriver-cd/screwdriver#2783]
In order for CD Foundation to support the project properly and make insights available for the project on LFX, the user thelinuxfoundation must be invited to the GitHub Screwdriver Organization.

Please invite the user thelinuxfoundation as an owner at the organization level (not per repository) to the GitHub organization.

**Comment by jithine** [comment]
@fdegir is this a standard practice to add `thelinuxfoundation` as an owner? Something called out in docs ?

**Comment by fdegir** [comment]
@jithine Yes, adding `thelinuxfoundation` as an owner to project organizations is the standard procedure. This is part of the project onboarding as documented [here](https://github.com/cdfoundation/toc/blob/e5f5ef6ae0e82fd418a584f0e7d228f0518a7503/process/new_project_onboarding.md#technical--infrastructure).

For some reason, this was missed during onboarding of a few projects such as [Jenkins X](https://github.com/jenkins-x/jx-community/issues/37), [Ortelius](https://github.com/ortelius/ortelius/issues/536), and Screwdriver as documented on this issue and we are trying to fix on those. This will help us with LFX Insights and so on.

**Comment by jithine** [comment]
Send invitation as owner.

**Comment by fdegir** [comment]
Thanks @jithine. LFX can access the Screwdriver GitHub Organization now.
