### ISSUE TITLE
The working of screwdriver.cd/jobDisabledByDefault

### ISSUE THREAD

**Issue by ibu1224** [screwdriver-cd/screwdriver#2817]
**What happened**:
If screwdriver.cd/jobDisabledByDefault is set for a job and the job is enabled from the options page, PR builds will not start.
On the UI, it appears that the build has started, but sd-setup-init is not actually executed.

<img width="333" alt="スクリーンショット 2023-01-17 15 43 41" src="https://user-images.githubusercontent.com/17828065/212828350-010b8655-434e-41db-ba70-92db2268478c.png">

**What you expected to happen**:
It is necessary to discuss whether this case can be executed or not and what should be done as an OSS specification, such as outputting a message when it occurs.

**How to reproduce it**:
1. Create a pipeline using screwdriver.cd/jobDisabledByDefault
2. Enable jobs disabled by default from the pipeline's option page
3. Create a PR build

Reproduced repositories and pipelines
- https://github.com/ibu1224/jobDisabledByDefault_test
- https://cd.screwdriver.cd/pipelines/10861/pulls

**Comment by tkyi** [comment]
Originally, there was a problem where people from different teams would copy-paste screwdriver.yamls that had periodic builds that run on specific team-owned machines. We added [this annotation](https://github.com/screwdriver-cd/guide/pull/540#issue-1263687521) to prevent that. Based off that reason, I think:

- When a job disabled by default is not enabled, the PR job cannot run. We should show a message in the UI to alert the user that some PR jobs are disabled. And the icon should not show as running.
- When a job disabled by default is enabled, the PR job can run (as usual).

What do you think?

**Comment by jithine** [comment]
I like @tkyi proposal, we also have few items in backlog to display better errors/notifications

https://github.com/screwdriver-cd/screwdriver/issues/2749
https://github.com/screwdriver-cd/screwdriver/issues/2347
