### ISSUE TITLE
[Nominations Open] Top CDF Contributor Award 2023 🏆

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2834]
This issue is to receive nominations for the Top CDF Contributor Award 2023 for Screwdriver project.

This award recognizes excellence of technical contributions to the CDF and its projects. This individual commits key pieces to projects and, more importantly, contributes in a way that benefits the project neutrally as a whole.

To nominate someone, reply to this issue with the following:

1. Full name of the person you’re nominating
1. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

**Nomination Deadline:** Friday, March 3, 2023

**Please note**: Last year's winner, Tiffany Kyi, cannot win the award for Top Contributor again this year.

More details are [available here](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md).

**Comment by adong** [comment]
1) I want to nominate https://github.com/yk634 from YJ
2) For his Ember upgrade work https://github.com/screwdriver-cd/ui/pull/844, which is a great lift to keep screwdriver UI's framework to stay on the latest, and keeps the security concerns low.

**Comment by kumada626** [comment]
1. Yoshika Shota https://github.com/s-yoshika
2. He played a central role in the implementing [artifact-unzip-service](https://github.com/screwdriver-cd/screwdriver/issues/1500), which made some of Screwdriver's functions microservices and broke away from dependence on external services (AWS Lambda).
