### ISSUE TITLE
Display corruption due to Ember@4 Upgrade

### ISSUE THREAD

**Issue by ibu1224** [screwdriver-cd/screwdriver#2838]
**What happened**:

The following PR has updated the version of Ember.
https://github.com/screwdriver-cd/ui/pull/844

There are several areas that need to be fixed.
I will consolidate the fixes into this Issue.

**Comment by ibu1224** [comment]
https://github.com/screwdriver-cd/ui/pull/844#issuecomment-1439029744

**Comment by adong** [comment]
On Build Details Page, the banner is offset a little bit, and _restart_ button not aligned to the right

![image](https://user-images.githubusercontent.com/15989893/223283324-998bfc0a-1200-48f0-80be-d0e217a13e5f.png)

**Comment by yk634** [comment]
In the Templates & Commands page, the sort icon does not appear in the table column.

The `ember-models-table` needs to be modified and a PR has been created and merged.
https://github.com/onechiporenko/ember-models-table/pull/532

We need to wait for a version with this change to be published and modify `screwdriver/ui` so that the sort icon appears.

**Comment by ibu1224** [comment]
Build results from previous commits in the same PR can no longer be selected from the UI.
![スクリーンショット 2023-03-09 8 57 34](https://user-images.githubusercontent.com/17828065/223880197-faa1662a-b0a2-4b79-ac99-b96bb1d3bc8a.png)

**Comment by jithine** [comment]
another issue https://github.com/screwdriver-cd/screwdriver/issues/2846

**Comment by jithine** [comment]
We've noticed few more issues, thanks to @DekusDenial 

1.  if u start a build you need to refresh the page to see the new build in action
2. page seems to be more elongated than before
3. loading message is all the way touching the top edge of the menu with no padding
4. “last successful” tab is broken, and active state seems weird as well 
5. on options page, the buttons on the right not really visually aligned, and some have hover state some don’t

**Comment by ibu1224** [comment]
@jithine 
I am working on this problem.
Please give me more details about the following problem with images etc.

> 2. page seems to be more elongated than before
> 3. on options page, the buttons on the right not really visually aligned, and some have hover state some don't

**Comment by ibu1224** [comment]
@jithine @DekusDenial
I am working on this problem.
Please give me more details about the following problem with images etc.

> 2. page seems to be more elongated than before
> 3. on options page, the buttons on the right not really visually aligned, and some have hover state some don't

**Comment by jithine** [comment]
@ibu1224 
2. Click on the start button on any pipeline, observe the loading dialogue which appears briefly. It's not centrally aligned like before. 
3. Options page perhaps we can park for now, and work as part of https://github.com/screwdriver-cd/screwdriver/issues/2792

**Comment by y-oksaku** [comment]
@jithine 
I have created a [PR](https://github.com/screwdriver-cd/ui/pull/925) that fixes some of the issues here.
Please explain the following issues more detail, using images and so on.

> - page seems to be more elongated than before
> - “last successful” tab is broken, and active state seems weird as well

**Comment by jithine** [comment]
@y-oksaku thank you for the fixes. Looks great. 

> “last successful” tab is broken, and active state seems weird as well

I think the `last successful` tab is working as expected. But the active state looks like it has a button select hover when clicking, 
<img width="263" alt="Screenshot 2023-05-11 at 12 22 21 PM" src="https://github.com/screwdriver-cd/screwdriver/assets/193126/ab4989cb-15cd-4a89-9ea4-70b98d1f2e8c">

> page seems to be more elongated than before

doesn't look like an issue to me, @adong @DekusDenial pls add more detail  if it's an issue.

**Comment by y-oksaku** [comment]
@jithine 
Thank you for this explanation. I made a PR to fix this issue!

**Comment by jithine** [comment]
@y-oksaku thanks for the propmt fix. More issues our internal users noted after we released this upgrade,. 

1. Disabling a job from workflow graph doesn't update the view without a page reload. 
<img width="305" alt="Screenshot 2023-05-16 at 8 42 44 AM" src="https://github.com/screwdriver-cd/screwdriver/assets/193126/31a7b9d3-49e3-4512-ac89-e1638017e745">

Above screen shot was just enabled, after a disable, Both didn't update the graph with proper status. Updating from options tab still works as expected.

2. Artifacts can no longer be right clicked and opened in a new tab
![image (1)](https://github.com/screwdriver-cd/screwdriver/assets/193126/e200f10a-c92e-4df8-a580-3a859a1ff01f)


3. . Direct loading on template page fails sometimes after login. Login gets stuck at `login#authenticate` page and seeing error on console

```
Error while processing route: templates.detail You must provide param `version` to `generate`. g@https://.../assets/vendor-158c7c16abae2a28dc410abad9cb075b.js:4142:23

```
