### ISSUE TITLE
[UI] artifacts display no longer deeplinks

### ISSUE THREAD

**Issue by adong** [screwdriver-cd/screwdriver#2840]
**What happened**:

Because jstree(https://github.com/ritesh83/ember-cli-jstree) is removed and basic-tree(https://github.com/dwickern/ember-basic-tree) is added. 

It causes a problem that the UI will no longer deeplink the artifacts url, such as `https://cd.screwdriver.cd/pipelines/11100/builds/850028/artifacts/artifacts/another%20directories/dog%204&abc%202.jpeg`

it will display 
```
Click a step to see logs
```

Instead of deep-linked artifacts

**What you expected to happen**:

UI should render the corresponding artifacts with given url. 

**How to reproduce it**:
Click on 
https://cd.screwdriver.cd/pipelines/11100/builds/850028/artifacts/artifacts/another%20directories/dog%204&abc%202.jpeg

will show the same as (which shouldn't)

https://cd.screwdriver.cd/pipelines/11100/builds/850028/artifacts/

**Comment by yk634** [comment]
As stated in the Objective of the PR, this is a known problem.
https://github.com/screwdriver-cd/ui/pull/844#issue-1415952386

We are in the process of fixing it.
