### ISSUE TITLE
[UI] artifacts deeplink does not expand directories open recursively

### ISSUE THREAD

**Issue by adong** [screwdriver-cd/screwdriver#2842]
**What happened**:
1) Visit https://cd.screwdriver.cd/pipelines/11100/builds/850028/artifacts/artifacts/another%20directories/dog%203&abc.jpeg
2) The directories from the path params are not expanded recursively
![image](https://user-images.githubusercontent.com/15989893/224154131-6ada4514-c639-4e9a-a14d-522add0afc99.png)

**What you expected to happen**:
1) If the query params are valid and exist in the `artifacts/`, then UI should recursively open and highlight the correct file
![image](https://user-images.githubusercontent.com/15989893/224155232-fc983a8e-717c-46a9-aa23-f57340b29238.png)

2) If they are not valid, show the default artifacts view

**How to reproduce it**:
Visit https://cd.screwdriver.cd/pipelines/11100/builds/850028/artifacts/artifacts/another%20directories/dog%203&abc.jpeg

**Comment by jithine** [comment]
related to https://github.com/screwdriver-cd/screwdriver/issues/2838
