### ISSUE TITLE
[UI] url does not update when click on directory icon under artifacts

### ISSUE THREAD

**Issue by adong** [screwdriver-cd/screwdriver#2844]
**What happened**:
Related to https://github.com/screwdriver-cd/screwdriver/issues/2842

1) The url does not update when I cannot click on the artifacts' directory

2) The url with directory link, artifact does not expand if the directory

![image](https://user-images.githubusercontent.com/15989893/226990342-a3f88be5-7024-46f1-bdc0-86319124df3f.png)

**What you expected to happen**:
Would expect the old behavior that can deep-link an artifacts directory

**How to reproduce it**:
https://cd.screwdriver.cd/pipelines/11100/builds/850045/artifacts

**Comment by sumitshinde-84** [comment]
I would like to work on this issue , can you please assign it to me?
