### ISSUE TITLE
[UI] Event tab keeps events from previous pipeline.

### ISSUE THREAD

**Issue by adong** [screwdriver-cd/screwdriver#2846]
**What happened**:
The `event tab` keeps events from the previous pipeline.

See the animated video: https://user-images.githubusercontent.com/15989893/227046233-33f79b7d-dcd0-4635-a1be-e7bd50694a54.mp4

**What you expected to happen**:
Go from pipeline to pipeline should not have the event data preserved in the event tab page

**How to reproduce it**:

Reproduce steps:

1) Go to https://cd.screwdriver.cd/pipelines/7

2) Search `sonar`

3) Click the 2nd to the last one, as shown in the screenshot:
![image](https://user-images.githubusercontent.com/15989893/227045948-66891836-c8a2-478a-8187-11addf7e2f25.png)

4) The event tab shows more events than current pipeline has (by preserving the events from previous  visited pipeline)

![image](https://user-images.githubusercontent.com/15989893/227046371-e77d6e5f-afeb-4cab-bdfb-88aff0d57892.png)

However, if you go to https://cd.screwdriver.cd/pipelines/777/events directly, you will see it only has fewer events, see screenshot:

![image](https://user-images.githubusercontent.com/15989893/227046119-05080510-898b-45bf-a96d-f63f32b616e5.png)

**Comment by jithine** [comment]
It's not just on search, any navigation to a new pipeline doesn't update the events list from previous pipeline
