### ISSUE TITLE
[Question] How to modify pipeline owner?

### ISSUE THREAD

**Issue by kwontaeheon** [screwdriver-cd/screwdriver#2851]
**What happened**:
I made a pipeline on screwdriver UI and want to add other people to the pipeline owner.
But I can't find any UI that changes pipeline owner.
Is there any other option to do this?

**What you expected to happen**:
changing(modify) owner of pipeline on screwdriver UI.

**How to reproduce it**:

**Comment by tanoda** [comment]
https://docs.screwdriver.cd/user-guide/authentication-authorization
The screwdriver hasn't owner concept, bu it utilizes SCM permission.
