### ISSUE TITLE
Pipeline navigation tabs do not work when Pull Requests tab is selected

### ISSUE THREAD

**Issue by yk634** [screwdriver-cd/screwdriver#2857]
**What happened**:

When Events tab is selected:
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/59165943/230589140-ef66a3fd-e282-48b7-a34c-c8a150062ea3.png">

When Pull Requests tab is selected:
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/59165943/230589322-2d3a95ac-3241-4561-a9eb-bc0a9d88f419.png">

**What you expected to happen**:

The Pipeline Navigator tab is also displayed correctly when selecting the Pull Requests tab.

**Comment by y-oksaku** [comment]
The navigation tab's state is controlled by [BsNav](https://www.ember-bootstrap.com/api/classes/Components.Nav.html).
So if we set active to `Builds` tab when PR build selected, we should remake navigation tabs without BsNav.
Alternatively, we can add `PR` tab into navigation tab.

https://github.com/screwdriver-cd/ui/blob/34e5f024f387bffa93a925c93cf8913f9bf0ef88/app/components/pipeline-nav/template.hbs#L15
