### ISSUE TITLE
Template detail view enhancements

### ISSUE THREAD

**Issue by sagar1312** [screwdriver-cd/screwdriver#2862]
**What happened**:
Template detail view in the UI have below limitations

1. Cannot delete a specific version of the template
2. Unable to get overall usage metrics for a template across all the versions
3. Unable to know how many pipelines are currently using the template
4. Unable to view usage metrics for a particular date/time range

**What you expected to happen**:

- [x] 1. Ability to filter template usage metrics for selected date range (last X months). Set default range to last **1 year**.
- [ ] 2. New metric (`Pipelines`) to show how many distinct pipelines are using the template
- [x] 3. Aggregated usage metrics (`Pipelines`, `Jobs` and `Builds`) across all the versions
- [x] 4. Usage metrics for all the individual versions
- [x] 5. Move trust status button position
- [x] 6. Date when the selected version was published
- [x] 7. Ability to deleted a specific version of the template

**How to reproduce it**:
N/A

**Comment by itleigns** [comment]
Hi, I would like to report a bug and ask a question as YJ member.

First, in my environment, the second newest template does not have the `latest` tag after the template with the `latest` tag is deleted from the UI, which seems not to match the description in the [PR](https://github.com/screwdriver-cd/screwdriver/pull/2863).

Secondly, deleting a template by version can only be performed by the Screwdriver administrator. Is that as expected? If so, shouldn't the ACTIONS tab be invisible to the standard user?

Lastly, It is easier to see if a template is `Trusted` or not by version. However, only the latest version can be changed from the UI. Also, when filtering by `Trusted` in the template list page, only the latest version is checked, and if the latest version is deleted, the result can change. We would like to rethink these specifications.

**Comment by jithine** [comment]
@sagar1312 ^^

**Comment by sagar1312** [comment]
>First, in my environment, the second newest template does not have the latest tag after the template with the latest tag is deleted from the UI, which seems not to match the description in the https://github.com/screwdriver-cd/screwdriver/pull/2863.

When version is deleted, we delete all the tags associated it. Template owner needs make a decision to create/update tags (including `latest`) if needed to point to other versions available.
For Ex: if a version with `stable` tag is deleted, Screwdriver cannot make a decision on which available version can be marked as `stable`. We are extending the same treatment for all the tags (including `latest`).

>Secondly, deleting a template by version can only be performed by the Screwdriver administrator. Is that as expected? If so, shouldn't the ACTIONS tab be invisible to the standard user?

It makes sense to hide the columns for non Screwdriver administrators. Will make the change.
@jithine Should we allow template owners to delete a specific version?

>Lastly, It is easier to see if a template is Trusted or not by version. However, only the latest version can be changed from the UI. Also, when filtering by Trusted in the template list page, only the latest version is checked, and if the latest version is deleted, the result can change. We would like to rethink these specifications.

I totally understand that inheriting `trusted` status from previous version may not be the right approach. Instead, it should have been maintained at a centralized place. We solved this for the new feature 'Pipeline Templates' we are currently working on.
What is the proposal here for Job templates?
Not show trusted status globally?
Allow users to change `Trusted` status for any version?

**Comment by itleigns** [comment]
@sagar1312 
> What is the proposal here for Job templates?
Not show Trusted status globally?
Allow users to change Trusted status for any version?

We discussed this in the YJ.
Ultimately, job template specifications should be managed in a centralized place to match the pipeline templates.
Until the pipeline template is completed, `Trusted` of the each version is good to be invisible and `Trusted` of the latest is treated as the `Trusted` of all versions as in the original.

**Comment by jithine** [comment]
My Thoughts.
1. Template owners & SD admins should be allowed to delete individual versions. 
2. Since trusted flag is inherited from the last trusted version, deleting the latest version shouldn't remove trusted status, since previous one would still have it. 
3. I actually like showing trusted against individual versions to convey the meaning when it got trusted in the first place.

**Comment by kumada626** [comment]
We found the performance degrade after deploy this implementation.
In our environment, it takes a long time to open the template detail page.
For example, it takes 43s to open the detail page of template that has 1592 pipelines, 11351 jobs and 206382 builds.
<img width="1507" alt="スクリーンショット 2023-10-19 16 25 39" src="https://github.com/screwdriver-cd/screwdriver/assets/8113204/ffaecaa0-1b80-41b8-adfe-d07d02baa58a">
<img width="1360" alt="スクリーンショット 2023-10-20 15 33 26" src="https://github.com/screwdriver-cd/screwdriver/assets/8113204/557b5a8a-f7dd-4226-8fae-c01ebae17d49">

**Comment by adong** [comment]
cc @sagar1312

**Comment by yakanechi** [comment]
The performance slowdown occurred when trying to retrieve the number of builds when the retrieval period is set by startTime and endTime on the template detail page.
It seems that the number of builds is obtained by executing the following query to the DB.

`SELECT templateId, COUNT(templateId) as count FROM builds as builds WHERE builds.templateId IN (***, ***, ...) AND (builds.createTime >= 'YYYY-MM-DDTHH:MM:SS' AND builds.createTime <= 'YYYY-MM-DDTHH:MM:SS') GROUP BY templateId;`

The performance slowdown in this query may be due to the fact that the data-schema indexes are not set to a createTime-only pattern.
https://github.com/screwdriver-cd/data-schema/blob/v22.9.6/models/build.js#L245-L250

**Comment by sagar1312** [comment]
> The performance slowdown occurred when trying to retrieve the number of builds when the retrieval period is set by startTime and endTime on the template detail page. It seems that the number of builds is obtained by executing the following query to the DB.
> 
> `SELECT templateId, COUNT(templateId) as count FROM builds as builds WHERE builds.templateId IN (***, ***, ...) AND (builds.createTime >= 'YYYY-MM-DDTHH:MM:SS' AND builds.createTime <= 'YYYY-MM-DDTHH:MM:SS') GROUP BY templateId;`
> 
> The performance slowdown in this query may be due to the fact that the data-schema indexes are not set to a createTime-only pattern. https://github.com/screwdriver-cd/data-schema/blob/v22.9.6/models/build.js#L245-L250

Updated index https://github.com/screwdriver-cd/data-schema/pull/541

**Comment by kumada626** [comment]
While investigating the performance issue, we found that /templates/{name}/metrics was called in two places: Metrics for each version at the bottom and builds/jobs in the header.
We thought it was inefficient to call the same endpoint twice and created a pull request to put together them into one call (https://github.com/screwdriver-cd/ui/pull/961)
After being [pointed out](https://github.com/screwdriver-cd/ui/pull/960#issuecomment-1799469421) that calling the endpoint without specifying a period may cause a large DB load, we set the default period 1 year.
However, we found that the endpoint has been called in the header "builds/jobs" without specifying a period from before. 
We are considering there are following options.:
- Calling the endpoint twice : 1 year for "Metrics for each version" and no period specifying for "builds/jobs"  (current situation)
- Changing the default for Metrics for each version to "all", put together the endpoint calls . (https://github.com/screwdriver-cd/ui/pull/960)
- Deleting build/jobs
  - This is from the time when there were no metrics for each version, may not be necessary now.

How do you think? @sagar1312 @jithine

**Comment by sagar1312** [comment]
> While investigating the performance issue, we found that /templates/{name}/metrics was called in two places: Metrics for each version at the bottom and builds/jobs in the header. We thought it was inefficient to call the same endpoint twice and created a pull request to put together them into one call ([screwdriver-cd/ui#961](https://github.com/screwdriver-cd/ui/pull/961)) After being [pointed out](https://github.com/screwdriver-cd/ui/pull/960#issuecomment-1799469421) that calling the endpoint without specifying a period may cause a large DB load, we set the default period 1 year. However, we found that the endpoint has been called in the header "builds/jobs" without specifying a period from before. We are considering there are following options.:
> 
> * Calling the endpoint twice : 1 year for "Metrics for each version" and no period specifying for "builds/jobs"  (current situation)
> * Changing the default for Metrics for each version to "all", put together the endpoint calls . ([fix(2862): Improve default display performance of template metrics ui#960](https://github.com/screwdriver-cd/ui/pull/960))
> * Deleting build/jobs
>   
>   * This is from the time when there were no metrics for each version, may not be necessary now.
> 
> How do you think? @sagar1312 @jithine

Lets us go with the first option i.e. Calling the endpoint twice : 1 year for "Metrics for each version" and no period specifying for "builds/jobs" for the header.
The request for the metrics to display in the header should be limited to the version being selected.
