### ISSUE TITLE
Relax artifacts to view SPA (Single-page application) web app, such as storybook

### ISSUE THREAD

**Issue by adong** [screwdriver-cd/screwdriver#2889]
**What happened**:
Right now, artifacts can only view standard html, and SPA web app, such as storybook is not loading properly.

**What you expected to happen**:
Need to relax the rule to be able to view it

**How to reproduce it**:
This static web app should be able to render, https://cd.screwdriver.cd/pipelines/11813/builds/868343/artifacts/storybook-static/index.html

Pipeline: https://cd.screwdriver.cd/pipelines/11813/events

**Comment by yk634** [comment]
We are considering releasing this change to our internal cluster.

What are your thoughts on the security risks, such as cross-site scripting, of allowing arbitrary javascript to be executed on the Artifacts screen?

I am not too sure, but is it necessary to add a sandbox attribute to the iframe tag or other measures?

**Comment by adong** [comment]
@yk634 
1) We still restrict users from viewing these files only inside the SD UI's iframe, not like github pages.
2) Add a `sandbox` attribute to `iframe` will block the users' javascript code from executing. 
3) Users still have serve any static files with relative path. I believe `same-origin` is still enforced, so users cannot load external javascripts. 
4) So far, we haven't seen any bad actors.

**Comment by yk634** [comment]
@adong 

Thank you for your response.

Now that I am convinced about the risk measures, I would like to make a release to the internal cluster.
