### ISSUE TITLE
API not work correctly if only use new admin settings

### ISSUE THREAD

**Issue by y-oksaku** [screwdriver-cd/screwdriver#2892]
**What happened**:

I cannot access `GET /pipelines/{id}` with API access token when the pipeline is private and the access token has only Screwdriver admin permission (NOT have repository permission).

This problem was caused by the following. I use only new admin settings, but this is not support new admin settings.

https://github.com/screwdriver-cd/screwdriver/blob/5c040c803659893d46c2f882536617d58ac846b6/plugins/banners/index.js#L26-L43

**What you expected to happen**:

Authenticate correctly when using Screwdriver admin's API tokens.

**How to reproduce it**:

**Comment by sagar1312** [comment]
In launcher, creator is declared to be map whose key and values must be of type String
`map[string]string`
https://github.com/screwdriver-cd/launcher/blob/master/screwdriver/screwdriver.go#L200

But in domain model, new attribute `id` has been added which could be either `String` or `Integer`
https://github.com/screwdriver-cd/data-schema/blob/master/core/scm.js#L8 

We should normalize the type to `String` in our schema instead of bleeding SCM specific data types.

Eventually, we also need to start storing SCM user ID in user table under a new column (of Type `Sequelize.String`) and identify the user based on SCM user ID instead of SCM username in all our workflows. Especially Screwdriver settings and token created by a user.

**Comment by adong** [comment]
Want to attach the log:

<blockquote>
2023/06/22 21:27:22 Error running launcher: Fetching Event ID 18: Parsing JSON response "{\"id\":18,\"parentEventId\":17,\"groupEventId\":17,\"causeMessage\":\"Manually started by adong\",\"commit\":{\"author\":{\"id\":15989893,\"avatar\":\"https://avatars.githubusercontent.com/u/15989893?v=4\",\"name\":\"Alan\",\"username\":\"adong\",\"url\":\"https://github.com/adong\"},\"committer\":{\"id\":15989893,\"avatar\":\"https://avatars.githubusercontent.com/u/15989893?v=4\",\"name\":\"Alan\",\"username\":\"adong\",\"url\":\"https://github.com/adong\"},\"message\":\"init\",\"url\":\"https://github.com/adong/sd-storybook-sample/commit/a073c080fdb116171361d017b85cdfd3bf44b07f\"},\"createTime\":\"2023-06-22T21:27:18.822Z\",\"creator\":{\"id\":15989893,\"avatar\":\"https://avatars.githubusercontent.com/u/15989893?v=4\",\"name\":\"Alan\",\"username\":\"adong\",\"url\":\"https://github.com/adong\"},\"meta\":{},\"pipelineId\":1,\"sha\":\"a073c080fdb116171361d017b85cdfd3bf44b07f\",\"startFrom\":\"main\",\"type\":\"pipeline\",\"workflowGraph\":{\"nodes\":[{\"name\":\"~pr\"},{\"name\":\"~commit\"},{\"name\":\"main\",\"id\":1},{\"name\":\"something\",\"id\":2}],\"edges\":[{\"src\":\"~commit\",\"dest\":\"main\"},{\"src\":\"~pr\",\"dest\":\"something\"}]},\"pr\":{}}": json: cannot unmarshal number into Go struct field Event.creator of type string
</blockquote>

See the screenshot I got from docker-desktop app:
![image](https://github.com/screwdriver-cd/screwdriver/assets/15989893/498ea347-9d9a-4009-a146-16bcc350ca9c)

**Comment by sagar1312** [comment]
We also need to make SCM user id type fix for gitlab
https://github.com/screwdriver-cd/scm-gitlab/pull/57/files#r1239773753

**Comment by adong** [comment]
Got the new error: `"id" must be a string`

API Server error:
```
230626/180346.007, (1687802623956:PPQF2LJ7NX:88284:lj8v06ak:10048) [request,server,error] data: ValidationError: "id" must be a string
```

UI: 
![image](https://github.com/screwdriver-cd/screwdriver/assets/15989893/ff600b0c-c1d9-4f57-b765-cffcacc302d6)

**Comment by y-oksaku** [comment]
@adong 

> Got the new error: `"id" must be a string`

I could not reproduce it. Could you give me more details please?

**Comment by adong** [comment]
@y-oksaku
Setup local development with screwdriver backend SHA commit version:

```
68549e68eeb2ab0715350381126fd4ca88ebbf97
```

```
rm -rf node_modules
rm package-lock.json
rm mw-data && mkdir mw-data


npm install
npm start
```

Then create a pipeline with the following git repo

```git@github.com:adong/sd-storybook-sample.git```


Run into above issue, ```ValidationError: "id" must be a string```

**Comment by adong** [comment]
False alert, I got it working by removing npm directory `~/.npm`

**Comment by adong** [comment]
The previous issue is no longer there after the latest Data schema PR got merged.
