### ISSUE TITLE
Job template enhancement - pipeline usage 

### ISSUE THREAD

**Issue by sagar1312** [screwdriver-cd/screwdriver#2911]
**What happened**:
The template detail view in the UI currently shows below metrics for each version
- how many distinct jobs have been using the template
- how many builds have been executed for jobs using the template

Template owners do not have visibility into which jobs/pipelines are using their templates.

**What you expected to happen**:
We need insight in to how many distinct pipelines have one or more jobs using the template.
Also we need a tabular view showing the details of all the pipelines  relying on specific version of a template.
This would help the template owners to analyze the usage and take necessary actions
Ex: Reach out to the pipeline owners to upgrade to more stable/latest versions and remove older versions of the template

**How to reproduce it**:
N/A

**Comment by ibu1224** [comment]
@sagar1312 @tkyi @jithine 
Is it possible to insert a load indicator while the template usage list screen is loading?

Especially for templates that are used in a large number of pipelines, it takes time to fetch the data. During this time, the page goes blank, which degrades the user experience.
<img width="1395" alt="スクリーンショット 2023-12-11 16 22 37" src="https://github.com/screwdriver-cd/screwdriver/assets/17828065/45663762-16a3-4790-a522-4af580d7f3ab">

**Comment by jithine** [comment]
@ibu1224 can you create an issue for loading ? Let's track separately fro this.
