### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#293]
> As a user, I want to pass structured data between my jobs, so that I can make informed decisions about what to deploy or test

Currently, there are almost no built-in ways to pass information between builds. The most common way is to use the value of the current Git tag.  But that data cannot be guaranteed to be correct.

Given this simple pipeline:

> main -> deploy -> promote

The `deploy` job would need to know the version of the application that was published in the `main` job, while the `promote` job would need to know the version that was tested in the `deploy` job.  This information is not available with just that git tag.

Instead, Screwdriver should provide a simple interface for reading/writing values that can be passed between builds in the same event.

Rules:
- `meta` is a command-line client (written in go) that is made available to the build container.
- Metadata should be passed from one job to the next in succession (in the same event) (see appendix A).
- When combining the results of matrix builds, they should be merge/replaced in a random order (to ensure users don't depend on a side-effect).
- When the event is done, a record of the metadata should be stored there as well.
- Metadata can contain strings, numbers, boolean, objects, and arrays.  The interface should account for this (see appendix B).
- `meta set` should not output anything, except during failures (`STDERR`).
- `meta get` should output in string representation with no newlines (see appendix C).

Stretch (gold bar):
- `meta` can read in from a file or STDIN.
- `meta get --previous` can read from the previous successful event.

---
### Preparation
- [x] Cucumber feature file
- [ ] Meta interface (discussed in this issue)
### Implementation
- [ ] Screwdriver.yaml changes
- [ ] Launcher changes
- [ ] API changes
- [ ] UI changes
- [ ] Store changes
- [ ] Schema changes
- [ ] Model changes
- [ ] Datastore changes
- [ ] Executor changes
### Outcome
- [ ] Cucumber feature passing
- [ ] Documentation

---
### A - Metadata passing

Example pipeline:

> main -> package -> deploy
#### main
- starts with:
  `{}`
- runs:
  `$ meta set coverage 99.52`
- results in:
  `{ "coverage": 99.52 }`
#### package
- starts with:
  `{ "coverage": 99.52 }`
- runs:
  `$ meta set version v3.1.2`
- results in:
  `{ "coverage": 99.52, "version": "v3.1.2" }`
#### deploy
- starts with:
  `{ "coverage": 99.52, "version": "v3.1.2" }`
- runs:
  `$ meta set url http://example.com`
- results in:
  `{ "coverage": 99.52, "url": "http://example.com", "version": "v3.1.2" }`
### B - Input Interface Suggestions

_note: the json structure below each line is just showing internal representation, not output_

``` bash
$ meta set foo true
{ "foo": true }

$ meta set foo 15.5
{ "foo": 15.5 }

$ meta set foo hello
{ "foo": "hello" }

$ meta set foo[] arrg
{ "foo": ["arrg"] }

$ meta set foo[1] zarp
{ "foo": [null,"zarp"] }

$ meta set foo.bar baz
{ "foo": { "bar": "baz" } }

# Extra cool things, but not required
$ echo "banana" | meta set foo -f -
{ "foo": "banana" }

$ meta set foo -f ./test
{ "foo": "contents of test" }
```
### C - Output Interface Suggestions

_note: the json structure above each line is just showing internal representation, not output_

``` bash
{ "foo": true }
$ meta get foo
true

{ "foo": "hello" }
$ meta get foo
hello

{ "foo": ["arrg"] }
$ meta get foo
["arrg"]

{ "foo": { "bar": "baz" } }
$ meta get foo
{"bar":"baz"}
```

**Comment by d2lam** [comment]
Hmmm this kinda concerns me: `When combining the results of matrix builds, they should be merge/replaced in a random order (to ensure users don't depend on a side-effect).`

If main is a matrix job  with FOO: [1,2]
FOO=1 sets `version` to `1.0`
FOO=2 sets `version` to `2.0`

main triggers deploy. Then inside deploy, `version` can be either `1.0` or `2.0`?

**Comment by stjohnjohnson** [comment]
Yup, it's inspired by [GoLang maps](https://blog.golang.org/go-maps-in-action#TOC_7.).  For us to pass metadata consistently between jobs, we need to have an approach that's the same regardless if you're running a matrix build or not.  The only option is merging the result.  If we don't pick a policy for this, then it will become an undocumented side-effect.  But any policy I thought of seemed hard to explain (e.g. merged based on alphabetical serialization of the sorted keys from your matrix builds).  So I thought back to the GoLang thing that @jer explained to me and it occurred to me this would be excellent for this problem.  If we enforce (and document) randomness, then users must make their own decisions about how to namespace their metadata in matrix builds such that they can retrieve it in later jobs.

**Comment by stjohnjohnson** [comment]
@catto How would you like to approach working on this?  I'm assuming you'll need a new repo for the meta go binary.  Would you like:
 - Us to create an empty repo first and then you give a PR
 - Your team makes the repo first and then we fork it
 - Another option

I created `#293-metadata` in Slack for any open discussions

**Comment by catto** [comment]
@stjohnjohnson Thanks, I'll contact you on the Slack channel

**Comment by tk3fftk** [comment]
I have a question about format of `meta get` .
The rules is defined:
> `meta get` should output in string representation with no newlines (see appendix C).

@minz1027 commented https://github.com/screwdriver-cd/launcher/pull/108#issuecomment-284044529:
> Another thing to note: if u do `/opt/sd/meta get foo` only in a step, u won't see the value of foo in log since there is no newline in the end. And we use newline as separator when parsing logs.

We need newline or not?

**Comment by minz1027** [comment]
@tk3fftk I think it should not include the newline in the value since user will probably assign the value to some variables. Just need to document it somewhere so that user won't get confused when they do `meta get` only.

**Comment by stjohnjohnson** [comment]
@tk3fftk @minz1027 it sounds like it's a bug if not outputting a newline will result in no log.  We should force a newline when we run steps (in the writing of the shell script).  But meta should not return a newline, that will allow it to work like a normal unix command.

**Comment by tk3fftk** [comment]
@minz1027 @stjohnjohnson I understood. You mean that the result is like this image when only run `meta get`. Thank you!
![2017-03-06 10 16 15](https://cloud.githubusercontent.com/assets/3445553/23593716/03310206-0256-11e7-828e-32f56a1e158b.png)

**Comment by minz1027** [comment]
@tk3fftk yes! That's what I mean.
@stjohnjohnson We have newline after sourcing the step file but when we log stuff, we always scan by looking for newlines using `scanner.Text()`. I will run some tests locally to see if that's the problem.

**Comment by stjohnjohnson** [comment]
@minz1027 also related https://github.com/screwdriver-cd/screwdriver/issues/488

**Comment by tk3fftk** [comment]
I found a problem😥   `meta` is not passed in pipeline.

To show log, I changed [these lines](https://github.com/screwdriver-cd/launcher/blob/master/launch.go#L198-L218) to `fmt` and print status of parent build (also add `Status` to Build in screwdriver.go).
In first line, log shows status of parent build `RUNNING`. The reason is that build status is not updated until end of a next build at [this line](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/builds/update.js#L124). `meta` and build status are updated in [same time](https://github.com/screwdriver-cd/launcher/blob/master/launch.go#L56). So a triggered build can not get previous `meta`.

![2017-03-08 18 49 20](https://cloud.githubusercontent.com/assets/3445553/23698811/566fcf02-0430-11e7-9197-50dc839bbe71.png)

**Comment by minz1027** [comment]
@tk3fftk good caught! can u help review the pr? 
https://github.com/screwdriver-cd/screwdriver/pull/494

**Comment by minz1027** [comment]
@tk3fftk I was writing the docs for meta-cli and found another bug for the meta-cli..

```
sh-3.2$ ./meta set foo.bar baz
sh-3.2$ ./meta get foo && echo
{"bar":"baz"}
sh-3.2$ ./meta get foo.bar && echo
null
```
The whole get argument is treated as a string key and the key 'foo.bar' maps to nothing.
https://github.com/screwdriver-cd/meta-cli/blob/master/meta.go#L43

**Comment by tk3fftk** [comment]
@minz1027 I only implemented `meta get` to satisfy these output interface suggestions. It seems to need function. I'll fix it.

**Comment by tk3fftk** [comment]
@minz1027 I fixed `meta get`. Could you review the PR?

**Comment by tkyi** [comment]
Blog post: http://blog.screwdriver.cd/post/158718077352/build-metadata
Documentation: https://docs.screwdriver.cd/user-guide/metadata
