### ISSUE TITLE
Identify sd@123:foo as as invalid requirement, share that ~sd@123:foo is correct

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#2936]
**What happened**:

I created a job that had
```
requires: [sd@123:foo]
```

when pipeline 123's foo job ran, this job did not run

**What you expected to happen**:

I expected the job to run OR Screwdriver to tell/warn me that I really wanted:
```
requires: [~sd@123:foo]
```

**How to reproduce it**:

Specify an external trigger incorrectly.

**Comment by tkyi** [comment]
should be resolved by https://github.com/screwdriver-cd/workflow-parser/pull/45
