### ISSUE TITLE
Allows special characters to be used in branches

### ISSUE THREAD

**Issue by yakanechi** [screwdriver-cd/screwdriver#2952]
**What happened**:
On GitHub, it was possible to use full-width space of Japanese in branch names, but these characters were not available in SD.

**What you expected to happen**:
Allows pipelines to be created and built with branch names that contain special characters and full-width space of Japanese.

**How to reproduce it**:
Work in the following sequence.
1. https://github.com/screwdriver-cd/data-schema/pull/542
2. https://github.com/screwdriver-cd/data-schema/pull/543
3. https://github.com/screwdriver-cd/scm-github/pull/218
4. https://github.com/screwdriver-cd/ui/pull/963

**Comment by yakanechi** [comment]
## Known Issue
These changes allow rootDirs with paths containing special characters to be used.
However, if you try to run a build using such a rootDir, the build of sd-launcher-setup will fail.

We will make corrections in the future.

**Comment by jithine** [comment]
Closing this, please re-open if there are more tasks pending.
