### ISSUE TITLE
Creating a pipeline from a non-existent repo has weird errors

### ISSUE THREAD

**Issue by jer** [screwdriver-cd/screwdriver#297]
Steps to reproduce: Create a pipeline from a valid github url that 404s

Get this message:
{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}

**Comment by d2lam** [comment]
There were many bugs that got fixed on Friday. Is this still happening?

**Comment by d2lam** [comment]
I tried and this doesn't seem to be an issue anymore.

**Comment by stjohnjohnson** [comment]
Totally still happening:
<img width="974" alt="screen shot 2016-10-23 at 10 34 03 pm" src="https://cloud.githubusercontent.com/assets/622065/19634515/bcb6aa36-9970-11e6-9094-b241a169bd7e.png">

**Comment by d2lam** [comment]
Hmm I see it now. Seems to happen to repos that are not owned by `screwdriver-cd`

**Comment by petey** [comment]
I'm 99% sure this happens when `pipeline.sync()` runs and it can't find a screwdriver.yaml.

**Comment by petey** [comment]
That error is thrown by the github module when requesting a file that doesn't exist.
During `sync` we look up screwdriver.yaml for pipeline configuration. When a screwdriver.yaml isn't found an error is thrown, and this error is not caught before the parser has a chance to give you a default config. A pipeline is already created at this point, but it is in a super weird state as it has no configuration.

**Comment by d2lam** [comment]
This is still happening. It fails at `parseUrl` and the API just catches and wrap the error. Creating PRs to fix this.

**Comment by d2lam** [comment]
Done!
<img width="1024" alt="screen shot 2016-11-02 at 10 48 08 pm" src="https://cloud.githubusercontent.com/assets/3401924/19956917/826a9bd6-a14e-11e6-8a1b-886fde086f5c.png">
