### ISSUE TITLE
The link should be visible in info message

### ISSUE THREAD

**Issue by yakanechi** [screwdriver-cd/screwdriver#2970]
**What happened**:
The link on the Info message is also sanitized and displayed as a result of sanitization with https://github.com/screwdriver-cd/ui/pull/974.
This is shown as follows when the build is blocked, for example
![スクリーンショット 2023-12-15 16 57 47](https://github.com/screwdriver-cd/screwdriver/assets/138551445/f33e88f9-02e3-4677-a2ac-f8470cffaaae)

**What you expected to happen**:
Only links should appear unsanitized.

**How to reproduce it**:
Running jobs simultaneously to generate a block

**Comment by adong** [comment]
You are correct, and I have a PR https://github.com/screwdriver-cd/ui/pull/977 to fix it.
