### ISSUE TITLE
Pipeline info on UI is not automatically updated when clicking sync button.

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2982]
**What happened**:
Even if there is an update to the pipeline information (e.g. repo name is renamed) when the sync button is clicked, the information on the UI is not updated until the page is reloaded.

**What you expected to happen**:
Pipeline info is updated without manually reload page.

**How to reproduce it**:
1. Change repo name.
2. Click sync pipeline button.
3. Pipeline name is not updated.
4. After manually reload page, pipeline name is updated.

**Comment by jithine** [comment]
Looks like this can be closed this linked PR.
