### ISSUE TITLE
[Nominations Open] Top CDF Contributor Award 2024 🏆

### ISSUE THREAD

**Issue by adong** [screwdriver-cd/screwdriver#2995]
This issue is to receive nominations for the Top CDF Contributor Award **2024** for the Screwdriver project.

This award recognizes excellence in technical contributions to the CDF and its projects. This individual commits key pieces to projects and, more importantly, contributes in a way that benefits the project neutrally as a whole.

To nominate someone, reply to this issue with the following:

1. Full name of the person you’re nominating
1. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

**Nomination Timeline:** 

* Nominations open: Monday, January 22
* Nominations close: Sunday, March 7th at 11:59 PST
* Voting opens: Thursday, February 22
* Voting closes: Friday, March 22 at 11:59 PST
* Winners announced at cdCon: April 16–18, 2024

**Please note**: Last year's winner, Yuta Kaneda, cannot win the award for Top Contributor again this year.

More details are [available here](https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md).

**Comment by zestyroxy** [comment]
I would like to nominate @adong who has been very active both in Screwdriver and the CDF for years now.

**Comment by jithine** [comment]
FYI @screwdriver-cd/yahoo-japan

**Comment by VonnyJap** [comment]
I would like to nominate Tiffany Kyi @tkyi for her active participation in not only being the code contributors, but also making sure pull requests are reviewed in timely manner.
