### ISSUE TITLE
Does we support offline screwdriver.yaml validation?

### ISSUE THREAD

**Issue by QubitPi** [screwdriver-cd/screwdriver#3006]
Hi SD team, we open this issue because we would like to validate syntax of a `screwdriver.yaml` file programmatically

We understand there is an online validator on SD UI but we would like to do the same thing in some GitHub Action CI/CD. So we digged in the source code a little bit and found programmatic validation is little bit of tricky in Screwdriver: 

While the nature of its own should be simple syntax/grammar checking, `screwdriver.yaml` validation seems to be deeply coupled with Hapi server, in particular

1. The validation happens in ["parsing phase" on server side](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/validator.js#L35-L39);
2. The parsing requires running [Hapi server instance states](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/validator.js#L32)
3. The validation also requires token

All these complexities prevent us from validating screwdriver.yaml in downstream projects' CI/CD phase in an environment without SD API server, such as GitHub Actions

Do we have a [data schema](https://github.com/screwdriver-cd/data-schema/blob/master/api/validator.js) that **statically** validates screwdriver.yaml like the below?

```javascript
require("screwdriver-data-schema").api.validator.SOME_SCHEMA_WE_ARE_LOOKING_FOR
  .validate(
    require('js-yaml').load(require("fs").readFileSync("screwdriver.yaml")
  )
```

Thanks

**Comment by jithine** [comment]
Offline validation is not quite possible since a `screwdriver.yaml` can be using many Job templates and shared commands, whose definition is provided by the API.
