### ISSUE TITLE
Support BitBucket.org

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#302]
We need to be able to swap out SCM providers.  In this case, let's swap out with bitbucket.org.

Rules:
- System can be configured for either GitHub or Bitbucket
- Interaction should remain the same

---
## Work
- [x] Users can login with their Bitbucket.org account
- [x] Pipeline can be from Bitbucket.org repository
- [x] Links on UI bring me to Bitbucket.org
- [x] Commit status is updated
- [x] Launcher can actually checkout from Bitbucket.org
- [x] Documentation for someone to switch
- [x] Proposed code is tested when a PR is opened/closed/synced on Bitbucket.org
- [x] Pipeline is started when a commit is pushed to Bitbucket.org

--- 
**Notes**: 
- Pull Request builds are not working due to our launcher's limitation. It currently only checks out from github for PRs. This issue will be addressed by https://github.com/screwdriver-cd/screwdriver/issues/312
- Basic documentation is included in [PR-315](https://github.com/screwdriver-cd/screwdriver/pull/315/files)
- More detailed documentation will be tracked by #304

**Comment by d2lam** [comment]
@stjohnjohnson  Some clarifications:
**Webhook:** is just swapping out these parts out to use parseHook
- https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/webhooks/github.js#L338-L343
- https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/webhooks/github.js#L261-L267
...

**Pull Request status:** I don't think there is anything left for this? It should be done automatically. 

**Checking out a repo and/or PR:** this should already been done by https://github.com/screwdriver-cd/launcher/pull/90/files. What else is left for this one?

**Comment by stjohnjohnson** [comment]
Sorry, it was a copy/pasta from the previous one.  Updated a bit.  You should use this as a checklist to verify all the parts are done.

**Webhook:** Yes, we should also remove/rename `github.js` and move back to `index.js`.
**PR status:** Just gotta verify it
**Checking out a repo**: Eh, that PR will only work if the scmId has two `:`s, but Bitbucket has three.

**Comment by d2lam** [comment]
@stjohnjohnson Thanks for clarifying! 
bitbucket also has two `:`s. It looks like this: `bitbucket.org:d2lam/{1234}:master`, so technically it should work.

**Comment by stjohnjohnson** [comment]
Ahh, excellent, I thought we used three `:`  I'm not sure how cloning from d2lam/{1234} is going to work though.

**Comment by d2lam** [comment]
Checkout should be fine, but for PR there will be a problem:
https://github.com/screwdriver-cd/launcher/blob/ca5d3e7cb5eaf20e373b236dc636c86bd866e5c6/git/git.go#L105-L107

**Comment by d2lam** [comment]
PR builds for bitbucket will not work for now until https://github.com/screwdriver-cd/screwdriver/issues/312 is resolved.

**Comment by stjohnjohnson** [comment]
@d2lam okay, so what items have been finished?  Can you check them off on the list please?

**Comment by stjohnjohnson** [comment]
@d2lam where is the documentation?  Are you going to do it similar to what is asked in https://github.com/screwdriver-cd/screwdriver/issues/304

**Comment by d2lam** [comment]
@stjohnjohnson  Hmmm weird I remember replying but I guess I never hit the "comment" button. What I said was:
Basic documentation is included in https://github.com/screwdriver-cd/screwdriver/pull/315/files
More detailed documentation will be included in https://github.com/screwdriver-cd/screwdriver/issues/304
