### ISSUE TITLE
Remove associated stages and the builds for the stages when a pipeline is deleted

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3025]
**What happened**:
This is a new feature to be implemented so no current situation was observed. 

**What you expected to happen**:
When a pipeline is deleted, the stages and the builds associated to the stages should be removed as well. The implementation whether to remove by deleting or archiving can be of further discussion. Thanks!

**Comment by sagar1312** [comment]
This has been implemented

**Comment by sagar1312** [comment]
This has been implemented
