### ISSUE TITLE
Allow a stage to declared as an upstream for a job outside of that stage

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3026]
**What happened**:
A stage always has two jobs that are setup like pre and post hooks, namely **_`setup`_** and **_`teardown`_**. Currently if there is a downstream job that is triggered by the completion of a stage, then that particular job has to put such settings in the screwdriver.yaml config. 
```yaml
jobA:
  requires: [~${stage}:teardown]
```

**What you expected to happen**:
Remove the requirements to explicitly mention a teardown job of a stage as the upstream job. And instead the stage name itself should be sufficient. 
```yaml
jobA:
  requires: [~${stage}]
```

**Comment by sagar1312** [comment]
This has been implemented
