### ISSUE TITLE
Options to hide PR workflow graphs should only be allowed in the Event tab

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3044]
**What happened**:
When "Show PR jobs" is toggled to hide all PRs in the Options tab
![Screenshot 2024-02-26 at 11 09 33 AM](https://github.com/screwdriver-cd/screwdriver/assets/7771180/184c327e-f71e-4c37-b147-0e4c603e640e)

the PR workflow graph is also hidden in the PR tab. 
![Screenshot 2024-02-26 at 11 10 01 AM](https://github.com/screwdriver-cd/screwdriver/assets/7771180/5c5fa75f-1b5b-4a6c-bd17-ed9f2f86d8af)

**What you expected to happen**:
The PR workflow should not be hidden in the PR tab, it should only apply the behavior on the event tab. 

**How to reproduce it**:
Toggle the "Show PR jobs" [here](https://cd.screwdriver.cd/pipelines/12/options) and check out the [PR tab]( https://cd.screwdriver.cd/pipelines/12/pulls)

**Comment by minghay** [comment]
@VonnyJap This has already been fixed in https://github.com/screwdriver-cd/ui/pull/1000
