### ISSUE TITLE
Job template info is missing from the build page

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3086]
**What happened**:

The [`first job`](https://github.com/VonnyJap/test-pr-config/blob/6f239fdbd9bb72d5fe9836857079693578e17034/screwdriver.yaml#L14-L16) is using `sd/noop@latest` template but the information now is missing from the build page. 

See screenshot below. 

<img width="1720" alt="Screenshot 2024-04-03 at 9 58 44 PM" src="https://github.com/screwdriver-cd/screwdriver/assets/7771180/2ed82e2d-85ec-4e79-a3fa-96797e533ad0">

<img width="1718" alt="Screenshot 2024-04-03 at 10 58 15 PM" src="https://github.com/screwdriver-cd/screwdriver/assets/7771180/b6b4aa3d-365d-41fc-9f86-17f0299219e1">

**What you expected to happen**:

The template info should be shown on the build page. 

**How to reproduce it**:

Please check [this build link](https://cd.screwdriver.cd/pipelines/12998/builds/934415) for example. 
Create a simple job that is using template like below and run the pipeline. 

```
shared:
  image: node:20

jobs:
  first:
    template: sd/noop@latest
    requires: [~pr, ~commit]
```

**Comment by adong** [comment]
For this issue, I can make a fix to display the job template for now.

This one needs more thought to distinguish whether is job or pipeline template.

Currently,
![image](https://github.com/screwdriver-cd/screwdriver/assets/15989893/dd69430d-107b-4f4c-8fcc-2bfd02bb804a)

There's only a `templateId: 8459`, I think we need to add a `templateType: job/pipeline` to do that.
