### ISSUE TITLE
Missing cache and subscribe from the Validator

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3114]
**What happened**:

The validate endpoint returns information on the pipeline level config like cache and subscribe but it is not shown in validator. Please see the screenshot. 

<img width="1721" alt="Screenshot 2024-05-09 at 10 07 12 PM" src="https://github.com/screwdriver-cd/screwdriver/assets/7771180/20176a8c-1814-46cf-8ea3-1884b2b3da17">

**What you expected to happen**:

The config like cache and subscribe should be shown in the validator. 

**How to reproduce it**:

I have an example of [pipeline template](https://github.com/VonnyJap/pipeline-template-example/blob/c824320f1760183d1a71d525caefd562431bb895/sd-template.yaml) that can be used to reproduce this issue on the validator, but it should also be reproducible for a user defined pipeline without a template.

**Comment by tkyi** [comment]
<img width="1624" alt="Screenshot 2024-08-05 at 4 00 21 PM" src="https://github.com/user-attachments/assets/4ecf0b49-0267-4f91-bb38-5cc0f7ea37e3">
Should be resolved
