### ISSUE TITLE
Workflow graph should be shown when validating pipeline template

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3115]
**What happened**:

Missing workflow graph when validating pipeline template

<img width="1721" alt="Screenshot 2024-05-09 at 10 19 42 PM" src="https://github.com/screwdriver-cd/screwdriver/assets/7771180/42d803fb-0397-454f-91bb-60f0742aa3ff">

**What you expected to happen**:

There should be a workflow graph displayed when validating a pipeline template.

**How to reproduce it**:
Please use [this sample template](https://github.com/VonnyJap/pipeline-template-example/blob/c824320f1760183d1a71d525caefd562431bb895/sd-template.yaml) to paste into validator.

**Comment by tkyi** [comment]
Backend part is done, changes need to made on the UI side to see the workflowGraph in the validator.
<img width="1359" alt="Screenshot 2024-07-10 at 7 00 38 PM" src="https://github.com/screwdriver-cd/screwdriver/assets/3230529/4d5f5a52-7134-47f2-86fa-f0b102d20425">
