### ISSUE TITLE
Internationalize the Docs

### ISSUE THREAD

**Issue by jer** [screwdriver-cd/screwdriver#318]
We would like to be able to support languages other than English, but it seems like mkdocs doesn't yet support this: https://github.com/mkdocs/mkdocs/issues/617

We need to figure out how to support this. Readthedocs could work, for instance: http://read-the-docs.readthedocs.io/en/latest/localization.html#localization-of-documentation

**Comment by stjohnjohnson** [comment]
Hmm, this is a great idea.  It looks like there are two options:
 - Use localization (string splitting)
 - Use readthedocs sub-projects (separate copies of the documentation)

@catto what would be best for your team?

@petey what do you think about readthedocs.org?

Also, I grabbed http://screwdriver-cd.readthedocs.io/ and http://screwdriver-cd.rtfd.io/ in case we want it.  I assume we'll also do https://guide.screwdriver.cd (or docs.).

**Comment by petey** [comment]
readthedocs is fine so long as we don't want to do anything fancy, like theming. I'm not sure if they support stuff that is dynamic, like the yaml page we have now, either.

**Comment by catto** [comment]
Actually, we haven't used any tools for localizing the documents. But updating the translated version will be heavy work if the repository or string is completely separated.
How about Sphinx+gh-pages? It supports theming and i18n by plugins. Nginx uses it for instance: https://www.nginx.com/resources/wiki/contributing/translating_docs/

Readthedocs is fine too. There is the document of trafficserver in Japanese and it seems to works well.
https://trafficserver.readthedocs.io/ja/latest/

**Comment by okuryu** [comment]
For many years, I have been [worked](https://github.com/yahoo/boomerang/commit/e6cf1e89fdb80dbd80c2484aa9cbc67bddf6211a) on [i18n](https://github.com/h5bp/html5boilerplate.com/commit/5a386a32c1ad45341e50ab92b51f43d41cc33955) docs [for](https://github.com/rwaldron/idiomatic.js/commit/121cbac5a93c60c669ea29f290d8d6d56bd8e67e) a [lot](https://github.com/Homebrew/legacy-homebrew/commit/d5ecd70607f4bce932f1d4cae8d56b4c5e9db0b6) of [projects](https://github.com/yahoo/formatjs-site/commit/d15c1fb9aeb195e9e3dbab552e413afc86e648b0) by [different](https://github.com/html5rocks/www.html5rocks.com/commit/674f4c9c035696ddc1c61eb6cf78f1c8accdde2f) processes. I think they have both pros and cons for either of these ways.

I'm currently interesting in an another approach by Locki ( ttps://locki.io/ ). Node.js community is considering this right now (see: ttps://github.com/nodejs/node/issues/8798 ). I'm not sure it's best way for i18n docs, but I think it's be worth a try experimentally. Anyway, I'm ready to help on all i18n issues by any processes.

**Comment by chikathreesix** [comment]
Hi @okuryu, I am Ryo, a creator of Locki. Thanks for getting interested in our service!
We'd love to help Screwdriver's localization so feel free to ask me any questions, requests or concerns!
Also, check out this video to get more insight on how Locki works. https://youtu.be/c21-ac_26sk

**Comment by okuryu** [comment]
@chikathreesix good eye :)

**Comment by stjohnjohnson** [comment]
@okuryu @catto @chikathreesix We added Locki to the documentation at http://docs.screwdriver.cd/ and configured it for English and Japanese.

Can you take a look and try it out?

**Comment by chikathreesix** [comment]
@stjohnjohnson Awesome!

**Comment by catto** [comment]
@stjohnjohnson I did it and it looks good for now.
http://docs.screwdriver.cd/cluster-management/
Can you see my activities in Locki project?

@chikathreesix Locki is awesome 👍 so easy to use!

**Comment by stjohnjohnson** [comment]
@catto I can!  That's awesome! 
<img width="748" alt="screen shot 2016-11-30 at 10 26 57 pm" src="https://cloud.githubusercontent.com/assets/622065/20783965/222ef456-b74c-11e6-991e-a3684c575b7d.png">


@chikathreesix Is there a way for people to offer a new language without me going to the project page and adding it?

**Comment by chikathreesix** [comment]
You can add admin members from the team setting here to allow them to add a new language.
https://locki.io/projects/113/user_roles
But we are also implementing a way to make a request for a new language from the frontend.

**Comment by catto** [comment]
@chikathreesix Is there any way to include html tags into the translated messages?
I confirmed that some of the messages include html tags like below and it isn't reflected in the translated message.
http://docs.screwdriver.cd/user-guide/api/
![image](https://cloud.githubusercontent.com/assets/1608595/20867451/ecab30ee-ba87-11e6-8ada-085afdf7cab6.png)

**Comment by chikathreesix** [comment]
@catto Thanks for pointing that out! ul and li were removed when the content is sanitized so I have added those tags to the safe tags list. I fixed the section and confirmed it's now working fine.

**Comment by catto** [comment]
@chikathreesix I also confirmed it's working fine. Thank you for your support!

**Comment by chikathreesix** [comment]
@catto Thanks for confirming it. Ping me anytime via email at ryo at locki.io if you have any questions.

**Comment by okuryu** [comment]
Sorry for delay. Looks good to me, and it's probably good starting translations docs for us. 🤘
