### ISSUE TITLE
Improving Functional Test Reliability for Beta and Prod Environments in OSSD

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3182]
**What happened**:

We run functional tests against the beta and prod environments for Open Source SD using the screwdriver-cd/screwdriver pipeline. Unfortunately, this pipeline has become very unstable, causing significant delays and blocking further releases.

Notable causes of flaky tests:

- As we continue running more tests, we've encountered GitHub rate limiting
- We have also faced issues with longer-running tests that eventually time out.

**What you expected to happen**:

A reliable set of functional tests that can be used to certify the version release.

**How to reproduce it**:

Go to the pipeline and select a random event, such as [this one](https://cd.screwdriver.cd/pipelines/1/events/816578). Notice how many restarts are required to get the entire test suite to pass.

**Comment by sd-buildbot-functional-beta-X1** [comment]
@kumada626 @sagar1312 - The plan is right now to tackle the problem with inconsistent and unreliable functional tests by splitting the tasks into two parallel jobs running with two different Github users. This hopefully will help to avoid the rate limiting.

**Comment by VonnyJap** [comment]
@kumada626 @sagar1312 - The plan is right now to tackle the problem with inconsistent and unreliable functional tests by splitting the tasks into two parallel jobs running with two different Github users. This hopefully will help to avoid the rate limiting.

**Comment by yakanechi** [comment]
@VonnyJap 
> We have also faced issues with longer-running tests that eventually time out.

To solve the above problem, we proposed the following PR to speed up testing by parallelization.
https://github.com/screwdriver-cd/screwdriver/pull/3194

However, as mentioned in the PR, the test will run faster than the Github rate limit reset, so the rate limit problem may occur again.

**Comment by VonnyJap** [comment]
@yakanechi - I learned that personal access token has the lowest rate limit. But if we can make a switch to use either oauth or github apps model of auth, it will help to avoid the rate limit. Please checkout the docs [here](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-github-app-installations). But we have not had time to incorporate the change.
