### ISSUE TITLE
Job template page takes a long time to load

### ISSUE THREAD

**Issue by yakanechi** [screwdriver-cd/screwdriver#3191]
**What happened**:
When we try to open the Job Template Details page, we get a long wait time.
This is especially occur in templates with many template use jobs.

**What you expected to happen**:
The job template detail page will load immediately.

**How to reproduce it**:
Open a detailed page of job templates used for many jobs.

**Comment by VonnyJap** [comment]
Closing ticket since the work is completed. Please feel free to reopen if otherwise.
