### ISSUE TITLE
Hard to know what pipeline is assign as remote trigger

### ISSUE THREAD

**Issue by y-oksaku** [screwdriver-cd/screwdriver#3193]
**What happened**:

Currently, the remote trigger is shown in the format `~sd@<pipeline id>:<job name>`.
This makes it difficult to identify the pipeline without visiting the upstream pipeline.

<img width="168" alt="example" src="https://github.com/user-attachments/assets/0008ddf8-b6ed-44d3-abfd-a66e08370a5c">

**What you expected to happen**:

Make it easier to identify the pipeline name on the workflow graph.

**How to reproduce it**:

**Comment by VonnyJap** [comment]
@y-oksaku @kumada626 - is this issue completed?

**Comment by kumada626** [comment]
@VonnyJap Yes, I think this issue is completed. There may be some room for improvement, but in that case, we should create a separate Issue to do so.
