### ISSUE TITLE
Restart a PR build via comments

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#320]
Right now it's mildly frustrating to restart a PR build by closing and re-opening the PR.  It ends up with things like this:
<img width="332" alt="screen shot 2016-10-27 at 9 18 08 am" src="https://cloud.githubusercontent.com/assets/622065/19775745/3e855190-9c26-11e6-9731-37457de4d689.png">

What about adding support for rebuilding via a comment?  Maybe whenever the comment contains the word "rebuild"?

> Rebuild this please?

or

> Can has a rebuild?

I'm not 100% sold on this though.  Maybe it's just as annoying as closing/opening.  What does the team think?

**Comment by stjohnjohnson** [comment]
I did some quick research, the events come in as [`issue_comments`](https://developer.github.com/v3/activity/events/types/#issuecommentevent) that can be parsed to identify if it's a PR or not.  The only field I cannot get out of the webhook is what branch is the PR targeting.  This would require a lookup which we cannot do without the token (which isn't available to `parseHook`).

**Comment by d2lam** [comment]
We close/reopen because the Restart button is not working:
https://github.com/screwdriver-cd/screwdriver/issues/244
<img width="1360" alt="screen shot 2016-10-27 at 10 14 14 am" src="https://cloud.githubusercontent.com/assets/3401924/19777702/53797e98-9c2e-11e6-9e78-5252dd5420a2.png">

If that works properly, I don't feel the need to do this as a user.

**Comment by stjohnjohnson** [comment]
@d2lam Hmm, true true.

**Comment by d2lam** [comment]
@stjohnjohnson  Should we close this then?

**Comment by d2lam** [comment]
` The only field I cannot get out of the webhook is what branch is the PR targeting. This would require a lookup which we cannot do without the token (which isn't available to parseHook)` 

The target branch is available in parseHook. This is the target branch: https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L442

**Comment by stjohnjohnson** [comment]
I'll close this.
