### ISSUE TITLE
One-page homepage

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#322]
Right now http://screwdriver.cd is our documentation via mkdocs.  It has a basic one-page on it, but it's not easy to grok as a new user.  I think we should split off our documentation to something like https://docs.screwdriver.cd and replace http://screwdriver.cd with a one-page bootstrap like page.

Proposed content:
- [x] Header
  - [x] Logo
  - [x] Links to Docs, Blog, Slack, GitHub
- [x] Intro image (maybe https://flic.kr/p/hmZTt which has commercial usage allowed)
  - [x] One-line description
  - [ ] Published Version (link to Roadmap below)
  - [x] Getting Started button (links to Getting Started below)
- [ ] Features
  - [ ] List of distinguishing features
  - [ ] Quick list of why we built screwdriver
  - [ ] Link to documentation for intro
- [ ] Screenshots
  - [ ] Screenshots/Screencasts
- [x] Getting Started
  - [x] In-a-box.py copy-paste script
  - [x] link to documentation for running your own cluster
- [ ] Roadmap
  - [ ] What version is running right now
  - [ ] What major features are coming up next
  - [ ] Link to changelog
- [ ] Usage
  - [ ] Logos of companies using Screwdriver (too soon?)
  - [x] Supported technologies
- [ ] About
  - [ ] History/Inspiration?
  - [x] Team
- [x] Footer
  - [x] Copyright
  - [x] Links to GitHub, Tumblr, etc.
  - [x] Moar links to stuff (documentation, about, etc)
- [x] Call to action

I'll be happy to take this on, however I'm looking for feedback on the content.

**Comment by petey** [comment]
That list looks like a lot of content, but I agree with splitting docs from the landing page.


[Don't fall into the trap](http://adventurega.me/bootstrap/).

**Comment by stjohnjohnson** [comment]
@petey what would you remove, or at least what would you want as a first pass?  And yes, I am falling into the trap ;)

**Comment by petey** [comment]
I might even put the screencast in the docs, and just have a link to that from getting started. Screenshots could be included as part of the feature list.

Too soon for usage section.

**Comment by stjohnjohnson** [comment]
This is more of a continuing improvement.  Closing this one out.
