### ISSUE TITLE
[Feature Request] Feature flag for Download Zipped Artifacts

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#3227]
**What happened**:
In current implementation, screwdriver zips artifacts on its API and no restriction on its download file size. Because of this, if users try to download a large file size artifacts might crushing API.
So we want to disable this feature until size restriction is implemented.

**What you expected to happen**:
If feature flag for Download Zipped Artifacts is set false on [UI config](https://github.com/screwdriver-cd/ui/blob/master/config/environment.js#L47), users only can download each artifacts and cannot download zipped directory or all artifacts(same as before).

**How to reproduce it**:

**Comment by VonnyJap** [comment]
@kumada626 - We can close this issue now?

**Comment by kumada626** [comment]
@VonnyJap Yes, I think we can close this issue. 
However, we have not implemented foolproof solution that is described in [design doc](https://github.com/screwdriver-cd/screwdriver/blob/master/design/sd-download-artifacts.md).
So it is good to create another issue to improve download artifacts feature.

**Comment by kumada626** [comment]
@VonnyJap Yes, we can close this issue.
