### ISSUE TITLE
Job List view to have options to change the number of historical builds

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3241]
**What happened**:

Job list view is very static right now, there is no option to make a change to view more historical builds because it is currently set to 5 based on [this config](https://github.com/screwdriver-cd/ui/blob/e661018e9517bc2b892a88ad2b0a2d5056726c14/config/environment.js#L64). 

**What you expected to happen**:

The job list view should have a filter to allow users to view more historical builds. 

**How to reproduce it**:

See screenshot when visiting the job list view in any pipeline.

![Screenshot 2024-11-14 at 9 40 49 PM](https://github.com/user-attachments/assets/692a97bc-2aff-4db8-9f83-883548534db9)

**Comment by tkyi** [comment]
<img width="1718" alt="Screenshot 2024-11-18 at 4 02 43 PM" src="https://github.com/user-attachments/assets/5abbfeb9-1714-4977-8430-aaac5d404805">
Should be completed with UI v1.0.1095
