### ISSUE TITLE
Bad yaml build gets stuck

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#326]
We modified config-parser to [return a parsed content if the yaml is bad](https://github.com/screwdriver-cd/config-parser/commit/b4012ca2958aa41d3137dc6cf189163834551643)

However, when a build with bad yaml runs, it will gets stuck: [example build](https://cd.screwdriver.cd/pipelines/acf8b38595ec7674cf810afac973874b482762f9)

~~Some investigation shows that the launcher was running is `2.0.12` even though we have updated the deployments to use `2.0.13`~~

**Comment by petey** [comment]
I think this is related to executor's `launchVersion` config. The default is `stable` (I think the `default.yaml` config is incorrect for executors). Maybe the latest launcher isn't `stable`? Changing my local config to set launchVersion to `latest` seems to fix the issue.

**Comment by d2lam** [comment]
Yeah, `stable` isn't `latest`. But I thought we were running your job on production. If it was local and and your local config was set to `stable` then it makes sense that launcher wasn't the correct version.

**Comment by d2lam** [comment]
Just an update on this: 
Petey submitted a fix and the job now runs and fails at `sd-setup` due to launcher still looking for `screwdriver.yaml`

**Comment by d2lam** [comment]
This is done! 

<img width="1412" alt="screen shot 2016-11-17 at 1 49 29 pm" src="https://cloud.githubusercontent.com/assets/3401924/20408982/b1c2974c-accc-11e6-8aa9-83e6776ddc08.png">
