### ISSUE TITLE
What is "Build Cache" ?

### ISSUE THREAD

**Issue by ginoh** [screwdriver-cd/screwdriver#357]
Hi, I have a question.

Has Cache depicted in the Overall Archtecture been already implemented ?

<img width="282" alt="2016-11-11 11 21 13" src="https://cloud.githubusercontent.com/assets/2827530/20203250/1c0c6cfe-a809-11e6-987b-4ea771d9a910.png">

**Comment by jpcollins** [comment]
Not yet.  It's dependent on execution engine and storage.  In Yahoo, we are exploring using PersistentVolumes in Kubernetes using NFS as storage backend right now.

**Comment by ginoh** [comment]
Thank you. I understand it.
I hope that the document would be updated if there is progress.
