### ISSUE TITLE
Simplify Documentation

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#371]
As a user it's difficult to navigate the current Screwdriver documentation.

We want to split up documentation into three distinct sections so it's more clear where SD owners vs users should go:
- [ ] cluster management (for SD owners)
   - [x] overall architecture
   - [x] local setup
   - [x] configuring API
      - [x] execution engines
      - [x] scm plugins
      - [x] datastore plugins
   - [x] configuring UI
   - [x] configuring Store
      - [x] logging plugins
   - [ ] debugging
- [x] using SD
   - [x] getting started
   - [x] setting up the SD yaml + secrets
   - [x] API/documentation page
   - [x] Authentication and Authorization
- [x] about
   - [x] appendix
     - [x] what is SD?
     - [x] domain model
   - [x] support

Other stuff:
 - [x] Analytics
 - [x] Splash page
 - [x] Internationalization

**Comment by stjohnjohnson** [comment]
What should the homepage be?  Just a big selector of choose your own adventure?
 - I want to learn more about SD
 - I want to manage a cluster
 - I want to use it

**Comment by stjohnjohnson** [comment]
Should we start playing around with Locki here? https://github.com/screwdriver-cd/screwdriver/issues/318

What about adding google analytics?

**Comment by tkyi** [comment]
Or should it be "Install/Setup Screwdriver" vs "Using Screwdriver"?

You could do the choose your own adventure thing for now.
I'm sure Jay will have some input later anyways.

**Comment by tkyi** [comment]
Ooh I've never heard of Google analytics. That looks pretty cool.

What are we prioritizing here? Fixing up the text in the documentation or enhancing it?

**Comment by stjohnjohnson** [comment]
Having enough of a foundation for users to get started and for us to continue to improve it.

**Comment by stjohnjohnson** [comment]
I say we timebox this to 2 days.

**Comment by stjohnjohnson** [comment]
Looks like the deployment job failed: https://cd.screwdriver.cd/pipelines/baa6a0374df961ac97669bf3a3089a24cfb72794/build/eacceef263c01726b282b31dbf352b3288a612b7

**Comment by tkyi** [comment]
Hm I wonder if it's related to an issue @d2lam opened: https://github.com/screwdriver-cd/screwdriver/issues/345

**Comment by stjohnjohnson** [comment]
So we resolved most things today.  Items left:

- [ ] Add Quickstart (PR in progress)
- [ ] Update Structure in README.md
- [ ] Add In-A-Box info

**Comment by tkyi** [comment]
^^Created a PR that should address everything but the debugging page
- [x] homepage
- [x] what is SD
- [x] running locally
- [ ] debugging
