### ISSUE TITLE
Quick Start on Splash Page

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#372]
Instead of having the splash page be a one-pager, it should instead by a quick getting started page for setting up a pipeline.

**Comment by FenrirUnbound** [comment]
We needed a reference repository, so we created [screwdriver-cd-test/config-examples](https://github.com/screwdriver-cd-test/config-examples) to store them all in. Each branch will reflect a different configuration that shows how to use a specific function or feature in the config.

**Comment by FenrirUnbound** [comment]
We want the splash page to be a sort of "create a working pipeline in <5 minutes". We realized that there are efforts in improving our guide, which include making example repositories.

We chose to have the splash page to link to the `screwdriver.yaml` of one of those example repositories. We felt that cloning an example would be more impactful than having a user copy-paste a bare-bones configuration file.

**Comment by stjohnjohnson** [comment]
Looks great! 👍  Story 🐑 ed
