### ISSUE TITLE
UI only has error page for 404 and 500

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#384]
Currently the UI only has error images for 404 and 500.
All error caught in the pipeline page will be treated as 404 no matter what stausCode it has.
https://github.com/screwdriver-cd/ui/blob/master/app/pipeline/route.js#L13

Example: this is a 403 error but shown as 404
<img width="1252" alt="screen shot 2016-12-06 at 10 58 24 am" src="https://cloud.githubusercontent.com/assets/20427140/20939259/f489a036-bba2-11e6-8536-4c18b6609063.png">

Can we dynamically decide the error page based on statusCode?

**Comment by petey** [comment]
I want to get rid of the images entirely.
