### ISSUE TITLE
Add pipeline sync or archive PR button to UI

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#389]
PR-364 was merged when the webhook API had problems. Therefore it is not archived.
We can only archive it via API. Can we add a `Sync` button or `Archive` button to solve this?

**Note**: `GET pipeline/{id}/sync` does not check if non-archived PRs are closed or not. So simply calling the sync endpoint won't fix this problem. 

**Solution 1**: Adding the PR check to `sync` endpoint and add a `Sync` button to UI
**Solution 2**: Adding an `Archive` button to the UI

<img width="1280" alt="screen shot 2016-12-12 at 11 00 48 am" src="https://cloud.githubusercontent.com/assets/20427140/21112474/c6e6c96c-c05a-11e6-93aa-4664d733227c.png">

**Comment by d2lam** [comment]
Will track this issue in https://github.com/screwdriver-cd/screwdriver/issues/417
