### ISSUE TITLE
Timestamps and log formatting

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#395]
Some builds are exhibiting some odd indentation with their logs. From one build in particular https://cd.screwdriver.cd/pipelines/2adc50a62f268d10f1e11b6106cf0a787566bca7/build/2ca1f36d97de0438bf58c12f4e9831ca06824d92:

![screen shot 2016-12-13 at 11 03 26 am](https://cloud.githubusercontent.com/assets/721148/21154616/de3f8d78-c123-11e6-87a8-fd2538537e3e.png)

**Comment by petey** [comment]
It'd be interesting to compare this with the actual logs. I have a feeling that there is some missing html encoding going on.

**Comment by FenrirUnbound** [comment]
Not quite sure. The build is linked above the picture though.

I'm unsure why the `<main>` tag gets injected however:

![screen shot 2016-12-13 at 1 43 46 pm](https://cloud.githubusercontent.com/assets/721148/21160609/4f971656-c13a-11e6-99a0-faacc69d1a04.png)

**Comment by petey** [comment]
There are numerous log lines that look like:

```
/usr/local/bin/bundle:22:in `<main>'
```

**Comment by d2lam** [comment]
This is resolved 👍
