### ISSUE TITLE
Search Filters

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#397]
> If you take a look at what the UI is actually doing, you'll see that all the filtering that is done right now is handled entirely in the UI after downloading the list of all pipelines in the system. There would be nothing stopping you from making that somewhat more intelligent, so that one could search for owner:screwdriver-cd, repo:ui, or branch:patch1. The results should already be sorted alphabetically.
@petey

Split from https://github.com/screwdriver-cd/screwdriver/issues/394#issuecomment-266848413

**Comment by d2lam** [comment]
I verified that this is working. Thanks @catto  for submitting the PR! 💯

**Comment by catto** [comment]
:cat2:
