### ISSUE TITLE
Set up PostgreSQL in RDS

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#398]
We would like to move from DynamoDB to RDS in order to have pagination and better queries.

## Summary

1. We followed the instructions and set up an instance with default settings and `screwdriver` as Database Name and created a master user:
http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_GettingStarted.CreatingConnecting.PostgreSQL.html

2. We used pgadmin to view the tables. In order to allow anyone to connect to the server, we opened up Inbound Rules for the Security Group to allow for:
PostgreSQL (5432)	TCP (6)	5432	0.0.0.0/0

2. We used `datastore-sequelize` to run the API locally (using SD-in-a-box) with the instance and tested:
- events
  - [x] list
- pipeline
   - [x] create
   - [x] delete
- secret
   - [x] create
   - [x] delete
- job
   - [x] disable
- build
   - [x] start
   - [x] stop
- user
   - [x] login
   - [x] logout

Secrets for RDS postgres instance: https://gist.github.com/minz1027/54c2317fad35a5ccd54741fd18d09110

**Comment by stjohnjohnson** [comment]
Is it best to allow anyone to connect?  How can we restrict it to allow only our K8S cluster to connect?  Or even better, just our API.

**Comment by tkyi** [comment]
There is still a master username and password that people need in order to connect.

**Comment by FenrirUnbound** [comment]
Restricting what entities can connect to the DB would be ideal. It limits the attack vectors to a finite group of machines.

> There is still a master username and password that people need in order to connect.

So an outsider tries to log in with a username and arbitrary password. What's the failed attempt logic like? Does it fail immediately or is there a back-off mechanism to prevent a brute force attack?

**Comment by tkyi** [comment]
I'm not sure if RDS has any security features built in, but this article might be worth looking into:
http://www.hexatier.com/guide-amazon-rds-database-security/
