### ISSUE TITLE
Double builds because of two webhooks

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#404]
We're currently getting double builds on some of our repositories.
 - https://cd.screwdriver.cd/pipelines/6172e25fa190fe5e23b3685f6e211bd9d066e578/build/64d46b041243eefed974ed5fe051d18662d89c30
 - https://cd.screwdriver.cd/pipelines/6172e25fa190fe5e23b3685f6e211bd9d066e578/build/bd55910dfe083b989286669523df36111de7c1c9

We have an organization webhook as well as repository level webhooks (thanks to https://github.com/screwdriver-cd/screwdriver/issues/379).

Things to do:
- [x] Remove org webhook
- [x] ~Sync all pipelines to setup repo webhooks~ Mass create pipelines

**Comment by d2lam** [comment]
We just need to remove the org webhook after the mass creating. The second bullet point will be resolved after the pipelines are mass created.

**Comment by d2lam** [comment]
This problem is resolved.
