### ISSUE TITLE
better SSL certs for screwdriver.cd

### ISSUE THREAD

**Issue by tonytamsf** [screwdriver-cd/screwdriver#413]
Can you fix the cert issue?

![screen shot 2017-01-05 at 2 35 44 pm](https://cloud.githubusercontent.com/assets/149837/21700228/42c09c78-d354-11e6-88fb-9378140b6ad7.png)

**Comment by d2lam** [comment]
@tonytamsf The page is not hosted by us, it's hosted by github pages so currently, we can't have it running on https. We could possibly switch to something else.

**Comment by tonytamsf** [comment]
got it,  thx

**Comment by stanleyhlng** [comment]
Lots of ppl discuss about "SSL + custom domain". https://github.com/isaacs/github/issues/156
