### ISSUE TITLE
Syncing PRs

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#417]
Currently, if webhook fails to send, PR jobs will be at a wrong state and there is no way to correct this since our current `sync` does not take care of PRs. 

- [x]  Add `getOpenedPRs()` to scm-base  --- https://github.com/screwdriver-cd/scm-base/pull/37
- [x]  Add `getOpenedPRs()` to scm-github: [example endpoint](https://api.github.com/repos/screwdriver-cd/models/pulls)
- [x]  Add `getOpenedPRs()` to scm-bitbucket: [example endpoint](https://api.bitbucket.org/2.0/repositories/d2lam2/%7Bde7d7695-1196-46a1-b87d-371b7b2945ab%7D/pullrequests?state=OPEN)
- [x]  Add `syncPRs()` to models      --- https://github.com/screwdriver-cd/models/pull/148
- [x]  Add `sync/pr` endpoint to API --- https://github.com/screwdriver-cd/screwdriver/pull/418
- [x]  Add a buttons to sync in UI
   - [x] Sync pipeline, PR,  webhooks
   - [x] Add tests

Related: https://github.com/screwdriver-cd/screwdriver/issues/389

**Comment by d2lam** [comment]
**Update as of 1/17:** 
The backend work is done. Sync PRs can be accessed through: `/v4/sync/pullrequests`
We are working on adding a button to the UI for the users to sync their pipeline.

**Comment by tkyi** [comment]
The UI pipeline is broken so the changes cannot be pushed out and verified. Looking into that today.

**Comment by d2lam** [comment]
This feature is done.
