### ISSUE TITLE
"Execution Engines" doc page has a yahoo-internal voice

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#424]
http://docs.screwdriver.cd/about/appendix/execution-engines/

This page reads to me as having been written by someone inside of yahoo. It might be nice to rephrase it so that it reads as coming from a someone involved with screwdriver.cd but not necessarily from within yahoo.

**Comment by petey** [comment]
Also, **really** need to remove TODOs

**Comment by tkyi** [comment]
Removed the page from the documentation since it isn't really user-relevant.
It might be nice to add an execution engines page to our `/design` folder in order to document design decisions in the future.
