### ISSUE TITLE
The redirection of the UI after logging in is annoying

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#425]
After logging in from pages like the pipeline page, the user is redirected to the homepage. This is a pretty poor flow, as it is difficult to get back to that page at present. The documentation suggests that there wasn't any way to configure this differently with ember-simple-auth.

The internets have this to say:
> The EmberJS router holds information about where the user has been, so just add this into your routes/application.js file in the actions object:
> ```
> sessionAuthenticationSucceeded: function() {
>   this.transitionTo(
>     this.controllerFor('application').get('previousRouteName')
>   );
> }
> ```

It appears that in ember-simple-auth@1.2.0-beta.1 individual routes may be able override the global configuration for the post-login route, which may also resolve this issue. https://github.com/simplabs/ember-simple-auth/blob/master/CHANGELOG.md#120-beta1

**Comment by petey** [comment]
I have reason to believe that the internet's suggestion is incorrect, and won't actually solve anything.

**Comment by minz1027** [comment]
@petey Currently, if you click `login` and login successfully, your will be redirected to the same login page, which is a bit confusing. If you refresh the page, you will be redirected to `home` page.

Looks like `routeIfAlreadyAuthenticated` is not happening immediately after you log in? 
https://github.com/screwdriver-cd/ui/blob/master/app/login/route.js#L5
