### ISSUE TITLE
It is unneccessary to require a user to configure their service account token for the k8s executor

### ISSUE THREAD

**Issue by jer** [screwdriver-cd/screwdriver#427]
There is an environment variable called `K8S_TOKEN` that is used to configure the api when running with the k8s executor. This is unnecessary configuration, since the token is always on disk here when you're in a pod:

    /var/run/secrets/kubernetes.io/serviceaccount/token

Removing the requirement to configure this would allow a user to delete their entire namespace and then bring it back up with only kubectl. As it stands, you have to make service account, then edit a yaml file, then make the rest of the components.

**Comment by stjohnjohnson** [comment]
According to the documentation, that is not required.  It's an optional field that defaults to reading that value: https://github.com/screwdriver-cd/executor-k8s/#initialization

**Comment by jer** [comment]
Aaah perfect, I didn't see that. Was going by the example deployment definition. Thanks.
