### ISSUE TITLE
feature request: support hosted bitbucket

### ISSUE THREAD

**Issue by DanielYWoo** [screwdriver-cd/screwdriver#430]
We have commercial license and host our own bitbucket, do you have a plan to support it? #

**Comment by stjohnjohnson** [comment]
Hey @DanielYWoo!  We actually already started work on it.  But ran into some issues and chose to move on and come back to it later.  Maybe you can help us out: https://github.com/screwdriver-cd/screwdriver/issues/255

Source code for BitBucket SCM module: https://github.com/screwdriver-cd/scm-bitbucket

**Comment by stjohnjohnson** [comment]
I'm going to merge this into https://github.com/screwdriver-cd/screwdriver/issues/255
