### ISSUE TITLE
Jenkins Executor

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#432]
> As an administrator, I want to use my existing Jenkins infrastructure, so that I can easily transition to Screwdriver

Many people already use Jenkins today.  Making an executor that integrates into an existing Jenkins farm would make migration/adoption easier.

Rules:
 - All builds are treated as Jenkins Jobs.
 - All jobs are ephemeral (create, start, delete when done).
 - Can configure to use a Jenkins Node Label.
 - Executes a Docker Compose command.
 - Require target node to have Docker and Docker Compose.
 - Package is called `screwdriver-executor-jenkins`

---
### Implementation
- [x] Executor changes
### Outcome
- [ ] Documentation

**Comment by catto** [comment]
We have started implementing executor-jenkins and would like to use docker directly like executor-docker, not docker-compose, for the first pass to check if whole build life cycle in Jenkins works well.

**Comment by catto** [comment]
I've created the Slack channel for this. `#432-jenkins-executor`
Let's talk in the channel if there are any concerns.

**Comment by jithin1987** [comment]
We now have https://github.com/screwdriver-cd/executor-jenkins
