### ISSUE TITLE
Rebuild Pipeline

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#433]
> As a user, I want to configure my pipeline to be rebuilt automatically if one of my explicit dependencies is rebuilt, so that I always am testing against the latest certified packages

Currently, there's no way in Screwdriver to trigger another pipeline.  This prevents users from creating chains of libraries -> service.  For example, the Screwdriver API should be rebuilt when a new version of Screwdriver Data Schema is built.

Instead, Screwdriver should offer users the ability to pick pipelines that will rebuild their code if completed.  

Here is a simple example.  We have two pipelines (1 and 2).  2 is configured to be rebuilt when 1 is completed.

> 1@main -> 1@publish -> 2@main -> 2@sandbox -> 2@production

Rules:
 - Users specify this at the entire pipeline level not per job (see appendix A).
 - Users can specify either a pipeline or a job in that pipeline.
 - Specifying a pipeline means that the trigger will only happen when all jobs in that pipeline complete.
 - Specifying a job means that the trigger will happen when that job completes.
 - The successful completion of the specified pipeline will trigger a new build of the `main` job.

---
### Preparation
- [ ] Cucumber feature file
### Implementation
- [ ] Screwdriver.yaml changes
- [ ] Launcher changes
- [ ] API changes
- [ ] UI changes
- [ ] Store changes
- [ ] Schema changes
- [ ] Model changes
- [ ] Datastore changes
- [ ] Executor changes
### Outcome
- [ ] Cucumber feature passing
- [ ] Documentation

---

### A - Rebuild Syntax

We're not 100% on the syntax or naming here, but it should be specified at a pipeline level:

```yaml
workflow:
 - publish

depends_on:
 - sd@123
 - sd@123:publish

```

**Comment by jithin1987** [comment]
This is addressed by https://github.com/screwdriver-cd/screwdriver/issues/770
