### ISSUE TITLE
Cannot use Screwdriver with a private repository

### ISSUE THREAD

**Issue by bitemyapp** [screwdriver-cd/screwdriver#436]
Currently get this error despite the application being authorized
![screenshot from 2017-01-25 16-06-05](https://cloud.githubusercontent.com/assets/320177/22311249/34adb19c-e318-11e6-9216-c19c3e542754.png)

**Comment by d2lam** [comment]
Hey @bitemyapp, I just looked into this more. It should have worked even if it's a private repo as long as you have access to it. Looking into the server log,  the error came from here: https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L432-L451

I think what happens is it couldn't find a `screwdriver.yaml` in your repo. Can you make sure that you have that file? If my theory is right, the error message here is confusing and inaccurate and we should definitely fix it.

**Comment by bitemyapp** [comment]
I think the issue was that the `screwdriver.yaml` existed in a `screwdriver` branch I had PR'd, but not in master.

**Comment by bitemyapp** [comment]
![screenshot from 2017-01-26 14-51-35](https://cloud.githubusercontent.com/assets/320177/22349799/f4b1d234-e3d6-11e6-881b-c8c52a1403da.png)
![screenshot from 2017-01-26 14-50-30](https://cloud.githubusercontent.com/assets/320177/22349800/f4c0854a-e3d6-11e6-8afd-9ec2be60569c.png)

Same result for OAuth application under my name (I have access to the repository) and for OAuth application under `betterteamapp`.

**Comment by bitemyapp** [comment]
![screenshot from 2017-01-26 14-52-21](https://cloud.githubusercontent.com/assets/320177/22349835/107e6630-e3d7-11e6-916a-7a7013a72559.png)

in master.

**Comment by stjohnjohnson** [comment]
Ahh, so the problem lies here: https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L701

We're not asking for read access to private repos. We can solve this by adding `repo` to the list: https://developer.github.com/v3/oauth/#scopes

I wish GitHub allowed us to ask for read only access to private repositories, because this grants our token WAY too much power:

> Grants read/write access to code, commit statuses, invitations, collaborators, adding team memberships, and deployment statuses for public and private repositories and organizations.

**Comment by d2lam** [comment]
So this seems like a github limitation. Travis-pro, which supports private repos would also need to ask for write access:
![screen shot 2017-01-26 at 3 49 10 pm](https://cloud.githubusercontent.com/assets/3401924/22355448/79d83bbc-e3df-11e6-87c7-481498b63689.png)

I submitted a PR to fix this.

**Comment by stjohnjohnson** [comment]
So not only would we need to allow private repos, but we would need to start adding read protection against the projects that you do _not_ have access to.

Changes would be needed at:
 - API
 - Store

**Comment by stjohnjohnson** [comment]
This shouldn't be closed until we fix the API and Store to support private pipelines.

**Comment by d2lam** [comment]
@bitemyapp  Can you try pulling screwdriver image `v0.4.88`? It should work now. However, like @stjohnjohnson mentioned, we currently don't have read protection against projects that you don't have access to (anyone can see it right now). We will try to find some time to work on it. If you want to contribute, here would be the place to do it: https://github.com/screwdriver-cd/screwdriver/tree/master/plugins/pipelines

Let us know if you have any questions or concerns.

**Comment by d2lam** [comment]
Talked with @bitemyapp  offline. It's able to create a pipeline from a private repo now.
To make it work, need to set `SCM_PRIVATE_REPO_SUPPORT` to `"true"`
Documented here: http://docs.screwdriver.cd/cluster-management/configure-api/#configuration

**Comment by d2lam** [comment]
The initial issue here (cannot create a project with private repo) was resolved. Creating a new issue for adding read protections: https://github.com/screwdriver-cd/screwdriver/issues/466 for easier tracking.

**Comment by QubitPi** [comment]
For those who are using [SD Docker Compose](https://github.com/screwdriver-cd/in-a-box), simply add [this line](https://github.com/QubitPi/screwdriver-cd-in-a-box/pull/6/files) to the `docker-compose.yml`

**Comment by QubitPi** [comment]
> Talked with @bitemyapp offline. It's able to create a pipeline from a private repo now. To make it work, need to set `SCM_PRIVATE_REPO_SUPPORT` to `"true"` Documented here: http://docs.screwdriver.cd/cluster-management/configure-api/#configuration

For those who are using [SD Docker Compose](https://github.com/screwdriver-cd/in-a-box), simply add [this line](https://github.com/QubitPi/screwdriver-cd-in-a-box/pull/6/files) to the `docker-compose.yml` generator which results something like

```yaml
            SCM_SETTINGS: |
                {
                    "github": {
                        "plugin": "github",
                        "config": {"username": "sd-buildbot", "email": "dev-null@screwdriver.cd", "secret": "SUPER-SECRET-SIGNING-THING", "privateRepo": true, "oauthClientId": "0f2065be8d54c2fba6bc", "oauthClientSecret": "1d8a1ba1581f3fb0b3f8d64a00c056d0ccc1bc3f"}
                    }
                }
```

More details [here](https://github.com/QubitPi/screwdriver-cd-in-a-box/pull/6#issue-2058093909)
