### ISSUE TITLE
Build looks stuck if docker pull takes long

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#438]
Builds look stuck with no logs or status messages for a while if I specify a large docker image to `screwdriver.yaml`.
They are actually pulling the docker image in the background, so it would be better if UI shows us a message or a log about preparation of the build at that time.

**Comment by stjohnjohnson** [comment]
I agree, this has always bothered me.  There are two issues going on here, depending on your execution engine.

1. Docker Swarm execution calls are synchronous and can be slow.  Docker swarm will make a Pull first then a Create.  This call will take as long as the pull takes.
2. Kubernetes calls have to way to report back asynchronous statuses (like downloading image, waiting for available machine, etc.).

We're hoping that we can solve that when we get to https://github.com/screwdriver-cd/screwdriver/issues/431.  We should be able to make all execution calls async (adding to the queue) and then have the engines themselves report back statuses on a regular basis (enqueued for X time, waiting for resources, downloading, etc.).

**Comment by d2lam** [comment]
This should be solved by https://github.com/screwdriver-cd/ui/pull/251
