### ISSUE TITLE
Whitelist by organization

### ISSUE THREAD

**Issue by mgoodness** [screwdriver-cd/screwdriver#441]
Rather than whitelisting everyone or whitelisting each user individually, it would be great if I could whitelist all the members of an organization with a single entry.

**Comment by stjohnjohnson** [comment]
Hey @mgoodness, that's an interesting idea.

Right now, we wouldn't be able to enumerate a list of users of an organization upfront without an admin-level token for that organization.  We could use the user's token to enumerate the list of orgs they belong to: https://developer.github.com/v3/orgs/#list-your-organizations  But we would need to do the same for Bitbucket.org and Bitbucket Server.

I'm not quite sure the right abstraction for that just yet.  But we can use this issue to brainstorm it.
