### ISSUE TITLE
Too much vertical spacing on Firefox

### ISSUE THREAD

**Issue by r3rastogi** [screwdriver-cd/screwdriver#449]
Running Firefox v51.0.1

![image](https://cloud.githubusercontent.com/assets/3217917/22613918/6e937f70-ea31-11e6-8995-9edcae5fe3a8.png)

**Comment by stjohnjohnson** [comment]
@petey looks like it might be something to do with the `white-space: pre-wrap`  Turning it off seems to make it look better.

**Comment by okuryu** [comment]
I expect this fixed in https://github.com/screwdriver-cd/ui/pull/145.

**Comment by stjohnjohnson** [comment]
Looks good!!  Thanks for the fixes
