### ISSUE TITLE
Support Gitlab

### ISSUE THREAD

**Issue by ZAntony** [screwdriver-cd/screwdriver#453]
Hello, like yahoo, support for this program found during using SCM just making and bitbucket, using gitlab excuse me I how to add?Or how to programming

**Comment by d2lam** [comment]
Hi @ZAntony, Screwdriver currently does not support Gitlab yet. It is definitely something we want to support in the future. If you would like to contribute, we can discuss further. It will be a separate plugin like [scm-github](https://github.com/screwdriver-cd/scm-github) and [scm-bitbucket](https://github.com/screwdriver-cd/scm-bitbucket ), based on the interface [scm-base](https://github.com/screwdriver-cd/scm-base)

**Comment by ZAntony** [comment]
thinks

**Comment by bdangit** [comment]
I would love support for Gitlab too.  Might have to hack out a `scm-gitlab` plugin one of these days soon.

Just for clarification, we need to override these? https://github.com/screwdriver-cd/scm-base#extending

**Comment by d2lam** [comment]
@bdangit Yup! Would love to see `scm-gitlab`! Let us know if you have any questions/concerns!

**Comment by d2lam** [comment]
@bdangit is currently working on this. 

Thanks Ben!

**Comment by bdangit** [comment]
I'm nearing completion of this plugin.  https://github.com/bdangit/scm-gitlab  A couple items to work on:

- [ ] fix `_checkoutCommand`; need to debug the checkout for gitlab experience. appears to not download all of the repo correctly.
- [ ] fix `_decorateAuthor`; debugging users that should exist still get `DEFAULT_AUTHOR`
- [ ] update documentation in the README.md

**Comment by bdangit** [comment]
Those that care to see the meat-making you can follow this: https://github.com/bdangit/scm-gitlab/issues/3

**Comment by d2lam** [comment]
Awesome @bdangit! I'm following the repo. 
Let us know when it becomes available! :D

**Comment by d2lam** [comment]
Hey @bdangit I have a branch to register this plugin for `in-a-box` to use:
https://github.com/screwdriver-cd/screwdriver/compare/gitlab

Let me know when the package is available :)

**Comment by bdangit** [comment]
hey @d2lam, I saw your #505 pr.  I reviewed it.

**Comment by d2lam** [comment]
PR was merged! I'll close this issue now. 

The [screwdriver-scm-gitlab](https://www.npmjs.com/package/screwdriver-scm-gitlab) is available and is community supported. 

Thanks @bdangit  for contributing! If you're kind enough, can you help us update our guide: http://docs.screwdriver.cd/cluster-management/configure-api/
Repo here: https://github.com/screwdriver-cd/guide

**Comment by bdangit** [comment]
sure I can do that.  Thanks again!  Also, anyone who uses the gitlab plugin, please bubble up your feedback.

**Comment by d2lam** [comment]
Closing this issue now.
