### ISSUE TITLE
Pipeline build badge not updated immediately

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#463]
**Problem**
Our badge in README is cached by github and won't get updated within 24 hours.
https://github.com/screwdriver-cd/screwdriver/blob/master/README.md shows
<img width="930" alt="screen shot 2017-02-22 at 10 30 38 am" src="https://cloud.githubusercontent.com/assets/20427140/23226338/0fed9010-f8ea-11e6-803f-15431d694b70.png">
while API returns
<img width="104" alt="screen shot 2017-02-22 at 10 31 45 am" src="https://cloud.githubusercontent.com/assets/20427140/23226380/2f5e9372-f8ea-11e6-8052-a8b23053176b.png">

**Root Cause**
We use [shields.io](http://shields.io/) to generate badges.
However, shields.io has a default max-age of 1 day for badges.
https://github.com/badges/shields/issues/726

Discussion about Github caches images.
https://github.com/github/markup/issues/224

**Comment by stjohnjohnson** [comment]
Interesting problem.  But it looks like it's out of our control for now.  Closing for now.
