### ISSUE TITLE
Artifacts should be listed on build page

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#468]
Now that we're uploading artifacts to the store, we should show the list of them on the Build UI and allow people to access them.

**Comment by minz1027** [comment]
### Summary for 03/06

@jerryzhang222 and I did some spike and discussed how to implement the build artifact UI today. And the following is what we came out with:

Proposed implementation:
1. Artifact-bookend creates a tree of files under ARTIFACT in JSON format and upload it to store.
(Need to `apt-get install tree` and `tree -J`)
e.g.
```json
[{"type":"directory","name": ".","contents":[
    {"type":"file","name":"CONTRIBUTING.md"},
    {"type":"file","name":"Dockerfile"},
    {"type":"file","name":"LICENSE"},
    {"type":"file","name":"README.md"},
    {"type":"directory","name":"executor","contents":[
      {"type":"file","name":"executor.go"},
      {"type":"file","name":"executor_test.go"}
    ]},
    {"type":"file","name":"launch.go"},
    {"type":"file","name":"launch_test.go"},
    {"type":"directory","name":"screwdriver","contents":[
      {"type":"file","name":"emitter.go"},
      {"type":"file","name":"emitter_test.go"},
      {"type":"file","name":"screwdriver.go"},
      {"type":"file","name":"screwdriver_test.go"}
    ]},
    {"type":"file","name":"screwdriver.yaml"}
  ]}
]

```
2. Inside the UI, when load `build` page:
    - if the build not finished yet, do nothing
    - if the build finished, 
       - make a api call to the store to get the tree JSON file
       - parse the JSON file
       - throw the parsed JSON to a JS package to render a pretty tree, e.g. [jqTree](https://mbraak.github.io/jqTree/), [bootstrap-treeview](https://github.com/jonmiles/bootstrap-treeview)

example parsed JSON:
```json
[{"type":"directory","name": ".","contents":[
    {"type":"file","name":"CONTRIBUTING.md", "href": "https://store.screwdriver.cd/v1/builds/123/ARTIFACTS/CONTRIBUTING.md"},
    {"type":"directory","name":"executor","contents":[
      {"type":"file","name":"executor.go", "href": "https://store.screwdriver.cd/v1/builds/123/ARTIFACTS/executor/executor.go"},
    ]}
  ]}
]
```

We are also working on drafting the static build page with the artifacts tree on the bottom and on the right side to see what looks better.

**Comment by minz1027** [comment]
Example output when using [jsTree](https://www.jstree.com/)

<img width="1146" alt="screen shot 2017-03-06 at 7 38 14 pm" src="https://cloud.githubusercontent.com/assets/20427140/23640808/c5789024-02a4-11e7-8db0-beb35d72e497.png">

**Comment by stjohnjohnson** [comment]
Please don't install other packages, you don't know if it's going to be yum, apt-get, or whatever.

That's what this is for https://github.com/screwdriver-cd/screwdriver/issues/300

Why not use `find .`  Why does it need to be uploaded in json format?  Why can't the API return the right format from the current text format you have?

**Comment by minz1027** [comment]
03/07 Updates
Talked to @petey and @stjohnjohnson and made some changes to the original plan:
- [ ] Enable cors in store
- [ ] Create a service in UI to fetch the plain manifest from store and parse it into desired JSON format
- [ ] Make a artifact-tree component, it will use the service to get JSON data and build the tree
- [ ] Embed the artifact-tree component into the build page

For design decisions:
We will go with [ember-cli-jsTree](https://github.com/ritesh83/ember-cli-jstree) which is an ember implementation for jsTree. And we will put the Artifact componet under logs for now.

**Comment by minz1027** [comment]
#### 03/08 Summary

Tested https://github.com/screwdriver-cd/ui/pull/146 with in-a-box, it is functionally working.
Need to work on unit tests tomorrow.

**Comment by minz1027** [comment]
#### 03/09 summary

Last PR open for review.

**Comment by tkyi** [comment]
Blog post: http://blog.screwdriver.cd/post/159006993017/storing-and-retrieving-artifacts
