### ISSUE TITLE
Subdirectory Support

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#471]
> As a user, I want to use the same Git repository for multiple pipelines, because I have a monorepo

Right now, Screwdriver has a 1:1 mapping of repo/branch to Pipeline.  This doesn't work well for teams with monorepos. There are a number of occasions where having a monorepo is beneficial and we should be supporting those use-cases.

Screwdriver should support subdirectories in a repository.  That way you can have multiple pipelines pointing to the same repo, but each one can be building different code (java, ruby, python, etc).

Rules:
 - Pipelines can take an optional subdirectory path.
 - Pipelines are only rebuilt when changes are made to that path.
 - PRs will only be run when changes are made to that path.
 - Screwdriver.yaml can specify additional paths to listen to.

**Comment by bdangit** [comment]
Yes!  Please support this.

**Comment by stjohnjohnson** [comment]
Based on @d2lam's changes in https://github.com/screwdriver-cd/scm-github/pull/60 we will need to change the context again to provide the Pipeline ID, otherwise Pull Request statuses will clobber each other when there are more than 1 pipeline per repo.

**Comment by d2lam** [comment]
I added PRs for including `pipelineId` in context, so we don't need to come back to it later.

**Comment by nkatzman** [comment]
yes please! I'm currently avoiding this issue with a script that detects and sets meta for directory changes (according to git). And then CI scripts that act accordingly.

Would be great to have subdirectory support. 👍 👍 👍

**Comment by tkyi** [comment]
This feature is complete: http://blog.screwdriver.cd/post/172605932687/monorepo-support-using-source-paths
