### ISSUE TITLE
Alternative Default Docker Registry

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#472]
> As a user, I want to change the default docker registry to my private registry, so that there are less human errors when selecting private images. 

Right now, Screwdriver just uses the default Docker implementation of `node:4 == hub.docker.com/r/_/node:4`.  For companies that run their own private registry, having to type out the private registry over and over again can lead to hard to detect human errors.

Screwdriver should support a way to specify a global default registry that translates `node:4` into the private registry.

Rules:
 - Configuration is made at the API layer.

**Comment by d2lam** [comment]
Question: should we support multiple docker registries?
Looks like we can easily tweak what's implemented in #618 to support it.
