### ISSUE TITLE
Bookends should always run

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#473]
Currently, if the build fails in the middle, bookends would not be executed. This shouldn't be the case. For example, if users store some deploy logs in the artifact folder. If the build breaks, they need to be able to look at the logs to debug. However, the `screwdriver-artifact-bookend` won't run since the build breaks.

**Comment by d2lam** [comment]
Verifying that it works: https://cd.screwdriver.cd/pipelines/122/builds/3707
The step exit fails, but it still runs the step `stuff` (since alwaysRun is set to true for this step) and also runs the bookend: 
<img width="872" alt="screen shot 2017-04-24 at 2 37 00 pm" src="https://cloud.githubusercontent.com/assets/3401924/25359842/90a77626-28fb-11e7-9b12-7ecd67abb678.png">

One thing is that the status of these steps are `Failure`. I think we should make those steps (for example, `stuff` and `artifact-bookend`) to be Success if runs successfully, while keeping the build status as Failure. 

I can dig into this more if that is the expected behavior.

**Comment by petey** [comment]
Yeah, this should definitely keep the correct step status.

**Comment by d2lam** [comment]
Actually this is not working. Those steps were not run. Need to look into this more.

**Comment by d2lam** [comment]
@minz1027  and I did some investigation on this. 

- [This](https://github.com/screwdriver-cd/launcher/blob/master/executor/executor.go#L101-L106) traps the `EXIT` to echo an extra line for `STEP_ID` before exiting. However, it does not prevent the shell from exiting. 
- The launcher will attempts to run the command because `alwaysRun` is `true`(See how update step status is called for `stuff`, but not `what`). However, since the shell already exits, subsequent steps will not be able to execute. 
- We don't have the solution to this yet. Any ideas?

**Comment by d2lam** [comment]
Consulted with @rphan about this. 
The trap route would not work for us.
One way that could get this work is to have a wrapper script and this script would run all the steps. 
In `wrapper.sh`:
```bash
. /tmp/step1.sh
. /tmp/step2.sh      # if this step fails, step3 will still run
. /tmp/step3.sh
```

However, this will require a lot of refactor in `launcher`. Currently, each command is fed into the `pty` like this: https://github.com/screwdriver-cd/launcher/blob/master/executor/executor.go#L83

If we write a `wrapper.sh` that includes all the step scripts, we need to handle the update step status in between steps. 

Also, this basically means always run ALL the steps. For example, if step2 fails & step3 doesn't have "alwaysRun", it will still run in this case. We need to add some extra checks so that step3 doesn't run in this example.

**Comment by d2lam** [comment]
Discussed with the team and decided to roll back this feature. We should revisit this later.

**Comment by d2lam** [comment]
Reason to roll back: based on current implementation of launcher, it's impossible to stay in the shell if the step fails & exits.

**Comment by d2lam** [comment]
**Update Dec 8, 2017**
Taking another stab at this, following some of the ideas here: https://github.com/screwdriver-cd/screwdriver/blob/master/design/director.md

PR is opened: https://github.com/screwdriver-cd/launcher/pull/133

Implementation details:
- Setup steps and user steps are run in one single shell. These steps will only run if previous steps succeed. If there is error, the first error will be stored and returned after the teardown steps execute. 
- After that, the shell will be killed and the teardown steps will be run in new shells. However, even if teardown bookend 1 fails, teardown bookend 2 will still run.
- Notes: environment variables set by the previous shell that runs user steps will NOT be passed to the teardown steps.

**Comment by jithin1987** [comment]
This now works as expected. Thanks @d2lam @minz1027
