### ISSUE TITLE
Should return error or redirect if pipelineId or buildId is invalid

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#478]
If I access to a correct build page like below, I can see a correct pipeline information and a correct build result.
https://cd.screwdriver.cd/pipelines/67/build/1356
![image](https://cloud.githubusercontent.com/assets/1608595/23447903/4b3545d0-fe91-11e6-98c3-a9e93bb3dcdc.png)

But I can also access to a build page which has wrong buildId, and it shows an incorrect pipeline and build result pair.
https://cd.screwdriver.cd/pipelines/67/build/889
![image](https://cloud.githubusercontent.com/assets/1608595/23447861/1a4d229e-fe91-11e6-8b72-9c9d710be62e.png)

UI should return a 404 error or redirect to other page if pipelineId or buildId is invalid.

**Comment by d2lam** [comment]
@catto  I'm not sure what you mean by: `But I can also access to a build page which has wrong buildId, and it shows an incorrect pipeline and build result pair.`

Build 889 does exist right? https://api.screwdriver.cd/v4/builds/889

**Comment by catto** [comment]
Yes, build 889 exists. But it is for the pipeline screwdriver-cd/scm-github, not for the pipeline screwdriver-cd/meta-cli.
UI shows that the pipeline is meta-cli and the build result is from scm-github. It's a bit confusing.
e.g. for the case a build url is accidentially trimmed the end of it.

**Comment by d2lam** [comment]
@catto  Oh I see! I didn't realize it belongs to a different pipeline. This is definitely a bug!

**Comment by minz1027** [comment]
Fixed by Catto's PR!
