### ISSUE TITLE
sd-setup-scm step is failed when using image which has no git package

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#479]
When I try to use [chef/chefdk](https://hub.docker.com/r/chef/chefdk/tags/) image which has no git package and failed to execute git clone.
![2017-03-02 18 56 41](https://cloud.githubusercontent.com/assets/3445553/23502236/6e95333e-ff7a-11e6-82d0-64cd96f3b385.png)

I think it should be able to use images which have no git package.

**Comment by stjohnjohnson** [comment]
Agreed.  We expected this to be a problem.  When we get to https://github.com/screwdriver-cd/screwdriver/issues/300 we should be able to pull git on-demand, even if the container doesn't have it.

I'll make sure we fill out the details in that ticket.

**Comment by stjohnjohnson** [comment]
Looks like it's resolved now per https://github.com/screwdriver-cd/scm-github/pull/59
