### ISSUE TITLE
UI does not show all buttons on certain resolutions

### ISSUE THREAD

**Issue by bdangit** [screwdriver-cd/screwdriver#487]
Between 839 px and 964 px, the Login/Logout button does not appear.

![image](https://cloud.githubusercontent.com/assets/933465/23583763/675c67e8-0102-11e7-90be-f616b34a1232.png)

Between 764 px and 772 px, the Github and Login/Logout button do not appear.

![image](https://cloud.githubusercontent.com/assets/933465/23583766/7a6bd738-0102-11e7-9565-8aa75015b0dc.png)

**Comment by bdangit** [comment]
Anything less than 764 px the hamburger sign appears.

**Comment by petey** [comment]
This should be fixed now with the new header.
