### ISSUE TITLE
[UX] Screwdriver UI should display brief instructions on each page

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#489]
- Create page:
Add a Git repository to Screwdriver by pasting your repository link below. We accept both HTTPS URLs and SSH URLs.
- Secrets page:
User [secrets](http://docs.screwdriver.cd/user-guide/configuration/secrets/) are stored encrypted in our datastore, and their values are only released to those builds that are authorized by the user. Add a secret Key and Value here to use it as an environment variable in your Screwdriver build. Add the key to your `screwdriver.yaml` to expose it to jobs in your workflow. The "Allow in PR" option will expose the key in Pull Request builds.
*Maybe also mention that secret names must have uppercase letters and/or numbers.* (https://github.com/screwdriver-cd/screwdriver/issues/541)

**Comment by tkyi** [comment]
Related to https://github.com/screwdriver-cd/screwdriver/issues/541

**Comment by ian-fox** [comment]
@petey @r3rastogi could you guys please have a look at this at some point? Thanks!
