### ISSUE TITLE
[UX] Non-admin denied from starting a build

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#495]
## Expected

Incredibly minor: When viewing a pipeline that I do not have admin permissions for, I would not expect to see the "Start" button.

Main point: Upon clicking the "Start" button, I expect the error to be descriptive regarding why the UI did not accept my click.

## Actual

Incredibly minor: The "Start" button is available. 

More importantly: if I click on the "Start" button, the error displayed isn't very descriptive. 

> Ember Data Request POST https://api.screwdriver.cd/v4/builds returned a 401 Payload (Empty Content-Type) [object Object]

![screen shot 2017-03-10 at 1 32 48 pm](https://cloud.githubusercontent.com/assets/721148/23813939/1742159e-0596-11e7-8d67-2e7429e680fa.png)

EDIT: Included screenshot

**Comment by petey** [comment]
This is definitely a bug. The UI shouldn't show a start button when you don't have access to start a build.

**Comment by d2lam** [comment]
Yeah, UI doesn't show `start` button if you're not logged in. Is it possible it was cached?

**Comment by FenrirUnbound** [comment]
After a month of not seeing it, I'm going to assume that I got into this state due to browser caching.

Closing as invalid.
