### ISSUE TITLE
Template without image should fail validation

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#510]
Currently, the creation of template is using `Job.job` as the schema validation for the `config`: https://github.com/screwdriver-cd/data-schema/blob/master/config/template.js#L40

They are not exactly the same. In a job, `image` is optional. In `template.config`, `image` is required. 

This bug allows template to not have `image` and if user plugs it in, the build will fail because image is not there. Example: https://api.screwdriver.cd/v4/templates/node%2Ftest/1.0.5

**Comment by stjohnjohnson** [comment]
I'm confused, why would a template NEED to provide an image?

**Comment by d2lam** [comment]
@stjohnjohnson I don't think it's the user's responsibility to figure out what image they should use for a specific template. A template should at least have an image that works for its steps. The user can override the image if they want to, but they shouldn't be required to know that information.

**Comment by d2lam** [comment]
It is required now. We can revisit this if we think it's not necessary.
