### ISSUE TITLE
UI - Secrets are in reverse order

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#514]
## Expected

The list of secrets to be in alphabetical order, from A through Z.

## Actual

It's in reverse order of when they were entered. So the oldest items are at the bottom of the list, and the most-recently added things are listed at the top of the list.

EDIT: Tried a different permutation.
EDIT2: Better wording

**Comment by d2lam** [comment]
Right now it's listing by reverse order of `id`. Are we ok with listing them in order of `id`? It won't be alphabetical, but it will be in the same order they were entered. That would be a quick change. Alphabetically sort will be more difficult.

**Comment by minz1027** [comment]
@FenrirUnbound We can add secret name as rangeKey in data-schema so that it will sort by name alphabetically. But we will probably need to rebuild the secret table..

**Comment by FenrirUnbound** [comment]
> Right now it's listing by reverse order of `id`

Ah ok, that explains the order that it's currently in. 

Instead of making modifications in the backend on how we store the data, would this be a better compromise: have the UI sort the order? I'm not a fan of putting a lot of logic in the front-end, but the additional overhead is small.
