### ISSUE TITLE
Template discovery

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#522]
UI that allows users to search and discover the available templates and what they do.

**Discovery:**
- [x] Search by template name, namespace, description
- [x] Search by template keywords
- [x] Sort alphabetically
- [ ] Sort [by usage](https://github.com/screwdriver-cd/screwdriver/issues/1091)
- [ ] Display metadata
  - [x] maintainer (released by: ___)
  - [x] last updated ___ time ago 
  - [x] latest version
  - [ ] # of downloads
  - [ ] tags
- [ ] Display warnings for templates that have reached EOL
- [x] Group by namespace

**Detail:**
- [x] Link to source
- [x] Delete template 
- [ ] Metadata
  - [x] maintainer (released by: ___)
  - [x] last updated ___ time ago)
  - [x] latest version
  - [ ] # of downloads
  - [ ] tags
- [x] Description
- [x] How to use template
- [ ] README
- [x] Versions - Release
- [x] Template image and steps (ala validator)

**Comment by petey** [comment]
The current designs for this feature:

Search:
![template a00 discover](https://user-images.githubusercontent.com/78533/27307640-7adc477e-54ff-11e7-912b-8b5159e66aca.png)

Single Template page:
![template a01 single](https://user-images.githubusercontent.com/78533/27307650-8d4e4c7c-54ff-11e7-810e-3fb5738b4e06.png)

**Comment by tkyi** [comment]
I would be interested in seeing a mock including a way to get to the validator from the templates discovery/search page.

**Comment by cybik** [comment]
May I suggest introducing the concept of "groups"? It'd be useful in cases where multiple templates "belonging" to a certain type of build would otherwise clutter the templates list (example: 10 to 15 templates on, say, building Android projects)

**Comment by minz1027** [comment]
Can we show all tags for the template in UI? Currently it lists all the version and there is no easy way to figure out what tag can be used. We don't even have an API endpoint to list all tags.

**Comment by FenrirUnbound** [comment]
One additional thing to add to the metadata list would be "personal" or "org"; some way to distinguish that the maintainer is a single person or a group.

One edge case to worry about is when the repository is transferred from "org" to "personal" or the other way. I figured that the data gets updated on the next published version, but I don't have a strong preference on the actual implementation.

**Comment by tkyi** [comment]
Link to source has been added.
![38157365-1c8c71fa-343b-11e8-96ce-e432dfc436d5](https://user-images.githubusercontent.com/3230529/38328317-6d463ece-37ff-11e8-8f74-d35d05276839.png)

**Comment by dwmarshall** [comment]
Should this be generalized to the concept of a template marketplace akin to other products' marketplaces? How do I share my `perl-life` template with the admins of other SD clusters? How do I import someone else's template into my cluster?

**Comment by jithin1987** [comment]
I'm closing this. Any further changes to templates and commands UI will be taken up-on based on design/user feedback.
