### ISSUE TITLE
User API Tokens

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#524]
> Users should be able to request a reusable token that can be used to identify them when making API requests. This is similar to tokens that github provides for the same purposes.

Currently the only support method of authentication is via OAuth flow. This works out great for humans to interact with the Screwdriver service. The downside with supporting only a signle authentication mechanism is it is incredibly difficult for developers to integrate tools or add on external features.

As an additional option, Screwdriver should be able to issue access tokens. This would allow users to interact with the Screwdriver API in a programmatic way. 

-----

Rules:

- Tokens should be specifically tied to the user that issued them
- Tokens should have a label/name associated with them
- Users can add a description to their issued tokens, so they know what they're using them for
- Users can revoke a token at any time.
- User can see when a token was last used
- No one can ever look up the raw value after initially generating the token

Discussion Items:

- Being able to generate unique tokens service-wide
- Secure methods of storing the tokens
   - Unique salt, similar to secrets
- Additional feature: token lifespans (purposely issuing a token with an expire time)

## Work

Outline & task list - #532

### 2017-04-26

* Removed `scope` requirement

### 2017-04-24 fenrirunbound

* Initial spec
   * First pass at the rules, work items
   * Topics that should be discussed or are possibly out-of-scope are documented in the *Discussion Items* section

**Comment by FenrirUnbound** [comment]
The feature is labelled with `component/API`. Do we also want to include UI-related features for token management (e.g., generating new tokens, deleting)? Or are there plans to include that in a separate feature?

**Comment by stjohnjohnson** [comment]
On a side note, we just realized that it would be amazing to have `pipeline` tokens as well.  That way it reduces the scope if the token is compromised.

**Comment by petey** [comment]
Done.
