### ISSUE TITLE
Emitter cannot read a long output

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#525]
In launcher, emitter scans *PipeReader using bufio.Scanner.
However, bufio.Scanner cannot read too long line.
If output is too long, below error will be occurred.
```
Error running launcher: Error with scanner: bufio.Scanner: token too long
```
This error happens, for example, in the case that a large package is downloaded and download command outputs download progress in one line.

**Comment by minz1027** [comment]
### Updates
This is still a problem. The share step one is fine since it just redirects the log to /dev/null. But we are having this same problem when doing `docker build`. Adding `--quite` will make the step pass.
But that's not a good long-term solution.

**Comment by minz1027** [comment]
The above change alone does not fix the problem ^^

Need to change the `log-service` to use `bufio.Reader` instead of `bufio.Scanner` too cuz now it's getting the super long string from the `launcher`.

https://github.com/screwdriver-cd/log-service/blob/master/logservice.go#L166

Will work on that.

**Comment by minz1027** [comment]
Problem fixed.
