### ISSUE TITLE
Build endpoint of UI is different from endpoint of API

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#527]
I found that a build link for notification is wrong in [here](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/builds/update.js#L80).  A build link is defined  `/pipelines/${pipeline.id}/builds/${id}` at this line. But actual UI endpoint is  `/pipelines/${pipeline.id}/build/${id}`.

On the other hand, the API endpoint is `/v4/builds/{id}`. "build" and "builds" difference may make confuse us.
I think UI endpoint should be `/pipelines/${pipeline.id}/builds/${id}`.

Related PR: https://github.com/screwdriver-cd/screwdriver/pull/515

**Comment by d2lam** [comment]
I agree with you!

**Comment by d2lam** [comment]
This is fixed. Thanks @tk3fftk!
