### ISSUE TITLE
Functional tests failing intermittently 

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#533]
Failing at different places for different reasons:

https://cd.screwdriver.cd/pipelines/1/builds/3623
```
1) Scenario: New Pull Request - features/git-flow.feature:17
   Step: When a pull request is opened - features/git-flow.feature:18
   Step Definition: features/step_definitions/git-flow.js:84
   Message:
{"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"No commits between master and darrenBranch"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
```

https://cd.screwdriver.cd/pipelines/1/builds/3675
```
1) Scenario: Create an event when user starts a job - features/events.feature:34
   Step: And the "publish" build succeeds with the same eventId as the "main" build -features/events.feature:39
   Step Definition: features/step_definitions/events.js:72
   Message: AssertionError: expected 1421 to equal 1434
```

https://cd.screwdriver.cd/pipelines/1/builds/3660
```
1) Scenario: New Pull Request - features/git-flow.feature:17
   Step: When a pull request is opened - features/git-flow.feature:18
   Step Definition: features/step_definitions/git-flow.js:84
   Message:
{"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"No commits between master and darrenBranch"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
```

**Comment by FenrirUnbound** [comment]
Reading this message:

>"message": "No commits between master and darrenBranch"

It would say this when there are no differences between `master` and `awesomeBranch`. One possibility is there's a failure with the `github.createFile()` operations: https://github.com/screwdriver-cd/screwdriver/blob/master/features/step_definitions/git-flow.js#L89

Does `github.createFile()` reject when it cannot create a file? Or do we need to look at the returned value and determine success/failure from the resolved data?

**Comment by d2lam** [comment]
Hasn't happened for a while. Closing this. Will reopen if seeing it again.
