### ISSUE TITLE
Screwdriver UI docker image is broken

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#544]
The `nginx:stable-alpine` docker image was retagged using a newer version of alpine. I'm not sure what the old version was, but `nginx:1.11.12-alpine` from a month ago still works.

The newer image requires a dependency `nginx-mod-http-lua` for the module we already had been installing `nginx-lua`. `nginx-lua` is required in order to use the lua command `content_by_lua_block` in the nginx config. After the alpine upgrade, this directive seems to no longer exist. 

The documentation for `nginx_lua` suggests that this is still a mainstay of that module: https://github.com/openresty/lua-nginx-module

There doesn't appear to be any specific documentation about `nginx-mod-http-lua`, and all I can discover is that this adds some `http_lua` module to nginx.

Running our docker image with the the new library installed results in the following error:
```
2017/05/05 00:47:12 [emerg] 1#1: unknown directive "content_by_lua_block" in /etc/nginx/nginx.conf:44
nginx: [emerg] unknown directive "content_by_lua_block" in /etc/nginx/nginx.conf:44
```

**Comment by jer** [comment]
It looks like nginx_lua became a virtual package for some reason, and nginx-mod-http-lua is the right one. Maybe nginx_lua used to bring in a version of nginx with lua statically compiled in, but now they only support dynamically linked modules.

Relevant PR: https://github.com/screwdriver-cd/ui/pull/161

**Comment by minz1027** [comment]
Resolved by https://github.com/screwdriver-cd/ui/pull/161. Things are working now! Thanks @jer!
