### ISSUE TITLE
Job keeps running if there is a Config Parser error

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#549]
Currently, if there is a `config-parser` error. The build will keep running forever, and user needs to manually stop it. 

This is an example of a job that has been running for more than a week:
<img width="1369" alt="screen shot 2017-05-09 at 4 23 55 pm" src="https://cloud.githubusercontent.com/assets/3401924/25876729/06beaa30-34d4-11e7-8d56-4b4131781cd1.png">

**Comment by petey** [comment]
When this step runs it should fail immediately, if there aren't other issues going on.
I think there are numerous things going on here that are possibly captured in other tickets.

* Fixed: config-parser doesn't error when there is no screwdriver.yaml
* No logs displayed when no screwdriver.yaml: #599 
* No build timeout: #545 

I'm going to close this ticket in favor of solving the other issues first.
