### ISSUE TITLE
Blue/Green Deployments for UI

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#553]
The UI fingerprints resources enabling subresource integrity (https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity). This causes issues while performing a rolling deployment as there is a point during the deployment where a user will try to request resources with the wrong fingerprint from what is available. To fix this, the UI should perform a blue-green deployment, where two parallel versions of the UI are running but only one is publicly routable.

How to make this work in k8s:
https://github.com/thesandlord/container-orchestration-comparisons/tree/master/blue-green-deployment/kubernetes

**Comment by jithin1987** [comment]
Closing this. Will leave it to cluster admins to handle their deployments.
