### ISSUE TITLE
How about trying GitLocalize instead of Locki

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#558]
We are currently using Locki to localize the documents. It's so easy to work and simple enough.
But there are some issues like
* Translated sentences aren't reviewed.
* It's hard to check diffs between original docs and translated one.

This is current translated docs of docs.screwdriver.cd. I can see some incorrect translations.
![image](https://cloud.githubusercontent.com/assets/1608595/26351756/dbb03ed2-3ff3-11e7-8eed-2bcb9f536f49.png)

I think [GitLocalize](https://gitlocalize.com/) can resolve these issues. It makes translation reviewable and manageable by git.
It seems that the only prerequisite is that docs are managed by GitHub. This suits for us.

What do you think about introducing GitLocalize?

**Comment by d2lam** [comment]
@catto I didn't try using it but it looks good from the demo video. 

> It makes translation reviewable and manageable by git

This is good. If you want to, you can go ahead and try changing it!

**Comment by catto** [comment]
@d2lam Thanks! I'm going to work on it

**Comment by okuryu** [comment]
+1

**Comment by chikathreesix** [comment]
Thank you for reviewing it, @catto! We'd love to help to migrate all translations into GitLocalize once you integrate the repo with it. cc: @sotayamashita

**Comment by sotayamashita** [comment]
@catto I am creating language switcher for Node.js website but I will make it be OSS. I can help you configure its in your website

**Comment by kumada626** [comment]
I tried GitLocalize on my repository which I forked from screwdriver-cd/guide.
* Automatically generate files and translate image paths.
* Easily review

But there are some issues.
* To show localized pages, we have to edit mkdocs.yml.
* mkdocs does not adopt multi languages, it has to show all languages menu bar like below.
<img width="329" alt="2017-06-24 10 26 07" src="https://user-images.githubusercontent.com/8113204/27504582-a822e730-58c7-11e7-92ce-d6d43115206d.png">

We want to switch these two display.
<img width="1208" alt="2017-06-24 10 36 04" src="https://user-images.githubusercontent.com/8113204/27504643-1b150cae-58c9-11e7-9214-4c09dbc6c50c.png">
<img width="1202" alt="2017-06-24 10 36 52" src="https://user-images.githubusercontent.com/8113204/27504644-1fa80078-58c9-11e7-9a5a-c63597e914c8.png">

Do you have any ideas to switch multi languages using GitLocalize with mkdocs?

**Comment by chikathreesix** [comment]
@kumada626 

Thank you for your feedback!
We are shipping YAML file support in few weeks but if mkdocs doesn't support i18n, that'd be actually hard.

Would it be difficult on your side to migrate to let's say, Jekyll since it supports multi-languages?

**Comment by stjohnjohnson** [comment]
@chikathreesix One of the reasons we picked Mkdocs was for the built-in search feature.  It's totally possible to move to Jekyll, just need to pick a good search plugin.

@kumada626 would you be interested in experimenting with using Jekyll instead of Mkdocs?

**Comment by kumada626** [comment]
@stjohnjohnson I'm interested in experimenting with using Jekyll instead of Mkdocs, but I have never used Jekyll before therefore I don't know a good search plugin of Jekyll.

@chikathreesix It's not certain how it would be difficult because I don't know how Jekyll supports multi-language. However, I think it's worth trying if there is a good search plugin of Jekyll. Do you know any good search plugin of Jekyll?

**Comment by stjohnjohnson** [comment]
@kumada626 Here are two multi-lingual plugins for Jekyll (that are still active):
 - https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin
 - https://github.com/untra/polyglot

Search:
 - https://github.com/christian-fei/Simple-Jekyll-Search

**Comment by kumada626** [comment]
@stjohnjohnson I try experimenting with using Jekyll instead of Mkdocs. https://github.com/screwdriver-cd/guide/pull/88
It seems to work almost like the current pages and still can search. 
In this state of repository, I think that GitLocalize can also be used.
When I actually tried it in my repository, GitLocalize seemed to work well.

**Comment by kumada626** [comment]
To use Gitlocalize, we have to register the screwdriver-cd/guide repo to Gitlocalize like below.
<img width="634" alt="2017-07-20 7 08 29" src="https://user-images.githubusercontent.com/8113204/28391784-4cf50f5c-6d1a-11e7-82cf-da6db630be77.png">
After registering repo to Gitlocalize, we can localize the documents using Gitlocalize.
So please register the screwdriver-cd/guide repo to Gitlocalize.

**Comment by kumada626** [comment]
The GitLocalize project of screwdriver-cd/guide is below.
https://gitlocalize.com/repo/160
Now, we can localize documents by using GitLocalize.
