### ISSUE TITLE
Build createTime > startTime

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#560]
For some builds, the `createTime` is somehow after the `startTime`. Example:
```
createTime: "2017-05-24T18:18:04.214Z",
startTime: "2017-05-24T18:16:45.553Z",
endTime: "2017-05-24T18:16:49.957Z"
```

This leads to wrong order of builds, which causes this: https://github.com/screwdriver-cd/screwdriver/issues/555

Initial investigation shows that it's impossible for this to happen. `createTime` is set before `start()`: https://github.com/screwdriver-cd/models/blob/master/lib/buildFactory.js#L171-L176 and it's a promise. So not sure how this happened.

**Comment by stjohnjohnson** [comment]
@d2lam didn't we discover this was due to NTP drift on the build nodes?

**Comment by d2lam** [comment]
Yes, this issue was created and we looked into the problem afterward. Forgot to update the ticket. It is due to time drift.
