### ISSUE TITLE
Able to change repo/branch

### ISSUE THREAD

**Issue by hui-yang** [screwdriver-cd/screwdriver#562]
I want to be able to change the git repo and branch after a project is created. So I don't have to go through setup like secrets again.

---
### Data Schema

- [x] Schema for updating a pipeline (https://github.com/screwdriver-cd/data-schema/pull/148)

### Models

- [x] Add update method for pipeline (https://github.com/screwdriver-cd/models/pull/176)

### API

- [x] Add a PUT route for updating pipelines (https://github.com/screwdriver-cd/screwdriver/pull/627)
- [x] Feature file (https://github.com/screwdriver-cd/screwdriver/pull/629)
- [ ] ~~Feature tests~~ _deferred_

### UI

- [x] Add edit panel on UI (https://github.com/screwdriver-cd/ui/pull/177)

## Outcome

- [ ] ~~Passing acceptance tests described in feature file~~ _deferred_
- [x] Documentation (https://github.com/screwdriver-cd/guide/pull/87)
- [ ] ~~Blog post~~

### 2017-06-20
- Added implementation spec

### 2017-06-27
- Added link to API PR

### 2017-06-29
- Added link to feature file PR

### 2017-06-30
- Added link to UI PR
- Removed passing acceptance tests requirement. Deferred to a later time.

### 2017-07-05
- Added link to guide PR
- Remove blog post requirement (the feature is pretty small)

**Comment by stjohnjohnson** [comment]
Totally reasonable.  I can't think of a reason why it wouldn't be possible.

- Need to add PUT on /v4/pipelines so we can update the URLs
- Need to add edit panel on UI

**Comment by tkyi** [comment]
What would the UPDATE take in? Should users update a `checkoutUrl` string or an `scmRepo` object?

**Comment by tkyi** [comment]
Getting an error when clicking Update now:
```
vendor-76a97f1….js:2167 TypeError: n.set is not a function
    at o.updatePipeline (screwdriver-ui-d4f0565….js:144)
    at e.join (vendor-76a97f1….js:1397)
    at Function.Be.join (vendor-76a97f1….js:2320)
    at vendor-76a97f1….js:1760
    at e.flaggedInstrument (vendor-76a97f1….js:2310)
    at vendor-76a97f1….js:1760
    at o.updatePipeline (screwdriver-ui-d4f0565….js:73)
    at o.send (vendor-76a97f1….js:3094)
    at o.n [as send] (vendor-76a97f1….js:3048)
    at vendor-76a97f1….js:1831
```
https://github.com/screwdriver-cd/ui/blob/master/app/pipeline/options/controller.js#L21
