### ISSUE TITLE
Cluster-wide Announcement

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#566]
One of our Screwdriver clusters has some custom bookends installed. One of those bookends was experiencing failures, which the operations team was addressing but the users were not uniformly aware.

It would be nice to have a way of sending out a kind of announcement or post a banner on the UI to inform all visitors that they may experience issues or that the cluster maintainers are investigating the problem.

**Comment by tkyi** [comment]
This issue is duplicated by https://github.com/screwdriver-cd/screwdriver/issues/966. Closing this one and tracking work in the other one.
