### ISSUE TITLE
Enforce Login

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#572]
We've noticed that some teams would like to require that only authenticated users can view the pipelines.  Thus preventing leaking of information to those without authentication.

We should have a feature to require all calls to be authenticated.

**Comment by d2lam** [comment]
This is a little confusing to me. Wouldn't this be accomplished by https://github.com/screwdriver-cd/screwdriver/issues/466? 

If read protection is implemented, then only people who have read permission to the repo can view the pipeline. What is the difference between these 2 issues?

**Comment by stjohnjohnson** [comment]
@d2lam, would #466 require logins?  Would there still be a logged-out experience?  If not, then this would be resolved by that one.

If there is still a logged-out experience, where I can visit things like https://cd.screwdriver.cd/pipelines/7.  Then it should be an option to require login (for companies with GHE as an example).

**Comment by d2lam** [comment]
I see. I didn't think that we would keep the logged-out experience. I'm not sure if I would care about some random public pipelines if I'm a user.

**Comment by stjohnjohnson** [comment]
@d2lam then that will affect how we design the UI.  There's no point to a login button since all access will send me there.

**Comment by d2lam** [comment]
Yup. Just my personal opinion. We can always discuss as a team & keep this ticket opened.

**Comment by stjohnjohnson** [comment]
Closing in favor of https://github.com/screwdriver-cd/screwdriver/issues/870
