### ISSUE TITLE
Ability to disable auto-starting PRs when from a fork

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#579]
Right now, if I want to add secrets into my PR (for doing things like deploying to a staging env), then I risk someone giving me a PR that dumps all my secrets.

Instead, I would like the option to opt-in to PRs provided not from a local branch.  That way they show up in Screwdriver, but don't automatically run on create or synchronize.

Ideally, I would want the GItHub status field to be populated with something like "Build Pending Collaborator Approval"

**Comment by stjohnjohnson** [comment]
## 2/24

 - Working on propagating a new field (source) from the pull-request
 - Adding pipeline-level annotations to specify when auto-start is deferred (default none): `beta.screwdriver.cd/restrict-pr`
 - Planning on adding a cluster-level feature to change the default.
 - Need to add documentation.
 - Unsure about how to appropriately signify to the PR that the build was not started due to fork/branch mode (since commit status is tied closely to the build operation).

**Comment by stjohnjohnson** [comment]
## 2/25

 - Pipeline-level config is available (in a PR).
 - No clear place for where to add cluster-level feature.  `scms` is a map of different SCMs, not sure where this setting should go.

**Comment by d2lam** [comment]
This feature should be done. 
Users can restrict PRs using pipeline-level `screwdriver.cd/restrictPR` annotation. 
Cluster admins can set default behavior using `RESTRICT_PR` environment variable
Guide: https://docs.screwdriver.cd/user-guide/configuration/annotations
