### ISSUE TITLE
Recent UI bugs

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#584]
Just wanted to bring these up in one thread:
 - [x] Banner takes up extra space on pipeline page
 - [x] Start button is offset out of the page
 - [x] Header switches into hamburger under 1230px (which is pretty big)
 - [x] Header looks crazy at exactly 1230px
 - [x] Pipeline search bar takes up too much space
 - [x] Color of tabs on Pipeline page hard to read
 - [x] In hamburger mode, hover is centered on the page which is confusing
 - [ ] In hamburger mode, there is a left-right scrollbar

----
<img width="1086" alt="screen shot 2017-06-07 at 12 37 59 pm" src="https://user-images.githubusercontent.com/622065/26897809-9f231caa-4b7e-11e7-8aef-cb75333babc2.png">
<img width="1212" alt="screen shot 2017-06-07 at 12 40 30 pm" src="https://user-images.githubusercontent.com/622065/26897811-9f2fc342-4b7e-11e7-938b-c296d4bb1aa5.png">
<img width="1076" alt="screen shot 2017-06-07 at 12 41 03 pm" src="https://user-images.githubusercontent.com/622065/26897810-9f2a74e6-4b7e-11e7-8caa-992780ed08b7.png">

**Comment by petey** [comment]
We will look at this.

The spec we were given for the current header set the large size of the search bar, which then necessitated the hamburger showing up at an excessive size. I'd prefer to have a smaller search bar, and fewer icons in the header.

**Comment by petey** [comment]
I haven't been able to reproduce a scrollbar appearing when the navbar is collapsed.
