### ISSUE TITLE
Pull Request context makes it impossible to use 

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#594]
![screen shot 2017-06-09 at 10 06 40 am](https://user-images.githubusercontent.com/622065/26986206-599e570c-4cfb-11e7-8cde-edb508c29706.png)

We should change our Context to be in the format:
```
Screwdriver/$pipeline_id/$job
```

Where `$job` is `PR` when it's a PR.

https://github.com/screwdriver-cd/scm-github/blob/ec86a4ea12ad585f92e86fa19874196660c719ca/index.js#L417

**Comment by petey** [comment]
👍

**Comment by d2lam** [comment]
We can change it. But I don't understand why it's impossible to use? You get to this page by clicking on `settings` for that specific repo, so it's implied that these contexts are for that `pipeline_id`. Right?
