### ISSUE TITLE
No logs displayed in build when no screwdriver config

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#599]
Similar to issue #593, when no screwdriver.yaml is present in the repo, and a build is run, we display the "parse error" build, but no logs are displayed.

https://cd.screwdriver.cd/pipelines/101/builds/5307

**Comment by d2lam** [comment]
This should be fixed:
![screen shot 2017-09-27 at 11 02 18 am](https://user-images.githubusercontent.com/3401924/30929554-ba0f15a8-a373-11e7-92d6-967d06ce4009.png)

![screen shot 2017-09-27 at 11 03 42 am](https://user-images.githubusercontent.com/3401924/30929561-bd72a2d2-a373-11e7-9dcd-296cc287febc.png)
