### ISSUE TITLE
Support for Multiple Executors

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#604]
## Summary 

Currently, Screwdriver.CD only supports a single executor strategy for running and managing builds. This works very well for tech ecosystems that maintain one executing infrastructure. 

This enhancement aims to allow the executor strategy to be configurable on a per-build basis. By allowing the user to utilize annotations, they can determine which executor strategy best helps with their jobs. 

In other words, users will be able to specify multiple executors in their configurations. We will replace the singular `executor-<>` with an `executor-router`, which will essentially act as a giant switch statement to handle the logic of deciding which executor to use (based on which annotations are passed in when a build is started). The `executor-router` will determine which `executor-<>` to use and the `executor-<>` should work as it always has.

### Data Schema

- [x] Allow annotations to be passed to methods of `executor-*` components (https://github.com/screwdriver-cd/data-schema/pull/146, https://github.com/screwdriver-cd/data-schema/pull/150)

### Executor Router

- [x] Constructs with list of executor plugins (https://github.com/screwdriver-cd/executor-router/pull/5, https://github.com/screwdriver-cd/executor-router/pull/6, https://github.com/screwdriver-cd/executor-router/pull/7, https://github.com/screwdriver-cd/executor-router/pull/8)
   - [x] Leverages annotations to determine which strategy to use
   - [x] Default strategy is always the first plugin given
      - [x] Use the default when no annotation is given
      - [x] Use the default when a non-existing annotation is given

### API

- [x] Update the `default.yaml` config for the executor stanza https://github.com/screwdriver-cd/screwdriver/pull/607
   - [x] `plugin` is the default plugin (see `plugin` here: https://github.com/screwdriver-cd/screwdriver/blob/master/config/default.yaml#L89)
   - [x] Always load the `executor-router` plugin , and construct it with the config values in `executor`.
   

## Outcome

- [x] API can communicate with multiple executors
- [x] Annotations are used to route builds to the correct executor
   - [x] If an annotation is not defined, the default executor is used

## Discussion Items

* Feature test

## References

* Parent issue: #595 
* Kubernetes Annotations (for inspiration): https://kubernetes.io/docs/reference/labels-annotations-taints/

### 2017-06-13

* Initial spec
* Added executor-router explanation to Summary

### 2017-06-14

* Added link to executor-router PR
* Added Kubernetes Annotations link
* Replaced executor-strategy with executor-router

### 2017-06-15

* Crossed out requirement under API
* Added links to new PRs for executor-router and API

### 2017-06-23

* Updated with another link to PR in executor-router
* Updated requirements for API

**Comment by FenrirUnbound** [comment]
## **Summary 2017-06-14**

### Executor Router

Started & completed. Merged in screwdriver-cd/executor-router#5

### API

Initial investigation and determined where the changes should exist, but no work committed.

**Comment by FenrirUnbound** [comment]
For a feature test, we should defer it to the `executor-k8s-vm` work. As long as the VM annotation uses the VM executor, it should validate that this effort works in routing to the correct strategy.

**Comment by tkyi** [comment]
Will that feature test live in the Screwdriver API repo or the `executor-k8s-vm` repo?

**Comment by d2lam** [comment]
Done!
