### ISSUE TITLE
Pipeline API tokens

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#614]
Similar to User API tokens, but scoped to a specific pipeline.

**Comment by kumada626** [comment]
## Proposal
We designed Pipeline API tokens as below.

Rules:
- Tokens should be specifically tied to the Pipeline that issued them
- Tokens should have a label/name associated with them
- No one can ever look up the raw value after initially generating the token

Users who are admins of the pipeline that issued token can below.
- Users can add a description to Pipeline tokens, so they know what they're using them for
- Users can revoke a token at any time
- User can see when a token was last used

Difference from User API token:
- scope: the Pipeline API tokens only interact with Screwdriver API which is related to the Pipeline.
- The Pipeline tokens can be created, regenerated, edited and deleted by the members who can edit its pipeline's secrets.

UI:
The Pipeline tokens can be generated, listed and deleted from the Pipeline's secret tab like below:

<img width="1116" alt="2018-05-23 14 51 39" src="https://user-images.githubusercontent.com/8113204/40406145-81434374-5e9a-11e8-8d5e-27551c0c7dcf.png">

or, from an another tab for token.
Flows of creating, regenerating, editing, and deleting pipeline tokens from the UI are the same as User API tokens.

I think the Pipeline tokens should have pipelineId to their data-schema, so we have to create new model for the Pipeline tokens or fix token model.

Please let me know if any points are missing.

**Comment by yuichi10** [comment]
How to store this pipeline token data?

**Comment by kumada626** [comment]
I think it should be the same way of the User API tokens are stored.

**Comment by lgfausak** [comment]
I seems tricky to figure out exactly which api calls could be used.  I imagine, for example, that the ability to create an event on that pipeline would be included?  Will the pipeline token have a different swagger (/v4/documentation) to be explicit about what can be done?

**Comment by kumada626** [comment]
I assume that the ability to create an event on that pipeline would be included. Like the Build token, we'll add `pipeline` to the api scope to restrict the ability of the Pipeline tokens.
https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/builds/get.js#L18
Currently, there is no different swagger for the Build tokens. Therefore, I think that we don't have to prepare another swagger for the Pipeline tokens.

**Comment by tk3fftk** [comment]
What is the API endpoints which generate a pipeline token and obtain JWT based on a pipeline token?

**Comment by kumada626** [comment]
I suppose to generate a pipeline token from `/pipelinetoken` and obtain JWT from `/auth/pipelinetoken/{pipelineId}` like user API token.  Because I think it will be better to new model for the Pipeline tokens, API endpoints also will be different from user API token. The names of API endpoints are examples, actual endpoints names are dependent of implementation.

**Comment by s-yoshika** [comment]
We started this implementation.

### Require Changes
models:
We can reuse `token` and `tokenFactory`(which are used to user token) to pipeline token, because these class have no special codes for user token.

data-schema:
We can almost reuse token schema, but we need to add `pipelineId` to token schema.

screwdriver: 
API design like below (as like /v4/tokens):
POST /v4/pipeline/{id}/tokens:    generate a new pipeline token
DEL   /v4/pipeline/{id}/tokens:     delete a pipeline token
PUT   /v4/pipeline/{id}/tokens/{tokenId}:   update a pipeline token
PUT   /v4/pipeline/{id}/tokens/{tokenId}/refresh:  refresh a pipeline token

We use pipeline scope as a new scope for pipeline tokens, so each pipeline and build API need to allow this scope.

**Comment by tkyi** [comment]
Probably need a `tokenId` for the delete, or you have have both endpoints:
DEL /v4/pipeline/{id}/tokens: delete all pipeline tokens
DEL /v4/pipeline/{id}/tokens/{tokenId}: delete a pipeline token

**Comment by s-yoshika** [comment]
@tkyi Thanks! you are right, so I added them.

**Comment by s-yoshika** [comment]
### Profile for credentials
The profile of pipeline API token is below.
```
username: The name of admin user.
pipeineId: The id of pipeline which pipeline API token is allowed
scmContext: scm which the pipeline belong to
scope: pipeline scope
```
the `username` is required for scm permission check, but pipeline API token does not want to associate with a specific user. If we associate it with a specific user, the token becomes invalid when that user leaves the admin in the repository, which is not much different from using the user API token. Therefore, we use admin as the username of pipeline API token.

**Comment by jithin1987** [comment]
Let's relax the same pipeline requirement for `GET` endpoints so that people who want to script can use pipeline tokens and not be forced to create multiple pipeline tokens for each pipeline they want to script. Else they will just fall back on user access tokens.

**Comment by minz1027** [comment]
@s-yoshika There is another thing is not covered by current implementation, the `lastUsed` field. For user accessToken, whenever it's used, we will update the `lastUsed` field. But that part is missing for pipeline token. Can refer to this PR for more details:
https://github.com/screwdriver-cd/screwdriver/pull/1138

**Comment by s-yoshika** [comment]
@minz1027  Thank you! I will fix to update the `lastUsed` of pipeline token as well as user token.

**Comment by tkyi** [comment]
This feature is available now: http://blog.screwdriver.cd/post/175722652927/pipeline-api-tokens-in-screwdriver
