### ISSUE TITLE
Allow for customization of resources

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#631]
> As a developer, I want to be able to ask for more or less resources to accomplish my job, because each job may use different resources.

As an example, for unit and functional tests of Screwdriver, it would be good to have more CPUs available.  With the deploy jobs, we wouldn't need more than 1 CPU and probably less memory.

As an admin, I should be able to customize how many resources are being used per executor.  As a user, I should be able to hint (via annotation?) which executor would best fit my needs.

**Comment by jithin1987** [comment]
I've split this into multiple issues which can be tackled separately #757 #758 #759

**Comment by d2lam** [comment]
Closing since we split this into different issues.
