### ISSUE TITLE
Cannot `alter table` with current sequelize pkg

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#633]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Screwdriver.cd version**: All

We are having problem adding a new column to existing tables since `sequelize` 3.X do not support `alter table` during sync. We tried to upgrade to `sequelize` 4.X but there is a bug in the pkg itself. So it is not working for us currently.

PR that pulled in 4.X: https://github.com/screwdriver-cd/datastore-sequelize/pull/18 

Issue open in `sequelize` repo: https://github.com/sequelize/sequelize/issues/7758
We have a fix PR open: https://github.com/sequelize/sequelize/pull/7759

**Comment by minz1027** [comment]
Petey's PR has been merged and released
https://github.com/sequelize/sequelize/commit/a7f18ba689d9a12191f400cc75e34b06e2f476df
We should pull it in to Screwdriver API and test it out.

**Comment by d2lam** [comment]
This is done
