### ISSUE TITLE
sha shouldn't be optional

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#64]
Build model's create expects sha to be there. 

Right now we only care about Pull request, so we get the sha from the payload. If it's not PR, this value will be undefined and create build will break. We need to do some lookup to get the sha before calling create. 

https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/github.js

**Comment by stjohnjohnson** [comment]
@d2lam This should be resolved with https://github.com/screwdriver-cd/models/pull/30 and https://github.com/screwdriver-cd/screwdriver/pull/75 Right?

**Comment by d2lam** [comment]
Yup. It's resolved.
