### ISSUE TITLE
Shared step cli has a leaky abstraction

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#650]
Shared step feature has been implemented at #300 and is available now.
But I think it's a bit verbose that we have to specify "exec" subcommand to the cli.

> sd-step exec --pkg-version "~2.7.0" core/git "git clone https://github.com/screwdriver-cd/screwdriver"

We might want to change the cli to allow shorthand usage like this:
> sd-step core/git@~2.7.0 git clone https://github.com/screwdriver-cd/screwdriver

* Omit `exec` subcommand
* Merge pkg-version option and package name using `@`
* Pass actual commands as arguments without double quotes

How do you think about this change?

**Comment by stjohnjohnson** [comment]
I would argue that it should be less verbose from that.  Something like:

```
sd-step git@~2.7.0 clone screwdriver-cd/screwdriver
```

I think tight dependency on Habitat interface is the dangerous part.  If we used it as a packaging and dependency management system, that would be safer.  So if all Screwdriver steps ran habitat packages that started with `screwdrivercd/` and they always executed a binary called `step` or something like that.

Example:
 - User runs command above
 - Internally we run `hab exec --pkg-version "~2.7.0" screwdriver-cd/git step clone screwdriver-cd/screwdriver`

What do you think @jer and @petey

**Comment by stjohnjohnson** [comment]
Actually, if I were to go one step further, I would expect our bookends to just be shared steps.  For example:

```bash
$ sd-step bookend-scm@~1.0.0 --repo="github.com/screwdriver-cd/screwdriver" --revision="e1ec7dd1f5e06aedad24550801f09e7afca8f7d8"
```

That `screwdrivercd/bookend-scm` hab package depends on Git and is able to do everything we need for scm setup.  It also means:
 - We can display things in a more user-friendly way
 - We can ship out changes to the bookend without updating the api image and node module (as long as we conform to semver).

**Comment by d2lam** [comment]
Tracking this in https://github.com/screwdriver-cd/screwdriver/issues/677
