### ISSUE TITLE
VM in k8s is slow in AWS

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#652]
### Problem
vm builds are 5 times slower than non-vm builds on AWS for cpu intensive commands, e.g. hab install, docker build etc.

### Investigation
I exec into the vm and non-vm builds and do a `top`:

- `hab` is taking up almost 100% of cpu in both builds when it tries to install pkgs during the beginning
- But it is much faster in the non-vm builds

To test out the cpu performance, I use `sysbench` on both vm and non-vm container to find the max prime number under 10000:
- vm takes 38 seconds
- non-vm takes 12 seconds

Try adding more cpus to the vm:
- Does not help a lot
- Confirmed with Habitat team, `hab install` is single thread

### Possible cause
- EC2 is also virtualization. Having nested virtualization may affect the performance of the cpu in vm. We are using `qemu` without `kvm` acceleration, which is just a emulation software and has no direct access to the hardware.

**Comment by minz1027** [comment]
How to check if kvm hardware acceleration is on:
https://www.linux-kvm.org/page/FAQ#How_can_I_check_that_I.27m_not_falling_back_to_QEMU_with_no_hardware_acceleration.3F

**Comment by jithine** [comment]
Not likely to solve, since we are not exploring VMs for AWS builds. cc https://github.com/screwdriver-cd/screwdriver/issues/2550
