### ISSUE TITLE
[UI] Cannot see logs on iPhone

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#655]
Cannot see build logs on iPhone. I click on the step but nothing happens.

Logs load without problem on Ian's Android phone.

**Comment by petey** [comment]
I think we may not be listening to the correct Safari UIWebComponent events to process the clicks in that component.

**Comment by stjohnjohnson** [comment]
Duplicate of https://github.com/screwdriver-cd/screwdriver/issues/486
