### ISSUE TITLE
[431] Redis Cluster

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#661]
The current candidate for Screwdriver's queuing mechanism is to use Resque, which is based on [Redis](https://redis.io/). This means that we will need to have a Redis cluster readily available, whether through an external vendor or hosted by our own means. 

This issue is to track and plan the effort required to hosting it ourselves.

-----

### Fault Tolerance

The criteria to learn here is how to maintain a highly-available cluster. 

* Redis Sentinel
   * [ ] Understand behavior when the Redis cluster goes down
   * [ ] Understand behavior when the Redis sentinels go down
   * [ ] Stretch: Sharing state between separate Redis clusters

### Security

The KPR to achieve here is how to securely host and deploy a Redis cluster. 

* [ ] Password-protected connection

### Pipeline

The objective here is to formalize a deployment strategy for a Redis cluster into Kubernetes

* [ ] Add objectives

## References

* Screwdriver Queue - #431 
   * [MVP Criteria](https://github.com/screwdriver-cd/screwdriver/issues/431#issuecomment-309840508)
* [Resque](https://github.com/resque/resque)
* [Node Resque](https://github.com/taskrabbit/node-resque)
* [Redis](https://redis.io/)
   * [Redis High-Availability](https://redis.io/topics/sentinel)

### 2017-07-24

* Initial spec
   * Objectives for Fault Tolerance, Security

**Comment by stjohnjohnson** [comment]
@FenrirUnbound what work here is still left?

**Comment by catto** [comment]
I have modified my cluster to use a high available redis cluster using sentinel on my k8s cluster.
It just exports master's endpoint as k8s service and it works with simply specifying it to SD API.
But we still might want to support specifying sentinel config to work with non-k8s env as described in this issue.

**Comment by FenrirUnbound** [comment]
> I have modified my cluster to use a high available redis cluster using sentinel on my k8s cluster.
It just exports master's endpoint as k8s service and it works with simply specifying it to SD API.
But we still might want to support specifying sentinel config to work with non-k8s env as described in this issue.

I'm curious to know if you have tested how resilient it is when it fails over. 

When we initially set up an HA Redis cluster, all of our testing showed that it recovered much slower than deploying a StatefulSet in Kubernetes and allowing Kubernetes to maintain the service. If my memory serves me correctly, our "Doomsday" exercises discovered this much:

The workflow for an HA redis cluster recovery was:
• Redis master goes down
• `x` number of sentinel checks fail for the current master. This can happen over `n` minutes.
• `y` seconds pass while the sentinels determine which redis to promote to master
• `z` amount of time passes for the clients to eventually connect to the new master. The time it took to recover was never consistent in our tests.

In the event that the master went down, some `m` number of minutes pass until a new master is elected and receives updates. In those `m` minutes, none of those updates are persisted or queued; they were essentially dropped. We essentially experienced data loss for those `m` number of minutes.

The workflow for a StatefulSet Redis cluster was:
• Redis master goes down
• Kubernetes spins up a new pod in < 15 seconds.

In the event that the master went down, we would only lose data for a matter of seconds instead of minutes. This ultimately pushed us away from pursuing this in the first place, and it's why we abandoned it.

In a non-Kubernetes environment, this would definitely have been a desirable setup.

**Comment by FenrirUnbound** [comment]
One thing we didn't try was AWS' Redis service: https://aws.amazon.com/redis/

Last year, they didn't provide the ability to password-protect the master; the only security measures available were network-level ACLs. Last I checked, they now have offer the ability to password-protect the master and allow TLS-based communication. If cloud is an option, I would highly consider investigating that as a possible solution for users that can leverage it.

**Comment by jithin1987** [comment]
We don't use redis for queuing and now have a HA RabbitMQ cluster. Removing redis altogether from our architecture will be addressed at a later point.
