### ISSUE TITLE
Bootstrap Tables

### ISSUE THREAD

**Issue by ian-fox** [screwdriver-cd/screwdriver#662]
**FEATURE REQUEST**

Ember bootstrap has an [[addon]](https://github.com/radireddy/ember-bootstrap-table) for [[bootstrap tables]](https://v4-alpha.getbootstrap.com/content/tables/). 

Switching our tables to these would allow users to filter/sort by various columns, and enable pagination.

**Comment by jithin1987** [comment]
Not planning this hard switch. Any changes in libraries will be addressed based on use-cases to support.
