### ISSUE TITLE
Display information about environment before start

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#665]
In other services like Travis, Jenkins, Wercker, etc. the first command they run shows information about the environment.  Items like:

 - User
 - OS Version
 - SD Version
 - Docker Container SHA

### Travis
![screen shot 2017-07-26 at 9 51 51 am](https://user-images.githubusercontent.com/622065/28633269-188143a8-71e8-11e7-824d-9b4ddbf45497.png)

## Wercker
![screen shot 2017-07-26 at 9 55 17 am](https://user-images.githubusercontent.com/622065/28633415-94e80512-71e8-11e7-97e2-f8754655d780.png)

**Comment by petey** [comment]
Some of this information is in the build page header, some can be extracted with a little difficulty from the existing bookend steps. 

Customers I have talked to have expressed very little interest in the output of the bookends, instead asking that those are further hidden from them in the UI.

**Comment by stjohnjohnson** [comment]
Well most of it is actually metadata inside the container.  And I agree it should be hidden by default, but it should also be there if we want to debug.  Like what user is this build running as right now?

**Comment by jpcollins** [comment]
Agree with St John's point.  We want it for debugging but hidden by default.

**Comment by stjohnjohnson** [comment]
We now show some of that information:
<img width="1395" alt="screen shot 2018-03-11 at 11 47 30 pm" src="https://user-images.githubusercontent.com/622065/37269192-9d764200-2586-11e8-9211-debf1c4c1d5d.png">

Code here: https://github.com/screwdriver-cd/launcher/blob/45da1242b84117ad5738d3d7d7b10d133f18d62b/launch.go#L297-L304

We should add more to it as we keep adding features.
