### ISSUE TITLE
Build fails in sd-setup-scm when using Docker image with non-root user

### ISSUE THREAD

**Issue by bjorncs** [screwdriver-cd/screwdriver#666]
Hi. 

I have a pipeline using a custom Docker image on cd.screwdriver.cd. The build fails with the error _Installing a package requires root or administrator privileges. Please retry this command as a super user or use a privilege-granting facility such as sudo._ in the _sd-setup-scm_ step. Our image uses a non-root user (although with passwordless sudo access). 

Build output: https://cd.screwdriver.cd/pipelines/287/builds/8013

Thanks!

**Comment by petey** [comment]
@catto Does `hab` require installation to be run as the root user? If so, this bookend needs to be fixed.

**Comment by catto** [comment]
@petey Yes, `hab` requires the root privileges since v0.11.0. The issue seems to be resolved if we add `sudo` to sd-step command in the bookend, but root user would be the owner of the workspace in this case.

I think we have two options as below.
* Let `sd-step` running only `hab install` as root.
* Revert the use of `sd-step` in scm bookends.

But let's do latter one for quick fix. I'll submit a PR for it, so please merge it if okay.

**Comment by stjohnjohnson** [comment]
@catto does it require root for exec as well as install?  If it's just install, then we should attempt to sudo install.

Probably around here: https://github.com/screwdriver-cd/sd-step/blob/master/sd-step.go#L79

If we sudo the install but not the exec, the workspace won't be written as root.

**Comment by catto** [comment]
@stjohnjohnson Exactly. But how about the container with no sudo commands? For instance, `node:6` container doesn't have it.

**Comment by stjohnjohnson** [comment]
@catto then I propose the following flow:
 1. Check if we are `root`, if so `hab install`
 2. If not, check if `sudo` exists, if so `sudo hab install`
 3. Attempt to run `hab install` anyway

**Comment by jithin1987** [comment]
@catto @stjohnjohnson you could do something like 
```
(command -v hab >/dev/null 2>&1 && (([ "`whoami`" == "root" ] && echo "I am root" && hab install) ||  (command -v sudo >/dev/null 2>&1 && echo "I am sudo" && hab install))) || echo "Cannot run hab"
```

**Comment by catto** [comment]
Sorry for the delay and thank you for the comment. I'm interested in detecting root user with `user` package in go. I'll fix the issue on this weekend.

**Comment by d2lam** [comment]
Thanks @catto
