### ISSUE TITLE
User Login UX is not optimal

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#670]
It is somewhat difficult to users to understand if they are logged in or not. We've already made some changes to the pipeline page to address this, but can do more in the header to indicate when a user should log in.

**Comment by tkyi** [comment]
Some ideas to make it more obvious:
- showing the user profile picture when logged in
- showing a **Sign In** message (like Github) when not logged in

**Comment by jithin1987** [comment]
Closing this. Any further updates will be addressed in header refresh.
