### ISSUE TITLE
Display reason an event and build was triggered.

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#671]
The current view of a pipeline shows the list of triggered events, but there is no indication of whether that event was triggered by a user, or by a code change. It is difficult to distinguish between events that have the same SCM sha.

**Comment by jithin1987** [comment]
This information (cause message) is available if user hovers of the commit sha on event list. But we should show it in main graph section on right side as well.

**Comment by tkyi** [comment]
Should be resolved by "Started by" and "Committed by" taglines
<img width="414" alt="Screen Shot 2022-07-14 at 6 16 57 PM" src="https://user-images.githubusercontent.com/3230529/179127393-447cb017-fb22-45d8-a976-a3baf693af64.png">
