### ISSUE TITLE
Display custom meta information per step in build

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#674]
It would be interesting to define a standard for meta in which users could supply some data in the build that could be surfaced to the build page. 

For Example:
```
meta set step.test.ui_output "Tests: 889/889 Coverage: 98%"
```
Results in:
![screen shot 2017-07-28 at 11 21 31 am](https://user-images.githubusercontent.com/78533/28731117-74446e68-7387-11e7-991b-552a24392c04.png)

**Comment by stjohnjohnson** [comment]
I love it!  We just have to take into account that `meta` is global for the entire pipeline, not just the job.

**Comment by marian-r** [comment]
This would be super useful. Currently there is no easy way to see the test results and it is time consuming to dig into the logs.

**Comment by hk-vmg** [comment]
Does this exist now? https://docs.screwdriver.cd/user-guide/metadata#coverage-and-test-results

**Comment by tkyi** [comment]
^Comment related to https://github.com/screwdriver-cd/screwdriver/issues/2287
