### ISSUE TITLE
Freeze windows

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#675]
Context:
=======
As a user, 
I want to configure my jobs to only run during a specific time period,
So I can monitor my system for issues

## Objective:
A freeze window can be defined as an array of cron expressions, wherein each cron specifies a window during which builds are delayed from building. Any builds queued during this time will remain queued until the freeze window is over.

### Configuration
An annotation containing an array of strings of standard CRON syntax, e.g. the following contains two freeze windows:
```
["* * ? * 1", "0-23 0-59 * 1 ?"]
``` 
The first window blocks builds every Monday. The second window blocks builds in January.

Note: The combinations of day of week and day of month are usually invalid. Therefore only one out of day of week and day of month can be specified. The other field should be set to "?". 

Note: If multiple builds are triggered during the freeze window, only one build will be queued and when that job gets to run outside the window, the lastest git sha at that time will be pulled.

### Implementation
- [ ] An annotation allows definition of freeze windows
- [ ] Jobs will be blocked when outside the window
- [ ] Jobs will be collapsed before running in the window.

**Comment by OnTitansShoulder** [comment]
Hello, recently we are trying to add multiple freezeWindows with something like:
```
...
jobs:
  job: sth
    freezeWindows: ['* 17-20 * * 1-5', '* * * * 6-7', '* * 25-31 12 *', '* * 1-3 1 *']
...
```
However the screwdriver.yaml validator gives the following error:
> config-parse-error:
> echo “ValidationError: child “jobs” fails because [child “job1" fails because [child “freezeWindows” fails because [“freezeWindows” at position 1 fails because [“1” Cron expression for freeze windows], “freezeWindows” must be a string]]]“; exit 1

Looks like freezeWindows only takes a string instead of a list? @jithin1987 
Thanks

**Comment by tkyi** [comment]
@OnTitansShoulder The error message is misleading. `freezeWindows` supports an array of strings. Actually, I think those cron expressions are invalid because both day of the week and day of the month cannot be defined; one of those fields needs to be set to `?`.

> The combinations of day of week and day of month are usually invalid. Therefore only one out of day of week and day of month can be specified. The other field should be set to “?”.

https://docs.screwdriver.cd/user-guide/configuration/workflow.html#freeze-windows
