### ISSUE TITLE
Shared Step Improvement

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#677]
List of things we should probably do:

 - [x] Add Readme to https://github.com/screwdriver-cd/sd-step
 - [x] Change CLI interface per https://github.com/screwdriver-cd/screwdriver/issues/650
 - [x] Add design doc to https://github.com/screwdriver-cd/screwdriver
 - [x] Check for root, if not, sudo during install per https://github.com/screwdriver-cd/screwdriver/issues/666
 - [x] Capture logs for debugging if needed instead of sending to `/dev/null`: https://github.com/screwdriver-cd/sd-step/blob/b9cc1857f5d7a39626860193e3da7dddfab1fb99/sd-step.go#L79
 - [ ] Provide option for using alternative sources for hab packages (like artifactory)

**Comment by yuichi10** [comment]
### Summary 16/01/2018
I create sd-cmd which can exec binary commands. But there are no API for sd-cmd now, so I just try sd-cmd by [mock](https://github.com/yuichi10/mock_sd-cmd). 
In this project I do not use `urfave/cli` library because we received many kind of arguments or flags.

I think I can crate almost all function for execute binary but I have one problem for logging.
The problem summary is that I can't output log to file and terminal in right order in real time.
It will be a long sentence, though I will write the detail of this problem to 677-sd-cmd room on Slack.

**Comment by drewfish** [comment]
Some ideas/questions about the [commands design](https://github.com/screwdriver-cd/screwdriver/blob/master/design/commands.md):
* does it make sense to add a link to "habitat"?  I have no idea what that is
* can the same command be called multiple times within the same build? does each invocation get a separate log file?
* presumably there'll be shared steps to provision/release selenium. which team will author those?
* the `$SD_ARTIFACTS_DIR/.sd/commands/namespace/name/version/timestamp.log` directory structure seems overly long
    * something like `$SD_ARTIFACTS_DIR/.sd/commands/{timestamp}-{namespace}-{name}.log` would be nice. would be nice if this log also contains the fully-resolved version of the command as well as it's full invocation (all arguments)

**Comment by stjohnjohnson** [comment]
@drewfish 

 - Good point, sorry. https://www.habitat.sh/
 - Can be called unlimited times.
 - Right now there is no name space restrictions, so it can be anyone.  The thing we haven't thought of yet is how to bundle commands or even templates with SD.
 - I like it, good idea.

And for composition, it's completely possible.  Binary or Habitat package would work fine, Docker commands would not have access to spin up new containers.

**Comment by drewfish** [comment]
The one trick with "this log also contains.. all arguments" is that that might contain the env vars which have the secrets, e.g. `sd_cmd foo/bar@1 --token ${MY_SECRET}`. It might be better if there's a best practice for commands suggesting that they "print invocation details (but not secrets)" as the first thing they do.

**Comment by jithin1987** [comment]
Can we use `sd-cmd` shared command to do validation of the shared command rather than installing a separate npm module `screwdriver-command-validator`

Eg: `sd-cmd validate -f sd-command.yaml`

**Comment by minz1027** [comment]
To add to the validation thing ^^

We can have a command/validate api endpoint and have `sd-cmd validate` hit that endpoint. Something like this: https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/template-validator.js

**Comment by stjohnjohnson** [comment]
@tk3fftk Local mode would be if the package wasn't published to the registry.  Imagine if there was a shared folder of `.hart` files (because Depot is so difficult to setup).  The intent would be to use that.

Interesting catch.  I would say, if we wanted to support local mode, we would need to extend the configuration to replace `package` with `path` for local mode.  That way we could still use `package` for referring to the package when executing.

**Comment by catto** [comment]
Habitat type has been implemented and now we can use it with launcher v4.0.97 or later.
Currently it only supports habitat with remote repository, not local mode.

**Comment by jithin1987** [comment]
@tk3fftk Thanks for this https://github.com/screwdriver-cd/sd-cmd/pull/25 Could also update the docs https://docs.screwdriver.cd/user-guide/commands#creating-a-command with this information ?

**Comment by jithin1987** [comment]
> Provide option for using alternative sources for hab packages (like artifactory)

@catto @tk3fftk could you add the docs for this functionality in guide if this is completed?

**Comment by tk3fftk** [comment]
@jithin1987 We completed the feature of using a local habitat package (`.hart` file).  We also added 
 to the docs about the feature. But other sources (like artifactory) cannot be available. 
@catto Do you have any plan?

**Comment by jithin1987** [comment]
Perhaps we could leave it as enhancement and address in a different issue ?

**Comment by catto** [comment]
Closing via #1128
