### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by Nachtfeuer** [screwdriver-cd/screwdriver#678]
Hi,

I have not yet used screwdriver reading a bit documentation
missing some details.

My Background knowledge:
  - Java, C++, Groovy, Python, Bash
  - Travis CI
  - Jenkinsfile, Pipeline, MultiBranch Pipeline, Job DSL, ...
  - Docker, Packer, Ansible

Questions about Screwdriver to understand the
differences what can be done and what cannot be done:
 - matrix builds like:
    - centos 6, 7, 8, ...
    - python 2.7, 3.3,  3.5, 3.6, pyp2, pypy3, ....
    - cloud region (like AWS: us-east-1, eu-central-1, ...)
 - parametrizable builds?
    - trigger a build for a certain commit, tag or branch
    - partial execution like stopping after regression
    - running just one region (example AWS: us-east-1) only
 - parallelization?
 - blocking mechanism?
   - don't run this project when another project is in progress
     (in Jenkins: don't run this job when another is currently in progress)
 - way to go to deploy per region in cloud?
    - matrix build?
 - different pipelines for one git project:
    - possible?
    - production pipeline (complete ci/cd)
    - pipeline for certain time consuming tests running once the night only (example)
    - pipeline for just verifying the build and junit tests
- archive of build artifacts
 
would you mind to provide some comments, help, advises?

kind regards,
Thomas

**Comment by petey** [comment]
Hi Thomas,

Thanks for taking an interest in Screwdriver. The Screwdriver team is actively working on adding additional features to the product, and many of the things you mentioned are high on our roadmap. You can find the team activity, and the roadmap in our [Github project page](https://github.com/screwdriver-cd/screwdriver/projects/4).

We are currently working on a more [robust queuing system](https://github.com/screwdriver-cd/screwdriver/issues/431) which will be the main building block for many of the things you are looking for.

*Matrix builds*
Matrix builds, with respect to builds that use different container images, [has been documented](http://docs.screwdriver.cd/user-guide/configuration/) to use the form of:
```
jobs:
  mymatrixjob:
    image: mycontainer:{{CONTAINER_VERSION}}
    matrix:  
      CONTAINER_VERSION: [4,5,6]
    ...
```
Where the `mymatrixjob` will spawn three parallel jobs using `mycontainer:4`, `mycontainer:5`, and `mycontainer:6`. This would likely be the route you take for various versions of centos or python. Setting up deployment to various cloud providers might be better accomplished by use of environment variables on a per-job level. We will flesh this out further when we get closer to implementation.

*Parameterized Builds*
What you described as parameterized builds is actually three different features:
* Selective triggering:
    * Screwdriver already supports creating separate pipelines per branch of a repo, and those pipelines will be triggered based on commits to that branch
    * Triggering based on a changes to files in a specific path in a commit, would be covered by our [Subdirectory Support](https://github.com/screwdriver-cd/screwdriver/issues/471) feature, which provides support for monorepos.
    * Triggering based on tag: I'm really not sure what you mean by this? In Git, tags are just a "bookmark" to a repo at a certain SHA. Tagging does not, and should not, trigger a build.
* Partial execution: Already implemented. Any build will stop for any step that exits with a non-zero exit code. It would be up to the consumer to ensure that their regression tests do this.
* Running a deployment for one cloud region: This would fall under "Detached Jobs" or "Partial Pipelines" features. This is pretty high priority on our roadmap, and we've discussed this a lot internally over the last month, but requires some more groundwork to get ready. 

*Parallelization* 
This is currently not implemented, but we are already laying the groundwork for this feature. We have a proposed definition of parallelization in the [workflow configuration](http://docs.screwdriver.cd/user-guide/configuration/), but during discussions about detached jobs, we decided that this will not scale the way we need it to. We have work [high on our roadmap](https://github.com/screwdriver-cd/screwdriver/issues/654), to redefine workflows in a better way to make parallelization easier.

*Blocking Mechanisms*
This is [very high on our backlog](https://github.com/screwdriver-cd/screwdriver/issues/653). I expect us to begin to address this very soon after our queue MVP is done in the next couple weeks.

*Different pipelines for one git project*
This is already partially possible, but would be based on separate branches. 
* Support for monorepos would be provided by way of the [Subdirectory feature](https://github.com/screwdriver-cd/screwdriver/issues/471). This would also allow you to have separate directories containing different configurations for different pipelines.
* Support for multiple workflows from one configuration file is dependent on the outcome of our [Workflow overhaul](https://github.com/screwdriver-cd/screwdriver/issues/654) discussion.

*Archive of build artifacts*
We actually already have this feature! Any files that are present in the path starting with `${SD_ARTIFACTS_DIR}` will be stored in S3, and are available after the build is complete. Links to these files are available on the build page.
