### ISSUE TITLE
UI shows "Assertion Failed" error when a build starts

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#680]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): a BUG REPORT

**Screwdriver.cd version**:
- HEAD of UI(7daaa3f9)
- screwdrivercd/screwdriver:latest
- screwdrivercd/store:latest

**Environment**:
- **Cloud provider or hardware configuration**: VM on Openstack / 2 core / 6G mem
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.2.1511 (Core)

**What happened**:

I tried to customize the UI by building it locally. Here is the commands to reproduce.
```
$ git clone https://github.com/screwdriver-cd/ui.git
$ cd ui
$ npm install
$ bower install
$ vim config/environment.js # to use the local API server
$ vim package.json # to listen with 0.0.0.0:9000
$ npm start
```

Then I started new Screwdriver build from the UI, and I got the error message as below. But the build seems to be started normally.
>  Assertion Failed: You cannot update the id index of an InternalModel once set. Attempted to update 3.

![image](https://user-images.githubusercontent.com/1608595/28855616-d53f62a0-7778-11e7-9de3-1c4d717b23ff.png)

When I use the docker image screwdrivercd/ui:latest from Docker Hub, the error message didn't be shown.
I used the same API server in both cases.

**What you expected to happen**:

Builds start without an error message.

**How to reproduce it** (as minimally and precisely as possible):
Please see the description.

**Anything else we need to know**:
This issue is possibly the same as https://github.com/emberjs/data/issues/4972

**Comment by stjohnjohnson** [comment]
@petey and @catto, is this still an issue?

**Comment by d2lam** [comment]
Haven't seen this error. Since our UI has changed significantly since then, I will assume this is solved. 
@catto  please feel free to reopen if you're still seeing this error.
