### ISSUE TITLE
Export SD_EVENT_ID to build containers

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#681]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): a FEATURE REQUEST

Users can use `SD_PIPELINE_ID` and `SD_BUILD_ID` variable in their build container, but they don't cover all use cases.
It would be nice if builds export `SD_EVENT_ID` environment variable so that they can use it for tagging their artifacts through jobs in a workflow.

For example, an android app with multiple variants in multiple jobs.
> main -> publish-debug -> publish-release

- publish-debug job: myandroidapp-$eventId / variant: debug
- publish-release job: myandroidapp-$eventId / variant: release

Pipeline ID and build ID don't work in this case. A version of app can be used also, but an event ID ensures there is no duplicate of IDs and give a traceability to the artifacts.

Related: https://github.com/screwdriver-cd/screwdriver/issues/671

**Comment by d2lam** [comment]
@catto  It is now exposed
![screen shot 2017-09-29 at 10 53 04 am](https://user-images.githubusercontent.com/3401924/31028847-6760d3cc-a504-11e7-959b-6840bd243171.png)

**Comment by catto** [comment]
Thank you!
