### ISSUE TITLE
PR from personal branch fails to restart

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#689]
**What happened**:
When the PR is on a fork and user click on `restart` to rerun the build, it will fail to find the `sha`. It's because for PR restart, it's cloning from master, then does a `reset --hard sha`, but this `sha` is on the personal branch. 
```
git clone --quiet --progress --branch master $SCM_URL $SD_SOURCE_DIR
git reset --hard 2412f037fc495ee5bd5cc8debad66c81a434b7ba
```
<img width="1317" alt="screen shot 2017-08-09 at 11 39 51 am" src="https://user-images.githubusercontent.com/3401924/29139003-35be4c5a-7cfa-11e7-85e5-e019b6a6e7ca.png">

**How to reproduce it**:
- Fork a repo
- Open a PR, let it run once
- Restart the PR build

**Suggestions for fixing**:
We should probably call [getPRInfo](https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L744) first to get the pr ref then pass it to [build create](
https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/builds/create.js#L80)

**Comment by minz1027** [comment]
Done! It works great.
