### ISSUE TITLE
Workflow Fan-out

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#699]
# Context
As a screwdriver user,
I want to be able to fan out jobs in my workflow,
so I can deploy to multiple regions in parallel.

## Objective
Users can define a workflow that has multiple jobs that are triggered by the completion of another job.

### Tasks
- [x] Fully document the final definitions of a job fan out in the guide for workflows
- [ ] Queue multiple jobs as a result of a successful job completion 
    - [ ] Engine changes
    - [ ] Worker changes(?)

**Comment by tkyi** [comment]
Working without pub sub right now
