### ISSUE TITLE
Workflow Fan-in

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#700]
# Context
As a screwdriver user,
I want to be able to fan in jobs in my workflow,
so I run a test on all deployed regions in one job, after those regions were deployed in parallel.

## Objective
Users can define a workflow that has one jobs that is triggered by the completion of multiple other jobs [with the same initial trigger] finishing successfully.

### Tasks
- [x] Fully document the final definitions of a job fan in in the guide for workflows
- [ ] Queue a job when all the "dependent" jobs have  completed successfully
    - [ ] Engine changes
    - [ ] Worker changes(?)

**Comment by d2lam** [comment]
This feature is done
