### ISSUE TITLE
scm-github does not handle pull_request/review_requested

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#706]
**What happened**:
Currently, server keeps getting error:
```
[request,server,error] data: Error: there is no suitable webhook module
    at async.detect (/usr/src/app/node_modules/screwdriver-scm-router/index.js:108:35)
    at /usr/src/app/node_modules/async/dist/async.js:2779:17
    at /usr/src/app/node_modules/async/dist/async.js:421:16
    at iterateeCallback (/usr/src/app/node_modules/async/dist/async.js:928:24)
    at /usr/src/app/node_modules/async/dist/async.js:906:16
    at /usr/src/app/node_modules/async/dist/async.js:2772:21
    at scm.canHandleWebhook.then (/usr/src/app/node_modules/screwdriver-scm-router/index.js:102:25)
    at runMicrotasksCallback (internal/process/next_tick.js:64:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

```
whenever it receives a payload for `review_requested`. 

Github categorizes `review_requested` as a `pull_request` event. However, we don't have a special case to handle this. So it gets to [here](https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L811-L825) and tries to get the [`repository.ssh_url`](https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L649), but this field does  not exist in the payload.

**Comment by petey** [comment]
We shouldn't need a special handler. We have a whitelist of accepted events: https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L660-L662

**Comment by d2lam** [comment]
You're right. It doesn't get to the `repository.ssh_url` yet. Instead, it returns false before that [on this line](https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L814-L816)

When it gets to `scm-router`, it calls `canHandleWebhook`, and since that returns false, it will get to the error `there is no suitable webhook module` (https://github.com/screwdriver-cd/scm-router/blob/master/index.js#L100-L109)

I think ideally it shouldn't get to that error. It's very confusing looking at that log right now.

**Comment by d2lam** [comment]
I'm ok with keeping it as is since this is on the server logs. It behaves like this for all the non-handled events as well as the error cases, so it's hard to customize the error message.
