### ISSUE TITLE
Queue Circuit Breaker On When reconnect to Redis

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#710]
We will try to connect to Redis for every single request.
If we try to reconnect while it's still connected. Node-resque won't do anything, won't return callback. That leads to circuit breaker timeout since it cannot get anything in return.
https://github.com/screwdriver-cd/executor-queue/blob/master/index.js#L47
https://github.com/taskrabbit/node-resque/blob/master/lib/connection.js#L67

I have an issue open at node-resque to ask why they design it like this.
https://github.com/taskrabbit/node-resque/issues/211

For now, we will just have a check to see if the queue is connected before another connect.

**Comment by petey** [comment]
Fixed by https://github.com/screwdriver-cd/executor-queue/pull/8
