### ISSUE TITLE
"Secrets" tab is blank if user doesn't have perms

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#715]
**BUG REPORT**

**Screwdriver.cd version**: https://cd.screwdriver.cd/ on Tue Aug 22 22:50:34 UTC 2017

**What happened**:
* visited a random pipeline, e.g. https://cd.screwdriver.cd/pipelines/62
* clicked the "Secrets" tab
* saw a blank page (only standard header)

**What you expected to happen**:
* see some nice message explaining that I don't have permissions to see the secrets

**Comment by d2lam** [comment]
Sounds right. We will pick this up during our HIP sprint.
