### ISSUE TITLE
Bug: Artifacts should be listed in alphabetical order

### ISSUE THREAD

**Issue by r3rastogi** [screwdriver-cd/screwdriver#719]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Screwdriver.cd version**: 0.5.30

**What you expected to happen**: Deploy artifacts should be listed alphabetically, instead of whatever order `ls` uses.

**How to reproduce it** (as minimally and precisely as possible): Deploy a bunch of artifacts and see that the artifacts list upon a successful deploy is not in any reasonable order.

**Comment by drewfish** [comment]
I'm also seeing artifacts listed in an unknown order on my build page:
https://screwdriver.ouroath.com/pipelines/1000466/builds/58249
