### ISSUE TITLE
Bug: UI can not add Secrets multiple times without browser refresh 

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#720]
**Screwdriver.cd version**: 
- api: v0.5.18
- ui: v1.0.174
- store: v2.2.1

**Environment**:
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.3.1611 (Core)

**What happened**:
I could not add Secrets multiple times without browser refresh.

**What you expected to happen**:
I can add Secrets multiple times without browser refresh.

**How to reproduce it** (as minimally and precisely as possible):
Add something secret. We can push the Add button after fill in the form.
![image](https://user-images.githubusercontent.com/3445553/29699948-d0833ab8-899b-11e7-8ba7-9d5d654618fd.png)

Then, try to add another secret without browser refresh. We can not push the Add button despite of fill in the form.
![image](https://user-images.githubusercontent.com/3445553/29699950-db41d284-899b-11e7-8dd2-89dfe5ccd856.png)

We can add secret after browser refresh.
![image](https://user-images.githubusercontent.com/3445553/29699954-e1913fc6-899b-11e7-8b07-5c51e94a86c8.png)

**Comment by stjohnjohnson** [comment]
Resolved in your PR.  Thanks!
