### ISSUE TITLE
Add to collection dropdown

### ISSUE THREAD

**Issue by joelseq** [screwdriver-cd/screwdriver#727]
Currently if you don't have any collections and try to add a pipeline to a collection by clicking the "+" button on the search page, it shows an empty div.

![image](https://user-images.githubusercontent.com/12389411/29848302-8f3b8c7c-8cd4-11e7-912d-b49c8557ecef.png)

**Expected Outcome**: There should be a message telling the user that they don't own any collections and/or allow users to create a collection from the dropdown.

**Comment by jithin1987** [comment]
Now we allow users to create collection.
