### ISSUE TITLE
git-tag.sh didn't work with latest golang image

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#729]
Builds are failing at the git-tag step for launcher:
To be specific, it failed to validate the known hosts: https://cd.screwdriver.cd/pipelines/21/builds/9976

We are checking against the github fingerprint in `git-ssh.sh` as:
GITHUB_FINGERPRINT=16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48
https://gist.github.com/stjohnjohnson/3d2388b2a7ba658cdcdaffa8cd874e50#file-git-ssh-sh-L8

But with the latest golang image, it has upgraded to openssh 7.4 which generates the fingerprint as `SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8`
https://help.github.com/articles/github-s-ssh-key-fingerprints/

Need to fix the script. @stjohnjohnson

**Comment by tkyi** [comment]
Builds are also failing for sd-step at git-tag step
https://github.com/screwdriver-cd/sd-step/pull/6

**Comment by minz1027** [comment]
We have a fix in the toolbox already ^^
Switch to read from our Toolbox repo instead of stjohn's gist for all affected repos.

**Comment by minz1027** [comment]
problem solved by above PRs ^^^
