### ISSUE TITLE
UI should have a link to validator

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#733]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Screwdriver.cd version**: screwdrivercd/ui:v1.0.181

**What happened**:
UI has config validator, but I cannot access it except inputting the URL directly (/validator).

**What you expected to happen**:
UI should have a link to validator, especially on the header.

**Comment by petey** [comment]
Fixed by https://github.com/screwdriver-cd/ui/pull/213
