### ISSUE TITLE
Custom build parameters

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#734]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Screwdriver.cd version**: v0.5.42

Currently each build doesn't support additional build parameters provided by user at build time. It is nice to have this feature.
For example, when `/v4/builds` receives a payload including `{parameters: {NODE_ENV: 6}`, the build would override the environment variable or provide these values via `meta`.

**Comment by catto** [comment]
There is already a parameters key in the build model.
https://github.com/screwdriver-cd/data-schema/blob/12a06cbe0603a90403935ba5efb43d24112c28a2/models/build.js#L92-L94
I think we can achieve it by using this `parameters` object in the build model.

**Comment by petey** [comment]
We have actively avoided allowing parameterized builds in Screwdriver, historically. This is an anti-pattern that allows builds to run in different ways without any attribution or correlation to source code. There are some use-cases where it seems valuable, but these can largely be addressed by the use of the existing `meta` command, or proper configuration of jobs.
