### ISSUE TITLE
provide Guide under an https:// URL https://docs.screwdriver.cd/

### ISSUE THREAD

**Issue by dmitris** [screwdriver-cd/screwdriver#748]
**What happened**:
clicking on "i" next to the docs.screwdriver.cd/about/support URL in Chrome shows: "Your connection to the site is not secure"

**What you expected to happen**:
https://docs.screwdriver.cd being available

**How to reproduce it**:
navigate to http://docs.screwdriver.cd/ , click on "i" in the URL bar
![screen shot 2017-09-26 at 1 54 16 pm](https://user-images.githubusercontent.com/31205/30859119-96d43be2-a2c2-11e7-8b17-4cbe767a6818.png)

(I wonder if we could use a Let's Encrypt SSL certificate - https://letsencrypt.org/ )

**Comment by joelseq** [comment]
This can be done using CloudFlare: https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

but it won't be full https

**Comment by FenrirUnbound** [comment]
The guide is now hosted via HTTPS: https://docs.screwdriver.cd

-----

![screen shot 2017-10-06 at 3 44 34 pm](https://user-images.githubusercontent.com/721148/31301215-479a213e-aaad-11e7-82c2-e800622195a1.png)
