### ISSUE TITLE
 Configure build RAM capacity

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#759]
## Context

As a pipeline owner, I want the ability to configure my build to be run on a machine with higher RAM than what is allocated by default.

## Objective

RAM allocated by default might not be suitable for user build jobs with higher memory constraints. Users should be allowed to specify larger RAM for their builds.

## Requirements

1. User specifies in `screwdriver.yaml` user's RAM requirement.
1. Requirement can be specified at a job level or at a pipeline level.
1. If executor cannot honor user requirement then it should be communicated to user. (en entry is log should be okay)
1. We could provide presets to user eg: HIGH_RAM/HIGH which could potentially be combined with other resource requirements (eg: disk/cpu). Eg: HIGH could mean high capacity for cpu, disk & memory. HIGH_RAM could mean high capacity for RAM and default for everything else.

**Comment by tkyi** [comment]
**Daily summary 11/13**:

Changes have been implemented and merged. Just needed to change hyperctl-image to take in CPU and memory arguments and to pass in that data in the executor-k8s-vm.

Currently working on verifying the changes.

**Comment by tkyi** [comment]
**Daily summary 11/14:**

Tested out the new hyperctl image changes by running a build using the executor `k8s-vm` with job-level annotations:
```
annotations: 
            beta.screwdriver.cd/resource: HIGH
```

The CPU and memory were set to the "HIGH" settings, 6 vcpu and 12288 MB, respectively.

The initial work is considered done. Changes might be made in the future to tweak those values so they better suit our users' needs.

**Comment by tkyi** [comment]
Documentation: https://docs.screwdriver.cd/user-guide/configuration/annotations
