### ISSUE TITLE
UI is persisting error message in pipeline options page

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#765]
## Steps to reproduce

1. Use is in pipeline options page and clicks sync button on Pipeline.
2. For whatever reasons sync fails and user is shown error.
3. User navigates to a different pipeline's options page. Error message is still displayed.
4. User clicks Sync Pipeline. Error message is shown even if the Sync is success

## Expectation

- [x] Once user navigates out of pipeline options page, error message should be cleared.
- [ ] Even with in the same pipeline options page, if user clicks Sync again and if it succeeds, then error message should be cleared.

**Comment by tkyi** [comment]
#1 should be solved with the above PR. Not sure if #2 is solved yet.
