### ISSUE TITLE
Build job on an a trigger

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#768]
# Context

A job in a pipeline should be able to express that it should be built in response to successful completion another job (within same pipeline or external pipeline) ~~or successful completion in entirety of an external pipeline.~~ We will enhance `requires` syntax to support `~` which expresses an `ANY` relationship to a job in `requires`

Eg:  `Y : requires: [A, B, ~sd@pipeX:jobX]` means job `Y` should run whenever jobs `A` and `B` in same pipeline completes or whenever `jobX` in an external pipeline `pipeX` completes successfully.

# Objective

1. `jobA : requires: [~sd@pipeX:jobX` should  run job jobA whenever `jobX in pipeline pipeX completes. https://github.com/screwdriver-cd/screwdriver/issues/770
2. If multiple jobs in a pipeline has same `ANY` relationship  on an external job/piepline it should create a single pipeline event. Same as how `requires` work in context of `~commit` on multiple jobs.
3. A job which was triggered by `requires` on an external pipeline's job should have access to meta set by the build of the external pipeline job which started the event. - https://github.com/screwdriver-cd/screwdriver/issues/771
4. Warn users if an `ANY` relationship leads to a detached job run. Eg: `A: requires: [~commit], X: requires[~sd@pipeX:jobX, A], Y: requires[A], Z: requires: [X, Y]` (An advanced Fan-out use case, we can address this when we take up Fan-out feature)

# References
1. Original feature request https://github.com/screwdriver-cd/screwdriver/issues/433
2. Workflow config  @https://github.com/screwdriver-cd/screwdriver/blob/master/design/workflow.md#rebuild_on

**Comment by d2lam** [comment]
I'm not clear on the job criteria. Why does job X need to be a detached job? or why no other jobs should require job X? I think you have some scenario you want to avoid, but it's not very clear from reading it. Why do we want such criteria?

Also, how do we define "completion of an external pipeline"? We need to figure out what the last job is for that pipeline? I think for this, it's actually easier to tie it to a job. Like `rebuild_on: sd@123:staging`

**Comment by minz1027** [comment]
Agreed with @d2lam's comment about `completion of an external pipeline`. It's hard to define. For example, a pipeline has two flows, one: [A -> B], two: [C -> D]. What is the completion of the the pipeline in that case?

**Comment by d2lam** [comment]
@minz1027  For your 2nd question: the key difference between `requires` and `rebuild_on` is the **AND** vs **OR** relationship. 
`requires: [A,B]` means both A and B need to complete successfully
`rebuild_on: [A,B]` means the job rebuilds if either A or B complete successfully

**Comment by jithin1987** [comment]
@d2lam @minz1027 

1. Regarding completion of pipeline

Can't we figure out from subway graph for an event, if there are no more jobs to be triggered ? I define successful completion as this, for an event for a pipeline, all jobs which should have been triggered as part of it is successful, if any build for a job fails, then pipeline is not complete

For the scenario `One: [A -> B], two: [C -> D]` we should be able to infer from event workflow graph all jobs which should have been triggered as part of the event ie as part of same event, builds for jobs A,B,C & D is successful and there are no more jobs to be finished.

But for phase 1 I am okay with tying trigger to completion of a single job in external pipeline.

 2. Regarding within same pipeline, I agree it reduces to a `requires` scenario. I am trying to bring in the distinction of the trigger starting a separate event altogether. But it's not very useful I think.

3. Regarding job criteria. I visualize `rebuild_on` starts it's on event flow for some part of pipeline. Not just running a single job, it starts job and then the `requires` workflow will kick in for rest of jobs. What I wanted to capture is actually `Job Criteria 4.` Rest of them will automatically get applied.

**Comment by d2lam** [comment]
`Eg: Job X rebuild_on Foo and Job Z requires Job X and Y. We should ignore rebuild_on on Job X since Job X by itself cannot trigger Z. (This is an advanced use case of Fan-in which we need not address right now.)`

So your example config would look something like this:
```
X:
   rebuild_on: foo
Y: 
Z:
   requires: [X,Y]
```

I'm not sure if we should ignore the `rebuild_on` in this case (not run X when foo finishes). That's the same as saying user shouldn't be able to manually start X just because Z requires [X,Y]. My expectation is that X will still run, but Z doesn't run. I think this should be discussed and handled separately when we get to Workflow Fan In.

**Comment by jithin1987** [comment]
@d2lam  
> I'm not sure if we should ignore the rebuild_on in this case (not run X when foo finishes). That's the same as saying user shouldn't be able to manually start X just because Z requires [X,Y]. My expectation is that X will still run, but Z doesn't run. I think this should be discussed and handled separately when we get to Workflow Fan In.

My thought process is user will have to add `rebuild_on foo` for both X & Y, and API when processing foo will run both X & Y. But I think you are right, I will relax the X not running scenario if Y not present.

**Comment by jithin1987** [comment]
**Update**

We have decided not to use a new field to specify `ANY` relationship on jobs in same or external pipeline. Instead we will prefix a job with `~` to specify `ANY` relationship,  `X: requires: [~A, B, C]` means run job X whenever job `A` is completed or when jobs `B & C` are both completed.
