### ISSUE TITLE
Empowered Launcher

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#77]
This is a major change to the launcher and how we execute it.  Previously we would provide fields like: `jobId`, `pipelineId`, `repository`, and `branch`.  We want to reduce the context provided to the launcher and instead empower the launcher to get the information it needs.

This has multiple benefits like:
 - Only one place to change (`launcher`) when adding new information like `sha1` or `is_forked`
 - Launcher can now make requests on behalf of the build

Fields to be provided to executor:
 - `buildId` - Build Identifier (to look up stuff)
 - `container` - Container to start in
 - `apiUri` - URI to hit our API
 - `token` - Token to be able to read/write from the API

Input provided to launcher:
```bash
# docker run ... {{container}} 
SD_TOKEN={{token}} /opt/screwdriver/launch --api-uri {{apiUri}} {{buildId}}
```

**Comment by stjohnjohnson** [comment]
Done!

**Comment by Filbird** [comment]
:smile:
