### ISSUE TITLE
Bug: Notification packages fail to parse config when scope option is set

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#775]
**What happened**:

I sent this [PR](https://github.com/screwdriver-cd/screwdriver/pull/772). At that time, I just set scope in config and allow scoped notification packages. However, this will cause some issues that each notification plugin must allow a scope setting (scope key in config) when validatation.

So I think we should change the way to change the schema to the notification config.

My idea is as below.
```
email:
  config:
    host: ***
    port: ***
    from: ***
  module: '@module/package'
```
`module` is optional.  We use `module` as a notification package, when it is set.  If `module` is not set, we use _screwdriver-notification-xxx_ (same as the old way).
It makes constructor of notification package simpler, because we just pass `email.config` object. Also this looks similar to [a config for bookends](https://github.com/screwdriver-cd/build-bookend/blob/master/README.md).

If we will keep to use the [PR](https://github.com/screwdriver-cd/screwdriver/pull/772), we have to delete scope setting before calling notification plugin constructor. It makes the code a bit complex.

What should I do to fix this problem?

**reference**
- [previous PR](https://github.com/screwdriver-cd/screwdriver/pull/772)
- [notification packages validate place](https://github.com/screwdriver-cd/notifications-email/blob/master/index.js#L58)
- [bookends config](https://github.com/screwdriver-cd/build-bookend/blob/master/README.md)

**Comment by tk3fftk** [comment]
This should be closed😃
