### ISSUE TITLE
[UI] Subway map of pipeline jobs

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#782]
## Context

It's currently hard to tell what a user's workflow is going to do. Users should be able to see a subway map or overview of their pipeline so they know what jobs will be run in what order.

**Comment by petey** [comment]
We've gotten mocks from our designer to improve the look of the workflow, and have been working on implementation. I am currently working on implementing a new workflow drawn by d3 as an ember component.

<img width="517" alt="screen shot 2017-11-14 at 10 10 35 am" src="https://user-images.githubusercontent.com/78533/32796681-4c9fa128-c924-11e7-9a42-bd66c28fdb7b.png">

**Comment by petey** [comment]
https://github.com/screwdriver-cd/ui/pull/236
