### ISSUE TITLE
Hard to tell when a repository URL is invalid

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#783]
## Context

When trying to create a pipeline, the form outline turns a different color depending on if the repository URL is "valid" or not and the `Create Pipeline` button stays grayed out. It should be more obvious to a user (especially a colorblind one) when their repo URL is invalid. 

<img width="721" alt="screen shot 2017-11-03 at 5 00 59 pm" src="https://user-images.githubusercontent.com/3230529/32400045-d9ec03c4-c0b8-11e7-9b16-4a3c8088938d.png">

## What is expected

Ideally, a warning icon should show up with a tool tip saying the repo URL is not valid.

**Comment by d2lam** [comment]
This is related to https://github.com/screwdriver-cd/screwdriver/issues/668
We can track this there.
