### ISSUE TITLE
PR path in cache breaks all kinds of things

### ISSUE THREAD

**Issue by renaud-yahoo** [screwdriver-cd/screwdriver#793]
**What happened**:

Whilst testing PR jobs internally, I discovered that a PR job (that's using the exact same job definition as the main job) will always fail. I suspect that it's related to the fact that a PR job will create a folder in /cache that's named "PR-1:main", which contains a colon, and colons are a big no-no in folder names, especially with Java (as it relates to classpaths and many fun things).

**What you expected to happen**:

I expected it to work :P

**How to reproduce it**:

Ping me, I'll show you how.

**Comment by petey** [comment]
Near as I can tell, it is your template(s) that is making that directory based on the job name. Can you replace the `:` with another character when you make the directory?

**Comment by renaud-yahoo** [comment]
You might be right, there's ONE line that may relate to this. Testing fix.

**Comment by renaud-yahoo** [comment]
You were right.
