### ISSUE TITLE
Build failure error message should be bubbled up to user

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#794]
# Context

We have the ability to mark a build's status as failure because of k8s pod creation errors. But the error message which caused it is not surface up to user.

# Objective

1 .Surface up the error which caused pod creation failure to user.
2. In addition to build status, we need to capture a build status message and display it in build detail page.

**Comment by d2lam** [comment]
Looks like a duplicate of this: https://github.com/screwdriver-cd/screwdriver/issues/694

We should either close this or the other one.

**Comment by jithin1987** [comment]
Closing as duplicate of https://github.com/screwdriver-cd/screwdriver/issues/694
