### ISSUE TITLE
Retry a job's failed build 

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#795]
# Context

In a long pipeline if a build's job fails at at a hop further down in the pipeline for reasons outside of the job's step logic. Eg: Network timeout, k8s infrastructure issue etc, we should allow a user to rerun the build.

# Objective
1. Show retry button in UI in a job's failed build page.
2. Retried build for the job should create a new event which should inherit all the properties from the original event (meta, sha etc)
3. In a job's build page show the past failed builds.
4. ~Only failed builds should be allowed to be retried.~

**Comment by petey** [comment]
I disagree that the job retry should be captured in the same event as the original failed build. I feel that the user clicking the button to retry should spawn a completely new event, but it should act as a clone of the original event, e.g. same meta/environment, and restart from the failed job. We could also link in references to successful builds from the original event, as required, so joins are handled appropriately.

If we were to reuse the exact same event when retrying a job, we would lose the history of that failed build.

**Comment by jithin1987** [comment]
> I disagree that the job retry should be captured in the same event as the original failed build. I feel that the user clicking the button to retry should spawn a completely new event, but it should act as a clone of the original event, e.g. same meta/environment, and restart from the failed job. We could also link in references to successful builds from the original event, as required, so joins are handled appropriately.
> If we were to reuse the exact same event when retrying a job, we would lose the history of that failed build.

@petey Agreed. It should be a new event. I will update description.

**Comment by jithin1987** [comment]
This feature should be covered by #806. Hence closing this.
