### ISSUE TITLE
Display past builds for PR job

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#796]
# Context

If user makes incremental changes to a PR, it kicks off new builds. But UI shows only last build, there by loosing context of past builds.

# Objective

Display in PR build page, past builds for the PR job.

Design mocks:
![05a_jobs_dropdown_more](https://user-images.githubusercontent.com/193126/40160347-23cbb970-5962-11e8-982f-d6685d2bcf04.png)
![05a_jobs_dropdown](https://user-images.githubusercontent.com/193126/40160348-23e56c3a-5962-11e8-8be1-5f7519ed384c.png)
![05a_jobs](https://user-images.githubusercontent.com/193126/40160349-2419a072-5962-11e8-96fb-f69f0bf847b7.png)

**Comment by jithin1987** [comment]
_5/16/2018_
Updated with latest mocks.

**Comment by lusol** [comment]
@pranavrc don't do this one please

**Comment by tkyi** [comment]
Functionality is there, though CSS could be cleaned up:
<img width="720" alt="screen shot 2018-06-14 at 10 46 06 am" src="https://user-images.githubusercontent.com/3230529/41428869-3a342fde-6fc0-11e8-865f-5bcd54c95436.png">
