### ISSUE TITLE
 Persist meta from trigger jobs (Phase 2)

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#809]
## Context

Continuation of #771 to handle multiple external pipelines which can trigger current pipeline.

## Objective 

- [ ] If there is another external  pipeline `X` which is not the current triggering pipeline,  then `meta get --external sd@X:JOBA FOO` should fetch `meta set FOO` from last successful run of job `jobA` in pipeline `X`

**Comment by d2lam** [comment]
@jithin1987  Should it be `meta get --external sd@pipelineId:jobName FOO`? 

Otherwise if the pipeline `123` is something like: `~commit -> A -> (B,C) in parallel`, it will be unclear if `sd@123` should return the meta from `B` or `C`.

**Comment by jithin1987** [comment]
> @jithin1987 Should it be meta get --external sd@pipelineId:jobName FOO?
> 
> Otherwise if the pipeline 123 is something like: ~commit -> A -> (B,C) in parallel, it will be unclear if sd@123 should return the meta from B or C.

@d2lam Ideally meta should be associated with an event, so no matter which job's build uses meta every build part of same event sees the same value. Given our current implementation which ties meta to a specific build, I am okay with the above syntax.

**Comment by jithin1987** [comment]
Closing with https://github.com/screwdriver-cd/meta-cli/releases/tag/v0.0.28
