### ISSUE TITLE
Bug: [UI] The build progress icon makes a strange move

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#811]
**What happened**:
When build is in progress, the build status icon moves like below gif.
![ltam05a1f929fa81748b648f52979](https://user-images.githubusercontent.com/8113204/33465015-d85d52fc-d688-11e7-92b9-487dd2b4be45.gif)
That is the gif animation when the test job is in progress.

**What you expected to happen**:
The build status icon moves correctly when build is in progress.

**How to reproduce it**:
When I use Safari 11.0 (11604.1.38.1.7), the build status icon moves like that.
But when I use Chrome 61.0.3163.100, the build status icon moves correctly.
Screwdriver.cd versions are like below.
UI: v1.0.210
API: v0.5.127

**Comment by tkyi** [comment]
Firefox is broken, too

Tagging @petey

**Comment by petey** [comment]
Yes, we've noticed this in Firefox and Safari. I'm currently at a loss of how to address this since it seems these browsers are treating `transform-origin` differently. I will be removing the animation in my next PR until we can find a better resolution.

**Comment by petey** [comment]
We removed the animation for now.
