### ISSUE TITLE
Hard to tell when jobs are disabled

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#815]
Users have a hard time telling when their job is disabled. It's not really obvious from the UI or error messages when jobs are disabled/enabled.

**What happened**: All of a user's jobs were disabled, but when trying to start a build, the error message said `No jobs to start`.

**What you expected to happen**: When all of a user's jobs are disabled, it would be nice if the error message said `All jobs disabled`.

**How to reproduce it**: 
1. Disable all jobs in the Options page through the UI.
<img width="847" alt="screen shot 2017-12-05 at 11 17 20 am" src="https://user-images.githubusercontent.com/3230529/33625896-f18355a6-d9ad-11e7-8f29-5f9a7af43f60.png">

2. Click the Start button through the UI.
<img width="973" alt="screen shot 2017-12-05 at 11 17 08 am" src="https://user-images.githubusercontent.com/3230529/33625902-f5abf87c-d9ad-11e7-86cd-07fc7abeedfd.png">

**Other**:
- Might be nice if a modal pops up when you toggle to disable a job to make it more obvious that you've disabled one.
- Or instead of a generic toggle, the interaction can be a toggle between `disable job` and `enable job`.

**Comment by petey** [comment]
Given the desire to add more interaction to the build bubbles in the graph, e.g "start from here", maybe the disable job UX should go there, too.

**Comment by petey** [comment]
we should also provide a way to disable all PRs instead of each individual PR job, which won't help stop new PRs from starting things.

**Comment by tkyi** [comment]
Have already made job disabling easier to see in UI: https://github.com/screwdriver-cd/screwdriver/issues/1432

Opened another issue to track https://github.com/screwdriver-cd/screwdriver/issues/815#issuecomment-363273207
https://github.com/screwdriver-cd/screwdriver/issues/1576
