### ISSUE TITLE
[UI] Cannot navigate to trigger pipeline from workflow graph

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#816]
## Context

When a pipeline is triggered by an external pipeline workflow graph shows the connection, but nothing happens on clicking trigger node in workflow graph.

![screen shot 2017-12-05 at 11 50 12 am](https://user-images.githubusercontent.com/193126/33627488-865f5054-d9b2-11e7-87d5-f47b37f0ef7f.png)

## Expectation

Clicking the trigger node in workflow graph should take user to the external pipeline which triggered current pipeline

**Comment by tkyi** [comment]
This used to work when we first added external triggers. Not sure what changed.

**Comment by jithin1987** [comment]
This has been fixed.
