### ISSUE TITLE
Allow opening workflow graph nodes in a new tab/window

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#817]
## Context

Nodes in the  workflow graph represents jobs which are run as part of pipeline. These nodes are clickable, and clicking the node takes user to the build page of the job. However user cannot open it in a new tab or window since they are not real anchor links.

## Objective

Use `<a>` in the SVG workflow graph so that users have more control on viewing different jobs in the workflow under multiple tabs or windows

**Comment by d2lam** [comment]
This is done because of the new UI.
