### ISSUE TITLE
Old PR jobs don't get archived

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#824]
**What happened**:
An old PR job runs even though it is not in the config. 

**What you expected to happen**:
An old PR job should get archived and should not run when there is a new commit to the PR. 

**How to reproduce it**:
- `screwdriver-yaml` has `main` triggered by `~pr`
- Create a PR. `PR-1:main` will be created 
- Change the `screwdriver.yaml` so that `second` triggered by `~pr`
- We expect `PR-1:second` to run, and `PR-1:main` to be archived. However, both jobs will run.

**Reasons**:
- Take a look at these lines: https://github.com/screwdriver-cd/models/blob/master/lib/eventFactory.js#L33-L34. It checks if the job name includes `PR-#`, and is `ENABLED`, then start them
- The problem is that we never disable the jobs that are not in the new config.
- Before it gets to there, we should archive the jobs that are not in the `latestConfig`

**Comment by catto** [comment]
I think #798 is related to this issue

**Comment by minz1027** [comment]
- [ ] `pipeline.syncPR` archive the olds jobs that need to be archived
- [ ]  eventFactory filtered out archived jobs: https://github.com/screwdriver-cd/models/blob/master/lib/eventFactory.js#L33-L34.

**Comment by minz1027** [comment]
Done
