### ISSUE TITLE
`meta get` converts numbers to scientific notation

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#839]
**What happened**:
When we do `meta get` a number >6 digits, it will convert to +e06 
For example, 
```
$ meta set build_version_1 1234567
$ meta get build_version_1`
1.234567e+06
```

Example build: https://beta.cd.screwdriver.cd/pipelines/93/builds/7008

Looks like the `meta get` was fine, since `meta.json` stores the same format. 
```
$ cat /sd/meta/meta.json
{"build_version_1":1234567}
```

**Comment by d2lam** [comment]
@tk3fftk  could you help look into this?

**Comment by tk3fftk** [comment]
A meta value is converted to float64 from interface in spite of an integer is load from a json file. 
A scientific notation is shown when using `%v` for float64.
I have no idea why int becomes float64...

**Comment by d2lam** [comment]
Oh, now I remember having this issue before with GO.
Can we convert interface to float64 then convert to int64: `int64(value.(float64))`? @tk3fftk

**Comment by tk3fftk** [comment]
Ok, I'll try.

**Comment by d2lam** [comment]
This works now: https://cd.screwdriver.cd/pipelines/173/builds/15178

Thanks @tk3fftk
