### ISSUE TITLE
Previous/Next Jobs are not correct

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#841]
Since we implemented these links when we assumed that the pipeline is linear, these links don't work properly for workflow that has fan-out and fan-in. 

![screen shot 2018-01-12 at 4 55 57 pm](https://user-images.githubusercontent.com/3401924/34900970-81a411e2-f7b9-11e7-892d-0f86c824003b.png)

We should remove these links, and it should be resolved by our new UI design
@petey

**Comment by petey** [comment]
We will remove these in #871

**Comment by d2lam** [comment]
This is done
