### ISSUE TITLE
Add route for getting template tags

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#842]
## Context

It's hard for users to figure out what tags are available for each template and what versions they correspond to. It would be nice to have an endpoint where we could list the available tags for a specific template name (GET `/templates/{name}/tags`).

## Requirements
- [x] GET `/templates/{name}/tags` returns template tags

**Comment by ScottyFillups** [comment]
# Summary 01/19

The feature and tests have been written and [merged](https://github.com/screwdriver-cd/screwdriver/commit/e1699ad7d52cfd455cccaa7102d3bca2fe4856ff) into master. The feature has been deployed to https://cd.screwdriver.cd and seems to work correctly.

Here's a [demonstration](https://api.screwdriver.cd/v4/templates/screwdriver-cd%2Fsemantic-release/tags) of the endpoint, returning the tags for the `screwdriver-cd/semantic-release` template.

**Comment by tkyi** [comment]
This endpoint has been verified and is working in production.
