### ISSUE TITLE
Git-flow functional test failed very often

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#849]
**What happened**:
One of our git-flow functional test failed very often. In that test, we push new commit to a current PR and test if it creates a new build with the new change. Currently it's arbitrarily waiting for 3 seconds and then get the status. The can be too short sometimes. Then it will get the status for the previous build and failed the test.

**Current temp fix**
We bumped the wait time to 10 seconds for now. Should look into adding retry logic to check against the correct build.

**Proposed solution**
We check against the`buildId` to see if it's different from the the previous build.
We have the var already `this.previousBuildId`.

**Comment by jithin1987** [comment]
This is fixed already
