### ISSUE TITLE
Add template tags to template detail page

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#851]
## Context

It's hard for users to figure out what tags are available for each template and what versions they correspond to. There is already an API endpoint to get the template tags and versions (GET `/templates/{name}/tags`), but it would be nice if the users could see that in the template detail page on the UI (e.g., https://cd.screwdriver.cd/templates/screwdriver-cd%2Fsemantic-release).

## Requirements
- [x] Template detail pages display template tags next to the corresponding version numbers

## Related links
- API issue: https://github.com/screwdriver-cd/screwdriver/issues/842
- Related to templates discovery issue: https://github.com/screwdriver-cd/screwdriver/issues/522

**Comment by ScottyFillups** [comment]
# Summary 01/27

The feature and tests have been written and [merged](https://github.com/screwdriver-cd/ui/commit/c2b8b5f0e5a8b8065c498e38b4fedfad048237ba) into `master`. The feature has been deployed to https://cd.screwdriver.cd and seems to work correctly.

Here's a [demonstration](https://cd.screwdriver.cd/templates/screwdriver-cd%2Fsemantic-release) of the UI, displaying the tags for the `screwdriver-cd/semantic-release` template.

**Comment by tkyi** [comment]
Verified working in production.
