### ISSUE TITLE
Some pipelines would be permanently unavailable depending on cases

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#854]
**What happened**:
* `User A` has GitHub account and logged in to a Screwdriver.cd instance.
* `User A` has created new pipeline.
* Users who have write access to the repo can start the pipeline.
* `User A` removes or renames his/her GitHub account. (including the suspended state for GitHub Enterprise)
* Now no one can start the pipeline because of no admins for it. UI shows a JSON including a message like "suspended"

**What you expected to happen**:
Users who have write access can start build when a creator of the pipeline is not available.

**How to reproduce it**:
These steps are for an environment with GitHub Enterprise.
* Create new user on your GitHub Enterprise instance.
* Create new pipeline on Screwdriver.cd instance with the created user.
* Suspend the GitHub account
* No one can start new build for the pipeline even if there are admins of the repository.

**Comment by catto** [comment]
possible solution: 
* Add new admins to a pipeline when operations to the pipeline occurs
* Try next admin if API accesses are failed with auth error.
* Remove the failed admin from the pipeline admins.

**Comment by stjohnjohnson** [comment]
Good catch, @catto.  I recommend we actually do all three of those.

**Comment by yoshwata** [comment]
@minz1027 @d2lam @tkyi @jithin1987 Could someone close this issue?

**Comment by yoshwata** [comment]
This is related issue.
https://github.com/screwdriver-cd/screwdriver/issues/1117

**Comment by catto** [comment]
I confirmed that the issue has been fixed. Thanks @yoshwata!

**Comment by yoshwata** [comment]
@catto Thank you!
