### ISSUE TITLE
imagePullPolicy should be configurable by user or "Always"

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#869]
**What happened**:
A user wanted to use `some_user_created_image:A` docker image. 
The image was created by the user. The user updated the image with the same tag `A` and tried to use the image in builds.  But the build image was an old one. 
It might be caused by [pod template of executor-k8s](https://github.com/screwdriver-cd/executor-k8s/blob/master/config/pod.yaml.tim) and [hyperctl-image](https://github.com/screwdriver-cd/hyperctl-image/blob/master/scripts/hyper-pod-template.json) don't have `imagePullPolicy` setting. `imagePullPolicy: IfNotPresent` is used by default when `imagePullPolicy` is not set.

**What you expected to happen**:
I think we should add `imagePullPolicy: Always` setting to pod template or we should provide configurable `imagePullPolicy` setting with screwdriver.yaml to prevent using old image.

On the other hand, we should recommend users not to use same tag.
https://kubernetes.io/docs/concepts/configuration/overview/#container-images
> That is, if you’re specifying an image with other than the :latest tag, for example myimage:v1, and there is an image update to that same tag, the Kubelet won’t pull the updated image. You can address this by ensuring that any updates to an image bump the image tag as well (for example, myimage:v2), and ensuring that your configs point to the correct version.

**misc**:
`hyperd` may not be able to set `imagePullPolicy` yet. I couldn't find how to set. It only has the parameter.
https://github.com/hyperhq/hyperd/search?q=imagePullPolicy&type=Code&utf8=%E2%9C%93

**Comment by stjohnjohnson** [comment]
Interesting problem.  Generally we have recommended to people that they shouldn't use floating tags with Screwdriver.  What you've shown here is that it leaves for a very confusing state if they do use them.

I agree we should set the `imagePullPolicy` for k8s, feel free to open a PR for that.  Looking through our VM image, I think we already pull the image on each start: https://github.com/screwdriver-cd/hyperctl-image/blob/243258f77b0cfcd0fdee97a2346df916883001ea/scripts/hyper-runner.sh#L120
