### ISSUE TITLE
Support shorthand for internal pipeline triggers

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#874]
## Context
Users trying to use OR logic for requires on jobs within the same pipeline would like to use a shorthand (`requires: [~first, ~second]` vs `requires: [~sd@123@first, ~sd@123:second]`). Currently, they have to type out the full ~sd@ syntax.

## Request
It would be nice if we implemented support for a shorthand for triggers within the same pipeline using OR logic.

## Related links
Documentation: https://docs.screwdriver.cd/user-guide/configuration/workflow#advanced-logic
Related to: https://github.com/screwdriver-cd/screwdriver/issues/723

**Comment by marian-r** [comment]
This would also makes the pipeline graph a bit nicer, so that those OR jobs won't be detached i.e:
![screen shot 2018-03-23 at 4 57 59 pm](https://user-images.githubusercontent.com/4215517/37843133-fab85384-2ebb-11e8-98da-4cd8f7dc8d74.png)

**Comment by d2lam** [comment]
Backend for this feature is done.
However, we need some work on the UI to display properly

**Comment by tkyi** [comment]
### UI proposal
We think it makes sense to show every single possible workflow based on the `requires` keyword. For example, if a user has this yaml, where D requires B OR C:
![image from ios 1](https://user-images.githubusercontent.com/3230529/43024277-a9bc9da4-8c22-11e8-87ed-cdc68dcb6a98.jpg)

```
jobs:
  A:
    requires: [~pr, ~commit]
  B:
    requires: A
  C:
    requires: A
  D:
    requires: [~B, ~C] 
```
The event graph should look like this:
![image from ios](https://user-images.githubusercontent.com/3230529/43024284-b040bda4-8c22-11e8-8af8-3db204464550.jpg)

This change will probably done in the UI and should be the same in the validator.

**Comment by jithin1987** [comment]
There are 2 distinct use cases here, if we take above comment as an example

1. B && D || C && D => is what current implementation is. Leading to two distinct work flows. 
1. (B || C) && D => is also a legit use-case. This leads so a single workflow, inline with what pipeline graph shows.

**Comment by jithine** [comment]
This should now work as expected with https://github.com/screwdriver-cd/screwdriver/issues/2071

Guide update pending
