### ISSUE TITLE
GETTING STARTED link in screwdriver.cd is broken

### ISSUE THREAD

**Issue by difki** [screwdriver-cd/screwdriver#879]
Hello SD team,

I have tried to install screwdriver on my ec2 instance but the link provided in the getting started guide (http://screwdriver.cd/) is broken.

I'm taking a "wild" guess but looks like you moved the file from git but **didn't push the update to the screwdriver.cd** site 

in-a-box.py moving commit :https://github.com/screwdriver-cd/screwdriver/commit/7d731355d05c2601bccc2bedd75439464f09d46f

<img width="1437" alt="screen shot 2018-02-09 at 14 00 22" src="https://user-images.githubusercontent.com/13364691/36027079-63c01712-0da2-11e8-96b8-fe9af12383c3.png">
<img width="207" alt="screen shot 2018-02-09 at 14 00 43" src="https://user-images.githubusercontent.com/13364691/36027082-67762fa4-0da2-11e8-802f-3403e3864c16.png">

**Comment by stjohnjohnson** [comment]
Good catch!  That's my bad.  I'll fix it now.

**Comment by stjohnjohnson** [comment]
Updated the homepage.  Thanks for the heads up!
