### ISSUE TITLE
Hitting the limit of GitHub API request

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#881]
**What happened**:
I tried periodical build by hitting builds/events API of Screwdriver.cd.
After some days, I faced with a problem that new build never start with the message below.
![image](https://user-images.githubusercontent.com/1608595/36145239-19c3db3a-10f4-11e8-9075-0887503a959f.png)

I pushed the new commit (new SHA) and the problem has been resolved.
This problem seems to be the same as https://github.com/screwdriver-cd/screwdriver/issues/387 but I opened the new issue because the context is different.

**What you expected to happen**:
I can start new build for the same commit as many times as desired.

**How to reproduce it**:
Start new build many times with the same commit.

References:
* Need to fix this issue to achieve the build periodically feature (#688)
* Statuses API has the limit 
> Note: there is a limit of 1000 statuses per sha and context within a repository. Attempts to create more than 1000 statuses will result in a validation error.
https://developer.github.com/v3/repos/statuses/

**Comment by stjohnjohnson** [comment]
Interesting problem!  What do you recommend we do here?  Should we quietly ignore this error?

**Comment by catto** [comment]
@stjohnjohnson This issue especially occurs for builds triggered by `~commit`. Most of PR builds are not affected since users push their commit frequently and its trigger may not be automated or built periodically.

So I suggest to stop adding commit statuses for non-PR builds. Build status information on PR pages are extremely useful but I think users rarely see their commits page to check build statuses.
https://github.com/screwdriver-cd/screwdriver/commits/master

**Comment by stjohnjohnson** [comment]
@catto That seems like a reasonable move.  I was hoping at some point to use the commit statuses to indicate the current location of code X in the pipeline (did it deploy to production) but I think we're far off.  Feel free to open a PR to disable that feature.

**Comment by ScottyFillups** [comment]
The PR has been merged, and we have verified that builds will run regardless of whether the Github 1000 status limit has been reached.

**Comment by catto** [comment]
@ScottyFillups Thank you for fixing this!
