### ISSUE TITLE
Users cannot understand the error log of too long job name

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#890]
**What happened**:
A user try to use a long job name which exceeds [max length (25)](https://github.com/screwdriver-cd/data-schema/blob/88728e6990bffd26124013e280d150553a0f8dce/models/job.js#L15).
Then, the user try to start build but UI shows the error message `"Data too long for column 'name' at row 1" ` and a build didn't start.
The user could not understand the meaning of this message. And there is no way to know the max length of job name is 25 except reading code.

Template name and Command name may cause the same problem.

**What you expected to happen**:
The error message should be more friendly or we should increase the max length of job name.

**How to reproduce it**:
Configure long job name (more than 25) on screwdriver.yaml and try to start a build.

**Comment by stjohnjohnson** [comment]
Hmm, this is a serious problem.  We're going to encounter things like this with Joi.  There has to be a better way for us to give more human readable errors.

**Comment by d2lam** [comment]
On a separate note, should we increase this limit? `25` is not really unreasonable. I ran into this problem a while ago and thought my job name wasn't that ridiculously long.

**Comment by catto** [comment]
I agree with increasing the limit. I found that PR jobs were limited to shorter length than other jobs because those are named `PR-xxx:<jobname>`. 128 is fine?

And I think the validator should return config error as same as yaml error so that users can notice the cause of an error at least.

**Comment by tkyi** [comment]
This change has been pulled in and is verified as working.
