### ISSUE TITLE
Issue Labels

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#899]
I think we might have too many labels and/or not the right labels.  Currently we have [34 of them](https://github.com/screwdriver-cd/screwdriver/labels) of which a good chunk have never been used.

Now that GitHub highlights two specific labels for ["first time contributors"](https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/) we should take this opportunity to figure out what would be a good set of labels for our work.

_Note: labels apply to both PRs and issues, so my proposal covers both sides._

### WIP Proposal

| **label** | **issue** | **pull request** |
| --------- | --------- | --------------- |
| `bug` | filing a bug | fixing a bug |
| `feature` | filing a request for a new feature | implementing a new feature |
| `help wanted` | ready for someone to work on | ready for a review | 
| `need more info` | needs clarification | needs clarification |
| `in progress` | being worked on | not ready for review, being updated |
| `urgent` | must be resolved quick | needs immediate review |

Things missing:
 - Blocked? Is it useful?
 - Backlog/Acknowledged - It's _going_ to be worked on
 - Resolution? Fixed/Won't Fix/Duplicate?
 - Discussion/Question

## Status

 - [x] Updated [Screwdriver labels](https://github.com/screwdriver-cd/screwdriver/labels)
 - [ ] Updated all repository labels
 - [ ] Updated [generator](https://github.com/screwdriver-cd/generator-screwdriver)

**Updated 3/11**

**Comment by catto** [comment]
What about priorities? I think it should be managed by project feature, but `priority/high` label seems to be useful for contributors who don't know the project page or may not see the page frequently

**Comment by stjohnjohnson** [comment]
@catto Agreed, but we have a number of `priority/high` issues that have been sitting around for over an year now.  Is that the right label.  One thing we've discussed in the past is priority vs urgency vs impact.  Maybe `urgent/high` is what we need, or even just `urgent`

**Comment by catto** [comment]
@stjohnjohnson  Make sense! `urgent` label is the thing I want probably.

**Comment by ScottyFillups** [comment]
I think your proposal is a good idea. In general, I think it's best to avoid "namespacing" labels, eg. `feedback/help wanted`. If the label is important, then just remove the namespace or rename it:

* `priority/high` -> `urgent`
* `feedback/help wanted` -> `help wanted`

If it isn't important enough to be a label by itself, it probably shouldn't be a label.

**Comment by FenrirUnbound** [comment]
> If it isn't important enough to be a label by itself, it probably shouldn't be a label.

Labels seem to be far more beneficial for folks that are not intimately involved with the code base. Designating that it's a call for help or that it's a feature request helps categorize what's expected when you look into an issue.

My only qualm is the `urgent` label. It's not very valuable to have an issue labeled as `urgent` when it's the 10th item in the backlog.

**Comment by ScottyFillups** [comment]
@FenrirUnbound I agree that there needs to be labels for things such as `feature` and `help wanted`, I just think labels in the form of `feature/X` or `help/Y` should be avoided. Labels aren't intended to describe the entire issue or PR; you can also fit information in the title.

I don't see a significant advantage of `type/feature` when you can just do `feature` or `feature request`. Maybe we should research how some popular open-source projects approach labels, like Node.js: https://github.com/nodejs/node/issues?page=3&q=is%3Aissue+is%3Aopen

> My only qualm is the `urgent` label. It's not very valuable to have an issue labeled as `urgent` when it's the 10th item in the backlog.

If that's the case, then either:
* Somebody is misusing the `urgent` label
* You're unfortunate enough have nine other items that are `urgent` in your backlog

My point is, the `urgent` tag doesn't seem to be the problem here. If everyone used it more conservatively, we shouldn't (?) have these problems.

**Comment by stjohnjohnson** [comment]
Okay, so I made some changes to the Screwdriver issue labels (not all of the repos yet).

Let's try it for a few weeks and see what labels might be missing.  Once we're happy, I'll make the change to the generator as well as the other repos.

Also found some interesting articles about this:
 - https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/
 - https://tailordev.fr/blog/2016/09/27/communication-with-github-issues-1/

I really liked the difference between "feature" and "feature request" as well as "feature", "bug", "improvement"

**Comment by d2lam** [comment]
@stjohnjohnson  I think we need a `blocked`. I find that pretty helpful

**Comment by jithin1987** [comment]
I believe current labels we have for tracking issues in this repository is good enough. Since this repository `screwdriver` is the one which tracks issues, updating labels here should suffice. 

https://github.com/screwdriver-cd/screwdriver/labels
