### ISSUE TITLE
Build started by non-logged in user

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#90]
Given a scenario where the user "Jer" is not logged in and has not authorized Screwdriver. When that user opens a PR, the API will complain about the user not existing in the ecosystem yet. This results in a 500 being returned by the server.

**Comment by stjohnjohnson** [comment]
Wait, this shouldn't happen.  It won't use Jer as the user to authenticate.  It uses the person who setup the pipeline.  It just logs that Jer starts the build.

https://github.com/screwdriver-cd/models/blob/786aaa957d522a2f82c8a2f811ba7e59dc7198f7/lib/buildFactory.js#L108

**Comment by stjohnjohnson** [comment]
Unable to replicate this.  We don't use the PR user, we use the pipeline user.
