### ISSUE TITLE
Bitbucket data center support

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#925]
## Context

[scm-bitbucket](https://github.com/screwdriver-cd/scm-bitbucket) does not support bitbucket data center. It needs to be enhanced to support it.

**Comment by stjohnjohnson** [comment]
Is there a difference to bitbucket data center vs. bitbucket server vs. bitbucket.org?

**Comment by stjohnjohnson** [comment]
Not sure if this helps: https://github.com/screwdriver-cd/screwdriver/issues/255

**Comment by jithin1987** [comment]
> Not sure if this helps: #255

This is a duplicate of #255. We can close this. From what we know `scm-bitbucket` supports only bitbucket.org and we have seen interest in various partners wanting to support bitbucket server

**Comment by d2lam** [comment]
#255 is meant for bitbucket server. Let's close this.
