### ISSUE TITLE
Template - Namespaces

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#926]
## Context

Namespaces allows related templates to be grouped together as a collection. For example templates `nodejs/build, nodejs/publish` can group together the templates under namespace `nodejs`

## Objective

1. Introduce a new field `namespace` in template config for namespace. 
1. Use slash '/' in template name for namespace, if user has not explicitly set `namespace` field in config.
1. UI to display namespace information in template detail page. For now have the same behavior of having `/` in name. Eg: For Namespace `nodejs` and template name `publish` display `nodejs/publish` in UI See https://cd.screwdriver.cd/templates/screwdriver-cd%2Fsemantic-release-node8 for reference
1. UI to revamp template page to group templates by namespaces.
1. API to filter templates based on `namespace`.

## Implementation
- [x] [data-schema] Add namespace to template, templateTag schemas
- [x] [models] Handle ambiguous full template name by checking for namespace in create, get, list for templates, templateTags
- [x] [screwdriver] Pass in namespace for create template, allow filtering using namespace for template list
- [x] [UI] Display namespace information in template detail page and validator
- [x] [config-parser] Add `SD_TEMPLATE_FULLNAME` and `SD_TEMPLATE_NAMESPACE` env vars
- [x] [guide] Add namespace to templates doc
- [x] [UI] Link to namespace in templates page, have a namespace page; add breadcrumbs

## References

Template second pass - https://github.com/screwdriver-cd/screwdriver/issues/616

## Updates

3/22/18 - We will introduce a new field in template config called `namespace`
5/22/18 - Add implementation tasks
6/5/18 - Update tasks with new UI plan

**Comment by jithin1987** [comment]
> For Screwdriver commands, namespace is its own field. Should we have templates match that format for consistency?

Yes we should have our own field and have a migration path of existing templates which uses `/` in name for namespacing.

**Comment by d2lam** [comment]
How are we handling permission for namespace? Who owns the namespace? 
I think it should be part of the objective/acceptance criteria for this story.

**Comment by tkyi** [comment]
@d2lam I don't think @jithin1987 wanted to handle that part in the first pass, just make the `namespace` field available for now.

I do agree there should be a bigger discussion about namespace auth and ownership in the near future though.

**Comment by tkyi** [comment]
Some more things to consider:
1. Now that I’m adding template namespace, should I include it in `$SD_TEMPLATE_NAME` (https://github.com/screwdriver-cd/config-parser/blob/master/lib/phase/flatten.js#L145)? Or just create a new environment variable `$SD_TEMPLATE_NAMESPACE` or `$SD_TEMPLATE_FULLNAME`?
2. An issue I ran into is that after defaulting to get the template with `namespace/name` vs `name_with_pseudo-namespace`, the UI will always show the metadata for `namespace/name` in the template detail page.
3. Should we add `createTime` metadata to the template data-schema and bubble it up in the UI as `last pushed` or `last publish` like in DockerHub or npm (probably not directly related to namespaces)?

**Comment by tkyi** [comment]
After further discussion with @jithin1987, here are the conclusions: 
### 1
We should treat both templates below as the same template.
```
namespace: nodejs
name: lib
```
and
```
name: nodejs/lib
```
Users can use this in their screwdriver.yaml by specifying: `template: nodejs/lib`

- We will assume the string before the first slash (`/`) is the namespace if only name is provided.
- Should only allow one slash in a name.
- If you have a namespace, then you can't have a name with a slash.

### 2
If a user does not define a namespace explicitly and there is no slash in their name, we will implicitly add a `default` namespace for them. 
```
name: nodejslib
```
equals
```
namespace: default
name: nodejslib
```
Users can use this in their screwdriver.yaml by specifying: `template: default/nodejslib` or `template: nodejslib`

## Note - Breaking change
This change requires a DB migration and will be a breaking change, since we will assume all templates have a `namespace`.

**Comment by tkyi** [comment]
After discussing what to do with the template namespace UI, here's a short-term idea we have to showcase namespaces.

Given a template named `nodejs/lib`,
1. Make `nodejs` and `lib` separate links (no space in between, just use CSS)
2. Clicking `nodejs` should take you to the `/templates/namespace/nodejs` page
- `nodejs` will be the header and `Template namespace` is the subheader
- the page should look similar to the `/templates` page and it will only show templates with the `nodejs` namespace
3. There should be breadcrumbs on the namespace and template detail page ([templates](cd.screwdriver.cd/templates)/nodejs` and `[templates](cd.screwdriver.cd/templates)/[nodejs]()/lib`, respectively)

**Comment by tk3fftk** [comment]
We found a bug. The pages of template which has old namespace and name are not opened in 
https://cd.screwdriver.cd/templates (like `screwdriver/template-publish`)

**Comment by tkyi** [comment]
@tk3fftk After migrating the templates DB, this shouldn't be an issue, since all templates should have a namespace and name after migration. I sent @catto migration information in the Slack channel `#616-templates`. 
But it would be good for us to make the UI changes backwards compatible.
cc: @jithin1987

**Comment by tkyi** [comment]
## New UI Changes

Templates are still searchable by `<namespace>/<name>` (using cmd+F) on the templates page:
<img width="1176" alt="screen shot 2018-06-27 at 2 20 20 pm" src="https://user-images.githubusercontent.com/3230529/42000534-cee4968c-7a15-11e8-9393-e9233e4dab3d.png">

Clicking on the namespace will take you to a page with templates with that namespace:
<img width="1174" alt="screen shot 2018-06-27 at 2 28 04 pm" src="https://user-images.githubusercontent.com/3230529/42000693-5dc2a524-7a16-11e8-8356-863f3f15b72e.png">

Clicking on a template name will take you to the template detail page, with breadcrumbs to get back.
<img width="848" alt="screen shot 2018-06-27 at 2 20 40 pm" src="https://user-images.githubusercontent.com/3230529/42000715-6ecf29be-7a16-11e8-8298-ded8f7422b12.png">

**Comment by jithin1987** [comment]
I've updated DB but found two bugs.

1. It does not show templates with same name but different namespace. It reduces it to a single template.
2. Fixing above causes https://github.com/screwdriver-cd/screwdriver/issues/1158

**Comment by tk3fftk** [comment]
@tkyi Thank you for sharing! 
@jithin1987 Thank you for the bug report! We suspended UI update and DB migration.

**Comment by jithin1987** [comment]
@tk3fftk PR for fixing issues I shared https://github.com/screwdriver-cd/ui/pull/325

**Comment by tkyi** [comment]
This feature has been verified. More details here: http://blog.screwdriver.cd/post/175385505042/introducing-template-namespaces
