### ISSUE TITLE
OOM Killed Pod hangs a build

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#929]
**What happened**:
Only Screwdriver.cd cluster admin can know a build pod is OOM killed.
A build is hanged without any errors on UI when a build pod is killed. It seems that the build is still running.

Example:
This `build` step started from `11:01:27` and was aborted after 2 hours.
![image](https://user-images.githubusercontent.com/3445553/37501985-154f3184-2914-11e8-8163-8fe1dbe3d1b3.png)

But the build log was ended on `11:03:07` without any errors. (`publish` is a next steps)
![image](https://user-images.githubusercontent.com/3445553/37501972-0898bc3a-2914-11e8-89bc-d537170263a4.png)

**What you expected to happen**:
A build should be failed and UI should shows some error message for users when a build pod is killed.

**How to reproduce it**:
Start a build which requires a large amount of memory (e.g. Java). But it depends on the cluster resource settings.

**Comment by stjohnjohnson** [comment]
I've seen a similar problem if the container crashes on start.  We need to monitor the state of the container.  If it dies, then mark the build as failed.

**Comment by tk3fftk** [comment]
There may be two type of OOM Killed.
- Pod OOM Killed
    - This means Kubernetes Pods are killed when the pod uses over requested/limited memory resources.
        - Pod's `containerStatuses.state.terminated.reason` will be `OOMKilled `.
    - The solution is that users configure more memory resource ( `ram: HIGH` )
- Process OOM Killed
    - This means `launch` process is OOM killed in a container.
        - Pod's `containerStatuses.state.terminated.reason` will be `Error `.
    - The solution may be that set `oom_score_adj` to `-17` or a low number in `laucher` and `logservice`.

**Comment by jithine** [comment]
This should work as expected with executor-k8s now
