### ISSUE TITLE
Pipeline per repo (instead of per branch)

### ISSUE THREAD

**Issue by aayore** [screwdriver-cd/screwdriver#930]
# Context
Since many feature branches are short-lived, it is tedious to create and delete a pipeline for each branch.

# Objective
After a repo is configured for a pipeline, any branch containing `screwdriver.yaml` should build according to said `screwdriver.yaml`.

**Comment by tkyi** [comment]
You shouldn't need to create a separate pipeline for any short-lived features. The idea is that when you open a pull request against the pipeline repo's branch, it'll automatically run the PR job against that code. It does limit you to only running one job for PR builds though.

Is your problem only being able to run one job per PR?

**Comment by aayore** [comment]
The use case is more for validation of WIP.  The functionality I'd like to see is the default in CircleCI and GitLab CI.

**Comment by aayore** [comment]
I think my use case is addressed by opening a WIP PR and committing against that until I'm ready to merge.  Thank you, @tkyi!

**Comment by aayore** [comment]
For the record, I've been running under the PR model for a while now, and I find it unnecessarily tedious.  I lose history and troubleshooting insight when I have all my branch commits consolidated in a single `PR-X:Name` view.  GitHub is sending the webhooks for every commit, so it'd be nice if SD would build for event that contains a SD.yaml.  As it is, the manual aspect is increased; when I create a new branch, I either have to create a PR or create a new pipeline.  If more control were moved to the SD.yaml, it'd be easier to automate more fully.
