### ISSUE TITLE
New events/pipeline page is not user-friendly

### ISSUE THREAD

**Issue by sakka2** [screwdriver-cd/screwdriver#933]
**What happened**:
---
It is a little confusing to reach the detail page of past builds since the UI of events/pipeline page has been updated.   Particularly, there are several points as below.

- __It takes 3 steps__  
Previously we could get past build pages by just 1 click of the build bubble, but now it takes 3 steps.
   1. click the event line from lists to show desired pipeline above the page
   2. click the build bubble to show the tooltip
   3. click the link to go to the detail page

<img width="561" alt="2018-03-16 18 23 15" src="https://user-images.githubusercontent.com/16560466/37583710-d33b9114-2b95-11e8-823d-b65072b904d8.png" width=50%>

- __Hard to notice changing pipeline workflow graph__  
When we click the event line, It is a little difficult to notice that whether the pipeline which is showing above the page (pipeline workflow graph) has changed or not. Sometimes it only changes commit hash.  If there are many event lines, even the displaying of pipeline workflow graph will be gone when scrolling.

- __Build bubbles are still clickable__  
Build bubbles of each event line are still clickable as before, so people might be confused because it looks still linking to the detail page.
 
 
 

**What you expected to happen**:
---
- As before, move to the build detail page directly from the build bubble of each event line, and show start button in there for restarting the build.

- Make it easier to notice the changes of pipeline workflow graph  
   1. Fix the pipeline workflow graph at the top of the page, and scroll only event lines.
   2. Make whole line of each event clickable, and each build bubble unclickable.
   3. Change the color of selected event line to be noticed easily.

**Comment by tk3fftk** [comment]
https://github.com/screwdriver-cd/screwdriver/issues/968 is related with i.

**Comment by tkyi** [comment]
Closing as this UI is out of date
