### ISSUE TITLE
Streamline development workflow

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#936]
## Context

Screwdriver components are spread across various GitHub repositories as described in [Contributing document](https://docs.screwdriver.cd/about/contributing#where-to-contribute) There is no stream lined documentation on how to make changes to a low level dependency (eg: [Model](https://github.com/screwdriver-cd/models)) and functionally test the changes in local development environment without having to publish the npm package.

## Objective

1. Publish a guideline document on how to develop screwdriver components locally.
1. Document should describe how a low level dependency (Eg: [Model](https://github.com/screwdriver-cd/models)), can be build locally and functionally tested. 
1. Document should describe how a user can run an SD setup (Eg: API running with updated Model) with the updated dependency.
1. Update documentation in [Contributing document](https://docs.screwdriver.cd/about/contributing) with findings

## References
1. https://docs.screwdriver.cd/about/contributing#where-to-contribute

**Comment by minz1027** [comment]
### Updates 04/12
A repo for developer docker-compose.yaml and guide for set up screwdriver for development locally

**Comment by tkyi** [comment]
Added documentation for now. Might revisit this issue again in the future.
