### ISSUE TITLE
Allow builds to tag event

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#939]
## Context

In a pipeline events page GIT SHA and commit message is what uniquely identifies an event. It would be helpful for users to quickly identify an event using a key->value pair which a build can set to identify a specific event rather than going through the SHA and commit message.

For example a build in a release pipeline can set value `RELEASE_VERSION=1.5.1` to identify an event which built Version `1.5.1` and use that to quickly identify the event. In a roll back scenario this helps users to quickly identify the event from which they need to invoke roll back.

## Objective

1. Expose a mechanism for builds to tag event.
    1. It can be an entry in `meta`
2. UI should display the tag for the event.

**Comment by jithin1987** [comment]
> How is this different than git tags?
value can be same as git tag. Feature is about surfacing that value in UI so that someone who wants to do a roll back can quickly identify which event to select.

**Comment by tkyi** [comment]
Wondering if this is the right way to go about providing a solution for identifying events. From this proposal, a tag/label can only be set through meta. 
There are times when I might rerun a build without making any code changes and I would want to label that event with a different label (e.g. if it's pulling in different npm package versions compared to the last one). If the label is only set through meta, changing the label might only be possible by starting the event through the API.

**Comment by jithin1987** [comment]
>  There are times when I might rerun a build without making any code changes and I would want to label that event with a different label (e.g. if it's pulling in different npm package versions compared to the last one). If the label is only set through meta, changing the label might only be possible by starting the event through the API.

That's a good point. We can do this when we get to https://github.com/screwdriver-cd/screwdriver/issues/1339
Since re-run is creating a new event, mechanism will be same.

**Comment by tkyi** [comment]
Blog post: https://blog.screwdriver.cd/post/184069527107/meta-event-label-and-stop-a-build 
Documentation: https://docs.screwdriver.cd/user-guide/metadata#event-labels
