### ISSUE TITLE
Add user-created pipelines into a user's collection automatically

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#947]
## Context
If a user creates a pipeline, they probably want an easy way to keep track of it or navigate to it.

## Proposal
Users should all have a "My Pipelines" collection (or "Favorites") by default. When a user creates a pipeline, that pipeline should be automatically added to their "My Pipelines" collection.

**Comment by drewfish** [comment]
... or perhaps "My Creations"

**Comment by edudar** [comment]
... or just a (multi-?)selector for collections on a pipeline creation screen. There's plenty of space to fill.
