### ISSUE TITLE
feature: show "pulling docker image" instead of "setting up build"

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#959]
**What happened**:
One of my pipeline builds spends a long time in the "setting up build".

**What you expected to happen**:
I suspect that it's pulling the (large) docker image. If so, it would be nice if something like "puling docker image" is shown, to indicate _why_ the setup is taking so long.

**How to reproduce it**:

**Comment by jithin1987** [comment]
we now display time splits properly.
