### ISSUE TITLE
feature:  build log or meta captures which exact version of the template is used

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#960]
**What happened**:
In my build which uses a template, I don't know which exact version of the template was used. This especially becomes important when I act in the role of a template author, and help debug failing builds from users of my template.

**What you expected to happen**:
The exact version of template is logged somewhere in the buildlog or meta. (If in the buildlog perhaps in sd-setup-launcher? If in meta, I/we still need to figure out a way for the build meta to be accessible for a completed build.)

**How to reproduce it**:

**Comment by d2lam** [comment]
Sounds like a valid request. It's not too difficult to implement. 

I'm putting some notes here in case someone wants to take a stab at it now or later:
- Template is getting parsed when `getConfiguration` is called: https://github.com/screwdriver-cd/models/blob/master/lib/pipeline.js#L124. This happens during pipeline sync or event create.
- In `config-parser`, when flattens, it will call: https://github.com/screwdriver-cd/config-parser/blob/master/lib/phase/flatten.js#L129
- The getting exact version is happening here: https://github.com/screwdriver-cd/models/blob/master/lib/templateFactory.js#L82-L118

**Comment by drewfish** [comment]
yeah that works for me

**Comment by minz1027** [comment]
@drewfish it's available now :)
