### ISSUE TITLE
Build at any pipeline point, if active

### ISSUE THREAD

**Issue by renaud-yahoo** [screwdriver-cd/screwdriver#961]
NOTE: This is a feature request.

Would it be possible for SD4 to offer a `requires` parameter that, if used, would allow any given job to be user-triggerable? Of course, the UI for "~user" (in the example below) would not be shown, and instead a given job with that setting could just be "started whenever".

Example:

``` 
    debug:
        requires:
            - ~pr
            - ~commit
            - ~user
```

**Comment by tkyi** [comment]
There is now the ability to start any job in a pipeline even if it was never run before.
Not sure if this addresses your issue: https://github.com/screwdriver-cd/screwdriver/issues/1335

Feel free to reopen if it doesn't.
