### ISSUE TITLE
feature: deep link to build step

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#962]
**What happened**:
In a build page I click on the step to see the logs for that step. Unfortunately I have no way to share a URL to that particular log.

**What you expected to happen**:
Clicking the step name adds a fragment identifier to the URL.
https://en.wikipedia.org/wiki/Fragment_identifier

**How to reproduce it**:

**Comment by DekusDenial** [comment]
will consider addressing this as part of the metrics deep-linking to build and its steps

**Comment by tkyi** [comment]
Should be accessible now at `<api_url>/pipelines/<pipeline_id>/builds/<build_id>/steps/<step_name>`

Example: https://cd.screwdriver.cd/pipelines/7/builds/106183/steps/install-browsers
