### ISSUE TITLE
$GIT_BRANCH invalid value in PR builds?

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#965]
**What happened**:
`git diff $GIT_BRANCH --numstat` results in `Invalid object name 'origin/refs/pull/14/head'`

**What you expected to happen**:
`$GIT_BRANCH` is a valid value which can be passed to `git diff`

**How to reproduce it**:

**Comment by drewfish** [comment]
In a PR build I did a `tree .git/refs` and saw this:
```
.git/refs
 |-- heads
 | |-- master
 | `-- pr
 |-- remotes
 | `-- origin
 | `-- HEAD
 `-- tags
```

**Comment by tkyi** [comment]
Are you expecting the branch name of the PR?

**Comment by lfjewett** [comment]
This is the closest issue I could find to what we're searching for.  We have a pipeline workflow that runs a set of templates against different accounts depending on the branch.  Commits to the develop branch run templates in a DEV account and Commits to master run them in production.   It's fairly simple to write logic to switch the account parameters based off the GIT_BRANCH value for this job.  However if a job is started as part of ~pr then we have no idea if that PR is headed to develop or master and no easy way to find out.

One work around is to grab the value using a github API token with the following; 

`https://api.github.com/repos/org/project/pulls/10 | jq '.base["ref"]'`

It would be **very** helpful if Screwdriver provided this information for us instead, and would make for much simpler and cleaner pipelines.  Perhaps someone else has an easier way to find the real branch for a PR?

**Comment by jithin1987** [comment]
What we could do is make `GIT_BRANCH` always be the target Git branch for which the job is configured. And if it's a Pull Request then introduce `GIT_PR_REF` which will hold the current `GIT_BRANCH` value for a Pull Request

**Comment by yoshwata** [comment]
I hope that `GIT_BRANCH` would be the branch name that we can push to.
