### ISSUE TITLE
[UI]Need response when click restart button in build page

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#971]
**What happened**:
In redesigned build page, it seems that we can restart a job by pressing the restart button. However, there was no response or feedback after pressing it. I thought the button had not worked properly, so I pressed it several times. Then actually screwdriver started builds for each button action unexpectedly.

**What you expected to happen**:
The UI shows modal below when the start button on a pipeline page is pressed. This behavior brings a sense of ease to user. Also it prevents starting the same build multiple times.
<img width="978" alt="2018-04-03 11 35 33" src="https://user-images.githubusercontent.com/4645011/38226179-35463e24-3733-11e8-8a5a-2e0c5d13c0d3.png">

**How to reproduce it**:
Click the restart button on a build page.

**Comment by tkyi** [comment]
This feature is working in production:
<img width="1347" alt="screen shot 2018-05-23 at 4 19 58 pm" src="https://user-images.githubusercontent.com/3230529/40456261-3941cfb8-5ea5-11e8-803a-415f6e294ff5.png">
