### ISSUE TITLE
[UX] template page shows step command as one line

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#973]
**What happened**:
On the template page the command for a step is all one line:
https://screwdriver.ouroath.com/templates/tools%2Fsimple-docker
```# by default sets the image name to match the git repo name (ie: alvinf/sdv4-docker-push-example in this example) # best to stick to this so do not modify unless absolutely needed!!! export IMAGE=`echo $GIT_URL | awk 'match($0, /:.*\/.*.git/) {print tolower(substr($0, RSTART+1, RLENGTH-5))}'` echo $IMAGE export TIMESTAMP=$(date -u +"%Y%m%d-%H%M%S") echo $TIMESTAMP # more helpful environment variables for later export PRINCIPAL=cd.screwdriver.project.sd$SD_PIPELINE_ID if [ ! -z $SD_PULL_REQUEST ]; then export PRINCIPAL=$PRINCIPALpr fi echo $PRINCIPAL```
It's wrapped, but still quite hard to read.

**What you expected to happen**:
The shown command preserves whitespace found in the template source:
https://git.ouroath.com/Tools/simple-docker/blob/master/sd-template.yaml#L8-L20
```
          # by default sets the image name to match the git repo name (ie: alvinf/sdv4-docker-push-example in this example)
          # best to stick to this so do not modify unless absolutely needed!!!
          export IMAGE=`echo $GIT_URL | awk 'match($0, /:.*\/.*.git/) {print tolower(substr($0, RSTART+1, RLENGTH-5))}'`
          echo $IMAGE
          export TIMESTAMP=$(date -u +"%Y%m%d-%H%M%S")
          echo $TIMESTAMP
          # more helpful environment variables for later
          export PRINCIPAL=cd.screwdriver.project.sd$SD_PIPELINE_ID
          if [ ! -z $SD_PULL_REQUEST ]; then
              export PRINCIPAL=$PRINCIPALpr
          fi
          echo $PRINCIPAL
```

**How to reproduce it**:

**Comment by tkyi** [comment]
Verified that the fix is working as expected.
