### ISSUE TITLE
Use curlWrapper for artifact-bookend

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#989]
**What happened**:
If image has an old `curl` version, it will result in some error like:
`Peer reports incompatible or unsupported protocol version.`

**How to fix it**:
I propose to use `${curlWrapper}` to call the curl itself. Since the `curlWrapper` checks if the version doesn't meet the `ALLOW_VERSION`, we can leverage it. 

Currently, it's only use that for the `encoded` part. 
https://github.com/screwdriver-cd/artifact-bookend/blob/master/commands.txt#L3

**Comment by d2lam** [comment]
@sakka2  What do you think about this?

**Comment by sakka2** [comment]
@d2lam 
The error message `Peer reports incompatible or unsupported protocol version.`  happens when `curl` version is old. 
Dose this mean that if it is via `sd-step`, the error will happen?

**Comment by d2lam** [comment]
Right, @sakka2!
Thanks for submitting the PR 👍

**Comment by d2lam** [comment]
@sakka2  If it's via `sd-step`, it will not happen. However, there is also a bug in the `teardown` bookend where the `PATH` is not added. I created a PR for it: https://github.com/screwdriver-cd/launcher/pull/168

**Comment by sakka2** [comment]
@d2lam thanks!

**Comment by sakka2** [comment]
It seems build has not started.
https://cd.screwdriver.cd/pipelines/73/builds/20257

**Comment by jithin1987** [comment]
Closing this since we are not using hab wrapper.
