### ISSUE TITLE
date -> date-time

### ISSUE THREAD

**Issue by nicolaifsf** [screwdriver-cd/screwdriver#99]
'date' -> 'date-time' in swagger.json so that codegen will work properly with the way we format date and time.

**Comment by stjohnjohnson** [comment]
What's interesting is they are currently listed as strings:
```
"endTime": {
"type": "string",
"description": "When this build stopped running",
"x-format": {
"isoDate": true
}
},
```

**Comment by stjohnjohnson** [comment]
@nicolaifsf what are you looking for with the type.  Is string + isoDate not sufficient?

**Comment by jithin1987** [comment]
won't fix.
