### ISSUE TITLE
$K8S_NODE_SELECTORS of k8s-vm should be $K8S_VM_NODE_SELECTORS

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#996]
**What happened**:
`K8S_NODE_SELECTORS` exists in both `k8s` and `k8s-vm` executor settings.
We cannot set other selectors if we want to use other selectors with multiple executors (i.e. `k8s` and `k8s-vm`).

**What you expected to happen**:
`K8S_NODE_SELECTORS` and `K8S_PREFERRED_NODE_SELECTORS` of `k8s-vm` should have `K8S_VM` prefix.
This change does not have compatibility so how about this change?

**Comment by tkyi** [comment]
I think your idea sounds reasonable. It should be doable. 👍

**Comment by tk3fftk** [comment]
Thanks! I'll send pull requests😄

**Comment by tk3fftk** [comment]
This issue should be closed. Thank you for your reviews!
